SELECT
    MP.CODPRJ,ROUND(SUM(CONVERT(float,KA.TEMPO)),1)/60 TEMPO, KO.NUMEXEC
FROM
    MPRJ MP
    INNER JOIN MTAREFA MT ON MT.CODCOLIGADA = MP.CODCOLIGADA AND MT.IDPRJ=MP.IDPRJ
    INNER JOIN KORDEMCOMPL KO ON KO.CODCOLIGADA = MP.CODCOLIGADA AND KO.CODFILIAL=MP.CODFILIAL AND KO.CODORDEM=MT.CODTRFAUX 
	INNER JOIN KORDEM K ON K.CODCOLIGADA = MP.CODCOLIGADA AND K.CODFILIAL=MP.CODFILIAL AND K.CODORDEM=MT.CODTRFAUX
    INNER JOIN KATVORDEM KA ON KA.CODCOLIGADA = MP.CODCOLIGADA AND KA.CODFILIAL=MP.CODFILIAL AND KA.CODORDEM=MT.CODTRFAUX
WHERE
    MP.CODPRJ='3.07840.32.001'
	AND MP.REVISAO=(SELECT MAX(REVISAO) FROM MPRJ
					WHERE CODPRJ='3.07840.32.001')
	AND K.STATUS!=6
	AND KA.STATUS!=6
GROUP BY
    NUMEXEC,CODPRJ
ORDER BY
    NUMEXEC

--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT
    MP.CODPRJ,ROUND(SUM(CONVERT(float,KA.TEMPO)),1)/60 TEMPO, KO.NUMEXEC
FROM
    MPRJ MP
    INNER JOIN MTAREFA MT ON MT.CODCOLIGADA = MP.CODCOLIGADA AND MT.IDPRJ=MP.IDPRJ
    INNER JOIN KORDEMCOMPL KO ON KO.CODCOLIGADA = MP.CODCOLIGADA AND KO.CODFILIAL=MP.CODFILIAL AND KO.CODORDEM=MT.CODTRFAUX
    INNER JOIN KATVORDEM KA ON KA.CODCOLIGADA = MP.CODCOLIGADA AND KA.CODFILIAL=MP.CODFILIAL AND KA.CODORDEM=MT.CODTRFAUX
	INNER JOIN KORDEM K ON K.CODCOLIGADA = MP.CODCOLIGADA AND K.CODFILIAL=MP.CODFILIAL AND K.CODORDEM=MT.CODTRFAUX
WHERE
    MP.CODPRJ='3.07840.32.001'
	AND MP.REVISAO=(SELECT MAX(REVISAO) FROM MPRJ
					WHERE CODPRJ='3.07840.32.001')
	AND K.STATUS!=6
	AND KA.STATUS!=6
	AND K.REPROCESSAMENTO=1
GROUP BY
    NUMEXEC,CODPRJ
ORDER BY
    NUMEXEC

--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT MT.ID,K.CODCOLIGADA,K.CODFILIAL,MP.CODCCUSTO,K.CODORDEM,KA.CODESTRUTURA,NUMEXEC,KL.PRIORIDADE,KA.CODATIVIDADE,KA.QTPREVISTA,KA.TEMPO,K.REPROCESSAMENTO
	FROM
		MPRJ MP
		INNER JOIN MTAREFA MT ON MT.CODCOLIGADA = MP.CODCOLIGADA AND MT.IDPRJ=MP.IDPRJ
		INNER JOIN KATVORDEM KA ON KA.CODCOLIGADA = MP.CODCOLIGADA AND KA.CODFILIAL=MP.CODFILIAL AND KA.CODORDEM=MT.CODTRFAUX
		INNER JOIN KATVORDEMCOMPL KL ON KL.CODCOLIGADA = MP.CODCOLIGADA AND KL.CODFILIAL=MP.CODFILIAL AND KL.CODORDEM=MT.CODTRFAUX AND KL.IDATVORDEM=KA.IDATVORDEM
		INNER JOIN KORDEM K ON K.CODCOLIGADA = MP.CODCOLIGADA AND K.CODFILIAL=MP.CODFILIAL AND K.CODORDEM=MT.CODTRFAUX
		INNER JOIN KORDEMCOMPL KO ON KO.CODCOLIGADA = MP.CODCOLIGADA AND KO.CODFILIAL=MP.CODFILIAL AND KO.CODORDEM=MT.CODTRFAUX
	WHERE
		MP.CODPRJ='3.07840.32.001'
		AND MP.REVISAO=(SELECT MAX(REVISAO) FROM MPRJ
						WHERE CODPRJ='3.07840.32.001')
		AND K.STATUS!=6
		AND KA.STATUS!=6
	ORDER BY CODESTRUTURA,NUMEXEC,PRIORIDADE

SELECT * FROM KATVORDEMCOMPL
WHERE CODESTRUTURA LIKE '03.023%'



SELECT * FROM KORDEM WHERE CODCCUSTO='3.07840.32.001' AND DSCORDEM='CONE POS.4 - 4 - GAM-07840-DE-0014' AND REPROCESSAMENTO=1
