

UPDATE K SET CODMODELO='Base',CODMODELOFEITO='Base' FROM KATVORDEM K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KITEMORDEM K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMMP K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMCOMPL K WHERE  CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMMATERIAPRIMA K WHERE  CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMCUSTOIND K WHERE  CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMCUSTOMAOOBRA K WHERE  CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMCUSTOPOSTO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMHISTORICOCUSTO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMMPTERCEIRO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMPROCESSO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KATVORDEMSUBPRODUTO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KHISTATVORDEMMP K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KHISTLOGAPONTAMENTO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KHISTLOGATIVIDADE K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KHISTLOGPRODUCAO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KITEMORDEMCOMPL K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KITEMRDEMCUSTOIND K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KLOGAPONTAMENTO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base',CODMODELOFEITO='Base' FROM KLOGATIVIDADE K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base',CODMODELOFEITO='Base' FROM KLOGPRODUCAO K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KMAOOBRAALOC K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KMOVESTOQUE K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 

UPDATE K SET CODMODELO='Base' FROM KPARADAATV K WHERE CODMODELO='base' COLLATE Latin1_General_CS_AS 


