
ALTER TABLE KATVORDEMCOMPL
NOCHECK CONSTRAINT FKKATVORDEMCOMPL_KATVORDEM

ALTER TABLE KATVORDEMMP
NOCHECK CONSTRAINT FKKATVORDEMMP_KATVORDEM

ALTER TABLE KATVORDEMPROCESSO
NOCHECK CONSTRAINT FKKATVORDEMPROCESSO_KATVORDEM

ALTER TABLE KLOGAPONTAMENTO
NOCHECK CONSTRAINT FKKLOGAPONTAMENTO_KATVORDEM

 UPDATE KATVORDEMCOMPL SET IDATVORDEM=10 WHERE CODORDEM='35259/22' AND IDATVORDEM=9

 UPDATE KATVORDEM SET IDATVORDEM=10 WHERE CODORDEM='35259/22' AND IDATVORDEM=9

UPDATE KATVORDEMMP SET IDATIVIDADE=10 WHERE CODORDEM='35259/22' AND IDATIVIDADE=9

UPDATE KATVORDEMPROCESSO SET IDATVORDEM=10 WHERE CODORDEM='35259/22' AND IDATVORDEM=9

UPDATE KLOGAPONTAMENTO SET IDATV=10 WHERE CODORDEM='35259/22' AND IDATV=9

UPDATE KMAOOBRAALOC SET IDATVORDEM=10 WHERE CODORDEM='35259/22' AND IDATVORDEM=9

ALTER TABLE KATVORDEMCOMPL
CHECK CONSTRAINT FKKATVORDEMCOMPL_KATVORDEM

ALTER TABLE KATVORDEMMP
CHECK CONSTRAINT FKKATVORDEMMP_KATVORDEM

ALTER TABLE KATVORDEMPROCESSO
CHECK CONSTRAINT FKKATVORDEMPROCESSO_KATVORDEM

ALTER TABLE KLOGAPONTAMENTO
CHECK CONSTRAINT FKKLOGAPONTAMENTO_KATVORDEM
