SELECT TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,GS.APLICACAO,GS.CODSENTENCA
 FROM INFORMATION_SCHEMA.TABLES I
LEFT JOIN CORPORE.DBO.GDIC G ON
G.TABELA=I.TABLE_NAME
LEFT JOIN CORPORE.DBO.GCONSSQL GS ON
GS.SENTENCA LIKE CONCAT('%',I.TABLE_NAME,' %')
WHERE 
G.TABELA IS NULL 
AND TABLE_TYPE!='VIEW' 
AND TABLE_NAME NOT LIKE '%CRM%'
ORDER BY TABLE_NAME


select * from sys.procedures p

select * from sys.objects where object_id=86141098

select * from sys.syscomments where id=86141098

 

 