
;WITH CTE AS (
SELECT R.CODCOLIGADA,R.CODFILIAL,R.CODORDEM,R.NUMEXEC,R.CODTRF,R.IDATVORDEM,K.[STATUS] STATUSATV,R.[STATUS] STATUSORDEM,CASE WHEN K.TEMPO>R.PREVISTO THEN K.TEMPO ELSE R.PREVISTO END PREVISTO  
FROM 
KATVORDEM K 
 INNER JOIN ( 
     SELECT  R.CODCOLIGADA,R.CODFILIAL,R.CODORDEM,IDATVORDEM,K.[STATUS],SUM(PREVISTO)/60.0  PREVISTO,KL.NUMEXEC,
SUBSTRING(K.RESPONSAVEL,CHARINDEX('/',K.RESPONSAVEL)+1,CASE WHEN CHARINDEX('|',K.RESPONSAVEL)=0 THEN LEN(K.RESPONSAVEL)-CHARINDEX('/',K.RESPONSAVEL) ELSE CHARINDEX('|',K.RESPONSAVEL)-CHARINDEX('/',K.RESPONSAVEL)-1 END) CODTRF 
FROM ( 
     SELECT CODCOLIGADA,CODFILIAL,CODORDEM,IDATVORDEM,
    CAST(DATEDIFF(SECOND,DTHRINICIAL,DTHRFINAL) AS BIGINT) PREVISTO
      FROM KMAOOBRAALOC WHERE EFETIVADO = 0
     UNION ALL
     SELECT CODCOLIGADA,CODFILIAL,CODORDEM,IDATVORDEM,CAST(DATEDIFF(SECOND,DTHRINICIAL,DTHRFINAL) AS BIGINT) PREVISTO
      FROM ZMDKATVORDEMPROGRAMACAO WHERE STATUS!=2
     ) R INNER JOIN KORDEM K ON
    R.CODORDEM=K.CODORDEM
    AND R.CODCOLIGADA=K.CODCOLIGADA
    AND R.CODFILIAL=K.CODFILIAL 
    INNER JOIN KORDEMCOMPL KL ON
    R.CODORDEM=KL.CODORDEM
    AND R.CODCOLIGADA=KL.CODCOLIGADA
    AND R.CODFILIAL=KL.CODFILIAL 
    WHERE K.[STATUS]!=6 AND CODCCUSTO='3.07840.32.001' AND K.RESPONSAVEL LIKE '%/1.20%' AND ( K.REPROCESSAMENTO IS NULL OR K.REPROCESSAMENTO=0)
    GROUP BY R.CODCOLIGADA,R.CODFILIAL,R.CODORDEM,IDATVORDEM,K.[STATUS],KL.NUMEXEC,
	SUBSTRING(K.RESPONSAVEL,CHARINDEX('/',K.RESPONSAVEL)+1,CASE WHEN CHARINDEX('|',K.RESPONSAVEL)=0 THEN LEN(K.RESPONSAVEL)-CHARINDEX('/',K.RESPONSAVEL) ELSE CHARINDEX('|',K.RESPONSAVEL)-CHARINDEX('/',K.RESPONSAVEL)-1 END)
    ) R 
    ON K.CODORDEM=R.CODORDEM 
    AND K.CODCOLIGADA=R.CODCOLIGADA 
    AND K.CODFILIAL=R.CODFILIAL 
    AND K.IDATVORDEM=R.IDATVORDEM
    WHERE K.[STATUS]!=6 AND (R.[STATUS]!=5 OR K.[STATUS]!=1)
    )
, CTEA AS (
    SELECT * FROM CTE
), CTEB AS (SELECT NUMEXEC,CODTRF,SUM(PREVISTO) TOTAL FROM CTE GROUP BY NUMEXEC,CODTRF)
,CTEC AS (
SELECT A.CODORDEM,A.NUMEXEC,A.CODTRF,A.IDATVORDEM,A.STATUSATV,A.STATUSORDEM,
CASE WHEN A.STATUSATV=5 THEN (PREVISTO/(SELECT TOTAL FROM CTEB WHERE NUMEXEC=A.NUMEXEC AND CODTRF=A.CODTRF))*100 ELSE 0 END PESO
FROM CTEA A ) 
SELECT NUMEXEC,CODTRF,REPLACE(FORMAT(ROUND(SUM(PESO),2),'0.00'),'.',',')+'%' PESO FROM CTEC
GROUP BY NUMEXEC,CODTRF
ORDER BY CODTRF,NUMEXEC

