;WITH CTE3 AS (
	 SELECT COUNT(IDCRIACAOPAI) CONTAGEM,IDCRIACAO,OS,EXECUCAO,CODTRFPAI 
 FROM FLUIG.DBO.Z_CRM_EX001005 Z
	INNER JOIN KITEMORDEM KI ON 
	KI.CODCOLIGADA=Z.CODCOLIGADA 
	AND KI.CODFILIAL=Z.CODFILIAL 
	AND KI.CODESTRUTURA=Z.CODIGOPRD COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI 
	INNER JOIN KORDEMCOMPL KL ON 
	KL.CODCOLIGADA=KI.CODCOLIGADA 
	AND KL.CODFILIAL=KI.CODFILIAL 
	AND KL.CODORDEM=KI.CODORDEM 
	AND KL.NUMEXEC=Z.EXECUCAO 
 WHERE Z.OS='3.07829.32.001' AND Z.ITEMEXCLUSIVO!=2 AND Z.CODTRFPAI='1.14' AND EXECUCAO=20 AND COALESCE(CODIGOPRD,'')!='' AND KI.STATUS!=6
 GROUP BY OS,CODTRFPAI,EXECUCAO,IDCRIACAO

),CTE2 AS (

	SELECT CODCOLIGADA,CODFILIAL,CODORDEM,MAX(TEMPO) TEMPO FROM (
		SELECT CODCOLIGADA,CODFILIAL,CODORDEM,SUM(TEMPO)TEMPO 
		FROM KATVORDEM 
		GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM
		UNION ALL
		SELECT CODCOLIGADA,CODFILIAL,CODORDEM,SUM(CAST(DATEDIFF(SECOND,DTHRINICIAL,DTHRFINAL) AS BIGINT))/60 TEMPO 
		FROM KMAOOBRAALOC  
		WHERE EFETIVADO=0
		GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM
		UNION ALL
		SELECT CODCOLIGADA,CODFILIAL,CODORDEM,SUM(CAST(DATEDIFF(SECOND,DTHRINICIAL,DTHRFINAL) AS BIGINT))/60 TEMPO 
		FROM ZMDKATVORDEMPROGRAMACAO  
		WHERE STATUS!=2
		GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM
	) R 
	GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM 
),
 CTE AS
(
    
    
    SELECT  Z.IDCRIACAO,Z.IDCRIACAOPAI,CONCAT(Z.DESCRICAO, ' - ' COLLATE Latin1_General_CI_AS ,Z.POSICAODESENHO) DESCRICAO,Z.EXECUCAO,Z.CODTRFPAI,Z.OS,1 FILHO,0 PAI,Z.INDICE,Z.NIVEL,KI.CODORDEM,CAST(C2.TEMPO AS INT) ACUMULADO,C2.TEMPO,CAST(C2.TEMPO AS FLOAT) ACC
    FROM FLUIG.DBO.Z_CRM_EX001005 Z
    LEFT JOIN FLUIG.DBO.Z_CRM_EX001005 C ON  
	Z.EXECUCAO=C.EXECUCAO AND Z.OS=C.OS  
	AND Z.CODTRFPAI=C.CODTRFPAI 
	AND Z.IDCRIACAO = C.IDCRIACAOPAI
	INNER JOIN KITEMORDEM KI ON 
	KI.CODCOLIGADA=Z.CODCOLIGADA 
	AND KI.CODFILIAL=Z.CODFILIAL 
	AND KI.CODESTRUTURA=Z.CODIGOPRD COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI 
	INNER JOIN KORDEMCOMPL KL ON 
	KL.CODCOLIGADA=KI.CODCOLIGADA 
	AND KL.CODFILIAL=KI.CODFILIAL 
	AND KL.CODORDEM=KI.CODORDEM 
	AND KL.NUMEXEC=Z.EXECUCAO 
	INNER JOIN CTE2 C2 ON
	C2.CODCOLIGADA=KI.CODCOLIGADA
	AND C2.CODFILIAL=KI.CODFILIAL
	AND C2.CODORDEM=KI.CODORDEM
	WHERE Z.OS='3.07829.32.001' AND Z.ITEMEXCLUSIVO!=2 AND Z.CODTRFPAI='1.14' AND Z.EXECUCAO=20 AND C.IDCRIACAO IS NULL AND KI.STATUS!=6

	UNION ALL

    SELECT Z.IDCRIACAO,Z.IDCRIACAOPAI,CONCAT(Z.DESCRICAO, ' - ' COLLATE Latin1_General_CI_AS ,Z.POSICAODESENHO) DESCRICAO,Z.EXECUCAO,Z.CODTRFPAI,Z.OS,1 FILHO,
	CASE WHEN C.PAI=1 THEN 1 ELSE 0 END AS PAI,Z.INDICE,Z.NIVEL,KI.CODORDEM,CAST((C.ACUMULADO/CAST(C3.CONTAGEM AS FLOAT))+(C2.TEMPO) AS INT) ACUMULADO,C2.TEMPO,(C.ACUMULADO/CAST(C3.CONTAGEM AS FLOAT)) ACC
    FROM FLUIG.DBO.Z_CRM_EX001005 Z
	INNER JOIN CTE C ON
	Z.OS=C.OS
	AND Z.CODTRFPAI=C.CODTRFPAI
	AND Z.EXECUCAO=C.EXECUCAO
	AND Z.IDCRIACAO=C.IDCRIACAOPAI
	INNER JOIN KITEMORDEM KI ON 
	KI.CODCOLIGADA=Z.CODCOLIGADA 
	AND KI.CODFILIAL=Z.CODFILIAL 
	AND KI.CODESTRUTURA=Z.CODIGOPRD COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI 
	INNER JOIN KORDEMCOMPL KL ON 
	KL.CODCOLIGADA=KI.CODCOLIGADA 
	AND KL.CODFILIAL=KI.CODFILIAL 
	AND KL.CODORDEM=KI.CODORDEM 
	AND KL.NUMEXEC=Z.EXECUCAO 
	INNER JOIN CTE2 C2 ON
	C2.CODCOLIGADA=KI.CODCOLIGADA
	AND C2.CODFILIAL=KI.CODFILIAL
	AND C2.CODORDEM=KI.CODORDEM
	INNER JOIN CTE3 C3 ON
	Z.OS=C3.OS
	AND Z.CODTRFPAI=C3.CODTRFPAI
	AND Z.EXECUCAO=C3.EXECUCAO
	AND Z.IDCRIACAO=C3.IDCRIACAO
	WHERE Z.OS='3.07829.32.001' AND Z.ITEMEXCLUSIVO!=2 AND Z.CODTRFPAI='1.14' AND Z.EXECUCAO=20 AND C.PAI=0 AND KI.STATUS!=6
)


SELECT IDCRIACAO,IDCRIACAOPAI,DESCRICAO,EXECUCAO,CODTRFPAI,INDICE,OS,CODORDEM,CAST(SUM(CAST(ACUMULADO AS INT))/60.0 AS DECIMAL(18,2)) TEMPO,TEMPO,ACC
 FROM CTE 
 GROUP BY IDCRIACAO,IDCRIACAOPAI,DESCRICAO,EXECUCAO,CODTRFPAI,OS,INDICE,CODORDEM,TEMPO,ACC
 ORDER BY CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)


