	SELECT P.IDPRD,P.CODIGOPRD,P.DESCRICAO,CONCAT(P.CODIGOPRD,' - ',P.NOMEFANTASIA) NOMEPRODUTO  
	FROM TPRD P
	INNER JOIN KORDEM K ON
	K.CODCOLIGADA=P.CODCOLIGADA
	INNER JOIN KATVORDEM KA ON
	KA.CODCOLIGADA=K.CODCOLIGADA
	AND KA.CODFILIAL=K.CODFILIAL
	AND KA.CODORDEM=K.CODORDEM
	INNER JOIN KATVORDEMMP KM ON 
	KM.CODCOLIGADA=KA.CODCOLIGADA
	AND KM.CODFILIAL=KA.CODFILIAL
	AND KM.CODORDEM=KA.CODORDEM
	AND KM.IDATIVIDADE=KA.IDATVORDEM 
	AND KM.IDPRODUTO=P.IDPRD
	WHERE K.CODORDEM='32135/22' 
	AND KA.CODATIVIDADE='WATV028-00'
	UNION 
	SELECT P.IDPRD,P.CODIGOPRD,P.DESCRICAO,CONCAT(P.CODIGOPRD,' - ',P.NOMEFANTASIA) NOMEPRODUTO  
	FROM TPRD P
	INNER JOIN KORDEM K ON
	K.CODCOLIGADA=P.CODCOLIGADA
	INNER JOIN KATVORDEM KA ON
	KA.CODCOLIGADA=K.CODCOLIGADA
	AND KA.CODFILIAL=K.CODFILIAL
	AND KA.CODORDEM=K.CODORDEM
	INNER JOIN KATVORDEMMP KM ON 
	KM.CODCOLIGADA=KA.CODCOLIGADA
	AND KM.CODFILIAL=KA.CODFILIAL
	AND KM.CODORDEM=KA.CODORDEM
	AND KM.IDATIVIDADE=KA.IDATVORDEM 
	AND KM.IDPRODUTO=P.IDPRD
	INNER JOIN KCOMPSUBSTITUTO KC ON
	KC.CODCOLIGADA=KA.CODCOLIGADA
	AND KC.CODFILIAL=KA.CODFILIAL
	AND KC.CODESTRUTURA=KA.CODESTRUTURA
	AND KC.CODATIVIDADE=KA.CODATIVIDADE
	AND KC.IDPRDORIGEM=KM.IDPRODUTO
	WHERE K.CODORDEM='32135/22' 
	AND KA.CODATIVIDADE='WATV028-00'