DECLARE @OS VARCHAR(30) = '3.07842.32.001'
DECLARE @EXEC1 INT = 1
DECLARE @EXEC2 INT = 4

SELECT R2.CODCCUSTO,R2.CODESTRUTURA, R2.CODORDEM, R2.DSCORDEM, R2.IDATVORDEM,ATV.DSCATIVIDADE/*,SUBSTRING(CODIGOPRD,0,7) MASKPRD*/, CODIGOPRD,CASE WHEN K.CODORDEM IS NULL THEN CASE WHEN PAPCLOTE IS NULL THEN 'SEM LOTE' ELSE PAPCLOTE END ELSE K.CODORDEM END AS LOTE_PREVISTO, CASE WHEN TL.NUMLOTE IS NULL THEN 'SEM LOTE' ELSE TL.NUMLOTE END AS LOTE_APONTADO, CODUNDCONTROLE, NOMEFANTASIA,CASE WHEN NUMPLANOCORTE IS NULL THEN 'SEM PLANO' ELSE NUMPLANOCORTE END AS NUMPLANOCORTE, KS1.DSCSTATUS STATUS_ATIVIDADE,KS2.DSCSTATUS STATUS_OP, IDPRODUTO, CASE WHEN QUANTIDADE_PREVISTA IS NULL THEN 0 ELSE QUANTIDADE_PREVISTA END AS QUANTIDADE_PREVISTA,CASE WHEN SUM( QUANTIDADE_EFETIVADA ) IS NULL THEN 0 ELSE SUM( QUANTIDADE_EFETIVADA ) END AS QUANTIDADE_APONTADA,POSI플O,REPROCESSAMENTO FROM (
	SELECT DISTINCT KOL.NUMEXEC,KM1.IDATVORDEMMATERIAPRIMA,KA.CODESTRUTURA,K.CODCOLIGADA,K.CODFILIAL,K.CODCCUSTO,K.CODORDEM,K.DSCORDEM,KAL.IDATVORDEM,KA.CODATIVIDADE,T.CODIGOPRD,L.IDLOTE IDLOTE,TP.CODUNDCONTROLE,T.NOMEFANTASIA,PAPC.NUMPLANOCORTE,PAPC.NUMLOTE PAPCLOTE,KA.STATUS STATUS_ATIVIDADE,K.STATUS STATUS_OP,KM1.IDPRODUTO,KM1.QUANTIDADE QUANTIDADE_PREVISTA,KM2.QUANTIDADE QUANTIDADE_EFETIVADA,'PRINCIPAL' POSI플O
		FROM 
			KORDEM K
			LEFT JOIN KATVORDEM KA ON
			KA.CODCOLIGADA=K.CODCOLIGADA
			AND KA.CODFILIAL=K.CODFILIAL
			AND KA.CODORDEM=K.CODORDEM

			INNER JOIN KORDEMCOMPL KOL ON 
			KOL.CODCOLIGADA=K.CODCOLIGADA
			AND KOL.CODFILIAL=K.CODFILIAL
			AND KOL.CODORDEM=K.CODORDEM

			INNER JOIN KATVORDEMMP KM1 ON
			KM1.CODCOLIGADA=K.CODCOLIGADA
			AND KM1.CODFILIAL=K.CODFILIAL
			AND KM1.CODORDEM=K.CODORDEM
			AND KM1.IDATIVIDADE=KA.IDATVORDEM
			AND KM1.EFETIVADO=0

			LEFT JOIN KATVORDEMMP KM2 ON
			KM2.CODCOLIGADA=K.CODCOLIGADA
			AND KM2.CODFILIAL=K.CODFILIAL
			AND KM2.CODORDEM=K.CODORDEM
			AND KM2.IDATIVIDADE=KA.IDATVORDEM
			AND KM2.IDPRODUTO=KM1.IDPRODUTO
			AND KM2.EFETIVADO=1

			LEFT JOIN KATVORDEMMPLOTE L ON
			L.CODCOLIGADA=K.CODCOLIGADA
			AND L.CODFILIAL=K.CODFILIAL
			AND L.IDATVORDEMMATERIAPRIMA=KM2.IDATVORDEMMATERIAPRIMA

			INNER JOIN KATVORDEMCOMPL KAL ON 
			KAL.CODCOLIGADA=K.CODCOLIGADA
			AND KAL.CODFILIAL=K.CODFILIAL
			AND KAL.CODORDEM=K.CODORDEM
			AND KAL.IDATVORDEM=KA.IDATVORDEM

			LEFT JOIN TPRODUTO T ON
			T.IDPRD=KM1.IDPRODUTO

			LEFT JOIN TPRD TP ON
			TP.IDPRD=T.IDPRD
		
			LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE PAPC ON
			PAPC.CODCOLIGADA=K.CODCOLIGADA
			AND PAPC.CODFILIAL=K.CODFILIAL
			AND PAPC.CODORDEM=K.CODORDEM
			AND PAPC.IDATVORDEM=KM1.IDATIVIDADE
			AND PAPC.CODIGOMP =T.CODIGOPRD

		WHERE K.CODCCUSTO=@OS AND KOL.NUMEXEC BETWEEN @EXEC1 AND @EXEC2 AND KA.STATUS!=6 AND K.STATUS!=6

		UNION ALL

		SELECT NUMEXEC,IDATVORDEMMATERIAPRIMA, CODESTRUTURA,CODCOLIGADA,CODFILIAL,CODCCUSTO,CODORDEM,DSCORDEM,IDATVORDEM,CODATIVIDADE,CODIGOPRD,IDLOTE,CODUNDCONTROLE,NOMEFANTASIA,NUMPLANOCORTE,PAPCLOTE,STATUS_ATIVIDADE,STATUS_OP,IDPRODUTO,QUANTIDADE_PREVISTA,QUANTIDADE_EFETIVADA,POSI플O FROM (
			SELECT DISTINCT KOL.NUMEXEC,KM2.IDATVORDEMMATERIAPRIMA, KA.CODESTRUTURA,K.CODCOLIGADA,K.CODFILIAL,K.CODCCUSTO,K.CODORDEM,K.DSCORDEM,KAL.IDATVORDEM,KA.CODATIVIDADE,T.CODIGOPRD,L.IDLOTE,TP.CODUNDCONTROLE,T.NOMEFANTASIA,PAPC.NUMPLANOCORTE,PAPC.NUMLOTE PAPCLOTE,KA.STATUS STATUS_ATIVIDADE,K.STATUS STATUS_OP,KM2.IDPRODUTO,KM3.QUANTIDADE QUANTIDADE_PREVISTA,KM2.QUANTIDADE QUANTIDADE_EFETIVADA,CONCAT('SUBSTITUTO DO ',KCOMP.IDPRDORIGEM) POSI플O
			FROM 
				KORDEM K
				LEFT JOIN KATVORDEM KA ON
				KA.CODCOLIGADA=K.CODCOLIGADA
				AND KA.CODFILIAL=K.CODFILIAL
				AND KA.CODORDEM=K.CODORDEM

				INNER JOIN KORDEMCOMPL KOL ON 
				KOL.CODCOLIGADA=K.CODCOLIGADA
				AND KOL.CODFILIAL=K.CODFILIAL
				AND KOL.CODORDEM=K.CODORDEM

				LEFT JOIN KATVORDEMMP KM1 ON
				KM1.CODCOLIGADA=K.CODCOLIGADA
				AND KM1.CODFILIAL=K.CODFILIAL
				AND KM1.CODORDEM=K.CODORDEM
				AND KM1.IDATIVIDADE=KA.IDATVORDEM
				AND KM1.EFETIVADO=0

				INNER JOIN KATVORDEMMP KM2 ON
				KM2.CODCOLIGADA=K.CODCOLIGADA
				AND KM2.CODFILIAL=K.CODFILIAL
				AND KM2.CODORDEM=K.CODORDEM
				AND KM2.IDATIVIDADE=KA.IDATVORDEM
				AND KM2.IDPRODUTO!=KM1.IDPRODUTO
				AND KM2.EFETIVADO=1

				LEFT JOIN KATVORDEMMPLOTE L ON
				L.CODCOLIGADA=K.CODCOLIGADA
				AND L.CODFILIAL=K.CODFILIAL
				AND L.IDATVORDEMMATERIAPRIMA=KM2.IDATVORDEMMATERIAPRIMA

				LEFT JOIN KATVORDEMMP KM3 ON
				KM3.CODCOLIGADA=K.CODCOLIGADA
				AND KM3.CODFILIAL=K.CODFILIAL
				AND KM3.CODORDEM=K.CODORDEM
				AND KM3.IDATIVIDADE=KM2.IDATIVIDADE
				AND KM3.IDPRODUTO=KM2.IDPRODUTO
				AND KM3.EFETIVADO=0

				INNER JOIN KATVORDEMMPLOTE KML ON
				KML.CODCOLIGADA=KM1.CODCOLIGADA
				AND KML.CODFILIAL=KM1.CODFILIAL

				INNER JOIN KATVORDEMCOMPL KAL ON 
				KAL.CODCOLIGADA=K.CODCOLIGADA
				AND KAL.CODFILIAL=K.CODFILIAL
				AND KAL.CODORDEM=K.CODORDEM
				AND KAL.IDATVORDEM=KA.IDATVORDEM

				LEFT JOIN TPRODUTO T ON
				T.IDPRD=KM2.IDPRODUTO

				LEFT JOIN TPRD TP ON
				TP.IDPRD=T.IDPRD
		
				LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE PAPC ON
				PAPC.CODCOLIGADA=K.CODCOLIGADA
				AND PAPC.CODFILIAL=K.CODFILIAL
				AND PAPC.CODORDEM=K.CODORDEM
				AND PAPC.IDATVORDEM=KM1.IDATIVIDADE
				AND PAPC.CODIGOMP =T.CODIGOPRD 

				LEFT JOIN KCOMPSUBSTITUTO KCOMP ON
				KCOMP.CODCOLIGADA=K.CODCOLIGADA
				AND KCOMP.CODFILIAL=K.CODFILIAL
				AND KCOMP.CODESTRUTURA=KA.CODESTRUTURA
				AND KCOMP.IDPRD=KM2.IDPRODUTO 
				AND KCOMP.CODATIVIDADE=KA.CODATIVIDADE

			WHERE K.CODCCUSTO=@OS AND KOL.NUMEXEC BETWEEN @EXEC1 AND @EXEC2 AND KM2.IDPRODUTO = (SELECT IDPRD FROM TLOTEPRD WHERE IDLOTE=KML.IDLOTE) AND KM1.IDPRODUTO != (SELECT IDPRD FROM TLOTEPRD WHERE IDLOTE=KML.IDLOTE) AND KA.STATUS!=6 AND K.STATUS!=6 AND KM3.QUANTIDADE IS NULL ) R
		) R2 

		LEFT JOIN TLOTEPRD TL ON
			TL.CODCOLIGADA=R2.CODCOLIGADA
			AND TL.IDLOTE=R2.IDLOTE
		LEFT JOIN KSTATUS KS1 ON
			KS1.CODCOLIGADA=R2.CODCOLIGADA
			AND KS1.CODSTATUS=R2.STATUS_ATIVIDADE
		LEFT JOIN KSTATUS KS2 ON
			KS2.CODCOLIGADA=R2.CODCOLIGADA
			AND KS2.CODSTATUS=R2.STATUS_OP
		LEFT JOIN KATIVIDADE ATV ON
			ATV.CODCOLIGADA=R2.CODCOLIGADA
			AND ATV.CODFILIAL=R2.CODFILIAL
			AND ATV.CODATIVIDADE=R2.CODATIVIDADE
		LEFT JOIN KORDEM K ON
			K.CODCOLIGADA=R2.CODCOLIGADA
			AND K.CODFILIAL=R2.CODFILIAL
			AND SUBSTRING(K.RESPONSAVEL,0,15)=R2.CODIGOPRD
			AND K.CODORDEM IN (SELECT CODORDEM FROM KORDEMCOMPL WHERE NUMEXEC=R2.NUMEXEC)
			AND K.STATUS!=6
		LEFT JOIN KORDEMCOMPL KL ON
			KL.CODCOLIGADA=K.CODCOLIGADA
			AND KL.CODFILIAL=K.CODFILIAL
			AND KL.CODORDEM=K.CODORDEM
		WHERE (R2.NUMEXEC IS NOT NULL OR SUBSTRING(CODIGOPRD,0,7)!='03.023') and REPROCESSAMENTO is null 
		GROUP BY KL.NUMEXEC,R2.CODCCUSTO, R2.CODESTRUTURA,K.RESPONSAVEL, R2.CODORDEM, R2.DSCORDEM, R2.IDATVORDEM,ATV.DSCATIVIDADE,CODIGOPRD,K.CODORDEM,TL.NUMLOTE, CODUNDCONTROLE, NOMEFANTASIA, NUMPLANOCORTE, KS1.DSCSTATUS,KS2.DSCSTATUS, IDPRODUTO, QUANTIDADE_PREVISTA,POSI플O,PAPCLOTE,REPROCESSAMENTO
		ORDER BY CODORDEM,R2.IDATVORDEM,CODIGOPRD




		 