DECLARE @OS VARCHAR(30),@CODTRFPAI VARCHAR(10),@EXECUCAO INT

SET @OS = '3.07849.32.001'
SET @CODTRFPAI = '1.11'
SET @EXECUCAO = 10

SELECT * FROM (
SELECT CAST(K.CODCOLIGADA AS VARCHAR(10)) CODCOLIGADA,CAST(K.CODFILIAL AS VARCHAR(10)) CODFILIAL,K.CODESTRUTURA,K.CODORDEM,EX.DESCRICAO COLLATE SQL_Latin1_General_CP1_CI_AI DESCRICAO,
K.QTDEPLANEJADA,EX.INDICE ORD FROM FLUIG.DBO.Z_CRM_EX001005 EX 
INNER JOIN KITEMORDEM K ON
K.CODCOLIGADA=EX.CODCOLIGADA
AND K.CODFILIAL=EX.CODFILIAL
AND K.CODESTRUTURA=EX.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
AND K.CODCCUSTO=EX.OS COLLATE SQL_Latin1_General_CP1_CI_AI
INNER JOIN KORDEMCOMPL KL ON 
KL.CODCOLIGADA=K.CODCOLIGADA
AND KL.CODFILIAL=K.CODFILIAL
AND KL.CODORDEM=K.CODORDEM
AND KL.NUMEXEC=EX.EXECUCAO
WHERE EX.OS=@OS AND EX.CODTRFPAI=@CODTRFPAI AND EXECUCAO=@EXECUCAO AND K.STATUS!=6 
UNION ALL
SELECT null,null,T.CODIGOPRD,KMP.CODORDEM,T.NOMEFANTASIA,KMP.QUANTIDADE,EX.INDICE ORD FROM FLUIG.DBO.Z_CRM_EX001005 EX 
INNER JOIN KITEMORDEM K ON
K.CODCOLIGADA=EX.CODCOLIGADA
AND K.CODFILIAL=EX.CODFILIAL
AND K.CODESTRUTURA=EX.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
AND K.CODCCUSTO=EX.OS COLLATE SQL_Latin1_General_CP1_CI_AI
INNER JOIN KORDEMCOMPL KL ON 
KL.CODCOLIGADA=K.CODCOLIGADA
AND KL.CODFILIAL=K.CODFILIAL
AND KL.CODORDEM=K.CODORDEM
AND KL.NUMEXEC=EX.EXECUCAO
INNER JOIN KATVORDEMMP KMP ON
KMP.CODCOLIGADA=K.CODCOLIGADA
AND KMP.CODFILIAL=K.CODFILIAL
AND KMP.CODORDEM=K.CODORDEM
INNER JOIN TPRD T ON
T.CODCOLIGADA=KMP.CODCOLIGADA
AND T.IDPRD=KMP.IDPRODUTO
WHERE EX.OS=@OS AND EX.CODTRFPAI=@CODTRFPAI AND EXECUCAO=@EXECUCAO AND K.STATUS!=6 AND KMP.EFETIVADO=0 ) R
ORDER BY CAST( '/'+REPLACE(ORD,'.','/')+'/' AS hierarchyid),CODCOLIGADA DESC

