DECLARE @OS VARCHAR(30)='3.07840.32.001'
DECLARE @NUMEXEC INT=1
SET @NUMEXEC =(SELECT TOP 1 KC.NUMEXEC FROM 
				MPRJ M 
				INNER JOIN MTAREFA MF ON M.CODCOLIGADA = MF.CODCOLIGADA AND M.IDPRJ = MF.IDPRJ 
				INNER JOIN MTRFCOMPL MT ON M.CODCOLIGADA = MT.CODCOLIGADA AND MF.IDPRJ = MT.IDPRJ AND MT.IDTRF = MF.IDTRF
				INNER JOIN KITEMORDEM KI ON M.CODCOLIGADA = KI.CODCOLIGADA AND M.CODFILIAL = KI.CODFILIAL AND M.CODPRJ = KI.CODCCUSTO AND KI.CODORDEM = MF.CODTRFAUX 
				INNER JOIN KORDEMCOMPL KC ON KI.CODCOLIGADA = KC.CODCOLIGADA AND KI.CODFILIAL = KC.CODFILIAL AND KI.CODORDEM = KC.CODORDEM 
				INNER JOIN FLUIG.DBO.Z_CRM_EX001005 EX (NOLOCK) ON KI.CODCOLIGADA = EX.CODCOLIGADA AND KI.CODFILIAL = EX.CODFILIAL AND EX.EXECUCAO = KC.NUMEXEC AND EX.OS=M.CODPRJ COLLATE Latin1_General_CI_AS 
				WHERE M.CODPRJ=@OS AND MT.TAG LIKE '%'
				GROUP BY KC.NUMEXEC
				ORDER BY KC.NUMEXEC)

SELECT K.CODCCUSTO,K.CODORDEM,K.DSCORDEM,KAL.IDATVORDEM,T.CODIGOPRD,KOO.CODORDEM OP_REFERENCIA,TP.CODUNDCONTROLE,T.NOMEFANTASIA,PAPC.NUMPLANOCORTE,PAPC.QTDEMP QTDPLANOTOTAL,K.STATUS,KM1.IDPRODUTO,KM1.QUANTIDADE QUANTIDADE_PREVISTA,KM2.QUANTIDADE QUANTIDADE_EFETIVADA
	FROM 
		KORDEM K
		LEFT JOIN KATVORDEM KA ON
		KA.CODCOLIGADA=K.CODCOLIGADA
		AND KA.CODFILIAL=K.CODFILIAL
		AND KA.CODORDEM=K.CODORDEM

		LEFT JOIN KORDEMCOMPL KOL ON 
		KOL.CODCOLIGADA=K.CODCOLIGADA
		AND KOL.CODFILIAL=K.CODFILIAL
		AND KOL.CODORDEM=K.CODORDEM

		INNER JOIN KATVORDEMMP KM1 ON
		KM1.CODCOLIGADA=K.CODCOLIGADA
		AND KM1.CODFILIAL=K.CODFILIAL
		AND KM1.CODORDEM=K.CODORDEM
		AND KM1.IDATIVIDADE=KA.IDATVORDEM
		AND KM1.EFETIVADO=0

		LEFT JOIN KATVORDEMMP KM2 ON
		KM2.CODCOLIGADA=K.CODCOLIGADA
		AND KM2.CODFILIAL=K.CODFILIAL
		AND KM2.CODORDEM=K.CODORDEM
		AND KM2.IDATIVIDADE=KA.IDATVORDEM
		AND KM2.IDPRODUTO=KM1.IDPRODUTO
		AND KM2.EFETIVADO=1

		LEFT JOIN KATVORDEMCOMPL KAL ON 
		KAL.CODCOLIGADA=K.CODCOLIGADA
		AND KAL.CODFILIAL=K.CODFILIAL
		AND KAL.CODORDEM=K.CODORDEM
		AND KAL.IDATVORDEM=KA.IDATVORDEM

		LEFT JOIN TPRODUTO T ON
		T.IDPRD=KM1.IDPRODUTO

		LEFT JOIN TPRD TP ON
		TP.IDPRD=T.IDPRD
		
		LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE PAPC ON
		PAPC.CODCOLIGADA=K.CODCOLIGADA
		AND PAPC.CODFILIAL=K.CODFILIAL
		AND PAPC.CODORDEM=K.CODORDEM
		AND PAPC.IDATVORDEM=KM1.IDATIVIDADE
		AND PAPC.CODIGOMP =T.CODIGOPRD

		LEFT JOIN KORDEMCOMPL KOOL ON 
		KOOL.CODCOLIGADA=K.CODCOLCFO
		AND KOOL.CODFILIAL=K.CODFILIAL

		LEFT JOIN KORDEM KOO ON 
		KOO.CODCOLIGADA=K.CODCOLIGADA
		AND KOO.CODFILIAL=K.CODFILIAL
		AND KOO.DSCORDEM=T.NOMEFANTASIA
		AND KOO.CODORDEM IN ( SELECT CODORDEM FROM KORDEMCOMPL WHERE NUMEXEC=@NUMEXEC)

	WHERE K.CODCCUSTO=@OS AND KOL.NUMEXEC=@NUMEXEC AND KA.STATUS!=6 AND K.STATUS!=6

	UNION ALL

	SELECT CODCCUSTO,CODORDEM,DSCORDEM,IDATVORDEM,CODIGOPRD,CODUNDCONTROLE,NOMEFANTASIA,NUMPLANOCORTE,OP_REFERENCIA,QTDEMP QTDPLANOTOTAL,STATUS,IDPRODUTO,QUANTIDADE_PREVISTA,QUANTIDADE_EFETIVADA FROM (
		SELECT DISTINCT KM2.IDATVORDEMMATERIAPRIMA,K.CODCCUSTO,K.CODORDEM,K.DSCORDEM,KAL.IDATVORDEM,T.CODIGOPRD,KM2.IDLOTE,TP.CODUNDCONTROLE,T.NOMEFANTASIA,PAPC.NUMPLANOCORTE,KOO.CODORDEM OP_REFERENCIA,PAPC.QTDEMP,K.STATUS,KM2.IDPRODUTO,KM3.QUANTIDADE QUANTIDADE_PREVISTA,KM2.QUANTIDADE QUANTIDADE_EFETIVADA
		FROM 
			KORDEM K
			LEFT JOIN KATVORDEM KA ON
			KA.CODCOLIGADA=K.CODCOLIGADA
			AND KA.CODFILIAL=K.CODFILIAL
			AND KA.CODORDEM=K.CODORDEM

			LEFT JOIN KORDEMCOMPL KOL ON 
			KOL.CODCOLIGADA=K.CODCOLIGADA
			AND KOL.CODFILIAL=K.CODFILIAL
			AND KOL.CODORDEM=K.CODORDEM

			LEFT JOIN KATVORDEMMP KM1 ON
			KM1.CODCOLIGADA=K.CODCOLIGADA
			AND KM1.CODFILIAL=K.CODFILIAL
			AND KM1.CODORDEM=K.CODORDEM
			AND KM1.IDATIVIDADE=KA.IDATVORDEM
			AND KM1.EFETIVADO=0

			INNER JOIN KATVORDEMMP KM2 ON
			KM2.CODCOLIGADA=K.CODCOLIGADA
			AND KM2.CODFILIAL=K.CODFILIAL
			AND KM2.CODORDEM=K.CODORDEM
			AND KM2.IDATIVIDADE=KA.IDATVORDEM
			AND KM2.IDPRODUTO!=KM1.IDPRODUTO
			AND KM2.EFETIVADO=1

			LEFT JOIN KATVORDEMMP KM3 ON
			KM3.CODCOLIGADA=K.CODCOLIGADA
			AND KM3.CODFILIAL=K.CODFILIAL
			AND KM3.CODORDEM=K.CODORDEM
			AND KM3.IDATIVIDADE=KM2.IDATIVIDADE
			AND KM3.IDPRODUTO=KM2.IDPRODUTO
			AND KM3.EFETIVADO=0

			INNER JOIN KATVORDEMMPLOTE KML ON
			KML.CODCOLIGADA=KM1.CODCOLIGADA
			AND KML.CODFILIAL=KM1.CODFILIAL

			LEFT JOIN KATVORDEMCOMPL KAL ON 
			KAL.CODCOLIGADA=K.CODCOLIGADA
			AND KAL.CODFILIAL=K.CODFILIAL
			AND KAL.CODORDEM=K.CODORDEM
			AND KAL.IDATVORDEM=KA.IDATVORDEM

			LEFT JOIN TPRODUTO T ON
			T.IDPRD=KM2.IDPRODUTO

			LEFT JOIN TPRD TP ON
			TP.IDPRD=T.IDPRD
		
			LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE PAPC ON
			PAPC.CODCOLIGADA=K.CODCOLIGADA
			AND PAPC.CODFILIAL=K.CODFILIAL
			AND PAPC.CODORDEM=K.CODORDEM
			AND PAPC.IDATVORDEM=KM1.IDATIVIDADE
			AND PAPC.CODIGOMP =T.CODIGOPRD 

			LEFT JOIN KORDEM KOO ON 
			KOO.CODCOLIGADA=K.CODCOLIGADA
			AND KOO.CODFILIAL=K.CODFILIAL
			AND KOO.DSCORDEM=T.NOMEFANTASIA
			AND KOO.CODORDEM IN ( SELECT CODORDEM FROM KORDEMCOMPL WHERE NUMEXEC=@NUMEXEC)

		WHERE K.CODCCUSTO=@OS AND KOL.NUMEXEC=@NUMEXEC AND KM2.IDPRODUTO = (SELECT IDPRD FROM TLOTEPRD WHERE IDLOTE=KML.IDLOTE) AND KM1.IDPRODUTO != (SELECT IDPRD FROM TLOTEPRD WHERE IDLOTE=KML.IDLOTE) AND KA.STATUS!=6 AND K.STATUS!=6 AND KM3.QUANTIDADE IS NULL ) R
	ORDER BY K.CODORDEM,KAL.IDATVORDEM



