
INSERT INTO Z_CRM_EX001019 (ID,PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,
QTDEUNCOMPONENTES,QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,OSCOMPONENTES,
SOLICITACAOCOMPONENTES,PRIORIDADEATVCOMPONENTES,EXECUCAO) 
SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODAUTOINC = 'Z_CRM_ML001019')+ROW_NUMBER()OVER(ORDER BY C.ID) ID,PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,
QTDEUNCOMPONENTES,QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,OSCOMPONENTES,
SOLICITACAOCOMPONENTES,PRIORIDADEATVCOMPONENTES,'52' EXECUCAO
 FROM Z_CRM_EX001019 WHERE OSCOMPONENTES='3.07829.32.001' AND IDCRIACAOCOMPONENTES=2 AND EXECUCAO=51 
 UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_ML001019 UNION ALL SELECT ID FROM Z_CRM_EX001019) AS MLS) WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019'
