BEGIN 
	
	BEGIN TRANSACTION;

	UPDATE EX SET EX.DESQTDE=ML.DESQTDE, EX.TOTALQTDE=ML.TOTALQTDE 
	FROM Z_CRM_ML001005 ML
		INNER JOIN Z_CRM_EX001005 EX ON
		ML.OS=EX.OS
		AND ML.IDCRIACAO=EX.IDCRIACAO
		WHERE ML.OS='3.07854.32.001' AND EX.CODTRFPAI='1.12'

	EXEC SP_CRM_ATUALIZAQTDES_EX '3.07854.32.001','1','1.12'
	EXEC SP_CRM_ATUALIZAQTDES_EX '3.07854.32.001','2','1.12'

	IF @@ERROR > 0 
	
		BEGIN 

			PRINT 'ERROR ATUALIZANDO QUANTIDADES' 
			ROLLBACK;

		END

	  ELSE 
	
			BEGIN 

				PRINT 'SUCESSO ATUALIZANDO QUANTIDADES' 
		
				DELETE C FROM Z_CRM_EX001019 C INNER JOIN Z_CRM_EX001005 E ON C.OSCOMPONENTES=E.OS AND C.IDCRIACAOCOMPONENTES=E.IDCRIACAO WHERE E.CODTRFPAI='1.12' AND OSCOMPONENTES='3.07854.32.001'

				INSERT INTO Z_CRM_EX001019 (ID,PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,QTDEUNCOMPONENTES,
				QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,OSCOMPONENTES,PRIORIDADEATVCOMPONENTES,EXECUCAO,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)  
				SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001005')+ROW_NUMBER()OVER(ORDER BY C.ID) ID,
				PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,QTDEUNCOMPONENTES,
				QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,OSCOMPONENTES,PRIORIDADEATVCOMPONENTES,E.EXECUCAO,C.RECCREATEDBY,C.RECCREATEDON,C.RECMODIFIEDBY,C.RECMODIFIEDON
					FROM Z_CRM_ML001019 C INNER JOIN Z_CRM_EX001005 E ON
					E.OS=C.OSCOMPONENTES
					AND E.IDCRIACAO=C.IDCRIACAOCOMPONENTES WHERE C.OSCOMPONENTES='3.07854.32.001' AND E.CODTRFPAI='1.12'

				UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_ML001005 UNION ALL SELECT ID FROM Z_CRM_EX001005) AS MLS) 
				WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001005' AND CODSISTEMA = 'K'




			END

		IF @@ERROR > 0 

			BEGIN 
				PRINT 'ERRO ATUALIZANDO COMPONENTES' 
				ROLLBACK;
			END

		ELSE 

			BEGIN
			
				PRINT 'SUCESSO ATUALIZANDO COMPONENTES' 
			
				DELETE C FROM Z_CRM_EX001021 C INNER JOIN Z_CRM_EX001005 E ON C.OSPROCESSO=E.OS AND C.IDCRIACAOPROCESSO=E.IDCRIACAO WHERE E.CODTRFPAI='1.12' AND OSPROCESSO='3.07854.32.001'

				INSERT INTO Z_CRM_EX001021 (ID,PRIORIDADE,IDCRIACAOPROCESSO,CODATIVIDADE,OSPROCESSO,IDPROCESSO,DESCATIVIDADE,HABILIDADEREQUERIDA,
				CODHABILIDADE,CODPOSTO,DESCPOSTO,FILA,CONFIGURACAO,PROCESSAMENTO,DESAGREGACAO,ESPERA,MOVIMENTACAO,MINUTOSGASTOS,DESCPROCESSO,DOCAPOIOATV1,DOCAPOIOATV2,DOCAPOIOATV3,DOCAPOIOATV4,
				FORNPARA,INTEGRADOPROCESSO,EXECUCAO,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)
				SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001005')+ROW_NUMBER()OVER(ORDER BY C.ID) ID,
				PRIORIDADE,IDCRIACAOPROCESSO,CODATIVIDADE,OSPROCESSO,IDPROCESSO,DESCATIVIDADE,HABILIDADEREQUERIDA,
				CODHABILIDADE,CODPOSTO,DESCPOSTO,FILA,CONFIGURACAO,PROCESSAMENTO,DESAGREGACAO,ESPERA,MOVIMENTACAO,MINUTOSGASTOS,DESCPROCESSO,DOCAPOIOATV1,DOCAPOIOATV2,DOCAPOIOATV3,DOCAPOIOATV4,
				FORNPARA,INTEGRADOPROCESSO,E.EXECUCAO,C.RECCREATEDBY,C.RECCREATEDON,C.RECMODIFIEDBY,C.RECMODIFIEDON 
				FROM Z_CRM_ML001021 C INNER JOIN Z_CRM_EX001005 E ON
					E.OS=C.OSPROCESSO
					AND E.IDCRIACAO=C.IDCRIACAOPROCESSO WHERE OSPROCESSO='3.07854.32.001' AND E.CODTRFPAI='1.12'

				UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_ML001005 UNION ALL SELECT ID FROM Z_CRM_EX001005) AS MLS) 
				WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001005' AND CODSISTEMA = 'K'
  
			END

			IF @@ERROR > 0 
				BEGIN 
					PRINT 'ERRO ATUALIZANDO PROCESSO'
					ROLLBACK;
				END
			ELSE 

				PRINT 'SUCESSO ATUALIZANDO PROCESSOS' 
				COMMIT TRANSACTION
END




--------------------------------------------------------------------------------------------------------------------------------------------------------



BEGIN 

				PRINT 'SUCESSO ATUALIZANDO QUANTIDADES' 

				INSERT INTO Z_CRM_EX001019 (ID,PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,QTDEUNCOMPONENTES,
				QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,OSCOMPONENTES,PRIORIDADEATVCOMPONENTES,EXECUCAO,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)  
				SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019')+ROW_NUMBER()OVER(ORDER BY ID) ID,
				PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,QTDEUNCOMPONENTES,
				QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,OSCOMPONENTES,PRIORIDADEATVCOMPONENTES,1,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON
				from Z_CRM_EX001019  where IDCRIACAOCOMPONENTES in (
				SELECT IDCRIACAO FROM Z_CRM_EX001005 WHERE OS='3.07854.32.001' 
				AND EXECUCAO=1 AND INDICE LIKE '2.1.1.1.1.1.2.1.2.1.1.4.2.2%' ) and OSCOMPONENTES='3.07854.32.001'

				UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_EX001019 UNION ALL SELECT ID FROM Z_CRM_EX001019) AS MLS) 
				WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019' AND CODSISTEMA = 'K'

				INSERT INTO Z_CRM_EX001021 (ID,PRIORIDADE,IDCRIACAOPROCESSO,CODATIVIDADE,OSPROCESSO,IDPROCESSO,DESCATIVIDADE,HABILIDADEREQUERIDA,
				CODHABILIDADE,CODPOSTO,DESCPOSTO,FILA,CONFIGURACAO,PROCESSAMENTO,DESAGREGACAO,ESPERA,MOVIMENTACAO,MINUTOSGASTOS,DESCPROCESSO,DOCAPOIOATV1,DOCAPOIOATV2,DOCAPOIOATV3,DOCAPOIOATV4,
				FORNPARA,INTEGRADOPROCESSO,EXECUCAO,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)
				SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021')+ROW_NUMBER()OVER(ORDER BY ID) ID,
				PRIORIDADE,IDCRIACAOPROCESSO,CODATIVIDADE,OSPROCESSO,IDPROCESSO,DESCATIVIDADE,HABILIDADEREQUERIDA,
				CODHABILIDADE,CODPOSTO,DESCPOSTO,FILA,CONFIGURACAO,PROCESSAMENTO,DESAGREGACAO,ESPERA,MOVIMENTACAO,MINUTOSGASTOS,DESCPROCESSO,DOCAPOIOATV1,DOCAPOIOATV2,DOCAPOIOATV3,DOCAPOIOATV4,
				FORNPARA,INTEGRADOPROCESSO,1,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON 
				from Z_CRM_EX001021  where IDCRIACAOPROCESSO in (
				SELECT IDCRIACAO FROM Z_CRM_EX001005 WHERE OS='3.07854.32.001' 
				AND EXECUCAO=1 AND INDICE LIKE '2.1.1.1.1.1.2.1.2.1.1.4.2.2%' ) and OSPROCESSO='3.07854.32.001'

				UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_EX001021 UNION ALL SELECT ID FROM Z_CRM_EX001021) AS MLS) 
				WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021' AND CODSISTEMA = 'K'




			END