SELECT IDCRIACAO,IDCRIACAOPAI,INDICE,NIVEL,POSICAOINDICE,CODTRFPAI,DESCRICAO,NUMDESENHO,POSICAODESENHO
FROM Z_CRM_EX001005 Z 
WHERE OS='3.07867.32.001' AND Z.ITEMEXCLUSIVO!=2 and INDICE like '5.%'--='1.15'
ORDER BY CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)



SELECT IDCRIACAO,IDCRIACAOPAI,INDICE,NIVEL,POSICAOINDICE,CODTRFPAI,DESCRICAO,NUMDESENHO,POSICAODESENHO
FROM Z_CRM_EX001005 Z 
WHERE OS='3.07867.32.001' AND Z.ITEMEXCLUSIVO!=2 and CODTRFPAI='1.48'
ORDER BY CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)

SELECT IDCRIACAO,IDCRIACAOPAI,INDICE,NIVEL,POSICAOINDICE,CODTRFPAI,DESCRICAO,NUMDESENHO,POSICAODESENHO
FROM Z_CRM_EX001005 Z 
WHERE OS='3.07867.32.001' AND Z.ITEMEXCLUSIVO!=2
ORDER BY CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)


SELECT * FROM (SELECT M.IDCRIACAO IDCRIACAOM,Z.IDCRIACAO,M.DESCRICAO DESCRICAOM,Z.DESCRICAO,M.INDICE INDICEM,Z.INDICE,
CASE WHEN M.CODTRFPAI = '' THEN (SELECT CODTRFPAI FROM Z_CRM_ML001005 WHERE INDICE=LEFT(M.INDICE,1) AND M.OS=OS) ELSE M.CODTRFPAI END CODTRFPAIM,
Z.CODTRFPAI 
FROM Z_CRM_EX001005 Z 
LEFT JOIN Z_CRM_ML001005 M ON 
M.CODCOLIGADA=Z.CODCOLIGADA 
AND M.CODFILIAL=Z.CODFILIAL 
AND M.IDCRIACAO=Z.IDCRIACAO 
AND M.OS=Z.OS 
WHERE M.OS='3.07867.32.001' AND Z.ITEMEXCLUSIVO!=2) R 
ORDER BY CODTRFPAI,CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)