DELETE FROM Z_CRM_EX001021 WHERE OSPROCESSO='3.07867.32.001' AND EXECUCAO=1 AND IDCRIACAOPROCESSO IN (SELECT IDCRIACAO FROM Z_CRM_EX001005 WHERE OS='3.07867.32.001' AND CODTRFPAI='1.20' AND EXECUCAO=1)

DELETE FROM Z_CRM_EX001019 WHERE OSCOMPONENTES='3.07867.32.001' AND EXECUCAO=1 AND IDCRIACAOCOMPONENTES IN (SELECT IDCRIACAO FROM Z_CRM_EX001005 WHERE OS='3.07867.32.001' AND CODTRFPAI='1.20' AND EXECUCAO=1)

DELETE FROM Z_CRM_EX001005 WHERE OS='3.07867.32.001' AND CODTRFPAI='1.20' AND EXECUCAO=1

INSERT INTO Z_CRM_EX001021 SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021')+ROW_NUMBER()OVER(ORDER BY ID) ID
,companyid,cardid,documentid,version,tableid,PRIORIDADE,IDCRIACAOPROCESSO,CODATIVIDADE,OSPROCESSO,IDPROCESSO,DESCATIVIDADE,HABILIDADEREQUERIDA,CODHABILIDADE,CODPOSTO,DESCPOSTO,FILA,
CONFIGURACAO,PROCESSAMENTO,DESAGREGACAO,ESPERA,MOVIMENTACAO,MINUTOSGASTOS,DESCPROCESSO,DOCAPOIOATV1,DOCAPOIOATV2,DOCAPOIOATV3,DOCAPOIOATV4,masterid,SOLICITACAOPROCESSO,FORNPARA,INTEGRADOPROCESSO,1 EXECUCAO,CODTRFEX,RECCREATEDBY,
RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON 
FROM Z_CRM_EX001021 WHERE OSPROCESSO='3.07867.32.001' AND EXECUCAO=2 AND IDCRIACAOPROCESSO IN (SELECT IDCRIACAO FROM Z_CRM_EX001005 WHERE OS='3.07867.32.001' AND CODTRFPAI='1.20' AND EXECUCAO=2)

INSERT INTO Z_CRM_EX001019 SELECT (SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019')+ROW_NUMBER()OVER(ORDER BY ID) ID,companyid,cardid,documentid,version,tableid,PRODUTOCOMPONENTES,IDPRDCOMPONENTES,CODIGOPRDCOMPONENTES,CODUNDCOMPONENTES,IDCRIACAOCOMPONENTES,QTDEUNCOMPONENTES,
QTDETOTALCOMPONENTES,SUBSTITUTOCOMPONENTES,INSUMOCOMPONENTES,LISTACOMPONENTES,masterid,IDCOMPONENTES,OSCOMPONENTES,SOLICITACAOCOMPONENTES,INTEGRADOCOMPONENTES,PRIORIDADEATVCOMPONENTES,1 EXECUCAO,
CODTRFEX,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON 
FROM Z_CRM_EX001019 WHERE OSCOMPONENTES='3.07867.32.001' AND EXECUCAO=2 AND IDCRIACAOCOMPONENTES IN (SELECT IDCRIACAO FROM Z_CRM_EX001005 WHERE OS='3.07867.32.001' AND CODTRFPAI='1.20' AND EXECUCAO=2)

INSERT INTO Z_CRM_EX001005 SELECT 
(SELECT VALAUTOINC FROM CORPORE.dbo.GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001005')+ROW_NUMBER()OVER(ORDER BY ID) ID
,companyid,cardid,documentid,version,tableid,TITULOITEM,NIVEL,POSICAO,DESCRICAO,NUMDESENHO,REVISAODESENHO,NUMDBI,REVISAODBI,DESQTDE,TOTALQTDE,BITOLAESP,LARGURAMASSA,ESPLARGURAROSCA,COMPRIMENTO,
MATERIAL,PESO,OBSERVACOES,TIPO,SEQ,masterid,PESOMATERIAL,OS,DATAREVISAO,PESOBRUTO,PESOLIQUIDO,OBSERVACOESDESENHO,PERIMETROCORTE,AREAPINTURA,OBSPROCESSO,OBSGERAL,QUANTIDADEMATERIAL,TIPODESENHO,
POSICAOCOMPLETA,ESPESSURA,BITOLA,LARGURA,MASSALINEAR,DIAMETROEXTERNO,DIAMETROINTERNO,ESPROSCA,POSICAOCOMPLETAANTIGA,NOVOMATERIAL,MATERIAL_ZOOM,IDMATERIAL,CODIGOPRD,INDICE,POSICAOESTRUTURA,
POSICAODESENHO,AREASECAO,ALTURA,LARGURAMESA,ESPALMA,ESPMESA,POSICAOINDICE,INDICEANTIGO,IDCRIACAO,PRODUTORM,IDPRD,EXPANSOR,CODIGOPRDMATERIAL,CODTRFOS,UNDMEDIDA,ORDEM,LARGURAABA,ESPABA,INTEGRADO,
DSCTRFOS,SOLICITACAO,PAIDETALHADO,COMPORLISTA,CODTRFITEM,IDTRFITEM,NOMETRFITEM,CODIGOTAREFADESC,IDPRJOS,DESCOS,DETALHADO,NUMDOCDELP,REVISAODOCDELP,CODCOLIGADA,DIAMETROEXTERNODISCO,DIAMETROINTERNODISCO,
CHECKUSINAGEM,CHECKCALDERARIA,CODFILIAL,CODTRFPAI,EXECINTEGRADAS,IDTRFPAI,NOMETRFPAI,EXECUCOES,PESOUNITARIO,OPSUNITARIAS,QTDEUNCOMP,OP,1 EXECUCAO,CODTRFEX,IDCRIACAOPAI,ITEMEXCLUSIVO,RECCREATEDBY,
RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON,PESOUNLIQUIDO,ITEMDERETORNO
FROM Z_CRM_EX001005 WHERE OS='3.07867.32.001' AND CODTRFPAI='1.20' AND EXECUCAO=2

UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_ML001005 UNION ALL SELECT ID FROM Z_CRM_EX001005) AS MLS) 
WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001005' AND CODSISTEMA = 'K'

UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_ML001019 UNION ALL SELECT ID FROM Z_CRM_EX001019) AS MLS) 
WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019' AND CODSISTEMA = 'K'

UPDATE CORPORE.dbo.GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT ID FROM Z_CRM_ML001021 UNION ALL SELECT ID FROM Z_CRM_EX001021) AS MLS) 
WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021' AND CODSISTEMA = 'K'