SELECT * FROM KATVORDEMMP WHERE CODORDEM='68054/23'


--INSERT INTO FLUIG.DBO.Z_CRM_EX001019 			
--SELECT (SELECT VALAUTOINC FROM CORPORE.DBO.GAUTOINC WHERE CODSISTEMA = 'K' AND CODAUTOINC = 'Z_CRM_ML001019')+ROW_NUMBER()OVER (ORDER BY M.ID) ID,
--M.COMPANYID,M.CARDID,M.DOCUMENTID,M.VERSION,M.TABLEID,M.PRODUTOCOMPONENTES,M.IDPRDCOMPONENTES,M.CODIGOPRDCOMPONENTES,M.CODUNDCOMPONENTES,
--		M.IDCRIACAOCOMPONENTES,M.QTDEUNCOMPONENTES,M.QTDETOTALCOMPONENTES,M.SUBSTITUTOCOMPONENTES,M.INSUMOCOMPONENTES,M.LISTACOMPONENTES,M.MASTERID,
--		M.IDCOMPONENTES,M.OSCOMPONENTES,M.SOLICITACAOCOMPONENTES,M.INTEGRADOCOMPONENTES,M.PRIORIDADEATVCOMPONENTES, I.EXECUCAO, NULL,M.RECCREATEDBY,
--		M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
--FROM  FLUIG.DBO.Z_CRM_ML001019 M  (NOLOCK)
--	INNER JOIN FLUIG.DBO.Z_CRM_EX001005 I (NOLOCK) ON I.OS = M.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = I.IDCRIACAO
--	LEFT JOIN FLUIG.DBO.Z_CRM_EX001021 P (NOLOCK) ON  I.OS = P.OSPROCESSO AND P.IDCRIACAOPROCESSO = I.IDCRIACAO AND M.PRIORIDADEATVCOMPONENTES = P.PRIORIDADE AND P.EXECUCAO = I.EXECUCAO
--	LEFT JOIN FLUIG.DBO.Z_CRM_EX001019 E (NOLOCK) ON M.OSCOMPONENTES = E.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = E.IDCRIACAOCOMPONENTES AND M.PRIORIDADEATVCOMPONENTES = E.PRIORIDADEATVCOMPONENTES AND M.IDPRDCOMPONENTES = E.IDPRDCOMPONENTES  AND E.EXECUCAO = I.EXECUCAO
--WHERE P.ID IS NULL AND  E.ID IS NULL AND M.OSCOMPONENTES = '3.07883.32.001' AND  I.CODTRFPAI = '1.28' AND I.EXECUCAO = 1--AND I.ITEMEXCLUSIVO = 0


INSERT INTO KATVORDEMMP
		SELECT 
		(SELECT VALAUTOINC 
		FROM GAUTOINC  (NOLOCK)
		WHERE CODAUTOINC = 'IDATVORDEMMATERIAPRIMA' 
		AND CODSISTEMA = 'K' 
		AND CODCOLIGADA = 0) + ROW_NUMBER() OVER (ORDER BY C.CODCOLIGADA) ID, 
	A.CODCOLIGADA, A.CODORDEM, A.CODESTRUTURA, A.CODMODELO, A.IDATVORDEM, A.DTHRINICIOPREV DTAPONTAMENTO, C.IDPRD, NULL NSEQITMGRD, ISNULL(C.QTD,0) * ISNULL(I.QTDEPLANEJADA,0) QTD,
	0 EFETIVADO, NULL IDLOTE, A.CODFILIAL, ISNULL(C.QTD,0), 0 QTFIXA, 
		ISNULL((SELECT SALDOGERALFISICO FROM TPRD (NOLOCK) WHERE CODCOLIGADA = A.CODCOLIGADA AND  IDPRD = C.IDPRD),0) ESTOQUE, 'fluig',GETDATE(), 'fluig', GETDATE(),
	NULL ESTOQUETERCEIRO, NULL CODCOLCFO, NULL CODCFO, NULL CODFILIALMP, NULL CODLOCAL
	FROM (
			SELECT  CODCOLIGADA, CODIGOPRD, IDPRD, QTD,
						ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
								) CODATIVIDADE,
					COMPONENTES.CODFILIAL, EXECUCAO, CODTRFPAI, NUMPROCESSO, ITEMEXCLUSIVO
			FROM (
				SELECT I.ITEMEXCLUSIVO, I.CODIGOPRD, E.IDPRD,  CAST(E.DESQTDE AS float) QTD, I.NIVEL, I.INDICE, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) E ON I.OS = E.OS AND I.INDICE = E.NIVEL  AND E.EXECUCAO = I.EXECUCAO
				WHERE E.ITEMEXCLUSIVO <> 2 AND Z.NUMPROCESSO = 107646 AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0  AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )

				UNION ALL
		
				SELECT I.ITEMEXCLUSIVO, I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO 
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND Z.NUMPROCESSO = 107646
			
				UNION ALL

					-- CODIGOS NÃO MANUFATURADO
				SELECT I.ITEMEXCLUSIVO, P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT)  QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) P ON I.OS = P.OS AND I.NIVEL = P.INDICE  AND P.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND Z.NUMPROCESSO = 107646 AND I.TIPODESENHO = 'NAOMANUFATURADO' 

			
			) AS COMPONENTES
			WHERE IDPRD <> ''
			AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			) AS C

			INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE C.CODIGOPRD+';'+C.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(C.EXECUCAO AS varchar(10))+'/'+C.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
			INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
			INNER JOIN KATVORDEM (NOLOCK) A ON O.CODCOLIGADA = A.CODCOLIGADA AND O.CODFILIAL = A.CODFILIAL AND O.CODORDEM = A.CODORDEM AND C.CODATIVIDADE = A.CODATIVIDADE
			LEFT JOIN KATVORDEMMP (NOLOCK) MP ON MP.CODCOLIGADA = O.CODCOLIGADA AND MP.CODFILIAL = O.CODFILIAL AND MP.CODORDEM = O.CODORDEM AND A.IDATVORDEM = MP.IDATIVIDADE AND MP.IDPRODUTO = C.IDPRD AND MP.EFETIVADO = 0
	WHERE MP.CODCOLIGADA IS NULL AND O.RESPONSAVEL LIKE '%;'+CAST(107646 AS VARCHAR(10))+'-%';

	SELECT * FROM FLUIG.DBO.ML001004 WHERE NUM_OS='3.07883.32.001'