CREATE TABLE ZEXECUCAOCOMPL (
ID INT IDENTITY(1,1),
OS VARCHAR(25) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
CODTRFPAI VARCHAR(4) COLLATE SQL_Latin1_General_CP1_CI_AI,
CODORDEM VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AI,
EXECUCAO INT NOT NULL,
IDCRIACAO INT NOT NULL ,
CODCECULA INT,
DESCCELULA VARCHAR(70) COLLATE SQL_Latin1_General_CP1_CI_AI,
TAG VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AI,
RECCREATEDBY VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE(),
RECMODIFIEDBY VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
RECMODIFIEDON DATETIME NOT NULL DEFAULT GETDATE(),
CONSTRAINT PK_IDCRIACAOEXCOMPL PRIMARY KEY ( OS,CODORDEM ),
CONSTRAINT FK_IDCRIACAOEXCOMPL FOREIGN KEY ( OS,EXECUCAO,IDCRIACAO ) REFERENCES ZEXECUCAO (OS,EXECUCAO,IDCRIACAO),
INDEX IDCRIACAO2 (OS,CODTRFPAI,EXECUCAO,IDCRIACAO),
INDEX IDCRIACAO (OS,EXECUCAO,IDCRIACAO),
INDEX CODORDEM (CODORDEM),
INDEX ORDEM (OS,EXECUCAO,CODORDEM)
)


CREATE TABLE Z_CRM_EX001005COMPL (
ID INT IDENTITY(1,1),
CODCOLIGADA INT,
CODFILIAL INT,
OS VARCHAR(25) NOT NULL,
CODTRFPAI VARCHAR(4),
CODORDEM VARCHAR(30) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI,
EXECUCAO INT NOT NULL,
IDCRIACAO INT NOT NULL ,
CODCECULA INT,
DESCCELULA VARCHAR(70) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI,
TAG VARCHAR(15) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI,
RECCREATEDBY VARCHAR(50) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOT NULL,
RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE(),
RECMODIFIEDBY VARCHAR(50) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOT NULL,
RECMODIFIEDON DATETIME NOT NULL DEFAULT GETDATE(),
CONSTRAINT PK_IDCRIACAOEXCOMPL PRIMARY KEY ( OS,CODORDEM ),
CONSTRAINT FK_IDCRIACAOEXCOMPL FOREIGN KEY ( OS,EXECUCAO,IDCRIACAO) REFERENCES Z_CRM_EX001005 (OS,EXECUCAO,IDCRIACAO),
INDEX IDCRIACAO2 (OS,CODTRFPAI,EXECUCAO,IDCRIACAO),
INDEX IDCRIACAO (OS,EXECUCAO,IDCRIACAO),
INDEX CODORDEM (CODORDEM),
INDEX ORDEM (OS,EXECUCAO,CODORDEM)
)

INSERT INTO Z_CRM_EX001005COMPL
SELECT distinct Z.CODCOLIGADA,Z.CODFILIAL,Z.OS,Z.CODTRFPAI,K.CODORDEM,Z.EXECUCAO,Z.IDCRIACAO,C.CODCLIENTE,C.DESCRICAO,MTC.TAG,'fluig',GETDATE(),'fluig',GETDATE() FROM Z_CRM_EX001005 Z
INNER JOIN CORPORE_DEV.DBO.KITEMORDEM K ON
K.CODCOLIGADA=Z.CODCOLIGADA
AND K.CODFILIAL=Z.CODFILIAL
AND K.CODESTRUTURA=Z.CODIGOPRD COLLATE LATIN1_GENERAL_CI_AS
AND K.CODCCUSTO=Z.OS COLLATE LATIN1_GENERAL_CI_AS
INNER JOIN CORPORE_DEV.DBO.KORDEMCOMPL KL ON 
KL.CODCOLIGADA=K.CODCOLIGADA
AND KL.CODFILIAL=K.CODFILIAL
AND KL.CODORDEM=K.CODORDEM
AND KL.NUMEXEC=Z.EXECUCAO
INNER JOIN CORPORE_DEV.DBO.MPRJ M ON
M.CODCOLIGADA=K.CODCOLIGADA
AND M.CODFILIAL=K.CODFILIAL
AND M.CODPRJ=K.CODCCUSTO
AND M.POSICAO IN (1,4)
LEFT JOIN CORPORE_DEV.DBO.MTRF MT ON
MT.CODCOLIGADA=M.CODCOLIGADA
AND MT.IDPRJ=M.IDPRJ
AND MT.CODTRFAUX=K.CODORDEM
LEFT JOIN CORPORE_DEV.DBO.MTRFCOMPL MTC ON
MT.CODCOLIGADA=MTC.CODCOLIGADA
AND MT.IDPRJ=MTC.IDPRJ
AND MT.IDTRF=MTC.IDTRF
LEFT JOIN CORPORE_DEV.DBO.GCONSIST C ON 
C.CODTABELA = 'CELULA'
AND C.APLICACAO = 'M'
AND C.CODINTERNO = MTC.CELULA
WHERE Z.ITEMEXCLUSIVO!=2 