CREATE TABLE ZESTRUTURACOMPL (
ID INT IDENTITY(1,1) NOT NULL,
OS VARCHAR(25) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
CODORDEM VARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AI,
EXECUCAO INT NOT NULL,
IDCRIACAO INT NOT NULL ,
CODCECULA INT,
DESCCELULA VARCHAR(70) COLLATE SQL_Latin1_General_CP1_CI_AI,
TAG VARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AI,
RECCREATEDBY VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
RECCREATEDON DATETIME NOT NULL DEFAULT GETDATE(),
RECMODIFIEDBY VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
RECMODIFIEDON DATETIME NOT NULL DEFAULT GETDATE(),
CONSTRAINT PK_IDCRIACAOEX PRIMARY KEY ( OS,EXECUCAO,CODORDEM ),
CONSTRAINT FK_IDCRIACAOEX FOREIGN KEY ( OS,EXECUCAO,IDCRIACAO ) REFERENCES ZESTRUTURAEX (OS,EXECUCAO,IDCRIACAO),
INDEX IDCRIACAO (OS,EXECUCAO,IDCRIACAO),
INDEX ORDEM (OS,EXECUCAO,CODORDEM,IDCRIACAO)
)
