
DROP TABLE [Z_DELP_PROJECAOTAREFA]
CREATE TABLE [dbo].[Z_DELP_PROJECAOTAREFA](
	[CODCOLIGADA] [int] NULL,
	[CODPRJ] [varchar](30) NULL,
	[IDTRF] [int] NULL,
	[QUANTIDADE] [decimal](22, 4) NULL,
	[VALORTOTAL] [decimal](22, 4) NULL,
	[SCQTDSALDO] [decimal](22, 4) NULL,
	[SCQTDTOTAL] [decimal](22, 4) NULL,
	[SCVALORSALDO] [decimal](22, 4) NULL,
	[SCVALORTOTAL] [decimal](22, 4) NULL,
	[OCQTDSALDO] [decimal](22, 4) NULL,
	[OCQTDTOTAL] [decimal](22, 4) NULL,
	[OCVALORSALDO] [decimal](22, 4) NULL,
	[OCVALORTOTAL] [decimal](22, 4) NULL,
	[NFQTDSALDO] [decimal](22, 4) NULL,
	[NFQTDTOTAL] [decimal](22, 4) NULL,
	[NFVALORSALDO] [decimal](22, 4) NULL,
	[NFVALORTOTAL] [decimal](22, 4) NULL,
	[QTDAPONTAMENTO] [decimal](22, 4) NULL,
	[VALORAPONTAMENTO] [decimal](22, 4) NULL,
	[QTDSALDO] [decimal](22, 4) NULL,
	[VALORSALDO] [decimal](22, 4) NULL,
	[QTDPROJETADO] [decimal](22, 4) NULL,
	[VALORPROJETADO] [decimal](22, 4) NULL,
	[PERIODO] [varchar](20) NULL,
	[VALOR] [decimal](22, 4) NULL,
    [PRECO] [decimal](22, 4) NULL,
	[MOTIVO] [varchar](max) NULL,
	[SEQ] [int] NULL,
	[RECCREATEDBY] [varchar](50) NULL,
	[RECCREATEDON] [datetime] NULL
) 

CREATE INDEX PROJECAO_TAREFA_ ON Z_DELP_PROJECAOTAREFA(CODCOLIGADA,CODPRJ,IDTRF)
CREATE INDEX PROJECAO_TAREFA_DATA ON Z_DELP_PROJECAOTAREFA(CODCOLIGADA,CODPRJ,IDTRF,PERIODO)
CREATE INDEX PROJECAO_TAREFA_DATA_SEQ ON Z_DELP_PROJECAOTAREFA(CODCOLIGADA,CODPRJ,IDTRF,PERIODO,SEQ)

DROP TABLE [Z_DELP_PROJECAOPRODUTO]
CREATE TABLE [dbo].[Z_DELP_PROJECAOPRODUTO](
	[CODCOLIGADA] [int] NULL,
	[CODPRJ] [varchar](30) NULL,
	[IDTRF] [int] NULL,
	[IDPRD] [int] NULL,
	[SCQTDSALDO] [decimal](22, 4) NULL,
	[SCQTDTOTAL] [decimal](22, 4) NULL,
	[SCVALORSALDO] [decimal](22, 4) NULL,
	[SCVALORTOTAL] [decimal](22, 4) NULL,
	[OCQTDSALDO] [decimal](22, 4) NULL,
	[OCQTDTOTAL] [decimal](22, 4) NULL,
	[OCVALORSALDO] [decimal](22, 4) NULL,
	[OCVALORTOTAL] [decimal](22, 4) NULL,
	[NFQTDSALDO] [decimal](22, 4) NULL,
	[NFQTDTOTAL] [decimal](22, 4) NULL,
	[NFVALORSALDO] [decimal](22, 4) NULL,
	[NFVALORTOTAL] [decimal](22, 4) NULL,
	[QTDAPONTAMENTO] [decimal](22, 4) NULL,
	[VALORAPONTAMENTO] [decimal](22, 4) NULL,
	[VALORTOTAL] [decimal](22, 4) NULL,
	[QTDSALDO] [decimal](22, 4) NULL,
	[VALORSALDO] [decimal](22, 4) NULL,
	[QTDPROJETADO] [decimal](22, 4) NULL,
	[VALORPROJETADO] [decimal](22, 4) NULL,
	[PERIODO] [varchar](20) NULL,
	[VALOR] [decimal](22, 4) NULL,
    [PRECO] [decimal](22, 4) NULL,
	[MOTIVO] [varchar](max) NULL,
	[SEQ] [int] NULL,
	[RECCREATEDBY] [varchar](50) NULL,
	[RECCREATEDON] [datetime] NULL
) 

CREATE INDEX PROJECAO_TAREFA_PRODUTO ON Z_DELP_PROJECAOPRODUTO(CODCOLIGADA,CODPRJ,IDTRF,IDPRD)
CREATE INDEX PROJECAO_TAREFA_PRODUTO_DATA ON Z_DELP_PROJECAOPRODUTO(CODCOLIGADA,CODPRJ,IDTRF,IDPRD,PERIODO)
CREATE INDEX PROJECAO_TAREFA_PRODUTO_DATA_SEQ ON Z_DELP_PROJECAOPRODUTO(CODCOLIGADA,CODPRJ,IDTRF,IDPRD,PERIODO,SEQ)



