

SELECT 
				ISNULL(SUM(CUSTOEFETIVADO),0) SOMA_CUSTO, ISNULL(I.QTDEEFETIVADA,0) QTDE,   
				ISNULL((SELECT  
				SUM(ROUND(CAST(QTDHORAS AS FLOAT),4)) 
			FROM 
				ZMDKATVORDEMPROGRAMACAO (NOLOCK) X 
			WHERE 
				X.CODORDEM = I.CODORDEM AND X.CODCOLIGADA = I.CODCOLIGADA AND X.CODFILIAL = I.CODFILIAL AND X.STATUS = 1 AND X.IDATVORDEM = A.IDATVORDEM 
			),0) 
			 +  
			ISNULL((SELECT  
					SUM(ROUND(CAST(DATEDIFF(minute,X.DTHRINICIAL,X.DTHRFINAL)AS FLOAT)/60.0000,4)) 		
				FROM 
					KMAOOBRAALOC (NOLOCK) X 	
				WHERE 
					X.CODORDEM = I.CODORDEM AND X.CODCOLIGADA = I.CODCOLIGADA AND X.CODFILIAL = I.CODFILIAL AND X.EFETIVADO = 1 AND X.IDATVORDEM = A.IDATVORDEM 
			),0) 
				HORAS_APONTADAS 
			FROM 
				KITEMORDEM I 
				INNER JOIN KATVORDEM A ON  A.CODORDEM = I.CODORDEM and A.CODCOLIGADA = I.CODCOLIGADA AND A.CODFILIAL = I.CODFILIAL 
			WHERE 
				 I.CODCOLIGADA = 1 AND I.CODFILIAL = 7 
			GROUP BY 
				I.CODESTRUTURA, I.QTDEEFETIVADA, I.CODORDEM, I.CODCOLIGADA, I.CODFILIAL, A.IDATVORDEM  