--DECLARE @IDPRD INT
--SET @IDPRD=143397

--DELETE FROM TPRDCOMPL WHERE IDPRD=@IDPRD AND CODCOLIGADA=1
--DELETE FROM TPRDFIL WHERE IDPRD=@IDPRD AND CODCOLIGADA=1
--DELETE FROM TPRDFISCAL WHERE IDPRD=@IDPRD AND CODCOLIGADA=1
--DELETE FROM TPRDHISTORICO WHERE IDPRD=@IDPRD AND CODCOLIGADA=1
--DELETE FROM TPRDUND WHERE IDPRD=@IDPRD AND CODCOLIGADA=1
--DELETE FROM TPRODUTODEF WHERE IDPRD=@IDPRD AND CODCOLIGADA=1
--DELETE FROM TPRODUTO WHERE IDPRD=@IDPRD AND CODCOLPRD=1

SELECT * from ml001076 
 where NUMPROCESSO=90413
ORDER BY CAST(NUMPROCESSO AS INT)
