                    "SELECT "+
					"		DISTINCT PL.NUMLOTE, PL.IDLOTE, PL.DATAVALIDADE,E.SALDOFISICO2,P.CONTROLADOPORLOTE, P.IDPRD, P.CODIGOPRD, P.DESCRICAO "+
					"	FROM "+
					"		TPRD P "+
					"		INNER JOIN TLOTEPRD PL ON P.CODCOLIGADA = PL.CODCOLIGADA AND P.IDPRD = PL.IDPRD AND PL.IDSTATUS=6 "+
					"		INNER JOIN TLOTEPRDLOC E ON P.CODCOLIGADA = E.CODCOLIGADA AND P.IDPRD = E.IDPRD AND PL.IDLOTE=E.IDLOTE AND E.CODLOC IN ('21','22','23','25','27') "+
					"		INNER JOIN KCOMPONENTE KC ON P.CODCOLIGADA = KC.CODCOLIGADA AND E.CODFILIAL = KC.CODFILIAL AND P.IDPRD = KC.IDPRODUTO "+
					"		INNER JOIN KESTRUTURA KE ON P.CODCOLIGADA = KE.CODCOLIGADA AND E.CODFILIAL = KE.CODFILIAL AND KC.CODESTRUTURA = KE.CODESTRUTURA "+
					"	WHERE "+
					"		"+idprd+" "+
					"		"+numOS+" "+
					"		"+codFilial+" "	+ "	AND (P.CODIGOPRD LIKE '01.%' OR P.CODIGOPRD LIKE '02.%' OR P.CODIGOPRD LIKE '03.%') "+
					"UNION ALL "+
					"SELECT "+
					"		DISTINCT PL.NUMLOTE, PL.IDLOTE, PL.DATAVALIDADE,E.SALDOFISICO2,P.CONTROLADOPORLOTE, P.IDPRD, P.CODIGOPRD, P.DESCRICAO "+
					"	FROM "+
					"		TPRD P "+
					"		INNER JOIN TLOTEPRD PL ON P.CODCOLIGADA = PL.CODCOLIGADA AND P.IDPRD = PL.IDPRD AND PL.IDSTATUS=6 "+
					"		INNER JOIN TLOTEPRDLOC E ON P.CODCOLIGADA = E.CODCOLIGADA AND P.IDPRD = E.IDPRD AND PL.IDLOTE=E.IDLOTE AND E.CODLOC IN ('21','22','23','25','27') "+
					"		INNER JOIN KCOMPSUBSTITUTO KS ON P.CODCOLIGADA = KS.CODCOLIGADA AND E.CODFILIAL = KS.CODFILIAL AND P.IDPRD = KS.IDPRD "+
					"		INNER JOIN KESTRUTURA KE ON P.CODCOLIGADA = KE.CODCOLIGADA AND E.CODFILIAL = KE.CODFILIAL AND KC.CODESTRUTURA = KE.CODESTRUTURA "+
					"	WHERE "+
					"		"+idprd+" "+
					"		"+numOS+" "+
					"		"+codFilial+" "	+ "	AND (P.CODIGOPRD LIKE '01.%' OR P.CODIGOPRD LIKE '02.%' OR P.CODIGOPRD LIKE '03.%')   "

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
"SELECT " + 
"       DISTINCT NUMLOTE, IDLOTE, DATAVALIDADE, SALDOFISICO2, CONTROLADOPORLOTE, IDPRD, CODIGOPRD, DESCRICAO "+
"FROM   "+
"( "+
"    SELECT PL.NUMLOTE, PL.IDLOTE, PL.DATAVALIDADE,E.SALDOFISICO2,P.CONTROLADOPORLOTE, P.IDPRD, P.CODIGOPRD, P.DESCRICAO"+
"    FROM TPRD P"+ 
"    INNER JOIN TLOTEPRD PL ON P.CODCOLIGADA = PL.CODCOLIGADA AND P.IDPRD = PL.IDPRD AND PL.IDSTATUS=6 "+
"    INNER JOIN TLOTEPRDLOC E ON P.CODCOLIGADA = E.CODCOLIGADA AND P.IDPRD = E.IDPRD AND PL.IDLOTE=E.IDLOTE AND E.CODLOC IN ('21','22','23','25','27')"+
"    INNER JOIN KCOMPONENTE KC ON P.CODCOLIGADA = KC.CODCOLIGADA AND E.CODFILIAL = KC.CODFILIAL AND P.IDPRD = KC.IDPRODUTO"
"    INNER JOIN KESTRUTURA KE ON P.CODCOLIGADA = KE.CODCOLIGADA AND E.CODFILIAL = KE.CODFILIAL AND KC.CODESTRUTURA = KE.CODESTRUTURA "+
"    WHERE "+idprd+" "+numOS+" "+codFilial+" AND (P.CODIGOPRD LIKE '01.%' OR P.CODIGOPRD LIKE '02.%' OR P.CODIGOPRD LIKE '03.%') "+
"    UNION ALL "+
"    SELECT PL.NUMLOTE, PL.IDLOTE, PL.DATAVALIDADE,E.SALDOFISICO2,P.CONTROLADOPORLOTE, P.IDPRD, P.CODIGOPRD, P.DESCRICAO"+
"    FROM TPRD P "+
"    INNER JOIN TLOTEPRD PL ON P.CODCOLIGADA = PL.CODCOLIGADA AND P.IDPRD = PL.IDPRD AND PL.IDSTATUS=6 "+
"    INNER JOIN TLOTEPRDLOC E ON P.CODCOLIGADA = E.CODCOLIGADA AND P.IDPRD = E.IDPRD AND PL.IDLOTE=E.IDLOTE AND E.CODLOC IN ('21','22','23','25','27')"+
"    INNER JOIN KCOMPSUBSTITUTO KS ON P.CODCOLIGADA = KS.CODCOLIGADA AND E.CODFILIAL = KS.CODFILIAL AND P.IDPRD = KS.IDPRD"+
"    INNER JOIN KESTRUTURA KE ON P.CODCOLIGADA = KE.CODCOLIGADA AND E.CODFILIAL = KE.CODFILIAL AND KC.CODESTRUTURA = KE.CODESTRUTURA "+
"    WHERE "+idprd+" "+numOS+" "+codFilial+" AND (P.CODIGOPRD LIKE '01.%' OR P.CODIGOPRD LIKE '02.%' OR P.CODIGOPRD LIKE '03.%') "+
")  "+
"AS Z "
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
