--delete FROM KATVORDEMMP WHERE CODORDEM IN ( SELECT CODORDEM FROM KORDEM WHERE RESPONSAVEL LIKE '%;51768-2/1.19%' )
--delete FROM KATVORDEMCOMPL WHERE CODORDEM IN ( SELECT CODORDEM FROM KORDEM WHERE RESPONSAVEL LIKE '%;51768-2/1.19%' )
--delete FROM KATVORDEM WHERE CODORDEM IN ( SELECT CODORDEM FROM KORDEM WHERE RESPONSAVEL LIKE '%;51768-2/1.19%' )
--delete FROM KITEMORDEM WHERE CODORDEM IN ( SELECT CODORDEM FROM KORDEM WHERE RESPONSAVEL LIKE '%;51768-2/1.19%' )
--delete FROM KORDEMCOMPL WHERE CODORDEM IN ( SELECT CODORDEM FROM KORDEM WHERE RESPONSAVEL LIKE '%;51768-2/1.19%' )
--delete FROM KORDEM WHERE RESPONSAVEL LIKE '%;51768-2/1.19%'

-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	BEGIN TRAN;

		WITH CTE AS
		(
    
			SELECT  CODCOLIGADA,CODFILIAL,OS,IDCRIACAO,IDCRIACAOPAI,EXECUCAO,DESCRICAO,CODIGOPRD,CODTRFPAI,NOMETRFPAI,IDTRFPAI,
					CONVERT(VARCHAR(MAX),POSICAOINDICE)  COLLATE SQL_Latin1_General_CP1_CI_AI INDICE,
					CONVERT(VARCHAR(MAX),'') COLLATE SQL_Latin1_General_CP1_CI_AI NIVEL,
					 CONVERT(VARCHAR(MAX),POSICAOINDICE) COLLATE SQL_Latin1_General_CP1_CI_AI POSICAOINDICE
			FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK)
			WHERE ( IDCRIACAOPAI = 0 OR IDCRIACAOPAI='' ) AND OS=@OS AND ITEMEXCLUSIVO!=2 AND CODTRFPAI=@CODTRFPAI AND EXECUCAO=@EXECUCAO

			UNION ALL

			SELECT  T.CODCOLIGADA,T.CODFILIAL,T.OS,T.IDCRIACAO,T.IDCRIACAOPAI,T.EXECUCAO,T.DESCRICAO,T.CODIGOPRD,CTE.CODTRFPAI,CTE.NOMETRFPAI,CTE.IDTRFPAI,
					 CONVERT(VARCHAR(MAX),CONCAT(CTE.INDICE COLLATE SQL_Latin1_General_CP1_CI_AI,'.' COLLATE SQL_Latin1_General_CP1_CI_AI,CAST(ROW_NUMBER() OVER(PARTITION BY T.CODTRFPAI,T.EXECUCAO ORDER BY T.POSICAOINDICE) AS VARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AI)) COLLATE SQL_Latin1_General_CP1_CI_AI INDICE,
					 CONVERT(VARCHAR(MAX),CTE.INDICE) COLLATE SQL_Latin1_General_CP1_CI_AI, 
					 CONVERT(VARCHAR(MAX),ROW_NUMBER() OVER(PARTITION BY T.CODTRFPAI,T.EXECUCAO ORDER BY T.POSICAOINDICE)) COLLATE SQL_Latin1_General_CP1_CI_AI
			FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) T
			INNER JOIN CTE ON T.IDCRIACAOPAI = CTE.IDCRIACAO AND T.EXECUCAO=CTE.EXECUCAO AND T.OS=CTE.OS 
			WHERE T.OS=@OS AND T.ITEMEXCLUSIVO!=2 AND T.EXECUCAO=@EXECUCAO

		)

		SELECT * INTO #CTE FROM CTE

	COMMIT;

	BEGIN TRAN;

		UPDATE Z SET Z.INDICE=Z2.INDICE,Z.NIVEL=Z2.NIVEL,Z.POSICAOINDICE=Z2.POSICAOINDICE,
		Z.CODTRFPAI=Z2.CODTRFPAI,Z.NOMETRFPAI=Z2.NOMETRFPAI,Z.IDTRFPAI=Z2.IDTRFPAI
		FROM Z_CRM_EX001005 (NOLOCK) Z 
		INNER JOIN #CTE Z2 ON Z.CODCOLIGADA=Z2.CODCOLIGADA AND Z.CODFILIAL=Z2.CODFILIAL AND Z.OS=Z2.OS AND Z.IDCRIACAO=Z2.IDCRIACAO AND Z.EXECUCAO=Z2.EXECUCAO
		WHERE Z.OS=@OS AND Z.ITEMEXCLUSIVO!=2 AND Z.EXECUCAO=@EXECUCAO;

	COMMIT;

	DROP TABLE #CTE

	EXEC SP_DELP_ATUALIZAQTDES_EX @OS,@EXECUCAO,@CODTRFPAI;