USE [CORPORE]
GO
/****** Object:  UserDefinedFunction [dbo].[FN_DELP_RETORNA_APONT_LOTE]    Script Date: 14/08/2024 09:28:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[FN_DELP_RETORNA_APONT_LOTE]
(	
	@CODCOLIGADA INT,
	@IDLOTE INT=NULL,
	@NUMLOTE VARCHAR(50)=NULL
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
		SUM(TL.QUANTIDADE2 * TI.PRECOUNITARIO) VALOR,
		SUM(TL.QUANTIDADE2) QUANTIDADE,
		TL.IDLOTE,
		T.CODCOLIGADA
	FROM
		TMOV T
		INNER JOIN TITMMOV TI ON T.CODCOLIGADA = TI.CODCOLIGADA
		AND T.IDMOV = TI.IDMOV
		INNER JOIN TITMLOTEPRD TL ON TL.CODCOLIGADA = TI.CODCOLIGADA
		AND TL.IDMOV = TI.IDMOV
		AND TL.NSEQITMMOV = TI.NSEQITMMOV
	WHERE
		T.CODTMV LIKE '2.2%'
		AND T.STATUS NOT IN ('C')
		AND TL.IDLOTE=ISNULL(@IDLOTE,(SELECT IDLOTE FROM TLOTEPRD WHERE NUMLOTE=@NUMLOTE))
	GROUP BY
		IDLOTE,
		T.CODCOLIGADA
)
