USE [CORPORE]
GO
/****** Object:  UserDefinedFunction [dbo].[FN_DELP_RETORNA_HORAS]    Script Date: 14/08/2024 09:28:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		RAFAEL.GRANJA
-- Create date: 13/08/2024
-- Description:	FUNCAO PARA RETORNAR HORAS
-- =============================================
CREATE FUNCTION [dbo].[FN_DELP_RETORNA_HORAS]
(	
	@CODCOLIGADA INT,
	@CODFILIAL INT,
	@CODORDEM VARCHAR(30),
	@IDATVORDEM INT=NULL
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT SUM(APONTADO) APONTADO,SUM(PREVISTO) PREVISTO,SUM(PROGRAMADO) PROGRAMADO FROM (
		SELECT SUM(CAST(DATEDIFF(SECOND, DTHRINICIAL, DTHRFINAL) AS BIGINT)/60.0) APONTADO,0 PREVISTO,0 PROGRAMADO
		FROM KMAOOBRAALOC
		WHERE CODCOLIGADA=@CODCOLIGADA AND CODFILIAL=@CODFILIAL AND CODORDEM=@CODORDEM AND IDATVORDEM=ISNULL(@IDATVORDEM,IDATVORDEM) AND EFETIVADO=1
		UNION
		SELECT 0,SUM(CAST(TEMPO AS BIGINT)),0
		FROM KATVORDEM
		WHERE CODCOLIGADA=@CODCOLIGADA AND CODFILIAL=@CODFILIAL AND CODORDEM=@CODORDEM AND IDATVORDEM=ISNULL(@IDATVORDEM,IDATVORDEM)
		UNION 
		SELECT 0,0,SUM(CAST(DATEDIFF(SECOND, DTHRINICIAL, DTHRFINAL) AS BIGINT)/60.0)
		FROM ZMDKATVORDEMPROGRAMACAO
		WHERE CODCOLIGADA=@CODCOLIGADA AND CODFILIAL=@CODFILIAL AND CODORDEM=@CODORDEM AND IDATVORDEM=ISNULL(@IDATVORDEM,IDATVORDEM) AND STATUS!=2
		) R
)
