USE [CORPORE]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_DELP_RETORNA_PLANOS]    Script Date: 14/08/2024 09:29:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		RAFAEL.GRANJA
-- Create date: 13/08/2024
-- Description:	FUNCAO PARA RETORNAR HORAS
-- =============================================
CREATE FUNCTION [dbo].[FN_DELP_RETORNA_PLANOS]
(	
	@CODCOLIGADA INT,
	@CODFILIAL INT,
	@CODORDEM VARCHAR(30)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT (
		SELECT CONCAT(NUMPLANOCORTE  COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI,', '  COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI,CHAR(10) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI)  
		FROM CORPORE.DBO.ZMDPLANOAPROVEITAMENTOCORTE WHERE CODCOLIGADA=@CODCOLIGADA AND CODFILIAL=@CODFILIAL AND CODORDEM=@CODORDEM
		FOR XML PATH(''),ELEMENTS ) PAPC
)
GO

