;WITH CTE AS
(
    
    SELECT  CODCOLIGADA,CODFILIAL,OS,IDCRIACAO,IDCRIACAOPAI,EXECUCAO,DESCRICAO,CODIGOPRD,CODTRFPAI,NUMDESENHO,POSICAODESENHO,TOTALQTDE,
            CONVERT(VARCHAR(MAX),ROW_NUMBER() OVER(PARTITION BY EXECUCAO ORDER BY POSICAOINDICE)) INDICE
    FROM FLUIG.DBO.Z_CRM_EX001005 
    WHERE OS='3.07840.32.001' AND ITEMEXCLUSIVO!=2  AND CODTRFPAI='1.20' AND EXECUCAO=1 AND IDCRIACAOPAI=''

    UNION ALL

    SELECT  T.CODCOLIGADA,T.CODFILIAL,T.OS,T.IDCRIACAO,T.IDCRIACAOPAI,T.EXECUCAO,T.DESCRICAO,T.CODIGOPRD,T.CODTRFPAI,T.NUMDESENHO,T.POSICAODESENHO,T.TOTALQTDE,
             CONVERT(VARCHAR(MAX),CONCAT(CTE.INDICE,'.',ROW_NUMBER() OVER(PARTITION BY T.EXECUCAO ORDER BY T.POSICAOINDICE))) INDICE
    FROM FLUIG.DBO.Z_CRM_EX001005 T
    INNER JOIN CTE ON  T.EXECUCAO=CTE.EXECUCAO AND T.OS=CTE.OS  AND T.CODTRFPAI=CTE.CODTRFPAI AND T.IDCRIACAOPAI = CTE.IDCRIACAO
	WHERE T.OS='3.07840.32.001' AND T.CODTRFPAI='1.20' AND T.EXECUCAO=1 AND T.IDCRIACAOPAI = CTE.IDCRIACAO

), 
CTE2 AS (
	SELECT CODCOLIGADA,CODFILIAL,CODORDEM,MAX(TEMPO) TEMPO FROM (
		SELECT CODCOLIGADA,CODFILIAL,CODORDEM,SUM(TEMPO)TEMPO FROM KATVORDEM 
		GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM
		UNION
		SELECT CODCOLIGADA,CODFILIAL,CODORDEM,SUM(CAST(DATEDIFF(SECOND,DTHRINICIAL,DTHRFINAL) AS BIGINT))/60 TEMPO FROM KMAOOBRAALOC  
		WHERE EFETIVADO=0
		GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM
	) R 
	GROUP BY CODCOLIGADA,CODFILIAL,CODORDEM 
)


SELECT IDCRIACAO,COALESCE(IDCRIACAOPAI,0) IDCRIACAOPAI,DESCRICAO,KI.CODORDEM,
CONVERT(VARCHAR(10),ISNULL(R2.DTHRINICIAL,ISNULL(PA.DTHRINICIAL,KI.DTHRINICIALPREV)),103) DTHRINICIAL,

CONVERT(VARCHAR(10),ISNULL(ISNULL(
CASE WHEN KI.DTHRFINALEFET>UA.DTHRINICIAL THEN KI.DTHRFINALEFET 
ELSE UA.DTHRINICIAL END,
DATEADD(MINUTE,CAST(C2.TEMPO AS INT),CAST(R2.DTHRINICIAL AS datetime))),DATEADD(MINUTE,CAST(C2.TEMPO AS INT),CAST(ISNULL(R2.DTHRINICIAL,ISNULL(PA.DTHRINICIAL,KI.DTHRINICIALPREV)) AS datetime))) 
,103) DTHRFINAL,
CAST(C2.TEMPO AS INT) TEMPO
FROM CTE Z
INNER JOIN KITEMORDEM KI ON 
KI.CODCOLIGADA=Z.CODCOLIGADA 
AND KI.CODFILIAL=Z.CODFILIAL 
AND KI.CODESTRUTURA=Z.CODIGOPRD COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI 
INNER JOIN KORDEMCOMPL KL ON 
KL.CODCOLIGADA=KI.CODCOLIGADA 
AND KL.CODFILIAL=KI.CODFILIAL 
AND KL.CODORDEM=KI.CODORDEM 
AND KL.NUMEXEC=Z.EXECUCAO 
LEFT JOIN ( -- PRIMEIRA PROGRAMACAO
	SELECT CODFILIAL,CODCOLIGADA,DTHRINICIAL,CODORDEM,ROW_NUMBER()OVER(PARTITION BY CODCOLIGADA,CODFILIAL,CODORDEM ORDER BY DTHRINICIAL) ORD
	FROM(
	SELECT CODFILIAL,CODCOLIGADA,DTHRINICIAL,CODORDEM FROM ZMDKATVORDEMPROGRAMACAO  WHERE STATUS!=2
	UNION
	SELECT CODFILIAL,CODCOLIGADA,DTHRINICIAL,CODORDEM FROM KMAOOBRAALOC  WHERE EFETIVADO=0
	) R 
) R2 ON R2.CODORDEM=KI.CODORDEM AND R2.CODCOLIGADA=Z.CODCOLIGADA AND R2.CODFILIAL=Z.CODFILIAL 
LEFT JOIN ( --ULTIMO APONTAMENTO 
	SELECT CODFILIAL,CODCOLIGADA,DTHRINICIAL,CODORDEM,ROW_NUMBER()OVER(PARTITION BY CODCOLIGADA,CODFILIAL,CODORDEM ORDER BY DTHRINICIAL DESC) ORD
	FROM KMAOOBRAALOC  WHERE EFETIVADO=1
) UA ON UA.CODORDEM=KI.CODORDEM AND UA.CODCOLIGADA=Z.CODCOLIGADA AND UA.CODFILIAL=Z.CODFILIAL 
LEFT JOIN CTE2 C2 ON C2.CODCOLIGADA=KI.CODCOLIGADA AND C2.CODFILIAL=KI.CODFILIAL AND C2.CODORDEM=KI.CODORDEM
LEFT JOIN ( --PRIMEIRO APONTAMENTO 
	SELECT CODFILIAL,CODCOLIGADA,DTHRINICIAL,CODORDEM,ROW_NUMBER()OVER(PARTITION BY CODCOLIGADA,CODFILIAL,CODORDEM ORDER BY DTHRINICIAL) ORD
	FROM KMAOOBRAALOC  WHERE EFETIVADO=1
) PA ON PA.CODORDEM=KI.CODORDEM AND PA.CODCOLIGADA=Z.CODCOLIGADA AND PA.CODFILIAL=Z.CODFILIAL 
WHERE ( R2.ORD=1 OR R2.ORD IS NULL ) AND ( UA.ORD=1 OR UA.ORD IS NULL ) AND ( PA.ORD=1 OR PA.ORD IS NULL ) AND KI.STATUS!=6




