USE [CORPORE]
GO
/****** Object:  StoredProcedure [dbo].[SP_CRM_INCLUITRFSOLUM]    Script Date: 23/06/2023 08:50:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_CRM_INCLUITRFSOLUM] @CODCOLIGADA INT, @IDPRJ INT, @CODORDEM VARCHAR(30) , @CODTRF VARCHAR(100)
AS
BEGIN

	DECLARE @IDTRF INT, @IDPAI INT

	SELECT @IDPAI = IDPAI , @IDTRF = IDTRF
	FROM MTAREFA T
	WHERE CODCOLIGADA = @CODCOLIGADA
	AND IDPRJ = @IDPRJ
	AND CODTRF = @CODTRF


	UPDATE MTRF SET CODTRF = LEFT(CODTRF,LEN(CODTRF)-3) + RIGHT(REPLICATE('0',3)+CAST(CAST(RIGHT(CODTRF,3) AS int)+1 AS varchar(4)),3)
	WHERE IDPRJ = @IDPRJ AND IDPAI = @IDPAI AND CODTRF >= @CODTRF

	INSERT INTO MTAREFA (CODCOLIGADA, IDPRJ, IDTRF, CODTRF, CODTRFAUX, NOME, DESCRICAO, IDPAI, ATIVA, VALOR, BLOQUEADA, SERVICO, UTILIZARVALOR,IDDISCIPLINA, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT O.CODCOLIGADA, @IDPRJ, ROW_NUMBER() OVER (ORDER BY I.NIVEL DESC)+ISNULL((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'M' AND	CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))),0),
		@CODTRF, 
		O.CODORDEM,LEFT( ISNULL(I.DESCRICAO,'')+' - POS. '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),90), ISNULL(I.DESCRICAO,'')+' - POS. '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,'') , @IDPAI, 1, 0, 0, 0, 0,null, 'fluig', GETDATE(),'fluig', GETDATE() 
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS AND I.ITEMEXCLUSIVO <> 2
		INNER JOIN KITEMORDEM (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN KORDEM (NOLOCK) O ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM AND O.RESPONSAVEL like I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS VARCHAR(MAX))+'/'+LEFT(@CODTRF,4)+'%'
	WHERE O.CODORDEM = @CODORDEM
	AND O.CODCOLIGADA = @CODCOLIGADA

	UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDTRF) FROM MTAREFA WHERE CODCOLIGADA = 1 AND IDPRJ = @IDPRJ) WHERE CODSISTEMA = 'M' AND CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))

	UPDATE P SET  QUANTIDADE = (SELECT SUM(ROUND((ISNULL(FILA,0)+ISNULL(CONFIGURACAO,0)+ISNULL(PROCESSA,0)+ISNULL(DESAGREGACAO,0)+ISNULL(ESPERA,0)+ISNULL(MOVIMENTACAO,0))/60,2)*K.QTDEPLANEJADA)
									FROM KITEMORDEM (NOLOCK) K
										INNER JOIN KATVESTRUTURA (NOLOCK) A ON A.CODCOLIGADA = K.CODCOLIGADA AND A.CODESTRUTURA = K.CODESTRUTURA AND A.CODFILIAL = K.CODFILIAL
									WHERE K.CODCOLIGADA = P.CODCOLIGADA AND K.CODFILIAL = M.CODFILIAL AND K.CODORDEM = P.CODTRFAUX ) ,
				CODUND = 'H' , SERVICO = 1, BDI = 1, UTILIZARVALOR = 1, BLOQUEADA = NULL, SUBOBRA = 0
		FROM MTAREFA (NOLOCK) P 
			INNER JOIN MPRJ (NOLOCK) M ON M.CODCOLIGADA = P.CODCOLIGADA AND M.IDPRJ = P.IDPRJ
		WHERE P.IDPRJ = @IDPRJ
		AND P.CODTRF = @CODTRF


END
