--SELECT E1.INDICE,E1.OS,E1.DESCRICAO,E1.POSICAODESENHO,E1.INDICEANTIGO,E1.IDCRIACAO,E1.IDCRIACAOPAI,E1.ITEMEXCLUSIVO,E1.EXECUCAO
--	FROM Z_CRM_EX001005 E1
--	INNER JOIN Z_CRM_EX001005 E2 ON
--	E2.INDICE=E1.INDICE
--	AND E2.OS=E1.OS
--	AND E2.EXECUCAO=E1.EXECUCAO
--	AND E2.ITEMEXCLUSIVO=E1.ITEMEXCLUSIVO
--	WHERE E1.OS like '%' AND E1.IDCRIACAO!=E2.IDCRIACAO AND E1.ITEMEXCLUSIVO<>2
--	ORDER BY CAST('/' + REPLACE(E1.INDICE, '.', '/') + '/' AS HIERARCHYID),EXECUCAO,DESCRICAO


--SELECT E1.INDICE,E1.DESCRICAO,E1.POSICAODESENHO,E1.INDICEANTIGO,E1.IDCRIACAO,E1.IDCRIACAOPAI
--FROM Z_CRM_ML001005 E1 WHERE OS='3.07843.32.001' --AND IDCRIACAO IN (849,970)
--ORDER BY CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)

SELECT *,"<? testando consulta>" 
	FROM (
		SELECT distinct 
			E1.OS,E1.INDICE,E1.NIVEL,E1.POSICAOINDICE,E1.DESCRICAO,E1.CODTRFPAI,E1.POSICAODESENHO,E1.INDICEANTIGO,E1.IDCRIACAO,E1.IDCRIACAOPAI,E1.ITEMEXCLUSIVO,E1.EXECUCAO
				FROM Z_CRM_EX001005 E1
					INNER JOIN Z_CRM_EX001005 E2 ON
					E2.INDICE=E1.INDICE
					AND E2.OS=E1.OS
					AND E2.EXECUCAO=E1.EXECUCAO
				WHERE E1.IDCRIACAO!=E2.IDCRIACAO AND E1.ITEMEXCLUSIVO<>2 AND E2.ITEMEXCLUSIVO<>2
		UNION 
		SELECT 
			distinct E1.OS,E1.INDICE,E1.NIVEL,E1.POSICAOINDICE,E1.DESCRICAO,E1.CODTRFPAI,E1.POSICAODESENHO,E1.INDICEANTIGO,E1.IDCRIACAO,E1.IDCRIACAOPAI,NULL,NULL EXECUCAO
				FROM 
					Z_CRM_ML001005 E1
					INNER JOIN Z_CRM_ML001005 E2 ON
					E2.INDICE=E1.INDICE
					AND E2.OS=E1.OS
				WHERE E1.IDCRIACAO!=E2.IDCRIACAO )R 
	ORDER BY CAST('/' + REPLACE(R.INDICE, '.', '/') + '/' AS HIERARCHYID),R.EXECUCAO,R.DESCRICAO


