USE [CORPORE]
GO
/****** Object:  StoredProcedure [dbo].[SP_DELP_INTEGRACAOREPETICAO]    Script Date: 16/10/2024 07:48:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_DELP_INTEGRACAOREPETICAO] (@OS VARCHAR(30))
AS


BEGIN

SET NOCOUNT ON;

SET LOCK_TIMEOUT 300000;  

DECLARE @CODFILIAL INT, @INDICE INT, @NUMPROCESSO INT,
		 @IDPAI INT, @IDPAIEXEC INT, @DSCEXECUCAO VARCHAR(MAX), @DATAINICIAL DATE;

CREATE TABLE #EXECUCOES (
EXECUCAO INT NOT NULL,
);


BEGIN TRAN 
INSERT INTO #EXECUCOES SELECT DISTINCT EXECUCAO FROM FLUIG.DBO.Z_CRM_EX001005 WHERE OS=@OS
COMMIT
	
	

PRINT 'INICIO DENTRO DA PROC'
	
	DECLARE @EXEC INT;

	DECLARE EXECUCOES CURSOR FOR 

		/**************************************************************************************************************************************************************
		
			SELECIONA AS EXECUÇÕES DO PROJETO PARA FAZER ITERAÇÃO

		***************************************************************************************************************************************************************/
		
		SELECT DISTINCT EXECUCAO FROM #EXECUCOES

	OPEN EXECUCOES

	FETCH NEXT FROM EXECUCOES INTO @EXEC
	
	WHILE @@FETCH_STATUS=0

		BEGIN
 
 			BEGIN TRAN 
				-- ATUALIZAR ESTRUTURAS SEM OPs
				UPDATE E SET
							TITULOITEM= M.TITULOITEM, 
							--NIVEL= M.NIVEL, 
							POSICAO= M.POSICAO, 
							DESCRICAO= M.DESCRICAO, 
							NUMDESENHO= M.NUMDESENHO, 
							REVISAODESENHO= M.REVISAODESENHO, 
							NUMDBI= M.NUMDBI, 
							REVISAODBI= M.REVISAODBI, 
							DESQTDE= M.DESQTDE, 
							TOTALQTDE= M.TOTALQTDE, 
							BITOLAESP= M.BITOLAESP, 
							LARGURAMASSA= M.LARGURAMASSA, 
							ESPLARGURAROSCA= M.ESPLARGURAROSCA, 
							COMPRIMENTO= M.COMPRIMENTO, 
							MATERIAL= M.MATERIAL, 
							PESO= M.PESO, 
							OBSERVACOES= M.OBSERVACOES, 
							TIPO= M.TIPO, 
							SEQ= M.SEQ, 
							masterid= M.masterid, 
							PESOMATERIAL= M.PESOMATERIAL, 
							OS= M.OS, 
							DATAREVISAO= M.DATAREVISAO, 
							PESOBRUTO= M.PESOBRUTO, 
							PESOLIQUIDO= M.PESOLIQUIDO, 
							OBSERVACOESDESENHO= M.OBSERVACOESDESENHO, 
							PERIMETROCORTE= M.PERIMETROCORTE, 
							AREAPINTURA= M.AREAPINTURA, 
							OBSPROCESSO= M.OBSPROCESSO, 
							OBSGERAL= M.OBSGERAL, 
							QUANTIDADEMATERIAL= M.QUANTIDADEMATERIAL, 
							TIPODESENHO= M.TIPODESENHO, 
							POSICAOCOMPLETA= M.POSICAOCOMPLETA, 
							ESPESSURA= M.ESPESSURA, 
							BITOLA= M.BITOLA, 
							LARGURA= M.LARGURA, 
							MASSALINEAR= M.MASSALINEAR, 
							DIAMETROEXTERNO= M.DIAMETROEXTERNO, 
							DIAMETROINTERNO= M.DIAMETROINTERNO, 
							ESPROSCA= M.ESPROSCA, 
							POSICAOCOMPLETAANTIGA= M.POSICAOCOMPLETAANTIGA,
							NOVOMATERIAL= M.NOVOMATERIAL, 
							MATERIAL_ZOOM= M.MATERIAL_ZOOM, 
							IDMATERIAL= M.IDMATERIAL, 
							CODIGOPRD= M.CODIGOPRD, 
							--INDICE= M.INDICE, 
							POSICAOESTRUTURA= M.POSICAOESTRUTURA, 
							POSICAODESENHO= M.POSICAODESENHO, 
							AREASECAO= M.AREASECAO, 
							ALTURA= M.ALTURA, 
							LARGURAMESA= M.LARGURAMESA, 
							ESPALMA= M.ESPALMA, 
							ESPMESA= M.ESPMESA, 
							--POSICAOINDICE= M.POSICAOINDICE, 
							INDICEANTIGO= M.INDICEANTIGO, 
							IDCRIACAO= M.IDCRIACAO,
							IDCRIACAOPAI = M.IDCRIACAOPAI,
							PRODUTORM= M.PRODUTORM, 
							IDPRD= M.IDPRD, 
							EXPANSOR= M.EXPANSOR, 
							CODIGOPRDMATERIAL= M.CODIGOPRDMATERIAL, 
							CODTRFOS= M.CODTRFOS, 
							UNDMEDIDA= M.UNDMEDIDA, 
							ORDEM= M.ORDEM, 
							LARGURAABA= M.LARGURAABA, 
							ESPABA= M.ESPABA, 
							INTEGRADO= M.INTEGRADO, 
							DSCTRFOS= M.DSCTRFOS,
							SOLICITACAO= M.SOLICITACAO, 
							PAIDETALHADO= M.PAIDETALHADO, 
							COMPORLISTA= M.COMPORLISTA, 
							CODTRFITEM= M.CODTRFITEM, 
							IDTRFITEM= M.IDTRFITEM, 
							NOMETRFITEM= M.NOMETRFITEM, 
							CODIGOTAREFADESC= M.CODIGOTAREFADESC, 
							IDPRJOS= M.IDPRJOS,
							DESCOS= M.DESCOS, 
							DETALHADO= M.DETALHADO, 
							NUMDOCDELP= M.NUMDOCDELP, 
							REVISAODOCDELP= M.REVISAODOCDELP, 
							CODCOLIGADA= M.CODCOLIGADA, 
							DIAMETROEXTERNODISCO= M.DIAMETROEXTERNODISCO,
							DIAMETROINTERNODISCO= M.DIAMETROINTERNODISCO,
							CHECKUSINAGEM= M.CHECKUSINAGEM, 
							CHECKCALDERARIA= M.CHECKCALDERARIA, 
							CODFILIAL= M.CODFILIAL, 
							CODTRFPAI= M.CODTRFPAI, 
							EXECINTEGRADAS= M.EXECINTEGRADAS, 
							--IDTRFPAI= M.IDTRFPAI, 
							--NOMETRFPAI= M.NOMETRFPAI, 
							EXECUCOES= M.EXECUCOES, 
							PESOUNITARIO= M.PESOUNITARIO, 
							OPSUNITARIAS= M.OPSUNITARIAS, 
							QTDEUNCOMP= M.QTDEUNCOMP, 
							CODTRFEX = M.CODTRFPAI,
							ITEMEXCLUSIVO= 0,
							RECCREATEDBY= M.RECCREATEDBY,
							RECCREATEDON= M.RECCREATEDON,
							RECMODIFIEDBY= M.RECMODIFIEDBY,
							RECMODIFIEDON = M.RECMODIFIEDON
				FROM FLUIG.DBO.Z_CRM_EX001005 E  
								INNER JOIN FLUIG.DBO.Z_CRM_ML001005(NOLOCK) M ON E.OS = M.OS AND E.IDCRIACAO = M.IDCRIACAO
								INNER JOIN (	
										SELECT E.CODCOLIGADA,E.CODFILIAL,E.IDCRIACAO,E.OS,E.EXECUCAO,SUM( CASE WHEN K.STATUS!=0 THEN 1 ELSE 0 END) TOTAL
										FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) E
										OUTER APPLY FLUIG.DBO.FN_DELP_RETORNA_ITENS_FILHOS_EX(E.CODCOLIGADA,E.CODFILIAL,E.OS,E.EXECUCAO,E.IDCRIACAO) F
										INNER JOIN FLUIG.DBO.Z_CRM_EX001005COMPL (NOLOCK) L ON
										L.CODCOLIGADA=F.CODCOLIGADA
										AND L.CODFILIAL=F.CODFILIAL
										AND L.OS=F.OS
										AND L.EXECUCAO=F.EXECUCAO
										AND L.IDCRIACAO=F.IDCRIACAO
										INNER JOIN KORDEM (NOLOCK) K ON
										K.CODCOLIGADA=L.CODCOLIGADA
										AND K.CODFILIAL=L.CODFILIAL
										AND K.CODORDEM=L.CODORDEM
										WHERE E.OS=@OS AND E.EXECUCAO=@EXEC AND E.ITEMEXCLUSIVO!=2 AND ISNULL(REPROCESSAMENTO,0) = 0
										GROUP BY E.CODCOLIGADA,E.CODFILIAL,E.IDCRIACAO,E.OS,E.EXECUCAO
										HAVING SUM( CASE WHEN K.STATUS!=0 THEN 1 ELSE 0 END)=0 ) F ON
								  F.CODCOLIGADA=E.CODCOLIGADA
								  AND F.CODFILIAL=E.CODFILIAL
								  AND F.OS=E.OS
								  AND F.EXECUCAO=E.EXECUCAO
								  AND F.IDCRIACAO=E.IDCRIACAO
								LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
												FROM KORDEM(NOLOCK) O
												INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
												INNER JOIN KITEMORDEM (NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
												WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL AND O.STATUS NOT IN (1,6) ) ORDENS ON E.CODCOLIGADA = ORDENS.CODCOLIGADA AND E.CODFILIAL = ORDENS.CODFILIAL AND E.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI 
												AND E.EXECUCAO = ORDENS.NUMEXEC AND E.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
				WHERE ORDENS.CODORDEM IS NULL
				AND E.OS = @OS
				AND E.EXECUCAO = @EXEC
				AND E.ITEMEXCLUSIVO <> 2

			COMMIT

			/**************************************************************************************************************************************************************
		
				ATUALIZA AS INFORMAÇÕES DOS ITENS DA EXECUÇÃO BASEADO NAS INFORMAÇÕES DA PRINCIPAL, COM EXECEÇÃO DAQUELES EM QUE A OP JÁ FOI PROGRAMADA OU APONTADA

			***************************************************************************************************************************************************************/

			BEGIN TRAN;

				DELETE E
				FROM FLUIG.DBO.Z_CRM_EX001005 E  
								INNER JOIN FLUIG.DBO.Z_CRM_ML001005(NOLOCK) M ON E.OS = M.OS AND E.IDCRIACAO = M.IDCRIACAO
								INNER JOIN (	
										SELECT E.CODCOLIGADA,E.CODFILIAL,E.IDCRIACAO,E.OS,E.EXECUCAO,SUM( CASE WHEN K.STATUS!=0 THEN 1 ELSE 0 END) TOTAL
										FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) E
										OUTER APPLY FLUIG.DBO.FN_DELP_RETORNA_ITENS_FILHOS_EX(E.CODCOLIGADA,E.CODFILIAL,E.OS,E.EXECUCAO,E.IDCRIACAO) F
										INNER JOIN FLUIG.DBO.Z_CRM_EX001005COMPL (NOLOCK) L ON
										L.CODCOLIGADA=F.CODCOLIGADA
										AND L.CODFILIAL=F.CODFILIAL
										AND L.OS=F.OS
										AND L.EXECUCAO=F.EXECUCAO
										AND L.IDCRIACAO=F.IDCRIACAO
										INNER JOIN KORDEM (NOLOCK) K ON
										K.CODCOLIGADA=L.CODCOLIGADA
										AND K.CODFILIAL=L.CODFILIAL
										AND K.CODORDEM=L.CODORDEM
										WHERE E.OS=@OS AND E.EXECUCAO=@EXEC AND E.ITEMEXCLUSIVO!=2 AND ISNULL(REPROCESSAMENTO,0) = 0
										GROUP BY E.CODCOLIGADA,E.CODFILIAL,E.IDCRIACAO,E.OS,E.EXECUCAO
										HAVING SUM( CASE WHEN K.STATUS!=0 THEN 1 ELSE 0 END)=0 ) F ON
								  F.CODCOLIGADA=E.CODCOLIGADA
								  AND F.CODFILIAL=E.CODFILIAL
								  AND F.OS=E.OS
								  AND F.EXECUCAO=E.EXECUCAO
								  AND F.IDCRIACAO=E.IDCRIACAO
								LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
												FROM KORDEM(NOLOCK) O
												INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
												INNER JOIN KITEMORDEM (NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
												WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL ) ORDENS ON E.CODCOLIGADA = ORDENS.CODCOLIGADA AND E.CODFILIAL = ORDENS.CODFILIAL AND E.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI 
												AND E.EXECUCAO = ORDENS.NUMEXEC AND E.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
				WHERE ORDENS.CODORDEM IS NULL
				AND E.OS = @OS
				AND E.EXECUCAO = @EXEC
				AND E.ITEMEXCLUSIVO <> 2

			COMMIT

			/**************************************************************************************************************************************************************
		
				DELETE OS ITENS DA EXECUÇÃO QUE AINDA NÃO GERARAM OP E SÃO DA PRINCIPAL

			***************************************************************************************************************************************************************/


			DECLARE  @ID INT, @IDCRIACAOPAI INT, @NIVEL VARCHAR(MAX), @IDCRIACAO INT, @POSICAOINDICE INT
						-- CRIA CÓPIA DA EXECUÇÃO


			--RENUMERA

			DECLARE EXECUCAO CURSOR FOR
				
				WITH CTE AS (
				SELECT	M.ID, M.IDCRIACAO, M.IDCRIACAOPAI,M.OS
				FROM FLUIG.DBO.Z_CRM_ML001005 M (NOLOCK)
					LEFT JOIN FLUIG.DBO.Z_CRM_EX001005 E (NOLOCK) ON M.IDCRIACAO = E.IDCRIACAO AND M.OS = E.OS AND E.EXECUCAO = @EXEC
					LEFT JOIN FLUIG.DBO.Z_CRM_ML001005 M2 (NOLOCK) ON M2.CODTRFPAI = M.CODTRFPAI AND M2.OS=M.OS AND M2.IDCRIACAOPAI=''
				WHERE E.ID IS NULL AND  M.OS = @OS AND ISNULL(M2.EXECINTEGRADAS,0)>=@EXEC)

				SELECT C.ID, C.IDCRIACAO, C.IDCRIACAOPAI FROM CTE C 
				LEFT JOIN FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) Z ON Z.OS=C.OS AND Z.IDCRIACAO=C.IDCRIACAOPAI AND Z.EXECUCAO=@EXEC
				LEFT JOIN CTE Z2 ON Z2.OS=C.OS AND Z2.IDCRIACAO=C.IDCRIACAOPAI 
				LEFT JOIN FLUIG.DBO.Z_CRM_EX001005COMPL ZL ON ZL.CODCOLIGADA=Z.CODCOLIGADA AND ZL.CODFILIAL=Z.CODFILIAL AND ZL.OS=Z.OS AND ZL.EXECUCAO=Z.EXECUCAO AND ZL.IDCRIACAO=Z.IDCRIACAO
				LEFT JOIN KORDEM K ON K.CODCOLIGADA=ZL.CODCOLIGADA AND K.CODFILIAL=ZL.CODFILIAL AND K.CODORDEM=ZL.CODORDEM
				WHERE ( Z.EXECUCAO=@EXEC OR Z.EXECUCAO IS NULL) AND (Z.IDCRIACAO IS NOT NULL OR Z2.IDCRIACAO IS NOT NULL OR C.IDCRIACAOPAI='')
				AND ISNULL(K.STATUS,0) NOT IN (5,6)

				/**************************************************************************************************************************************************************
		
					SELECIONA OS ITENS DA PRINCIPAL QUE DEVEM SER INSERIDOS NA EXECUÇÃO

				***************************************************************************************************************************************************************/

		
			OPEN EXECUCAO

			FETCH NEXT FROM EXECUCAO INTO @ID, @IDCRIACAO, @IDCRIACAOPAI

			WHILE @@FETCH_STATUS = 0
			BEGIN
			
				BEGIN TRAN 
					-- INSERE ITENS EXCLUIVOS CORRETAMENTE
					INSERT INTO FLUIG.dbo.Z_CRM_EX001005  (	 ID, companyid, cardid, documentid, version, tableid, TITULOITEM, NIVEL, POSICAO, DESCRICAO, NUMDESENHO, REVISAODESENHO, NUMDBI, REVISAODBI, DESQTDE, TOTALQTDE, BITOLAESP, LARGURAMASSA, 
																ESPLARGURAROSCA, COMPRIMENTO, MATERIAL, PESO, OBSERVACOES, TIPO, SEQ, masterid, PESOMATERIAL, OS, DATAREVISAO, PESOBRUTO, PESOLIQUIDO, OBSERVACOESDESENHO, PERIMETROCORTE, AREAPINTURA, 
																OBSPROCESSO, OBSGERAL, QUANTIDADEMATERIAL, TIPODESENHO, POSICAOCOMPLETA, ESPESSURA, BITOLA, LARGURA, MASSALINEAR, DIAMETROEXTERNO, DIAMETROINTERNO, ESPROSCA, POSICAOCOMPLETAANTIGA, 
																NOVOMATERIAL, MATERIAL_ZOOM, IDMATERIAL, CODIGOPRD,  POSICAOINDICE,  POSICAOESTRUTURA, POSICAODESENHO, AREASECAO, ALTURA, LARGURAMESA, ESPALMA, ESPMESA, INDICE, INDICEANTIGO, IDCRIACAO, 
																PRODUTORM, IDPRD, EXPANSOR, CODIGOPRDMATERIAL, CODTRFOS, UNDMEDIDA, ORDEM, LARGURAABA, ESPABA, INTEGRADO, DSCTRFOS, SOLICITACAO, PAIDETALHADO, COMPORLISTA, CODTRFITEM, IDTRFITEM, 
																NOMETRFITEM, CODIGOTAREFADESC, IDPRJOS, DESCOS, DETALHADO, NUMDOCDELP, REVISAODOCDELP, CODCOLIGADA, DIAMETROEXTERNODISCO, DIAMETROINTERNODISCO, CHECKUSINAGEM, CHECKCALDERARIA, CODFILIAL, 
																CODTRFPAI, EXECINTEGRADAS, IDTRFPAI, NOMETRFPAI, EXECUCOES, PESOUNITARIO, OPSUNITARIAS, QTDEUNCOMP, OP, EXECUCAO, CODTRFEX, IDCRIACAOPAI,ITEMEXCLUSIVO, RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)

							
						SELECT	M.ID, M.companyid, M.cardid, M.documentid, M.version, M.tableid, M.TITULOITEM, 
								M.NIVEL, 
							M.POSICAO, M.DESCRICAO, M.NUMDESENHO, M.REVISAODESENHO, M.NUMDBI, M.REVISAODBI, M.DESQTDE, 
							M.TOTALQTDE, M.BITOLAESP, M.LARGURAMASSA, M.ESPLARGURAROSCA, M.COMPRIMENTO, M.MATERIAL, M.PESO, M.OBSERVACOES, M.TIPO, M.SEQ, M.masterid, M.PESOMATERIAL, M.OS, M.DATAREVISAO, M.PESOBRUTO, 
							M.PESOLIQUIDO, M.OBSERVACOESDESENHO, M.PERIMETROCORTE, M.AREAPINTURA, M.OBSPROCESSO, M.OBSGERAL, M.QUANTIDADEMATERIAL, M.TIPODESENHO, M.POSICAOCOMPLETA, M.ESPESSURA, M.BITOLA, M.LARGURA, 
							M.MASSALINEAR, M.DIAMETROEXTERNO, M.DIAMETROINTERNO, M.ESPROSCA, M.POSICAOCOMPLETAANTIGA, M.NOVOMATERIAL, M.MATERIAL_ZOOM, M.IDMATERIAL, M.CODIGOPRD, 
							M.POSICAOINDICE, M.POSICAOESTRUTURA, 
							M.POSICAODESENHO, M.AREASECAO, M.ALTURA, M.LARGURAMESA, M.ESPALMA, M.ESPMESA,M.INDICE, 
							M.INDICEANTIGO, M.IDCRIACAO, M.PRODUTORM, M.IDPRD, M.EXPANSOR, M.CODIGOPRDMATERIAL, M.CODTRFOS, M.UNDMEDIDA, M.ORDEM, M.LARGURAABA, M.ESPABA, M.INTEGRADO, M.DSCTRFOS, M.SOLICITACAO, NULL PAIDETALHADO, 
							M.COMPORLISTA, M.CODTRFITEM, M.IDTRFITEM, M.NOMETRFITEM, M.CODIGOTAREFADESC, M.IDPRJOS, M.DESCOS, NULL DETALHADO, M.NUMDOCDELP, M.REVISAODOCDELP, M.CODCOLIGADA, M.DIAMETROEXTERNODISCO, M.DIAMETROINTERNODISCO, 
							M.CHECKUSINAGEM, M.CHECKCALDERARIA, M.CODFILIAL, M.CODTRFPAI, M.EXECINTEGRADAS, M.IDTRFPAI, M.NOMETRFPAI, M.EXECUCOES, M.PESOUNITARIO, M.OPSUNITARIAS, M.QTDEUNCOMP, NULL, @EXEC, M.CODTRFPAI , M.IDCRIACAOPAI, 0,
							M.RECCREATEDBY, M.RECCREATEDON, M.RECMODIFIEDBY, M.RECMODIFIEDON
					FROM FLUIG.DBO.Z_CRM_ML001005 M (NOLOCK)
					LEFT JOIN FLUIG.DBO.Z_CRM_EX001005 E ON
					E.OS=M.OS
					AND E.IDCRIACAO=M.IDCRIACAO
					AND E.EXECUCAO=@EXEC
					LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
											FROM KORDEM(NOLOCK) O
											INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
											INNER JOIN KITEMORDEM (NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
											WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL ) ORDENS
					ON M.CODCOLIGADA = ORDENS.CODCOLIGADA AND M.CODFILIAL = ORDENS.CODFILIAL AND M.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI 
											AND @EXEC = ORDENS.NUMEXEC AND M.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
					WHERE  M.OS = @OS AND M.IDCRIACAO = @IDCRIACAO  AND E.OS IS NULL AND ORDENS.CODORDEM IS NULL
					
				COMMIT

					FETCH NEXT FROM EXECUCAO INTO @ID, @IDCRIACAO, @IDCRIACAOPAI

			END

			CLOSE EXECUCAO
			DEALLOCATE EXECUCAO


							   
			-- ############################################################################################################################################
			--                           FIM DA INCLUSÃO DO EX001005
			-- ############################################################################################################################################

			FETCH NEXT FROM EXECUCOES INTO @EXEC

		END;

		/**************************************************************************************************************************************************************
		
			INSERE OS ITENS DA PRINCIPAL DENTRO DAS EXECUÇÕES

		***************************************************************************************************************************************************************/

		BEGIN TRAN 

			DELETE E21
			FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) E5
				INNER JOIN FLUIG.DBO.Z_CRM_EX001021 E21 ON E5.OS = E21.OSPROCESSO AND E5.IDCRIACAO = E21.IDCRIACAOPROCESSO AND E5.EXECUCAO = E21.EXECUCAO
				INNER JOIN FLUIG.DBO.Z_CRM_ML001005 (NOLOCK) M5 ON E5.OS = M5.OS AND E5.IDCRIACAO = M5.IDCRIACAO
				INNER JOIN FLUIG.DBO.Z_CRM_ML001021 (NOLOCK)M21 ON E5.OS = M21.OSPROCESSO AND E5.IDCRIACAO = M21.IDCRIACAOPROCESSO AND E21.CODATIVIDADE = M21.CODATIVIDADE
				LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
								FROM KORDEM(NOLOCK) O
								INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
								INNER JOIN KITEMORDEM(NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
								WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL AND O.STATUS NOT IN (1,6) ) ORDENS ON E5.CODCOLIGADA = ORDENS.CODCOLIGADA AND E5.CODFILIAL = ORDENS.CODFILIAL 
								AND E5.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND E5.EXECUCAO = ORDENS.NUMEXEC AND E5.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE ORDENS.CODORDEM IS NULL
			AND E5.OS = @OS
			AND E5.EXECUCAO = @EXEC
			AND E5.ITEMEXCLUSIVO <> 2

		COMMIT

		/**************************************************************************************************************************************************************
		
			DELETA AS ATIVIDADES DAS ESTRUTURAS DE EXECUÇÕES QUE AINDA NÃO CRIARAM OP OU ESTÃO CANCELADAS OU PLANEJADAS

		***************************************************************************************************************************************************************/

		BEGIN TRAN 

			DECLARE @IDMAX19 INT,@IDMAX21 INT;
			SET @IDMAX21 = CAST((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021') AS INT)

			INSERT INTO FLUIG.dbo.Z_CRM_EX001021  
				SELECT DISTINCT @IDMAX21+ROW_NUMBER()OVER(ORDER BY M.ID) ID,M.companyid,M.cardid,M.documentid,M.version,M.tableid,M.PRIORIDADE,M.IDCRIACAOPROCESSO,M.CODATIVIDADE,M.OSPROCESSO,M.IDPROCESSO,M.DESCATIVIDADE,
						M.HABILIDADEREQUERIDA,M.CODHABILIDADE,M.CODPOSTO,M.DESCPOSTO,M.FILA,M.CONFIGURACAO,M.PROCESSAMENTO,M.DESAGREGACAO,M.ESPERA,M.MOVIMENTACAO,M.MINUTOSGASTOS,
						M.DESCPROCESSO,M.DOCAPOIOATV1,M.DOCAPOIOATV2,M.DOCAPOIOATV3,M.DOCAPOIOATV4,M.masterid,M.SOLICITACAOPROCESSO,M.FORNPARA,M.INTEGRADOPROCESSO,I.EXECUCAO , NULL,
						M.RECCREATEDBY,M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
				FROM  FLUIG.dbo.Z_CRM_ML001021 M (NOLOCK)
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK)  ON I.OS = M.OSPROCESSO AND M.IDCRIACAOPROCESSO = I.IDCRIACAO
					LEFT JOIN FLUIG.dbo.Z_CRM_EX001021 E ON M.IDCRIACAOPROCESSO = E.IDCRIACAOPROCESSO AND M.CODATIVIDADE = E.CODATIVIDADE AND I.OS = E.OSPROCESSO AND E.EXECUCAO = I.EXECUCAO
					LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
						FROM KORDEM(NOLOCK) O
						INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
						INNER JOIN KITEMORDEM (NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
						WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL AND O.STATUS NOT IN (1,6) ) ORDENS ON I.CODCOLIGADA = ORDENS.CODCOLIGADA AND I.CODFILIAL = ORDENS.CODFILIAL 
								AND I.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND I.EXECUCAO = ORDENS.NUMEXEC AND I.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
				WHERE E.ID IS NULL AND ORDENS.CODORDEM IS NULL AND I.ITEMEXCLUSIVO != 2 AND M.OSPROCESSO = @OS  AND I.EXECUCAO = @EXEC

			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT MAX(ID) ID FROM FLUIG.DBO.Z_CRM_ML001021 UNION ALL SELECT MAX(ID) FROM FLUIG.DBO.Z_CRM_EX001021) AS MLS) 
			WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021' AND CODSISTEMA = 'K'

		COMMIT

		/**************************************************************************************************************************************************************
		
			INSERE AS ATIVIDADES DA PRINCIPAL NA EXECUCAO, EXECETO AS ATIVIDADES QUE JÁ EXISTEM E ITENS COM OP DIFERENTE DE CANCELADA E PLANEJADA

		***************************************************************************************************************************************************************/

		BEGIN TRAN 

			UPDATE Z SET PRIORIDADE=(SELECT MAX(PRIORIDADE) FROM  FLUIG.dbo.Z_CRM_EX001021(NOLOCK) WHERE OSPROCESSO=R.OSPROCESSO AND IDCRIACAOPROCESSO=R.IDCRIACAOPROCESSO AND EXECUCAO=R.EXECUCAO)+R.NUM-1
			FROM FLUIG.dbo.Z_CRM_EX001021 Z INNER JOIN (
			SELECT Z1.*,ROW_NUMBER() OVER( PARTITION BY Z1.OSPROCESSO,Z1.IDCRIACAOPROCESSO ORDER BY Z1.CODATIVIDADE) NUM 
			FROM FLUIG.dbo.Z_CRM_EX001021 Z1 
			INNER JOIN FLUIG.dbo.Z_CRM_EX001021 Z2 ON Z1.OSPROCESSO=Z2.OSPROCESSO AND Z1.EXECUCAO=Z2.EXECUCAO AND Z1.IDCRIACAOPROCESSO=Z2.IDCRIACAOPROCESSO 
			INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I ON I.OS = Z1.OSPROCESSO AND Z1.IDCRIACAOPROCESSO = I.IDCRIACAO AND I.EXECUCAO=Z1.EXECUCAO
			AND Z1.PRIORIDADE=Z2.PRIORIDADE AND Z1.CODATIVIDADE!=Z2.CODATIVIDADE 
			WHERE I.OS=@OS AND I.EXECUCAO=@EXEC AND I.ITEMEXCLUSIVO!=2) R ON 
			R.OSPROCESSO=Z.OSPROCESSO AND R.IDCRIACAOPROCESSO=Z.IDCRIACAOPROCESSO AND R.EXECUCAO=Z.EXECUCAO AND R.CODATIVIDADE=Z.CODATIVIDADE WHERE NUM>1

		COMMIT

		/**************************************************************************************************************************************************************
		
			SOMA MAIS 1 PARA AS ATIVIDADE QUE FICARAM COM PRIORIDADE IGUAL PORÉM SÃO ATIVIDADES DIFERENTES

		***************************************************************************************************************************************************************/

		BEGIN TRAN 
		-- COMPONENTES
			DELETE E19
			FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK)E5  
				INNER JOIN FLUIG.DBO.Z_CRM_EX001019 E19 ON E5.OS = E19.OSCOMPONENTES AND E5.IDCRIACAO = E19.IDCRIACAOCOMPONENTES AND E5.EXECUCAO = E19.EXECUCAO
				INNER JOIN FLUIG.DBO.Z_CRM_ML001005 (NOLOCK)M5 ON E5.OS = M5.OS AND E5.IDCRIACAO = M5.IDCRIACAO
				LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
								FROM KORDEM(NOLOCK) O
								INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
								INNER JOIN KITEMORDEM(NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
								WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL AND O.STATUS NOT IN (1,6) ) ORDENS ON E5.CODCOLIGADA = ORDENS.CODCOLIGADA AND E5.CODFILIAL = ORDENS.CODFILIAL 
								AND E5.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND E5.EXECUCAO = ORDENS.NUMEXEC AND E5.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE ORDENS.CODORDEM IS NULL
			AND E5.OS = @OS
			AND E5.EXECUCAO = @EXEC
			AND E5.ITEMEXCLUSIVO != 2

		COMMIT

		/**************************************************************************************************************************************************************
		
			DELETA OS COMPONENTES DAS ESTRUTURAS DE EXECUÇÕES QUE AINDA NÃO CRIARAM OP

		***************************************************************************************************************************************************************/

		BEGIN TRAN 

			SET @IDMAX19 = CAST((SELECT VALAUTOINC FROM GAUTOINC(NOLOCK) WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019') AS INT)

			INSERT INTO FLUIG.dbo.Z_CRM_EX001019 
			SELECT DISTINCT @IDMAX19+ROW_NUMBER()OVER(ORDER BY M.ID),M.companyid,M.cardid,M.documentid,M.version,M.tableid,M.PRODUTOCOMPONENTES,M.IDPRDCOMPONENTES,M.CODIGOPRDCOMPONENTES,M.CODUNDCOMPONENTES,
					M.IDCRIACAOCOMPONENTES,M.QTDEUNCOMPONENTES,M.QTDETOTALCOMPONENTES,M.SUBSTITUTOCOMPONENTES,M.INSUMOCOMPONENTES,'' LISTACOMPONENTES,M.masterid,
					M.IDCOMPONENTES,M.OSCOMPONENTES,M.SOLICITACAOCOMPONENTES,M.INTEGRADOCOMPONENTES,M.PRIORIDADEATVCOMPONENTES, I.EXECUCAO, NULL,M.RECCREATEDBY,
					M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
			FROM  FLUIG.dbo.Z_CRM_ML001019 M  (NOLOCK)
				INNER JOIN FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK) ON I.OS = M.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = I.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 P (NOLOCK) ON  I.OS = P.OSPROCESSO AND P.IDCRIACAOPROCESSO = I.IDCRIACAO AND M.PRIORIDADEATVCOMPONENTES = P.PRIORIDADE AND P.EXECUCAO = I.EXECUCAO
				LEFT JOIN FLUIG.dbo.Z_CRM_EX001019 E ON M.OSCOMPONENTES = E.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = E.IDCRIACAOCOMPONENTES AND M.PRIORIDADEATVCOMPONENTES = E.PRIORIDADEATVCOMPONENTES AND M.IDPRDCOMPONENTES = E.IDPRDCOMPONENTES  AND E.EXECUCAO = P.EXECUCAO
				LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
						FROM KORDEM(NOLOCK) O
						INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
						INNER JOIN KITEMORDEM (NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
						WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL AND O.STATUS NOT IN (1,6) ) ORDENS ON I.CODCOLIGADA = ORDENS.CODCOLIGADA AND I.CODFILIAL = ORDENS.CODFILIAL 
								AND I.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND I.EXECUCAO = ORDENS.NUMEXEC AND I.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE E.ID IS NULL AND ORDENS.CODORDEM IS NULL AND I.ITEMEXCLUSIVO != 2 AND M.OSCOMPONENTES = @OS AND I.EXECUCAO = @EXEC

			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT MAX(ID) ID FROM FLUIG.DBO.Z_CRM_ML001019(NOLOCK) UNION ALL SELECT MAX(ID) FROM FLUIG.DBO.Z_CRM_EX001019(NOLOCK)) AS MLS) 
			WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019' AND CODSISTEMA = 'K'

		COMMIT

		/**************************************************************************************************************************************************************
		
			INSERE OS COMPONENTES QUE POSSUEM ATIVIDADE RELACIONADA DA PRINCIPAL NA EXECUCAO, EXECETO OS COMPONENTES QUE JÁ EXISTEM E ITENS COM OP DIFERENTE DE CANCELADA E PLANEJADA, OS COMPONENTES DE LISTA DE MATERIAIS DEIXAM DE SER DA LISTA

		***************************************************************************************************************************************************************/


		BEGIN TRAN 

			SET @IDMAX19 = CAST((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'K' AND CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001019') AS INT)

			INSERT INTO FLUIG.dbo.Z_CRM_EX001019 
			SELECT @IDMAX19+ROW_NUMBER()OVER(ORDER BY M.ID),M.companyid,M.cardid,M.documentid,M.version,M.tableid,M.PRODUTOCOMPONENTES,M.IDPRDCOMPONENTES,M.CODIGOPRDCOMPONENTES,M.CODUNDCOMPONENTES,
					M.IDCRIACAOCOMPONENTES,M.QTDEUNCOMPONENTES,M.QTDETOTALCOMPONENTES,M.SUBSTITUTOCOMPONENTES,M.INSUMOCOMPONENTES,M.LISTACOMPONENTES,M.masterid,
					M.IDCOMPONENTES,M.OSCOMPONENTES,M.SOLICITACAOCOMPONENTES,M.INTEGRADOCOMPONENTES,0, I.EXECUCAO, NULL,M.RECCREATEDBY,
					M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
			FROM  FLUIG.dbo.Z_CRM_ML001019 M  (NOLOCK)
				INNER JOIN FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK) ON I.OS = M.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = I.IDCRIACAO
				LEFT JOIN FLUIG.dbo.Z_CRM_EX001021 P (NOLOCK) ON  I.OS = P.OSPROCESSO AND P.IDCRIACAOPROCESSO = I.IDCRIACAO AND M.PRIORIDADEATVCOMPONENTES = P.PRIORIDADE AND P.EXECUCAO = I.EXECUCAO
				LEFT JOIN FLUIG.dbo.Z_CRM_EX001019 E ON M.OSCOMPONENTES = E.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = E.IDCRIACAOCOMPONENTES AND ( M.PRIORIDADEATVCOMPONENTES = E.PRIORIDADEATVCOMPONENTES OR E.PRIORIDADEATVCOMPONENTES=0 ) AND M.IDPRDCOMPONENTES = E.IDPRDCOMPONENTES  AND E.EXECUCAO = I.EXECUCAO
								LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL, O.CODCCUSTO
						FROM KORDEM(NOLOCK) O
						INNER JOIN KORDEMCOMPL(NOLOCK) C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
						INNER JOIN KITEMORDEM (NOLOCK) I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
						WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL AND O.STATUS NOT IN (1,6) ) ORDENS ON I.CODCOLIGADA = ORDENS.CODCOLIGADA AND I.CODFILIAL = ORDENS.CODFILIAL 
								AND I.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND I.EXECUCAO = ORDENS.NUMEXEC AND I.OS=ORDENS.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE P.ID IS NULL AND  E.ID IS NULL AND ORDENS.CODORDEM IS NULL AND I.ITEMEXCLUSIVO != 2 AND M.OSCOMPONENTES = @OS AND  I.EXECUCAO = @EXEC

			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(ID) FROM (SELECT MAX(ID) ID FROM FLUIG.DBO.Z_CRM_ML001021(NOLOCK) UNION ALL SELECT MAX(ID) FROM FLUIG.DBO.Z_CRM_EX001021(NOLOCK)) AS MLS) 
			WHERE CODCOLIGADA = 0 AND CODAUTOINC = 'Z_CRM_ML001021' AND CODSISTEMA = 'K'

		COMMIT

		/**************************************************************************************************************************************************************

			INSERE OS COMPONENTES QUE NÃO POSSUEM ATIVIDADE RELACIONADA DA PRINCIPAL NA EXECUCAO, EXECETO OS COMPONENTES QUE JÁ EXISTEM E ITENS COM OP DIFERENTE DE CANCELADA E PLANEJADA, OS COMPONENTES DE LISTA DE MATERIAIS DEIXAM DE SER DA LISTA

		***************************************************************************************************************************************************************/

		BEGIN TRAN

			UPDATE E SET PRIORIDADEATVCOMPONENTES = 0
				FROM FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK) 
				LEFT JOIN FLUIG.dbo.Z_CRM_EX001021 P (NOLOCK) ON  I.OS = P.OSPROCESSO AND P.IDCRIACAOPROCESSO = I.IDCRIACAO  AND P.EXECUCAO = I.EXECUCAO
				LEFT JOIN FLUIG.dbo.Z_CRM_EX001019 E ON I.OS = E.OSCOMPONENTES AND I.IDCRIACAO = E.IDCRIACAOCOMPONENTES AND P.PRIORIDADE = E.PRIORIDADEATVCOMPONENTES AND E.EXECUCAO = I.EXECUCAO
			WHERE P.ID IS NULL AND  E.ID IS NULL AND I.ITEMEXCLUSIVO = 0 AND I.OS = @OS AND  I.EXECUCAO = @EXEC

		COMMIT

		/**************************************************************************************************************************************************************
		
			ATUALIZA A PRIORIDADE DA ATIVIDADE RELACIOANDA PARA 0 EM TODOS COMPONENTES SEM ATIVIDADE VINCULADA

		***************************************************************************************************************************************************************/

		BEGIN TRAN

			DELETE Z1 FROM FLUIG.DBO.Z_CRM_EX001005 Z1 
			LEFT JOIN FLUIG.DBO.Z_CRM_EX001005 Z2  ON Z1.IDCRIACAOPAI = Z2.IDCRIACAO AND Z1.OS = Z2.OS AND Z1.EXECUCAO = Z2.EXECUCAO
			WHERE Z1.OS=@OS AND Z2.IDCRIACAO IS NULL AND Z1.IDCRIACAOPAI!=''

		COMMIT

		/**************************************************************************************************************************************************************
		
			DELETE OS ITENS QUE FICARAM SEM REFERENCIA PARA UM ITEM PAI E NÃO SÃO ITENS PAIS

		***************************************************************************************************************************************************************/


	CLOSE EXECUCOES;
	DEALLOCATE EXECUCOES;
		
	DECLARE @NUM_OS VARCHAR(30), @CODTRFPAI VARCHAR(10), @EXECUCAO INT
	DECLARE TAREFAS CURSOR FOR
			
		SELECT DISTINCT K.OS,K2.CODTRFPAI,K3.EXECUCAO
			FROM (
			SELECT NUM_OS,ISNULL(CODTRFEX,'') CODTRFEX,ISNULL(EXECUCAO_INFO,'') EXECUCAO_INFO,NUMPROCESSO,P.END_DATE,CODCOLIGADA,ROW_NUMBER()OVER(PARTITION BY NUM_OS ORDER BY NUMPROCESSO DESC ) ID
			FROM FLUIG.DBO.ML001007 M 
			INNER JOIN FLUIG.DBO.PROCES_WORKFLOW P 
			ON P.COD_EMPRESA=M.CODCOLIGADA 
			AND P.NUM_PROCES=M.NUMPROCESSO 
			WHERE (CODTRFEX='' OR CODTRFEX IS NULL) AND (EXECUCAO_INFO='' OR EXECUCAO_INFO IS NULL) AND M.ERROINTEGRACAO=''
			) M
			INNER JOIN FLUIG.DBO.Z_CRM_ML001005 K ON
			K.CODCOLIGADA=M.CODCOLIGADA
			AND K.OS=M.NUM_OS
			AND K.RECMODIFIEDON>END_DATE
			INNER JOIN FLUIG.DBO.Z_CRM_ML001005 K2 ON
			K.CODCOLIGADA=K2.CODCOLIGADA
			AND K.CODFILIAL=K2.CODFILIAL
			AND K.OS=K2.OS
			AND K.CODTRFPAI=K2.CODTRFPAI
			INNER JOIN FLUIG.DBO.Z_CRM_EX001005 K3 ON 
			K.CODCOLIGADA=K3.CODCOLIGADA
			AND K.CODFILIAL=K3.CODFILIAL
			AND K.OS=K3.OS
			AND K.CODTRFPAI=K3.CODTRFPAI
			LEFT JOIN (SELECT DISTINCT OS,CODTRFPAI,EXECUCAO FROM FLUIG.DBO.Z_CRM_EX001005(NOLOCK) Z
				INNER JOIN KITEMORDEM K 
				ON K.CODCOLIGADA=Z.CODCOLIGADA
				AND K.CODFILIAL=Z.CODFILIAL
				AND K.CODESTRUTURA=Z.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
				AND K.CODCCUSTO=Z.OS COLLATE SQL_Latin1_General_CP1_CI_AI
				INNER JOIN KORDEMCOMPL KL ON
				K.CODCOLIGADA=KL.CODCOLIGADA
				AND K.CODFILIAL=KL.CODFILIAL
				AND K.CODORDEM=KL.CODORDEM
				AND Z.EXECUCAO=KL.NUMEXEC
				INNER JOIN KORDEM KO ON
				KO.CODCOLIGADA=K.CODCOLIGADA
				AND KO.CODFILIAL=K.CODFILIAL
				AND KO.CODORDEM=K.CODORDEM
				WHERE OS=@OS AND ( IDCRIACAOPAI='' OR IDCRIACAOPAI IS NULL ) AND ISNULL(K.QTDEEFETIVADA,0)>=K.QTDEPLANEJADA AND ITEMEXCLUSIVO!=2 ) K4 ON
				K4.OS=K.OS 
				AND K4.CODTRFPAI=K2.CODTRFPAI
				AND K4.EXECUCAO=K3.EXECUCAO
		WHERE K.OS=@OS AND ( K2.IDCRIACAOPAI='' OR K2.IDCRIACAOPAI IS NULL) AND ( K3.IDCRIACAOPAI='' OR K3.IDCRIACAOPAI IS NULL) AND K4.OS IS NULL
		AND K.ITEMEXCLUSIVO!=2 AND K2.ITEMEXCLUSIVO!=2  AND K3.ITEMEXCLUSIVO!=2  AND M.ID=2 

		/**************************************************************************************************************************************************************
		
			SELECIONA AS EXECUÇÕES EDITADAS PARA INTEGRAR AS ESTRUTURAS DE EXECUÇÃO

		***************************************************************************************************************************************************************/


		
	OPEN TAREFAS

	FETCH NEXT FROM TAREFAS INTO @NUM_OS, @CODTRFPAI, @EXECUCAO

	WHILE @@FETCH_STATUS = 0
	BEGIN


		EXEC SP_DELP_EDICAOEXECUCAO 0,@NUM_OS,@CODTRFPAI,@EXECUCAO

		/**************************************************************************************************************************************************************
		
			INTEGRA A ESTRUTURA DE EXECUÇÃO EDITADA

		***************************************************************************************************************************************************************/
		
		FETCH NEXT FROM TAREFAS INTO @NUM_OS, @CODTRFPAI, @EXECUCAO

	END

	CLOSE TAREFAS
	DEALLOCATE TAREFAS

	BEGIN TRAN 
		UPDATE FLUIG.dbo.Z_CRM_EX001005 SET ITEMEXCLUSIVO = 1
		WHERE OS = @OS AND ITEMEXCLUSIVO = 0;
	COMMIT

	DROP TABLE #EXECUCOES

END;

