
CREATE TABLE TEMP_CONSULTAS (
	SPID INT
)

DECLARE @TABLE TABLE(
SPID INT,
STATUS VARCHAR(MAX),
LOGIN VARCHAR(MAX),
HOSTNAME VARCHAR(MAX),
BLKBY VARCHAR(MAX),
DBNAME VARCHAR(MAX),
COMMAND VARCHAR(MAX),
CPUTIME INT,
DISKIO INT,
LASTBATCH VARCHAR(MAX),
PROGRAMNAME VARCHAR(MAX),
SPID_1 INT,
REQUESTID INT
)

INSERT INTO @TABLE EXEC SP_WHO2;

WITH CTE AS (
SELECT  A.SPID,A.BLKBY,0 BLO,1 ORD
FROM    @TABLE A
UNION ALL 
SELECT C2.SPID,C2.BLKBY,C.SPID BLO, ORD+1 ORD FROM CTE C 
INNER JOIN @TABLE C2 ON
CAST(C2.SPID AS VARCHAR(30))=C.BLKBY AND CAST(C2.SPID AS VARCHAR(30))!=C2.BLKBY AND CAST(C.SPID AS VARCHAR(30))!=C.BLKBY
)

INSERT INTO TEMP_CONSULTAS  SELECT A.SPID FROM CTE A 
INNER JOIN SYS.SYSPROCESSES B
ON A.SPID=B.SPID
OUTER APPLY SYS.DM_EXEC_SQL_TEXT(B.SQL_HANDLE)
WHERE ORD = (SELECT MAX(ORD) FROM CTE)  AND ORD!=1


DECLARE @SPID INT,@COMANDO text

	DECLARE MOVIMENTOS CURSOR FOR

		SELECT SPID FROM TEMP_CONSULTAS

	OPEN MOVIMENTOS 
	FETCH NEXT FROM MOVIMENTOS INTO @SPID
	WHILE @@FETCH_STATUS=0
		BEGIN
			SET @COMANDO=CONCAT('KILL ',@SPID)
			EXEC sp_sqlexec @COMANDO
		END
	CLOSE MOVIMENTOS
	DEALLOCATE MOVIMENTOS

DROP TABLE TEMP_CONSULTAS

 

