-- DECLARAÇÃO DE TODAS AS VARIÁVEIS
DECLARE @IDCRIACAO VARCHAR(500), @IDCRIACAOPAI VARCHAR(500), @INDICE VARCHAR(500), @INDICEPAI VARCHAR(500) , @OS VARCHAR(30), @QTDETOTAL VARCHAR(500)

PRINT 'OS: '+@OS

-- INÍCIO DO FOR PRINCIPAL PARA OS ITENS DA ESTRUTURA (Z_CRM_ML001005)
DECLARE ESTRUTURA CURSOR FOR 
		
	-- SELEÇÃO DE TODOS OS ITENS DA OS 
	SELECT 
		IDCRIACAO, INDICE, NIVEL, OS
	FROM 
		Z_CRM_ML001005 
	ORDER BY 
		OS,CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)

OPEN ESTRUTURA
	
PRINT 'Início do FOR'

FETCH NEXT FROM ESTRUTURA INTO @IDCRIACAO, @INDICE, @INDICEPAI , @OS
					
WHILE @@FETCH_STATUS = 0
	
BEGIN
		
	PRINT 'ITEM '+@INDICE+' E PAI '+@INDICEPAI

	IF (@INDICEPAI<>'' AND @INDICEPAI IS NOT NULL) 
			
		BEGIN

			-- PEGA O IDCRIACAO DO PAI
			SELECT @IDCRIACAOPAI = IDCRIACAO FROM Z_CRM_ML001005 WHERE OS=@OS AND INDICE = @INDICEPAI 

		END

	ELSE 
		
		SELECT @IDCRIACAOPAI = ''

	PRINT 'ITEM '+@INDICE+' DE IDCRIACAO '+@IDCRIACAO+' TEM O PAI '+@INDICEPAI+' DE IDCRIACAO '+@IDCRIACAOPAI

	-- SALVA O IDCRIACAO PAI PARA CADA ITEM
	UPDATE Z_CRM_ML001005 SET IDCRIACAOPAI = @IDCRIACAOPAI WHERE OS = @OS AND IDCRIACAO = @IDCRIACAO 

	SELECT @IDCRIACAOPAI = ''

FETCH NEXT FROM ESTRUTURA INTO @IDCRIACAO, @INDICE, @INDICEPAI , @OS 
	
END

CLOSE ESTRUTURA
DEALLOCATE ESTRUTURA

UPDATE Z SET  
PESOUNLIQUIDO=CASE WHEN PESOUNLIQUIDO='NULL' THEN 1 ELSE PESOUNLIQUIDO END,
PESOUNITARIO=CASE WHEN PESOUNITARIO='NULL' THEN 1 ELSE PESOUNITARIO END,
DESQTDE=CASE WHEN DESQTDE='NULL' THEN 1 ELSE DESQTDE END,
TOTALQTDE=CASE WHEN TOTALQTDE='NULL' THEN 1 ELSE TOTALQTDE END
FROM Z_CRM_ML001005 Z WHERE PESOUNLIQUIDO='NULL' OR PESOUNITARIO='NULL' OR DESQTDE='NULL' OR TOTALQTDE='NULL' 

-- INÍCIO DO FOR PRINCIPAL PARA OS ITENS DA ESTRUTURA (Z_CRM_ML001005)
DECLARE ESTRUTURA CURSOR FOR 
		
	-- SELEÇÃO DE TODOS OS ITENS DA OS 
	SELECT 
		IDCRIACAO,INDICE,OS
	FROM 
		Z_CRM_ML001005  
	ORDER BY 
		OS,CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID)

OPEN ESTRUTURA
	
PRINT 'INÍCIO DO FOR'

FETCH NEXT FROM ESTRUTURA INTO @IDCRIACAO, @INDICE, @OS
					
WHILE @@FETCH_STATUS = 0
	
BEGIN

	UPDATE 		
		P 	
	SET 		  
		P.TOTALQTDE = CASE WHEN (P.NIVEL IS NOT NULL AND P.NIVEL <>'') 
							THEN CAST(REPLACE((SELECT COALESCE(M.TOTALQTDE,1) FROM Z_CRM_ML001005 M WHERE M.OS=P.OS AND M.INDICE=P.NIVEL),',','.') AS FLOAT) * CAST(REPLACE(COALESCE(P.DESQTDE,1),',','.') AS FLOAT) 
							ELSE CAST(REPLACE(COALESCE(P.DESQTDE,1),',','.') AS FLOAT) 
						END,
		P.PESOBRUTO = REPLACE( CAST( (CASE WHEN (P.NIVEL IS NOT NULL AND P.NIVEL <>'') 
											THEN CAST(REPLACE((SELECT COALESCE(M.TOTALQTDE,1) FROM Z_CRM_ML001005 M WHERE M.OS=P.OS AND M.INDICE=P.NIVEL),',','.') AS FLOAT) * CAST(REPLACE(COALESCE(P.DESQTDE,1),',','.') AS FLOAT) 			
											ELSE CAST(REPLACE(COALESCE(P.DESQTDE,1),',','.') AS FLOAT) 
										END) * ISNULL(CAST(REPLACE(COALESCE(P.PESOUNITARIO,1.0),',','.') AS FLOAT),0) AS DECIMAL(18,4)),'.',','),		  
		P.PESOLIQUIDO = REPLACE( CAST( (CASE WHEN (P.NIVEL IS NOT NULL AND P.NIVEL <>'') 
												THEN CAST(REPLACE((SELECT COALESCE(M.TOTALQTDE,1) FROM Z_CRM_ML001005 M WHERE M.OS=P.OS AND M.INDICE=P.NIVEL),',','.') AS FLOAT) * CAST(REPLACE(COALESCE(P.DESQTDE,1),',','.') AS FLOAT) 			
												ELSE CAST(REPLACE(COALESCE(P.DESQTDE,1),',','.') AS FLOAT) 
										END) * ISNULL(CAST(REPLACE(COALESCE(P.PESOUNLIQUIDO,1.0),',','.') AS FLOAT),0) AS DECIMAL(18,4)),'.',',')    	
	FROM			
		Z_CRM_ML001005 P 	
	WHERE  		
		P.OS=@OS AND P.IDCRIACAO=@IDCRIACAO
		
FETCH NEXT FROM ESTRUTURA INTO @IDCRIACAO, @INDICE, @OS
	
END

CLOSE ESTRUTURA
DEALLOCATE ESTRUTURA

UPDATE 
		C
	SET 
		C.QTDEUNCOMPONENTES = CASE WHEN P.QTDEUNCOMP='DESENHO' AND C.LISTACOMPONENTES='L' THEN P.DESQTDE ELSE C.QTDEUNCOMPONENTES END, 
		C.QTDETOTALCOMPONENTES = (CAST((CASE WHEN P.QTDEUNCOMP='DESENHO' AND C.LISTACOMPONENTES='L'THEN P.DESQTDE ELSE REPLACE(C.QTDEUNCOMPONENTES,',','.')END) AS DECIMAL(18,4)))*(CAST(P.TOTALQTDE AS DECIMAL(18,4))/CAST(P.DESQTDE AS DECIMAL(18,4)))
	FROM 
		Z_CRM_ML001019 C 
		INNER JOIN Z_CRM_ML001005 P ON P.OS=C.OSCOMPONENTES AND P.IDCRIACAO=C.IDCRIACAOCOMPONENTES
	WHERE  		
		C.SUBSTITUTOCOMPONENTES = ''




  UPDATE Z SET [PESOUNITARIO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT(PESOUNITARIO,1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR PESOUNITARIO!='' OR PESOUNITARIO LIKE '%[^a-z.]%' 

  UPDATE Z SET [DIAMETROINTERNODISCO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([DIAMETROINTERNODISCO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [DIAMETROINTERNODISCO]!='' OR [DIAMETROINTERNODISCO] LIKE '%[^a-z.]%' 

  UPDATE Z SET [DIAMETROEXTERNODISCO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([DIAMETROEXTERNODISCO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [DIAMETROEXTERNODISCO]!='' OR [DIAMETROEXTERNODISCO] LIKE '%[^a-z.]%' 

  UPDATE Z SET [ESPABA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([ESPABA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [ESPABA]!='' OR [ESPABA] LIKE '%[^a-z.]%' 

  UPDATE Z SET [LARGURAABA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([LARGURAABA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [LARGURAABA]!='' OR [LARGURAABA] LIKE '%[^a-z.]%' 

  UPDATE Z SET [ESPALMA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([ESPALMA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [ESPALMA]!='' OR [ESPALMA] LIKE '%[^a-z.]%' 

  UPDATE Z SET [ALTURA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([ALTURA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [ALTURA]!='' OR [ALTURA] LIKE '%[^a-z.]%' 

  UPDATE Z SET [AREASECAO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([AREASECAO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [AREASECAO]!='' OR [AREASECAO] LIKE '%[^a-z.]%' 

  UPDATE Z SET [ESPROSCA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([ESPROSCA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [ESPROSCA]!='' OR [ESPROSCA] LIKE '%[^a-z0-9 .]%'

  UPDATE Z SET [DIAMETROINTERNO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([DIAMETROINTERNO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [DIAMETROINTERNO]!='' OR [DIAMETROINTERNO] LIKE '%[^a-z.]%' 

  UPDATE Z SET [DIAMETROEXTERNO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([DIAMETROEXTERNO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [DIAMETROEXTERNO]!='' OR [DIAMETROEXTERNO] LIKE '%[^a-z.]%' 

  UPDATE Z SET [MASSALINEAR]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([MASSALINEAR],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [MASSALINEAR]!='' OR [MASSALINEAR] LIKE '%[^a-z.]%' 

  UPDATE Z SET [BITOLA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([BITOLA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [BITOLA]!='' OR [BITOLA] LIKE '%[^a-z.]%' 

  UPDATE Z SET [LARGURA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([LARGURA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [LARGURA]!='' OR [LARGURA] LIKE '%[^a-z.]%' 
  
  UPDATE Z SET [ESPESSURA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([ESPESSURA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [ESPESSURA]!='' OR [ESPESSURA] LIKE '%[^a-z.]%' 

  UPDATE Z SET [AREAPINTURA]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([AREAPINTURA],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [AREAPINTURA]!='' OR [AREAPINTURA] LIKE '%[^a-z.]%' 
  
  UPDATE Z SET [PERIMETROCORTE]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([PERIMETROCORTE],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [PERIMETROCORTE]!='' OR [PERIMETROCORTE] LIKE '%[^a-z.]%' 

  UPDATE Z SET [PESOLIQUIDO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([PESOLIQUIDO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [PESOLIQUIDO]!='' OR [PESOLIQUIDO] LIKE '%[^a-z.]%' 

  UPDATE Z SET [PESOBRUTO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([PESOBRUTO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [PESOBRUTO]!='' OR [PESOBRUTO] LIKE '%[^a-z.]%' 
  
  UPDATE Z SET [COMPRIMENTO]=0 FROM [Z_CRM_ML001005] Z WHERE LEFT([COMPRIMENTO],1) NOT IN ('0','1','2','3','4','5','6','7','8','9') OR [COMPRIMENTO]!='' OR [COMPRIMENTO] LIKE '%[^a-z.]%'
  
  UPDATE Z SET [DATAREVISAO]='2022-01-12' FROM [Z_CRM_ML001005] Z WHERE DATAREVISAO LIKE '20022%' OR DATAREVISAO LIKE '0022%'


 INSERT INTO ZESTRUTURA SELECT LEFT([DESCRICAO],120)
      ,LEFT([NUMDESENHO],60)
      ,LEFT([REVISAODESENHO],10)
      ,LEFT([NUMDBI],50)
      ,LEFT([REVISAODBI],10)
      ,[DESQTDE]
      ,[TOTALQTDE]
      ,CAST(REPLACE(CASE WHEN [COMPRIMENTO]='' THEN NULL ELSE [COMPRIMENTO] END,',','.') AS NUMERIC(15,4))
      ,LEFT([MATERIAL],90)
      ,[OBSERVACOES]
      ,LEFT([OS],25)
      ,CAST(CASE WHEN [DATAREVISAO]='' OR [DATAREVISAO]='NULL' THEN NULL ELSE DATAREVISAO END  AS DATETIME )
      ,CAST(REPLACE(CASE WHEN [PESOBRUTO]='' THEN NULL ELSE [PESOBRUTO] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [PESOLIQUIDO]='' THEN NULL ELSE [PESOLIQUIDO] END,',','.') AS NUMERIC(15,4))
      ,[OBSERVACOESDESENHO]
      ,CAST(REPLACE(CASE WHEN [PERIMETROCORTE]='' THEN NULL ELSE [PERIMETROCORTE] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [AREAPINTURA]='' THEN NULL ELSE [AREAPINTURA] END,',','.') AS NUMERIC(15,4))
      ,[OBSPROCESSO]
      ,[OBSGERAL]
      ,LEFT([TIPODESENHO],20)
      ,CAST(REPLACE(CASE WHEN [ESPESSURA]='' THEN NULL ELSE [ESPESSURA] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [LARGURA]='' THEN NULL ELSE [LARGURA] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [BITOLA]='' THEN NULL ELSE [BITOLA] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [MASSALINEAR]='' THEN NULL ELSE [MASSALINEAR] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [DIAMETROEXTERNO]='' THEN NULL ELSE [DIAMETROEXTERNO] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [DIAMETROINTERNO]='' THEN NULL ELSE [DIAMETROINTERNO] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [ESPROSCA]='' THEN NULL ELSE [ESPROSCA] END,',','.') AS NUMERIC(15,4))
      ,LEFT([CODIGOPRD],30)
      ,LEFT([POSICAODESENHO],40)
      ,CAST(REPLACE(CASE WHEN [AREASECAO]='' THEN NULL ELSE [AREASECAO] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [ALTURA]='' THEN NULL ELSE [ALTURA] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [ESPALMA]='' THEN NULL ELSE [ESPALMA] END,',','.') AS NUMERIC(15,4))
      ,[POSICAOINDICE]
      ,LEFT([PRODUTORM],160)
      ,[IDPRD]
      ,[UNDMEDIDA]
      ,CAST(REPLACE(CASE WHEN [LARGURAABA]='' THEN NULL ELSE [LARGURAABA] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [ESPABA]='' THEN NULL ELSE [ESPABA] END,',','.') AS NUMERIC(15,4))
      ,LEFT([COMPORLISTA],3)
      ,LEFT([DESCOS],254)
      ,LEFT([NUMDOCDELP],90)
      ,LEFT([REVISAODOCDELP],10)
      ,[CODCOLIGADA]
      ,[CODFILIAL]
      ,CAST(REPLACE(CASE WHEN [DIAMETROEXTERNODISCO]='' THEN NULL ELSE [DIAMETROEXTERNODISCO] END,',','.') AS NUMERIC(15,4))
      ,CAST(REPLACE(CASE WHEN [DIAMETROINTERNODISCO]='' THEN NULL ELSE [DIAMETROINTERNODISCO] END,',','.') AS NUMERIC(15,4))
      ,LEFT([CHECKUSINAGEM],1)
      ,LEFT([CHECKCALDERARIA],1)
      ,LEFT([CODTRFPAI],4)
      ,LEFT([NOMETRFPAI],90)
      ,[EXECUCOES]
      ,CAST(REPLACE(CASE WHEN [PESOUNITARIO]='' THEN NULL ELSE [PESOUNITARIO] END,',','.') AS NUMERIC(15,4))
      ,LEFT([OPSUNITARIAS],3)
      ,LEFT([QTDEUNCOMP],15)
      ,[IDCRIACAO]
      ,[IDCRIACAOPAI]
      ,1
      ,[ITEMDERETORNO]
      ,ISNULL(LEFT([RECCREATEDBY],50),'fluig')
      ,ISNULL([RECCREATEDON],GETDATE())
      ,ISNULL(LEFT([RECMODIFIEDBY],50),'fluig')
      ,ISNULL([RECMODIFIEDON],GETDATE())
  FROM [FLUIG].[DBO].[Z_CRM_ML001005]