WITH CTE_Y AS (	
SELECT	R.*
FROM   TRELSLDLOTE (NOLOCK) R
WHERE  R.CODCOLIGADA = 1
AND R.CODFILIAL = 7
AND R.DATAMOVIMENTO <= GETDATE()
AND R.QTDEENTRADA IS NOT NULL
AND R.SALDOMOV <> 0
AND R.SEQUENCIAL=DBO.FN_DELP_VALORES_MAX_SEQUENCIAL_TRELSLDLOTE(R.CODCOLIGADA,R.CODFILIAL,R.IDLOTE,R.CODLOC)  
)
SELECT  
Y.IDMOV                                                       AS IDMOV_ORIGEM_SALDO,
       (SELECT CODTMV
        FROM   TMOV (NOLOCK)
        WHERE  CODCOLIGADA = 1
               AND IDMOV = Y.IDMOV)                                  AS MOV_ORIGEM_SALDO,
       P.IDPRD                                                        AS IDPRD2,
       Y.IDLOTE                                                      AS LOTE,
       CASE
         WHEN Y.DATAMOVIMENTO > TC.RECMODIFIEDON THEN Y.DATAMOVIMENTO
         ELSE ISNULL(Y.RECMODIFIEDON, GETDATE())
       END                                                            AS DATA_SALDO,
       CASE
         WHEN Y.DATAMOVIMENTO > TC.RECMODIFIEDON THEN ISNULL(Y.SALDOMOV, 0)
         ELSE ISNULL(TC.SALDOFISICO2, 0)
       END                                                            AS SALDOMOV,
Y.SEQUENCIAL                                                  AS SEQ,
Y.CODLOC                                                      AS CODLOC_SALDO,
Y.IDLOTE LOTE2,
Y.SEQUENCIAL SEQ,
Y.CODLOC  CODLOC_LOTE,
NF1.IDMOV IDMOV_NF,
NF1.NUMEROMOV NUM_NF,
NF1.CODTMV CODTMV_NF,
NF1.CODCCUSTO CCUSTO_NF,
DBO.FN_DELP_VALORES_CENTRO_CUSTO(NF1.CODCOLIGADA,'NOME',NF1.CODCCUSTO) DESCR_CCUSTO_NF,
NF1.CODCFO CFO_NF,
DBO.FN_DELP_VALORES_FORNECEDOR(NF1.CODCOLIGADA,'NOMEFANTASIA',NF1.CODCFO) FORNEC_NF,
DBO.FN_DELP_VALORES_ATENDENTE(NF1.CODCOLIGADA,'NOME',NF1.CODVEN1) EMITENTE_NF,
DBO.FN_DELP_VALORES_ATENDENTE(NF1.CODCOLIGADA,'NOME',NF1.CODVEN2) REQUISITANTE_NF,
NF1.HORARIOEMISSAO DT_EMISSAO_NF,
NF1.IDMOV 'IDMOV_1.2.08',
NF1.CODTMV 'CODTMV_1.2.08',
NF1.NUMEROMOV 'NUM_1.2.08',
OC.CODTMV CODTMV_OC,
OC.NUMEROMOV NUM_OC,
OC.CODCCUSTO CCUSTO_OC,
DBO.FN_DELP_VALORES_CENTRO_CUSTO(OC.CODCOLIGADA,'NOME',OC.CODCCUSTO) DESCR_CCUSTO_OC,
OC.CODVEN1,
OC.CODVEN2,
OC.CODCFO CFO_OC,
DBO.FN_DELP_VALORES_FORNECEDOR(OC.CODCOLIGADA,'NOMEFANTASIA',OC.CODCFO) FORNEC_OC,
DBO.FN_DELP_VALORES_ATENDENTE(OC.CODCOLIGADA,'NOME',OC.CODVEN1) COMPRADOR_OC,
DBO.FN_DELP_VALORES_ATENDENTE(OC.CODCOLIGADA,'NOME',OC.CODVEN2) REQUISITANTE_OC,
OC.HORARIOEMISSAO DT_EMISSAO_OC,
CASE
    WHEN LCL.DATA_RETIFICADA IS NOT NULL THEN ( CONVERT(VARCHAR(10), LCL.DATA_RETIFICADA, 103) )
    WHEN L.DATAVALIDADE IS NULL
        AND LCL.DATA_VALIDADE IS NULL
        AND LCL.DATA_RETIFICADA IS NULL THEN ( CONVERT(VARCHAR(10), LCL.DATA_VALIDADE_B, 103) )
    WHEN L.DATAVALIDADE IS NULL
        AND LCL.DATA_VALIDADE_B IS NULL
        AND LCL.DATA_RETIFICADA IS NULL THEN ( CONVERT(VARCHAR(10), LCL.DATA_VALIDADE, 103) )
    ELSE ( CONVERT(VARCHAR(10), L.DATAVALIDADE, 103) )
END                                                            AS DATA_VALIDA,
DATEDIFF(DAY, GETDATE(), L.DATAVALIDADE) DIAS_A_VENCER,
( CONVERT(VARCHAR(10), LCL.DATA_VALIDADE, 103) ) VALIDADE_COMP_A,
( CONVERT(VARCHAR(10), LCL.DATA_VALIDADE_B, 103) ) VALIDADE_COMP_B,
LCL.LOCALIZACAO_LOTE,
P.CAMPOLIVRE2 LOCALIZACAO_PRODUTO_F8,
P.CAMPOLIVRE3 LOCALIZACAO_PRODUTO_F7,
LS.DESCRICAO STATUS_LOTE,
FORMAT(L.DATAENTRADA, 'dd-MM-yyyy') DTA_ENTRADA_LOTE,
L.NUMLOTE NUM_LOTE,
P.CODIGOPRD PRODUTO,
P.DESCRICAO DESC_PRODUTO,
P.CODUNDCONTROLE UND,
L.CODCFO CFO_LOTE,
P.CODTB2FAT '2A_CLASSIF',
P.CODTB1FAT '1A_CLASSIF'
FROM TLOTEPRD (NOLOCK) L
INNER JOIN TLOTEPRDCOMPL (NOLOCK) LCL ON
LCL.CODCOLIGADA=L.CODCOLIGADA
AND LCL.IDLOTE=L.IDLOTE
INNER JOIN TSTATUSLOTEPRD (NOLOCK) LS ON
LS.IDSTATUS=L.IDSTATUS
INNER JOIN TPRD (NOLOCK) P ON
L.CODCOLIGADA=P.CODCOLIGADA
AND L.IDPRD=P.IDPRD
CROSS APPLY DBO.FN_DELP_RETORNA_LOTE_OC(L.CODCOLIGADA,L.IDLOTE,DEFAULT,'1.1','OC') OC
OUTER APPLY DBO.FN_DELP_RETORNA_LOTE_OC(L.CODCOLIGADA,L.IDLOTE,DEFAULT,'1.2.08','%') NF1
LEFT JOIN CTE_Y Y ON
L.CODCOLIGADA = Y.CODCOLIGADA
AND L.IDLOTE = Y.IDLOTE
LEFT JOIN TLOTEPRDLOC (NOLOCK) TC ON 
Y.CODCOLIGADA = TC.CODCOLIGADA
AND Y.IDLOTE = TC.IDLOTE
AND ISNULL(TC.SALDOFISICO2,0)!=0
WHERE ( OC.CODTMV IN ( '1.1.02', '1.1.32', '1.1.15' )
        OR OC.CODTMV LIKE ( '1.2.%' )
        OR OC.CODTMV LIKE ( '1.1.08' )
           AND OC.CODTMV NOT IN ( '1.2.23' ) )
	AND DATEDIFF(YEAR,L.RECCREATEDON,GETDATE())<=2
    AND L.NUMLOTE LIKE :NUMERO_LOTE
    AND L.IDSTATUS LIKE :COD_STATUS
    AND P.CODIGOPRD LIKE :PRODUTO

