SELECT DISTINCT R.NUMPLANOCORTE,P.STATUS FROM
	(SELECT Z.CODCOLIGADA,Z.CODFILIAL,Z.CODORDEM,Z.CODESTRUTURA,Z.IDATVORDEM,NUMPLANOCORTE,Z.QUANTIDADE,CODIGOMP,QTDEMP,NUMLOTE,
	 CASE WHEN K.QUANTIDADE>ISNULL(Z.QTDEAPONTADA,0) THEN Z.QUANTIDADE ELSE Z.QTDEAPONTADA END AS QTDAPONTADA
		FROM ZMDPLANOAPROVEITAMENTOCORTE Z
		INNER JOIN KATVORDEM K ON
		K.CODCOLIGADA=Z.CODCOLIGADA 
		AND K.CODFILIAL=Z.CODFILIAL
		AND K.CODORDEM=Z.CODORDEM
		AND K.IDATVORDEM=Z.IDATVORDEM
		AND K.CODESTRUTURA=Z.CODESTRUTURA) R
	INNER JOIN ZMDKATVORDEMPROGRAMACAO P ON
	P.CODCOLIGADA=R.CODCOLIGADA
	AND P.CODFILIAL=R.CODFILIAL
	AND P.NUMPLANOCORTE=R.NUMPLANOCORTE
	WHERE 
	--QTDAPONTADA IS NOT NULL AND 
	R.QTDAPONTADA<R.QUANTIDADE AND P.STATUS<>2


--SELECT * FROM ZMDKATVORDEMPROGRAMACAO