SELECT OS,EXECUCAO,CODTRFPAI CODTAREFA,EX.NOMETRFPAI TAREFA,
LEFT(ISNULL(EX.CODIGOPRD,'NÃO CRIADO'),6) MASK,
ISNULL(EX.CODIGOPRD,'NÃO CRIADO') CODIGOPRD,
ISNULL(EX.IDPRD,'NÃO CRIADO') IDPRD, EX.DESCRICAO,
ISNULL(K.CODORDEM,'NÃO CRIADA') OP,
CAST(ISNULL(K.QTDEPLANEJADA,EX.DESQTDE) AS INT) PREVISTO,
CAST(ISNULL(K.QTDEEFETIVADA,0) AS INT) EFETIVADO,
ISNULL(KS.DSCSTATUS,'NÃO CRIADA') STATUS 
FROM Z_CRM_EX001005 EX
LEFT JOIN CORPORE.DBO.KITEMORDEM K  ON
K.CODCOLIGADA=EX.CODCOLIGADA
AND K.CODFILIAL=EX.CODFILIAL
AND K.CODESTRUTURA=EX.CODIGOPRD COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI
AND K.CODCCUSTO=EX.OS COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI
LEFT JOIN CORPORE.DBO.KORDEMCOMPL KL
ON KL.CODCOLIGADA=K.CODCOLIGADA
AND KL.CODFILIAL=K.CODFILIAL
AND KL.CODORDEM=K.CODORDEM
LEFT JOIN CORPORE.DBO.KSTATUS KS ON
KS.CODCOLIGADA=K.CODCOLIGADA
AND KS.CODSTATUS=K.STATUS
WHERE ( TIPODESENHO='ACABADO' OR LEN(EX.INDICE)=1 ) AND ( KL.NUMEXEC=EX.EXECUCAO OR KL.NUMEXEC IS NULL) AND ( K.STATUS!=6 OR K.STATUS IS NULL)
ORDER BY OS,CODTAREFA,EXECUCAO,OP