 DECLARE @OS VARCHAR(30);
 SET @OS ='3.07860.32.001';

 WITH CTE AS ( 
        SELECT FORMAT(DATEPART(MONTH,MIN(DATAEMISSAO)),'00') MES ,FORMAT(DATEPART(YEAR,MIN(DATAEMISSAO)),'0000') ANO,FORMAT(DATEPART(MONTH,MAX(DATAEMISSAO)),'00') MESMAX ,FORMAT(DATEPART(YEAR,MAX(DATAEMISSAO)),'0000') ANOMAX 
        FROM FLAN WHERE CODCCUSTO=@OS
        UNION ALL  
        SELECT FORMAT(CASE WHEN MES=12 THEN 1 ELSE MES+1 END,'00') ,FORMAT(CASE WHEN MES=12 THEN ANO+1 ELSE ANO END,'0000') ANO ,MESMAX,ANOMAX 
        FROM CTE 
        WHERE  FORMAT(CASE WHEN MES=12 THEN 1 ELSE MES+1 END,'00')!=FORMAT(CASE WHEN MESMAX=12 THEN 1 ELSE MESMAX+1 END,'00') OR FORMAT(CASE WHEN MES=12 THEN ANO+1 ELSE ANO END,'0000')!=FORMAT(CASE WHEN MES=12 THEN ANOMAX+1 ELSE ANOMAX END,'0000') 
        ) 
SELECT C.ANO, C.MES, CONCAT(C.MES,'/',C.ANO) PERIODO,
		SUM(ISNULL(FAT_PREVISTO,0)) FAT_PREVISTO,
		SUM(ISNULL(FAT_REALIZADO,0)) FAT_REALIZADO
FROM CTE C LEFT JOIN (
SELECT MES,ANO,STATUSLAN,CASE WHEN ORD=1 OR R.STATUSLAN=0 THEN FAT_PREVISTO ELSE 0 END FAT_PREVISTO,0 FAT_REALIZADO,DATAEMISSAO  FROM (
SELECT MONTH(DATAEMISSAO) MES, YEAR(DATAEMISSAO) ANO,STATUSLAN,
			SUM(VALORORIGINAL) FAT_PREVISTO,
			0 FAT_REALIZADO,ROW_NUMBER()OVER(PARTITION BY MONTH(DATAEMISSAO),YEAR(DATAEMISSAO) ORDER BY RECCREATEDON DESC) ORD,DATAEMISSAO
			FROM FLAN L
			WHERE	PAGREC = 1
			AND		CODTDO <> '075'
			AND		CODCCUSTO = @OS AND CODTDO = '030'
			AND (STATUSLAN != 2 OR NOT EXISTS(SELECT * FROM FLAN L2 WHERE  MONTH(L2.DATAEMISSAO)=MONTH(L.DATAEMISSAO) AND  YEAR(L2.DATAEMISSAO)= YEAR(L.DATAEMISSAO)
			AND CODTDO = '030' AND L2.STATUSLAN IN (0,1) AND L2.CODCCUSTO=L.CODCCUSTO AND CODTDO!='075' AND PAGREC=1 )) 
		GROUP BY  MONTH(DATAEMISSAO),YEAR(DATAEMISSAO),STATUSLAN,RECCREATEDON,DATAEMISSAO ) R
UNION ALL
 SELECT MONTH(DATAEMISSAO) MES, YEAR(DATAEMISSAO) ANO,STATUSLAN,
			0 FAT_PREVISTO,
			SUM(VALORORIGINAL) FAT_REALIZADO,DATAEMISSAO
	FROM FLAN L
	WHERE	PAGREC = 1
	AND		CODTDO <> '075'
	AND		CODCCUSTO = @OS  AND CODTDO != '030' AND STATUSLAN!=2
GROUP BY  MONTH(DATAEMISSAO),YEAR(DATAEMISSAO),STATUSLAN,DATAEMISSAO
 ) F ON F.ANO=C.ANO AND F.MES=C.MES
 GROUP BY C.ANO, C.MES, RIGHT('0'+CAST(F.MES AS VARCHAR(2)),2)+'/'+CAST(F.ANO AS VARCHAR(4))
 ORDER BY ANO, MES


 SELECT MES,ANO,STATUSLAN,CASE WHEN ORD=1 OR R.STATUSLAN=0 THEN FAT_PREVISTO ELSE 0 END FAT_PREVISTO,0 FAT_REALIZADO,DATAEMISSAO  FROM (
SELECT MONTH(DATAEMISSAO) MES, YEAR(DATAEMISSAO) ANO,STATUSLAN,
			SUM(VALORORIGINAL) FAT_PREVISTO,
			0 FAT_REALIZADO,ROW_NUMBER()OVER(PARTITION BY MONTH(DATAEMISSAO),YEAR(DATAEMISSAO) ORDER BY RECCREATEDON DESC) ORD,DATAEMISSAO
			FROM FLAN L
			WHERE	PAGREC = 1
			AND		CODTDO <> '075'
			AND		CODCCUSTO = '3.07860.32.001' AND CODTDO = '030' AND MONTH(L.DATAEMISSAO)=6 AND  YEAR(L.DATAEMISSAO)= 2023
		GROUP BY  MONTH(DATAEMISSAO),YEAR(DATAEMISSAO),STATUSLAN,RECCREATEDON,DATAEMISSAO ) R

