SELECT
    'ML0010' + CONVERT(VARCHAR(10), l.COD_LISTA_PAI)  AS 'TABELA_PRINCIPAL',
    'ML0010' + CONVERT(VARCHAR(10), l.COD_LISTA_FILHO)  AS 'TABELA_PAIxFILHO',
    d.COD_LISTA,
    l.COD_LISTA_PAI,
    l.COD_LISTA_FILHO,
    l.COD_TABELA
    ,d.NUM_DOCTO_PROPRIED
    ,d.NUM_VERS_PROPRIED

FROM DEF_PROCES             p  
LEFT JOIN VERS_DEF_PROCES   vp  ON vp.COD_DEF_PROCES = p.COD_DEF_PROCES  
                            AND vp.LOG_ATIV = 1
LEFT JOIN DOCUMENTO         d   ON d.NR_DOCUMENTO    = vp.NUM_PASTA_FORM 
                            AND d.VERSAO_ATIVA = 1
LEFT JOIN SERV_DATASET      ds  ON ds.COD_DATASET    = d.NM_DATASET  
LEFT JOIN META_LISTA_REL    l   ON l.COD_LISTA_PAI    = d.COD_LISTA  
WHERE p.COD_DEF_PROCES LIKE '%'   
ORDER BY vp.NUM_VERS  DESC