WITH CTE AS (
SELECT CAST(ROW_NUMBER()OVER(ORDER BY T.IDMOV) AS VARCHAR(MAX)) IND, 1 NIVEL,M.IDTRF,M.IDPRJ,T.CODTMV,T.NUMEROMOV,T.SERIE,TI.CODCOLIGADA,TI.QUANTIDADEORIGINAL,TI.PRECOUNITARIO,TI.IDPRD,TI.IDMOV,NULL IDMOVPAI,TI.NSEQITMMOV 
FROM MPRJ P INNER JOIN MITEMPEDIDOMATEXTRA M ON
P.CODCOLIGADA=M.CODCOLIGADA
AND P.IDPRJ=M.IDPRJ  
INNER JOIN TMOV T ON
T.CODCOLIGADA=M.CODCOLIGADA
AND T.IDMOV=M.IDMOV
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=M.CODCOLIGADA
AND TI.IDMOV=M.IDMOV
AND TI.NSEQITMMOV=M.NSEQITMMOV
WHERE P.CODPRJ='3.07860.32.001' AND P.POSICAO IN (1,4) AND T.STATUS NOT IN ('C')
UNION ALL 
SELECT CAST(CONCAT(C.IND,'.',ROW_NUMBER()OVER(ORDER BY T.IDMOV)) AS VARCHAR(MAX)) IND,NIVEL+1 NIVEL,C.IDTRF,C.IDPRJ,T.CODTMV,T.NUMEROMOV,T.SERIE,TI.CODCOLIGADA,TI.QUANTIDADEORIGINAL,TI.PRECOUNITARIO,TI.IDPRD,TI.IDMOV,TL.IDMOVORIGEM IDMOVPAI,TI.NSEQITMMOV 
FROM CTE C 
INNER JOIN TITMMOVRELAC TL ON
TL.CODCOLORIGEM=C.CODCOLIGADA
AND TL.IDMOVORIGEM=C.IDMOV
AND TL.NSEQITMMOVORIGEM=C.NSEQITMMOV
INNER JOIN  TMOV T ON
T.CODCOLIGADA=TL.CODCOLDESTINO
AND T.IDMOV=TL.IDMOVDESTINO
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=TL.CODCOLDESTINO
AND TI.IDMOV=TL.IDMOVDESTINO
AND TI.NSEQITMMOV=TL.NSEQITMMOVDESTINO
WHERE T.STATUS NOT IN ('C')
)
SELECT * FROM (
SELECT IND,NIVEL,IDTRF,IDPRJ,CODTMV,NUMEROMOV,SERIE,CASE WHEN CODTMV LIKE '1.1%' AND SERIE!='OC' AND SERIE LIKE 'S%' THEN 'SC'
														WHEN CODTMV LIKE '1.1%' AND SERIE='OC'  THEN 'OC'
														WHEN CODTMV LIKE '1.2%' THEN 'NF' END TIPO,
														IDMOV,IDMOVPAI,NSEQITMMOV,IDPRD,QUANTIDADEORIGINAL QUANTIDADE,PRECOUNITARIO*QUANTIDADEORIGINAL VALOR
FROM CTE 
) C 
PIVOT (
	SUM(QUANTIDADE) FOR TIPO IN ([SC],[OC],[NF]) 
) AS PIVOTED
ORDER BY CAST('/'+REPLACE(IND,'.','/')+'/' AS HIERARCHYID),IDPRD

