DECLARE @CMD NVARCHAR(2000);
DECLARE STATS_CURSOR CURSOR FOR 

-- UPDATE STATISTCS
SELECT DISTINCT 'UPDATE STATISTICS ' + OBJECT_SCHEMA_NAME(STAT.OBJECT_ID) + '.' + OBJECT_NAME(STAT.OBJECT_ID) + ';' AS COMMAND
FROM SYS.STATS AS STAT    
CROSS APPLY SYS.DM_DB_STATS_PROPERTIES(STAT.OBJECT_ID, STAT.STATS_ID) AS SP   
WHERE LAST_UPDATED < GETDATE()-7 OR MODIFICATION_COUNTER > ROWS*.10 AND DB_NAME()='FLUIG'

UNION

-- REBUILD INDEX
SELECT DISTINCT 'ALTER INDEX '+I.NAME+' ON '+DB_NAME(DATABASE_ID) + '.' +OBJECT_SCHEMA_NAME(S.OBJECT_ID) + '.' + OBJECT_NAME(I.OBJECT_ID) + ' REBUILD' COMMAND,*
FROM SYS.INDEXES I 
INNER JOIN SYS.DM_DB_INDEX_USAGE_STATS S ON
I.OBJECT_ID=S.OBJECT_ID
AND I.INDEX_ID=S.INDEX_ID
WHERE DB_NAME(DATABASE_ID)='FLUIG' AND ( ISNULL(LAST_USER_UPDATE,ISNULL(LAST_SYSTEM_UPDATE,'1900-01-01')) < GETDATE()-7 ) AND ( USER_SEEKS+USER_SCANS+SYSTEM_SEEKS+SYSTEM_SCANS)>0 
AND ('ALTER INDEX '+I.NAME+' ON '+DB_NAME(DATABASE_ID) + '.' +OBJECT_SCHEMA_NAME(S.OBJECT_ID) + '.' + OBJECT_NAME(I.OBJECT_ID)) IS NOT NULL AND NAME NOT LIKE '%<%'  AND NAME NOT LIKE '%>%'

OPEN STATS_CURSOR  
FETCH NEXT FROM STATS_CURSOR INTO @CMD
 
WHILE @@FETCH_STATUS = 0  
BEGIN  
  EXEC SP_EXECUTESQL @CMD
  FETCH NEXT FROM STATS_CURSOR INTO @CMD 
END  
CLOSE STATS_CURSOR  
DEALLOCATE STATS_CURSOR

