
WITH CTEC AS (
	SELECT CAST(X.IDJOB AS VARCHAR(500) ) IDJOB,X.NOME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOME,X.CODSISTEMA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI SISTEMA,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA) PROGRAMADO,
	CASE WHEN GH.DATAINIEXEC IS NULL THEN 1 ELSE DATEDIFF(SECOND,GH.DATAINIEXEC,GH.DATAFIMEXEC) END LAST_RUN_DURATION,X.HORARECORRENCIA,X.MINUTORECORRENCIA,
	X.CODUSUARIO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI USUARIO,X.DATACRIACAO CRIACAO,X.RECMODIFIEDON ALTERACAO
	FROM CORPORE.DBO.GJOBX X 
	LEFT JOIN CORPORE.DBO.GJOBXEXECUCAO GX ON 
	GX.IDJOB=X.IDJOB
	LEFT JOIN  CORPORE.DBO.GJOBXEXECUCAOHST GH ON 
	GH.IDJOB=X.IDJOB
	WHERE TIPORECORRENCIA = 3
	UNION ALL
	SELECT IDJOB,NOME,SISTEMA,DATEADD(MINUTE,MINUTORECORRENCIA,DATEADD(HOUR,HORARECORRENCIA,PROGRAMADO)) PROGRAMADO,LAST_RUN_DURATION,HORARECORRENCIA,MINUTORECORRENCIA,USUARIO,CRIACAO,ALTERACAO FROM CTEC 
	WHERE DATEADD(MINUTE,MINUTORECORRENCIA,DATEADD(HOUR,HORARECORRENCIA,PROGRAMADO))<DATEADD(MONTH,1,PROGRAMADO)
),
CTE0 AS (
		SELECT 
		   CAST(S.JOB_ID AS VARCHAR(500) ) IDJOB,S.NAME AS JOBNAME,ST.DATABASE_NAME,   
			CAST(CASE SJ.NEXT_RUN_DATE
				WHEN 0 THEN CAST('N/A' AS CHAR(10))
				ELSE CONVERT(CHAR(10), CONVERT(DATETIME, CONVERT(CHAR(8),SJ.NEXT_RUN_DATE)),120)  + ' ' + LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8)
			END AS DATETIME) NEXTRUNTIME, 
			CAST(LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8) AS TIME) ACTIVE_START_TIME,
			CAST(LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_END_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_END_TIME),3,0,':')),6,0,':'),8) AS TIME) ACTIVE_END_TIME,
			SUM(CASE WHEN ST.LAST_RUN_DURATION=0 THEN CAST(CAST(1 AS DATETIME) AS INT) ELSE DATEDIFF(SECOND,'1900-01-01 00:00:00.000',CAST(STUFF(STUFF(RIGHT('00000' + CAST(LAST_RUN_DURATION AS VARCHAR),6),3,0,':'),6,0,':') AS DATETIME) ) END) LAST_RUN_DURATION,
			L.NAME CREATOR,S.DATE_CREATED,S.DATE_MODIFIED,0 ROWN,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,CAST(CASE SJ.NEXT_RUN_DATE
				WHEN 0 THEN CAST('N/A' AS CHAR(10))
				ELSE CONVERT(CHAR(10), CONVERT(DATETIME, CONVERT(CHAR(8),SJ.NEXT_RUN_DATE)),120)  + ' ' + LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8)
			END AS DATETIME) NEXTRUNTIME2
	FROM MSDB.DBO.SYSJOBS S
	LEFT JOIN MSDB.DBO.SYSJOBSCHEDULES SJ ON S.JOB_ID = SJ.JOB_ID  
	LEFT JOIN MSDB.DBO.SYSSCHEDULES SS ON SS.SCHEDULE_ID = SJ.SCHEDULE_ID
	LEFT JOIN MSDB.DBO.SYSJOBSTEPS ST ON ST.JOB_ID=S.JOB_ID
	LEFT JOIN MASTER.SYS.SYSLOGINS L ON S.OWNER_SID = L.SID
	WHERE  S.ENABLED=1 AND SS.ENABLED=1 AND ( SS.FREQ_TYPE!=4 OR ( SS.FREQ_TYPE=4 AND SS.FREQ_SUBDAY_TYPE NOT IN(2,4) ) )  AND FREQ_TYPE=4 AND FREQ_SUBDAY_TYPE>1
	GROUP BY S.JOB_ID,S.NAME,SJ.NEXT_RUN_DATE,ST.DATABASE_NAME,SS.NAME,SS.FREQ_TYPE,SS.FREQ_RECURRENCE_FACTOR,SS.SCHEDULE_ID,SS.FREQ_INTERVAL,
	SJ.SCHEDULE_ID,SS.FREQ_SUBDAY_INTERVAL,SS.FREQ_SUBDAY_TYPE,SS.ACTIVE_START_TIME,SJ.NEXT_RUN_TIME,L.NAME,S.DATE_CREATED,S.DATE_MODIFIED,
	FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,ACTIVE_START_TIME,ACTIVE_END_TIME
	UNION ALL
	SELECT  CAST(IDJOB AS VARCHAR(500) ) IDJOB,JOBNAME,DATABASE_NAME,
	CASE FREQ_SUBDAY_TYPE 
	WHEN 1 THEN DATEADD(DAY,1,NEXTRUNTIME) 
	WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME) 
	WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	END AS NEXTRUNTIME,ACTIVE_START_TIME,ACTIVE_END_TIME,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,ROWN+1,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,NEXTRUNTIME2 FROM CTE0 
	WHERE CAST(CASE FREQ_SUBDAY_TYPE 
	WHEN 1 THEN DATEADD(DAY,1,NEXTRUNTIME) 
	WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME) 
	WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	END AS DATE)<=DATEADD(DAY,15,NEXTRUNTIME2)
),
 CTED AS (
		SELECT 
		   CAST(S.JOB_ID AS VARCHAR(500) ) IDJOB,S.NAME AS JOBNAME,ST.DATABASE_NAME,   
			CAST(CASE SJ.NEXT_RUN_DATE
				WHEN 0 THEN CAST('N/A' AS CHAR(10))
				ELSE CONVERT(CHAR(10), CONVERT(DATETIME, CONVERT(CHAR(8),SJ.NEXT_RUN_DATE)),120)  + ' ' + LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8)
			END AS DATETIME) NEXTRUNTIME, 
			CAST(LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8) AS TIME) ACTIVE_START_TIME,
			CAST(LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_END_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_END_TIME),3,0,':')),6,0,':'),8) AS TIME) ACTIVE_END_TIME,
			SUM(CASE WHEN ST.LAST_RUN_DURATION=0 THEN CAST(CAST(1 AS DATETIME) AS INT) ELSE DATEDIFF(SECOND,'1900-01-01 00:00:00.000',CAST(STUFF(STUFF(RIGHT('00000' + CAST(LAST_RUN_DURATION AS VARCHAR),6),3,0,':'),6,0,':') AS DATETIME) ) END) LAST_RUN_DURATION,
			L.NAME CREATOR,S.DATE_CREATED,S.DATE_MODIFIED,0 ROWN,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR
	FROM MSDB.DBO.SYSJOBS S
	LEFT JOIN MSDB.DBO.SYSJOBSCHEDULES SJ ON S.JOB_ID = SJ.JOB_ID  
	LEFT JOIN MSDB.DBO.SYSSCHEDULES SS ON SS.SCHEDULE_ID = SJ.SCHEDULE_ID
	LEFT JOIN MSDB.DBO.SYSJOBSTEPS ST ON ST.JOB_ID=S.JOB_ID
	LEFT JOIN MASTER.SYS.SYSLOGINS L ON S.OWNER_SID = L.SID
	WHERE  S.ENABLED=1 AND SS.ENABLED=1 AND ( SS.FREQ_TYPE!=4 OR ( SS.FREQ_TYPE=4 AND SS.FREQ_SUBDAY_TYPE NOT IN(2,4) ) )  AND FREQ_TYPE=4 AND FREQ_SUBDAY_TYPE=1
	GROUP BY S.JOB_ID,S.NAME,SJ.NEXT_RUN_DATE,ST.DATABASE_NAME,SS.NAME,SS.FREQ_TYPE,SS.FREQ_RECURRENCE_FACTOR,SS.SCHEDULE_ID,SS.FREQ_INTERVAL,
	SJ.SCHEDULE_ID,SS.FREQ_SUBDAY_INTERVAL,SS.FREQ_SUBDAY_TYPE,SS.ACTIVE_START_TIME,SJ.NEXT_RUN_TIME,L.NAME,S.DATE_CREATED,S.DATE_MODIFIED,
	FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,ACTIVE_START_TIME,ACTIVE_END_TIME
	UNION ALL
	SELECT  CAST(IDJOB AS VARCHAR(500) ) IDJOB,JOBNAME,DATABASE_NAME,
	DATEADD(DAY,1,NEXTRUNTIME) NEXTRUNTIME,ACTIVE_START_TIME,ACTIVE_END_TIME,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,ROWN+1,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR FROM CTED 
	WHERE ROWN<15
),

CTED2 AS (
	SELECT DISTINCT CAST(JOB_ID AS VARCHAR(500) ) IDJOB,JOBNAME,DATABASE_NAME,CAST(LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8) AS TIME) ACTIVE_START_TIME,
	CAST(LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_END_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_END_TIME),3,0,':')),6,0,':'),8) AS TIME) ACTIVE_END_TIME,
	DATEADD(DAY,ABS(DATEPART(WEEKDAY,NEXTRUNTIME)-DIASEMANA2),NEXTRUNTIME) PROGRAMADO ,DIASEMANA2,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,0 ROWN,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR FROM ( 
	SELECT 
		   S.JOB_ID,S.NAME AS JOBNAME,ST.DATABASE_NAME,   
			CAST(CASE SJ.NEXT_RUN_DATE
				WHEN 0 THEN CAST('N/A' AS CHAR(10))
				ELSE CONVERT(CHAR(10), CONVERT(DATETIME, CONVERT(CHAR(8),SJ.NEXT_RUN_DATE)),120)  + ' ' + LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(ACTIVE_START_TIME)))+ CONVERT(VARCHAR(6),ACTIVE_START_TIME),3,0,':')),6,0,':'),8)
			END AS DATETIME) NEXTRUNTIME, 
			SUM(CASE WHEN ST.LAST_RUN_DURATION=0 THEN CAST(CAST(1 AS DATETIME) AS INT) ELSE DATEDIFF(SECOND,'1900-01-01 00:00:00.000',CAST(STUFF(STUFF(RIGHT('00000' + CAST(LAST_RUN_DURATION AS VARCHAR),6),3,0,':'),6,0,':') AS DATETIME) ) END) LAST_RUN_DURATION,
			L.NAME CREATOR,S.DATE_CREATED,S.DATE_MODIFIED,FREQ_TYPE,SS.FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,ACTIVE_START_TIME,ACTIVE_END_TIME
	FROM MSDB.DBO.SYSJOBS S
	LEFT JOIN MSDB.DBO.SYSJOBSCHEDULES SJ ON S.JOB_ID = SJ.JOB_ID  
	LEFT JOIN MSDB.DBO.SYSSCHEDULES SS ON SS.SCHEDULE_ID = SJ.SCHEDULE_ID
	LEFT JOIN MSDB.DBO.SYSJOBSTEPS ST ON ST.JOB_ID=S.JOB_ID
	LEFT JOIN MASTER.SYS.SYSLOGINS L ON S.OWNER_SID = L.SID
	INNER JOIN (SELECT SS.SCHEDULE_ID,
			'D1' = CASE WHEN (FREQ_INTERVAL & 1  <> 0) THEN 0 ELSE -1 END,
			'D2' = CASE WHEN (FREQ_INTERVAL & 2  <> 0) THEN 1  ELSE -1 END,
			'D3' = CASE WHEN (FREQ_INTERVAL & 4  <> 0) THEN 2  ELSE -1 END,
			'D4' = CASE WHEN (FREQ_INTERVAL & 8  <> 0) THEN 3  ELSE -1 END,
			'D5' = CASE WHEN (FREQ_INTERVAL & 16 <> 0) THEN 4  ELSE -1 END,
			'D6' = CASE WHEN (FREQ_INTERVAL & 32 <> 0) THEN 5  ELSE -1 END,
			'D7' = CASE WHEN (FREQ_INTERVAL & 64 <> 0) THEN 6  ELSE -1 END,
			'D8' = CASE WHEN (FREQ_INTERVAL & 1  <> 0) THEN 7 ELSE -1 END,
			'D9' = CASE WHEN (FREQ_INTERVAL & 2  <> 0) THEN 8  ELSE -1 END,
			'D10' = CASE WHEN (FREQ_INTERVAL & 4  <> 0) THEN 9  ELSE -1 END,
			'D11' = CASE WHEN (FREQ_INTERVAL & 8  <> 0) THEN 10  ELSE -1 END,
			'D12' = CASE WHEN (FREQ_INTERVAL & 16 <> 0) THEN 11  ELSE -1 END,
			'D13' = CASE WHEN (FREQ_INTERVAL & 32 <> 0) THEN 12  ELSE -1 END,
			'D14' = CASE WHEN (FREQ_INTERVAL & 64 <> 0) THEN 13  ELSE -1 END 
        FROM MSDB..SYSSCHEDULES SS
	WHERE FREQ_TYPE = 8 ) F
	ON F.SCHEDULE_ID = SJ.SCHEDULE_ID
	WHERE  S.ENABLED=1 AND SS.ENABLED=1 AND ( SS.FREQ_TYPE!=4 OR ( SS.FREQ_TYPE=4 AND SS.FREQ_SUBDAY_TYPE NOT IN(2,4) ) )  AND FREQ_TYPE>4 AND FREQ_SUBDAY_TYPE>1
	GROUP BY  S.JOB_ID,S.NAME,SJ.NEXT_RUN_DATE,ST.DATABASE_NAME,SS.NAME,SS.FREQ_TYPE,SS.FREQ_RECURRENCE_FACTOR,SS.SCHEDULE_ID,SS.FREQ_INTERVAL,
	SJ.SCHEDULE_ID,SS.FREQ_SUBDAY_INTERVAL,SS.FREQ_SUBDAY_TYPE,SS.ACTIVE_START_TIME,SJ.NEXT_RUN_TIME,L.NAME,S.DATE_CREATED,S.DATE_MODIFIED,
	FREQ_TYPE,SS.FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,F.SCHEDULE_ID,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,ACTIVE_START_TIME,ACTIVE_END_TIME
	) C
	UNPIVOT
	(
		DIASEMANA2 FOR DATAPROGRAMADA IN (D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14)
	) AS CP
	WHERE DIASEMANA2!=-1
	UNION ALL
	SELECT IDJOB,JOBNAME,DATABASE_NAME,ACTIVE_START_TIME,ACTIVE_END_TIME,
	CASE FREQ_SUBDAY_TYPE 
	WHEN 1 THEN DATEADD(DAY,1,PROGRAMADO) 
	WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,PROGRAMADO)  
	WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,PROGRAMADO) 
	WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,PROGRAMADO)  
	END ,DIASEMANA2,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,
	ROWN+1 ROWN,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,
	FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR
	FROM CTED2 
	WHERE ROWN<15 AND
	( (CAST(CASE FREQ_SUBDAY_TYPE 
		WHEN 1 THEN DATEADD(DAY,1,PROGRAMADO) 
		WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,PROGRAMADO)  
		WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,PROGRAMADO) 
		WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,PROGRAMADO) 
	END AS TIME)<=CONVERT(TIME,ACTIVE_END_TIME) AND 
	CAST(CASE FREQ_SUBDAY_TYPE 
		WHEN 1 THEN DATEADD(DAY,1,PROGRAMADO) 
		WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,PROGRAMADO)  
		WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,PROGRAMADO) 
		WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,PROGRAMADO) 
	END AS TIME)>=CONVERT(TIME,ACTIVE_START_TIME)
	) OR CAST( ACTIVE_END_TIME AS TIME)<=CAST(ACTIVE_START_TIME AS TIME) )AND 
	CAST(CASE FREQ_SUBDAY_TYPE 
		WHEN 1 THEN DATEADD(DAY,1,PROGRAMADO) 
		WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,PROGRAMADO)  
		WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,PROGRAMADO) 
		WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,PROGRAMADO)  
	END AS DATE)=CAST(PROGRAMADO AS DATE)  
)
, CTED3 AS (

	SELECT IDJOB,JOBNAME,DATABASE_NAME,NEXTRUNTIME,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,
	ACTIVE_START_TIME,ACTIVE_END_TIME FROM CTED WHERE  NEXTRUNTIME>=GETDATE() 
	UNION ALL
	SELECT  CAST(IDJOB AS VARCHAR(500) ) IDJOB,JOBNAME,DATABASE_NAME,
	CASE FREQ_SUBDAY_TYPE 
	WHEN 1 THEN DATEADD(DAY,1,NEXTRUNTIME) 
	WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME) 
	WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	END ,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,FREQ_TYPE,FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,ACTIVE_START_TIME,ACTIVE_END_TIME FROM CTED3 
	WHERE CAST(CASE FREQ_SUBDAY_TYPE 
		WHEN 1 THEN DATEADD(DAY,1,NEXTRUNTIME) 
		WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
		WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME) 
		WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	END AS TIME)<CONVERT(TIME,ACTIVE_END_TIME) AND CAST(CASE FREQ_SUBDAY_TYPE 
		WHEN 1 THEN DATEADD(DAY,1,NEXTRUNTIME) 
		WHEN 2 THEN DATEADD(SECOND,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
		WHEN 4 THEN DATEADD(MINUTE,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME) 
		WHEN 8 THEN DATEADD(HOUR,FREQ_SUBDAY_INTERVAL,NEXTRUNTIME)  
	END AS DATE)=CAST(NEXTRUNTIME AS DATE) AND CAST( ACTIVE_END_TIME AS TIME)<=CAST(ACTIVE_START_TIME AS TIME)
) 


SELECT DISTINCT *,DATEADD(SECOND,LAST_RUN_DURATION,PROGRAMADO) FIM FROM (
	SELECT  CAST(X.IDJOB AS VARCHAR(500)) IDJOB,X.NOME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOME,X.CODSISTEMA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI SISTEMA,GH.DATAPROGRAMADA PROGRAMADO,
	AVG(CASE WHEN GH.DATAINIEXEC IS NULL THEN 1 ELSE DATEDIFF(SECOND,GH.DATAINIEXEC,GH.DATAFIMEXEC) END) LAST_RUN_DURATION,
	X.CODUSUARIO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI USUARIO,X.DATACRIACAO CRIACAO,X.RECMODIFIEDON ALTERACAO,0 MOD
	FROM CORPORE.DBO.GJOBX X 
	LEFT JOIN CORPORE.DBO.GJOBXEXECUCAO GX ON 
	GX.IDJOB=X.IDJOB
	INNER JOIN  CORPORE.DBO.GJOBXEXECUCAOHST GH ON 
	GH.IDJOB=X.IDJOB
	WHERE TIPORECORRENCIA IS NOT NULL
	GROUP BY X.IDJOB,X.NOME,X.CODSISTEMA,GH.DATAPROGRAMADA,X.CODUSUARIO,X.DATACRIACAO,X.RECMODIFIEDON
	UNION 
	SELECT DISTINCT IDJOB,NOME,SISTEMA,DATEADD(MINUTE,MINUTORECORRENCIA,DATEADD(HOUR,HORARECORRENCIA,PROGRAMADO)) PROGRAMADO,LAST_RUN_DURATION,USUARIO,CRIACAO,ALTERACAO,1  FROM CTEC 
	WHERE DATEADD(MINUTE,MINUTORECORRENCIA,DATEADD(HOUR,HORARECORRENCIA,PROGRAMADO))>=GETDATE()
	UNION ALL
	SELECT DISTINCT IDJOB,NOME,SISTEMA,DATEADD(DAY,ABS(DIASEMANA-DIASEMANA2),PROGRAMADO) PROGRAMADO,AVG(LAST_RUN_DURATION),USUARIO,CRIACAO,ALTERACAO,2
	FROM ( 
	SELECT X.NOME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOME,X.CODSISTEMA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI SISTEMA,
	CASE WHEN GH.DATAINIEXEC IS NULL THEN 1 ELSE DATEDIFF(SECOND,GH.DATAINIEXEC,GH.DATAFIMEXEC) END LAST_RUN_DURATION,
	X.CODUSUARIO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI USUARIO,X.DATACRIACAO CRIACAO,X.RECMODIFIEDON ALTERACAO,F.*,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA) PROGRAMADO,DATEPART(WEEKDAY,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA)) DIASEMANA
	FROM CORPORE.DBO.GJOBX X 
	LEFT JOIN CORPORE.DBO.GJOBXEXECUCAO GX ON 
	GX.IDJOB=X.IDJOB
	LEFT JOIN  CORPORE.DBO.GJOBXEXECUCAOHST GH ON 
	GH.IDJOB=X.IDJOB
	INNER JOIN (SELECT CAST(SS.IDJOB AS VARCHAR(500))IDJOB ,
			TIPORECORRENCIA, 
			'D1' = CASE WHEN (DIASDASEMANA & 1  <> 0) THEN 1 ELSE 0 END,
			'D2' = CASE WHEN (DIASDASEMANA & 2  <> 0) THEN 2  ELSE 0 END,
			'D3' = CASE WHEN (DIASDASEMANA & 4  <> 0) THEN 3  ELSE 0 END,
			'D4' = CASE WHEN (DIASDASEMANA & 8  <> 0) THEN 4  ELSE 0 END,
		'D5' = CASE WHEN (DIASDASEMANA & 16 <> 0) THEN 5  ELSE 0 END,
			'D6' = CASE WHEN (DIASDASEMANA & 32 <> 0) THEN 6  ELSE 0 END,
			'D7' = CASE WHEN (DIASDASEMANA & 64 <> 0) THEN 7  ELSE 0 END,
			'D8' = CASE WHEN (DIASDASEMANA & 1  <> 0) THEN 8 ELSE 0 END,
			'D9' = CASE WHEN (DIASDASEMANA & 2  <> 0) THEN 9  ELSE 0 END,
			'D10' = CASE WHEN (DIASDASEMANA & 4  <> 0) THEN 10  ELSE 0 END,
			'D11' = CASE WHEN (DIASDASEMANA & 8  <> 0) THEN 11  ELSE 0 END,
		'D12' = CASE WHEN (DIASDASEMANA & 16 <> 0) THEN 12  ELSE 0 END,
			'D13' = CASE WHEN (DIASDASEMANA & 32 <> 0) THEN 13  ELSE 0 END,
			'D14' = CASE WHEN (DIASDASEMANA & 64 <> 0) THEN 14  ELSE 0 END 
		FROM CORPORE.DBO.GJOBX SS
	WHERE TIPORECORRENCIA = 1 ) F
	ON F.IDJOB = X.IDJOB
	WHERE X.TIPORECORRENCIA =  1
	 ) AS C
	UNPIVOT
	(
		DIASEMANA2 FOR DATAPROGRAMADA IN (D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14)
	) AS CP
	WHERE DIASEMANA2!=0 AND PROGRAMADO>=GETDATE()
	GROUP BY IDJOB,NOME,SISTEMA,DATEADD(DAY,ABS(DIASEMANA-DIASEMANA2),PROGRAMADO),USUARIO,CRIACAO,ALTERACAO
	UNION ALL
	SELECT  CAST(X.IDJOB AS VARCHAR(500)) IDJOB,X.NOME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOME,X.CODSISTEMA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI SISTEMA,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA) PROGRAMADO,
	AVG(CASE WHEN GH.DATAINIEXEC IS NULL THEN 1 ELSE DATEDIFF(SECOND,GH.DATAINIEXEC,GH.DATAFIMEXEC) END) LAST_RUN_DURATION,
	X.CODUSUARIO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI USUARIO,X.DATACRIACAO CRIACAO,X.RECMODIFIEDON ALTERACAO,3
	FROM CORPORE.DBO.GJOBX X 
	LEFT JOIN CORPORE.DBO.GJOBXEXECUCAO GX ON 
	GX.IDJOB=X.IDJOB
	LEFT JOIN  CORPORE.DBO.GJOBXEXECUCAOHST GH ON 
	GH.IDJOB=X.IDJOB
	WHERE TIPORECORRENCIA = 2
	GROUP BY X.IDJOB,X.NOME,X.CODSISTEMA,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA),X.CODUSUARIO,X.DATACRIACAO,X.RECMODIFIEDON
	UNION
	SELECT  CAST(X.IDJOB AS VARCHAR(500)) IDJOB,X.NOME COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI NOME,X.CODSISTEMA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI SISTEMA,DATEADD(MONTH,1,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA)) PROGRAMADO,
	AVG(CASE WHEN GH.DATAINIEXEC IS NULL THEN 1 ELSE DATEDIFF(SECOND,GH.DATAINIEXEC,GH.DATAFIMEXEC) END) LAST_RUN_DURATION,
	X.CODUSUARIO COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI USUARIO,X.DATACRIACAO CRIACAO,X.RECMODIFIEDON ALTERACAO,4
	FROM CORPORE.DBO.GJOBX X 
	LEFT JOIN CORPORE.DBO.GJOBXEXECUCAO GX ON 
	GX.IDJOB=X.IDJOB
	LEFT JOIN  CORPORE.DBO.GJOBXEXECUCAOHST GH ON 
	GH.IDJOB=X.IDJOB
	WHERE TIPORECORRENCIA = 2
	GROUP BY X.IDJOB,X.NOME,X.CODSISTEMA,ISNULL(GX.DATAPROGRAMADA,GH.DATAPROGRAMADA),X.CODUSUARIO,X.DATACRIACAO,X.RECMODIFIEDON
	UNION ALL
	SELECT CAST(S.JOB_ID AS VARCHAR(500)) IDJOB,S.NAME AS JOBNAME,ST.DATABASE_NAME,
			CAST(CASE SJ.RUN_DATE
				WHEN 0 THEN CAST('N/A' AS CHAR(10))
				ELSE CONVERT(CHAR(10), CONVERT(DATETIME, CONVERT(CHAR(8),SJ.RUN_DATE)),120)  + ' ' + LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(SJ.RUN_TIME)))+ CONVERT(VARCHAR(6),SJ.RUN_TIME),3,0,':')),6,0,':'),8)
			END AS DATETIME) NEXTRUNTIME,  
			AVG(CASE WHEN SJ.RUN_DURATION=0 THEN CAST(CAST(1 AS DATETIME) AS INT) ELSE DATEDIFF(SECOND,'1900-01-01 00:00:00.000',CAST(STUFF(STUFF(RIGHT('00000' + CAST(SJ.RUN_DURATION AS VARCHAR),6),3,0,':'),6,0,':') AS DATETIME) ) END ) LAST_RUN_DURATION,
			L.NAME CREATOR,S.DATE_CREATED,S.DATE_MODIFIED,6
	FROM MSDB.DBO.SYSJOBS S
	LEFT JOIN MSDB.DBO.SYSJOBSCHEDULES SJ2 ON S.JOB_ID = SJ2.JOB_ID  
	LEFT JOIN MSDB.DBO.SYSSCHEDULES SS ON SS.SCHEDULE_ID = SJ2.SCHEDULE_ID
	LEFT JOIN MSDB.DBO.SYSJOBHISTORY SJ ON S.JOB_ID = SJ.JOB_ID 
	LEFT JOIN MSDB.DBO.SYSJOBSTEPS ST ON ST.JOB_ID=S.JOB_ID AND SJ.STEP_ID=ST.STEP_ID
	LEFT JOIN MASTER.SYS.SYSLOGINS L ON S.OWNER_SID = L.SID
	WHERE S.ENABLED=1 AND SS.ENABLED=1 AND ( SS.FREQ_TYPE!=4 OR ( SS.FREQ_TYPE=4 AND SS.FREQ_SUBDAY_TYPE NOT IN(2,4) ) )  AND FREQ_TYPE!=1 AND SJ.STEP_ID!=0
	GROUP BY S.JOB_ID,S.NAME,SJ.RUN_DATE,ST.DATABASE_NAME,SJ.RUN_TIME,L.NAME,S.DATE_CREATED,S.DATE_MODIFIED
	UNION ALL 
	SELECT DISTINCT CAST(JOB_ID AS VARCHAR(500)) IDJOB,JOBNAME,DATABASE_NAME,DATEADD(DAY,ABS(DATEPART(WEEKDAY,NEXTRUNTIME)-DIASEMANA2),NEXTRUNTIME) PROGRAMADO,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,8 FROM ( 
	SELECT 
		   S.JOB_ID,S.NAME AS JOBNAME,ST.DATABASE_NAME,   
			CAST(CASE SJ.NEXT_RUN_DATE
				WHEN 0 THEN CAST('N/A' AS CHAR(10))
				ELSE CONVERT(CHAR(10), CONVERT(DATETIME, CONVERT(CHAR(8),SJ.NEXT_RUN_DATE)),120)  + ' ' + LEFT(STUFF((STUFF((REPLICATE('0', 6 - LEN(NEXT_RUN_TIME)))+ CONVERT(VARCHAR(6),NEXT_RUN_TIME),3,0,':')),6,0,':'),8)
			END AS DATETIME) NEXTRUNTIME, 
			SUM(CASE WHEN ST.LAST_RUN_DURATION=0 THEN CAST(CAST(1 AS DATETIME) AS INT) ELSE DATEDIFF(SECOND,'1900-01-01 00:00:00.000',CAST(STUFF(STUFF(RIGHT('00000' + CAST(LAST_RUN_DURATION AS VARCHAR),6),3,0,':'),6,0,':') AS DATETIME) ) END) LAST_RUN_DURATION,
			L.NAME CREATOR,S.DATE_CREATED,S.DATE_MODIFIED,FREQ_TYPE,SS.FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14
	FROM MSDB.DBO.SYSJOBS S
	LEFT JOIN MSDB.DBO.SYSJOBSCHEDULES SJ ON S.JOB_ID = SJ.JOB_ID  
	LEFT JOIN MSDB.DBO.SYSSCHEDULES SS ON SS.SCHEDULE_ID = SJ.SCHEDULE_ID
	LEFT JOIN MSDB.DBO.SYSJOBSTEPS ST ON ST.JOB_ID=S.JOB_ID
	LEFT JOIN MASTER.SYS.SYSLOGINS L ON S.OWNER_SID = L.SID
	INNER JOIN (SELECT SS.SCHEDULE_ID,
			'D1' = CASE WHEN (FREQ_INTERVAL & 1  <> 0) THEN 1 ELSE 0 END,
			'D2' = CASE WHEN (FREQ_INTERVAL & 2  <> 0) THEN 2  ELSE 0 END,
			'D3' = CASE WHEN (FREQ_INTERVAL & 4  <> 0) THEN 4  ELSE 0 END,
			'D4' = CASE WHEN (FREQ_INTERVAL & 8  <> 0) THEN 5  ELSE 0 END,
			'D5' = CASE WHEN (FREQ_INTERVAL & 16 <> 0) THEN 5  ELSE 0 END,
			'D6' = CASE WHEN (FREQ_INTERVAL & 32 <> 0) THEN 6  ELSE 0 END,
			'D7' = CASE WHEN (FREQ_INTERVAL & 64 <> 0) THEN 7  ELSE 0 END,
			'D8' = CASE WHEN (FREQ_INTERVAL & 1  <> 0) THEN 8 ELSE 0 END,
			'D9' = CASE WHEN (FREQ_INTERVAL & 2  <> 0) THEN 9  ELSE 0 END,
			'D10' = CASE WHEN (FREQ_INTERVAL & 4  <> 0) THEN 10  ELSE 0 END,
			'D11' = CASE WHEN (FREQ_INTERVAL & 8  <> 0) THEN 11  ELSE 0 END,
			'D12' = CASE WHEN (FREQ_INTERVAL & 16 <> 0) THEN 12  ELSE 0 END,
			'D13' = CASE WHEN (FREQ_INTERVAL & 32 <> 0) THEN 13  ELSE 0 END,
			'D14' = CASE WHEN (FREQ_INTERVAL & 64 <> 0) THEN 14  ELSE 0 END 
        FROM MSDB..SYSSCHEDULES SS
	WHERE FREQ_TYPE = 8 ) F
	ON F.SCHEDULE_ID = SJ.SCHEDULE_ID
	WHERE  S.ENABLED=1 AND SS.ENABLED=1 AND ( SS.FREQ_TYPE!=4 OR ( SS.FREQ_TYPE=4 AND SS.FREQ_SUBDAY_TYPE NOT IN(2,4) ) )  AND FREQ_TYPE>4  AND FREQ_SUBDAY_TYPE=1
	GROUP BY S.JOB_ID,S.NAME,SJ.NEXT_RUN_DATE,ST.DATABASE_NAME,SS.NAME,SS.FREQ_TYPE,SS.FREQ_RECURRENCE_FACTOR,SS.SCHEDULE_ID,SS.FREQ_INTERVAL,
	SJ.SCHEDULE_ID,SS.FREQ_SUBDAY_INTERVAL,SS.FREQ_SUBDAY_TYPE,SS.ACTIVE_START_TIME,SJ.NEXT_RUN_TIME,L.NAME,S.DATE_CREATED,S.DATE_MODIFIED,
	FREQ_TYPE,SS.FREQ_INTERVAL,FREQ_SUBDAY_TYPE,FREQ_SUBDAY_INTERVAL,FREQ_RELATIVE_INTERVAL,FREQ_RECURRENCE_FACTOR,F.SCHEDULE_ID,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14
	) C
	UNPIVOT
	(
		DIASEMANA2 FOR DATAPROGRAMADA IN (D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14)
	) AS CP
	WHERE DIASEMANA2!=0 AND NEXTRUNTIME>=GETDATE()
	UNION ALL
	SELECT DISTINCT CAST(IDJOB AS VARCHAR(500)) IDJOB,JOBNAME,DATABASE_NAME,PROGRAMADO,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,9 FROM CTED2 WHERE PROGRAMADO>=GETDATE()
	UNION ALL
	SELECT DISTINCT CAST(IDJOB AS VARCHAR(500)) IDJOB,JOBNAME,DATABASE_NAME,NEXTRUNTIME,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,10 FROM CTED3 WHERE NEXTRUNTIME>=GETDATE()
	UNION ALL
	SELECT DISTINCT CAST(IDJOB AS VARCHAR(500)) IDJOB,JOBNAME,DATABASE_NAME,NEXTRUNTIME,LAST_RUN_DURATION,CREATOR,DATE_CREATED,DATE_MODIFIED,11 FROM CTE0 WHERE NEXTRUNTIME>=GETDATE()
	AND ( CAST( ACTIVE_END_TIME AS TIME)<=CAST(ACTIVE_START_TIME AS TIME)
		OR ( ( CAST(NEXTRUNTIME AS TIME)<=CONVERT(TIME,ACTIVE_END_TIME) ) AND 	( CAST(NEXTRUNTIME AS TIME)>=CONVERT(TIME,ACTIVE_START_TIME) ) ) )
) R
