
;WITH CTE AS (SELECT ROW_NUMBER()OVER(ORDER BY CODCOLIGADA ) ID,* FROM (
SELECT DISTINCT TI.CODCOLIGADA,T.CODTMV,TI.IDMOV,TI.IDPRD,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT GRUPO,TI.QUANTIDADE,TI.RECCREATEDON,
CONCAT(DATEPART(YEAR,TI.RECCREATEDON),'/',DATEPART(MONTH,TI.RECCREATEDON)) PERIODO FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN TMOVRELAC TR ON
TR.CODCOLDESTINO=T.CODCOLIGADA
AND TR.IDMOVDESTINO=T.IDMOV
INNER JOIN TMOV T2 ON 
T2.CODCOLIGADA=TR.CODCOLORIGEM
AND T2.IDMOV=TR.IDMOVORIGEM
WHERE T.CODTMV='3.1.02' AND T.CODLOCDESTINO='23'
UNION
SELECT DISTINCT TI.CODCOLIGADA,T.CODTMV,TI.IDMOV,TI.IDPRD,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT GRUPO,-1*TI.QUANTIDADE QUANTIDADE,TI.RECCREATEDON,
CONCAT(DATEPART(YEAR,TI.RECCREATEDON),'/',DATEPART(MONTH,TI.RECCREATEDON)) PERIODO FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
WHERE ( CODTMV='2.2.18' OR CODTMV='2.1.46' ) AND CODLOCDESTINO='23'
) R 
), CT2 AS (
	
	SELECT * FROM CTE
	
)
--SELECT * FROM CTE
--ORDER BY IDPRD,CAST(SUBSTRING(PERIODO,0,CHARINDEX('/',PERIODO))   AS INT) ASC,CAST(SUBSTRING(PERIODO,CHARINDEX('/',PERIODO)+1,LEN(PERIODO))  AS INT)


SELECT CODCOLIGADA,IDPRD,NOMEFANTASIA,GRUPO,EXTRATO,CASE WHEN PERIODO=CONCAT(DATEPART(YEAR,DATEADD(YEAR,1,GETDATE())),'/',DATEPART(MONTH,DATEADD(YEAR,1,GETDATE()))) THEN 'TOTAL' ELSE PERIODO END AS PERIODO FROM (
SELECT CODCOLIGADA,IDPRD,NOMEFANTASIA,GRUPO,SUM(QUANTIDADE) EXTRATO,PERIODO 
FROM CTE 
GROUP BY CODCOLIGADA,IDPRD,NOMEFANTASIA,GRUPO,PERIODO 
UNION ALL
SELECT CODCOLIGADA,IDPRD,NOMEFANTASIA,GRUPO,SUM(QUANTIDADE) EXTRATO,CONCAT(DATEPART(YEAR,DATEADD(YEAR,1,GETDATE())),'/',DATEPART(MONTH,DATEADD(YEAR,1,GETDATE())))
FROM CT2
GROUP BY CODCOLIGADA,IDPRD,NOMEFANTASIA,GRUPO ) R
ORDER BY IDPRD,CAST(SUBSTRING(PERIODO,0,CHARINDEX('/',PERIODO))   AS INT) ASC,CAST(SUBSTRING(PERIODO,CHARINDEX('/',PERIODO)+1,LEN(PERIODO))  AS INT)
