SELECT 	T.CODCOLIGADA , T.CODFILIAL, G.CODCCUSTO+' - '+G.NOME OS, T.NUMEROMOV, I.NSEQITMMOV, 
		T.CAMPOLIVRE1 OP, CL.DESCCELULA CELULA, P.CODIGOPRD+' - '+P.DESCRICAO PRODUTO, NUMPLANOCORTE PLANO_DE_CORTE, 
		T.CODLOC LOCAL_ESTOQUE,  
		CASE WHEN Z.NUMLOTE IS NOT NULL THEN TT.LOCALIZACAO_LOTE ELSE P.CAMPOLIVRE3  END AS LOCALIZADOR,  
		I.QUANTIDADE, I.CODUND,CASE WHEN GED.ID_Arquivo IS NULL THEN '' ELSE CONCAT('http://delp5008/Arquivo/VisualizarPDF?idArquivo=',GED.ID_Arquivo,'&view=true') END AS GEDLINK
FROM TMOV T
	INNER JOIN TITMMOV I ON T.CODCOLIGADA = I.CODCOLIGADA AND T.IDMOV = I.IDMOV
	INNER JOIN TPRD P ON I.CODCOLIGADA = P.CODCOLIGADA AND I.IDPRD = P.IDPRD
	INNER JOIN TLOTEPRD TL ON P.IDPRD = TL.IDPRD AND P.CODCOLIGADA = TL.CODCOLIGADA /*Trecho inserido para  modificação do ticket 11345*/
	INNER JOIN TLOTEPRDCOMPL TT ON TT.CODCOLIGADA = TL.CODCOLIGADA AND TT.IDLOTE = TL.IDLOTE /*Trecho inserido para  modificação do ticket 11345*/
	INNER JOIN GCCUSTO G ON G.CODCOLIGADA = T.CODCOLIGADA AND G.CODCCUSTO = T.CODCCUSTO
	LEFT JOIN MPRJ M ON T.CODCOLIGADA = M.CODCOLIGADA AND M.CODPRJ = T.CODCCUSTO AND M.POSICAO IN (1,4)
	LEFT JOIN FLUIG.DBO.Z_CRM_EX001005COMPL CL ON CL.CODCOLIGADA = M.CODCOLIGADA AND CL.OS = M.CODPRJ COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI  AND CL.CODORDEM = T.CAMPOLIVRE1 COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI 
	LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE Z ON Z.CODCOLIGADA = T.CODCOLIGADA AND Z.CODORDEM = T.CAMPOLIVRE1 AND Z.IDATVORDEM = T.CAMPOLIVRE2 AND Z.NUMPLANOCORTE = T.CAMPOLIVRE3
	LEFT JOIN GreenDocs.dbo.Arquivos GED ON 
    GED.NOME LIKE CONCAT('%',Z.NUMPLANOCORTE,'%') COLLATE SQL_Latin1_General_CP1_CI_AI AND Z.NUMPLANOCORTE IS NOT NULL  
    AND GED.ID_Arquivo = (SELECT MAX(ID_Arquivo) FROM GreenDocs.dbo.Arquivos WHERE NOME LIKE CONCAT('%',Z.NUMPLANOCORTE,'%') COLLATE SQL_Latin1_General_CP1_CI_AI AND Z.NUMPLANOCORTE IS NOT NULL) 
WHERE	T.CODTMV = '1.1.05'
AND		T.STATUS IN ('A','G')
AND		T.CODCOLIGADA = :COLIGADA
AND		T.IDMOV = :IDMOV
ORDER BY G.CODCCUSTO, T.NUMEROMOV, I.NSEQITMMOV