
		SELECT R2.IDPRODUTO,R2.PREVISTO,R2.APONTADO
		,R2.GRUPO,R2.MASKPRD,R2.CODIGOPRD,L.NUMLOTE,LC.SALDOFISICO2,L.IDSTATUS,LS.DESCRICAO
		,CASE WHEN PREVISTO = 0 THEN 'SUBSTITUTO' ELSE 'PRINCIPAL' END AS POSICAO,
		CASE WHEN PREVISTO = 0 THEN (SELECT IDPRDORIGEM FROM KCOMPSUBSTITUTO WHERE IDPRD=IDPRODUTO AND CODESTRUTURA=R2.CODESTRUTURA AND CODATIVIDADE=R2.CODATIVIDADE) ELSE R2.IDPRODUTO END AS SUBSTITUTO
		 FROM (
			SELECT EXECUCAO,CODCOLIGADA,CODFILIAL,CODESTRUTURA,CODORDEM,IDATVORDEM,CODATIVIDADE,SALDOPAPC,PAPC,IDPRODUTO,SUM(PREVISTO) PREVISTO,SUM(APONTADO) APONTADO,CODTB2FAT GRUPO,MASKPRD,CODIGOPRD FROM (
				SELECT KL.NUMEXEC EXECUCAO,KA.CODCOLIGADA,KA.CODFILIAL,KA.CODESTRUTURA,K.CODORDEM,KA.IDATVORDEM,KA.CODATIVIDADE,CASE WHEN PAPC.NUMPLANOCORTE IS NULL 
					THEN 0 
					ELSE 
						CASE WHEN PAPC.QTDEAPONTADA IS NULL 
							THEN  CASE WHEN PAPC.QUANTIDADE-KA.QUANTIDADE < 0  
										THEN 0
										ELSE PAPC.QUANTIDADE-KA.QUANTIDADE
										END
							ELSE PAPC.QUANTIDADE-PAPC.QTDEAPONTADA
							END			
					END AS SALDOPAPC,
				CASE WHEN PAPC.NUMPLANOCORTE IS NULL THEN '0' ELSE PAPC.NUMPLANOCORTE END AS PAPC,
				KMA.IDPRODUTO,
				CASE WHEN KMA.EFETIVADO=0 THEN KMA.QUANTIDADE ELSE 0 END AS PREVISTO,
				CASE WHEN KMA.EFETIVADO=1 THEN KMA.QUANTIDADE ELSE 0 END AS APONTADO,
				(SELECT CODTB2FAT FROM TPRODUTODEF WHERE CODCOLIGADA=KA.CODCOLIGADA AND IDPRD=KMA.IDPRODUTO) CODTB2FAT,
				LEFT(P.CODIGOPRD,6) MASKPRD,P.CODIGOPRD
				FROM KORDEM (NOLOCK) K 
					INNER JOIN KATVORDEM (NOLOCK) KA ON
					KA.CODCOLIGADA=K.CODCOLIGADA
					AND KA.CODFILIAL=K.CODFILIAL
					AND KA.CODORDEM=K.CODORDEM
					INNER JOIN KORDEMCOMPL (NOLOCK) KL ON
					KL.CODCOLIGADA=KA.CODCOLIGADA
					AND KL.CODFILIAL=KA.CODFILIAL
					AND KL.CODORDEM=KA.CODORDEM
					INNER JOIN KATVORDEMMP (NOLOCK) KMA ON
					KMA.CODCOLIGADA=KA.CODCOLIGADA
					AND KMA.CODFILIAL=KA.CODFILIAL
					AND KMA.CODORDEM=KA.CODORDEM
					AND KMA.IDATIVIDADE=KA.IDATVORDEM
					INNER JOIN TPRD (NOLOCK) P ON         
					KMA.CODCOLIGADA = P.CODCOLIGADA 
					AND KMA.IDPRODUTO = P.IDPRD
					LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE (NOLOCK) PAPC ON
					PAPC.CODCOLIGADA=KA.CODCOLIGADA
					AND PAPC.CODFILIAL=KA.CODFILIAL
					AND PAPC.CODORDEM=KA.CODORDEM
					AND PAPC.CODATIVIDADE=KA.CODATIVIDADE
				WHERE K.CODCCUSTO='3.07840.32.001' 
				AND KL.NUMEXEC=1
				AND K.STATUS NOT IN (5,6) AND KA.STATUS NOT IN (5,6) AND K.CODORDEM='31345/22' AND KA.IDATVORDEM=3 AND PAPC.NSEQPLANOCORTE IS NULL
					AND ( P.IDPRD=123830 OR P.IDPRD = (	SELECT IDPRDORIGEM FROM KCOMPSUBSTITUTO KC 
										INNER JOIN KESTRUTURA KE ON KC.CODESTRUTURA=KE.CODESTRUTURA AND KC.CODCOLIGADA=KE.CODCOLIGADA AND KC.CODFILIAL=KE.CODFILIAL 
										WHERE KE.CODESTRUTURA=KA.CODESTRUTURA AND KC.IDPRD=123830 AND KE.CODCCUSTO=K.CODCCUSTO AND KC.CODCOLIGADA=K.CODCOLIGADA 
										AND KC.CODFILIAL=K.CODFILIAL AND KC.CODATIVIDADE=KA.CODATIVIDADE	))
				) R 
				WHERE (CODTB2FAT = 0184 OR MASKPRD NOT IN ('01.053','01.019','01.020'))
				GROUP BY EXECUCAO,CODCOLIGADA,CODFILIAL,CODORDEM,IDATVORDEM,SALDOPAPC,PAPC,IDPRODUTO,CODTB2FAT,MASKPRD,CODATIVIDADE,CODESTRUTURA,CODIGOPRD
			) R2
			INNER JOIN TLOTEPRD L ON
			L.CODCOLIGADA=R2.CODCOLIGADA
			AND L.IDPRD=R2.IDPRODUTO
			INNER JOIN TSTATUSLOTEPRD LS ON
			LS.IDSTATUS=L.IDSTATUS
			INNER JOIN TLOTEPRDLOC LC ON
			LC.CODCOLIGADA=L.CODCOLIGADA
			AND LC.IDLOTE=L.IDLOTE  
			WHERE LC.CODLOC IN (23,25)
			ORDER BY CODORDEM,IDATVORDEM

