;WITH CTE AS (SELECT R.*,T2.IDMOV BAIXA,T2.CODTMV COD_BAIXA,T2.HORARIOEMISSAO HORA_BAIXA
 FROM ( SELECT DISTINCT TI.CODCOLIGADA,T.CODTMV COD_REQ,TI.IDMOV IDMOV_REQ,TI.NSEQITMMOV,TI.IDPRD,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT GRUPO,TI.QUANTIDADE,T.HORARIOEMISSAO,
CONCAT(DATEPART(YEAR,T.HORARIOEMISSAO),'-',FORMAT(DATEPART(MONTH,T.HORARIOEMISSAO),'00'),'-',FORMAT(DATEPART(DAY,T.HORARIOEMISSAO),'00'),' ',FORMAT(DATEPART(HOUR,T.HORARIOEMISSAO),'00'),':',FORMAT(DATEPART(MINUTE,T.HORARIOEMISSAO),'00')) HORA_TRANSFERENCIA 
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
WHERE T.CODTMV='3.1.02' AND T.CODLOCDESTINO='23' AND T.HORARIOEMISSAO > CAST('2022-12-01' AS DATE)  ) R
INNER JOIN TMOV T2 ON 
T2.CODCOLIGADA=R.CODCOLIGADA
AND R.HORA_TRANSFERENCIA IN (
--CONCAT(DATEPART(YEAR,T2.HORARIOEMISSAO),'-',FORMAT(DATEPART(MONTH,T2.HORARIOEMISSAO),'00'),'-',FORMAT(DATEPART(DAY,T2.HORARIOEMISSAO),'00'),' ',FORMAT(DATEPART(HOUR,T2.HORARIOEMISSAO),'00'),':',FORMAT(DATEPART(MINUTE,T2.HORARIOEMISSAO)-1,'00')),
CONCAT(DATEPART(YEAR,T2.HORARIOEMISSAO),'-',FORMAT(DATEPART(MONTH,T2.HORARIOEMISSAO),'00'),'-',FORMAT(DATEPART(DAY,T2.HORARIOEMISSAO),'00'),' ',FORMAT(DATEPART(HOUR,T2.HORARIOEMISSAO),'00'),':',FORMAT(DATEPART(MINUTE,T2.HORARIOEMISSAO),'00')),
CONCAT(DATEPART(YEAR,T2.HORARIOEMISSAO),'-',FORMAT(DATEPART(MONTH,T2.HORARIOEMISSAO),'00'),'-',FORMAT(DATEPART(DAY,T2.HORARIOEMISSAO),'00'),' ',FORMAT(DATEPART(HOUR,T2.HORARIOEMISSAO),'00'),':',FORMAT(DATEPART(MINUTE,T2.HORARIOEMISSAO)+1,'00')),
CONCAT(DATEPART(YEAR,T2.HORARIOEMISSAO),'-',FORMAT(DATEPART(MONTH,T2.HORARIOEMISSAO),'00'),'-',FORMAT(DATEPART(DAY,T2.HORARIOEMISSAO),'00'),' ',FORMAT(DATEPART(HOUR,T2.HORARIOEMISSAO),'00'),':',FORMAT(DATEPART(MINUTE,T2.HORARIOEMISSAO)+2,'00'))
)
AND T2.CODTMV='2.2.18'
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T2.CODCOLIGADA 
AND TI.IDMOV=T2.IDMOV
AND TI.NSEQITMMOV=R.NSEQITMMOV
AND TI.IDPRD=R.IDPRD
AND TI.QUANTIDADE=R.QUANTIDADE

)

SELECT T.CODCOLIGADA,T.IDMOV,T2.CAMPOLIVRE1 OP,T2.CAMPOLIVRE2 IDATV,T.HORARIOEMISSAO,T.CODTMV,TI.NSEQITMMOV,TP.IDPRD,TIL.IDLOTE,TLP.NUMLOTE
,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT,TI.QUANTIDADE,TL.SALDOFISICO2 SALDO23 FROM TMOV T 
LEFT JOIN CTE C ON
C.IDMOV_REQ=T.IDMOV 
AND C.CODCOLIGADA=T.CODCOLIGADA 
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN TITMLOTEPRD TIL ON 
TIL.CODCOLIGADA=TI.CODCOLIGADA
AND TIL.IDMOV=TI.IDMOV
AND TIL.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TLOTEPRD TLP ON 
TLP.CODCOLIGADA=TIL.CODCOLIGADA
AND TLP.IDLOTE=TIL.IDLOTE
LEFT JOIN TPRDLOC TL ON
TL.CODCOLIGADA=TP.CODCOLIGADA 
AND TL.IDPRD=TP.IDPRD
AND TL.CODLOC='23'
INNER JOIN TMOVRELAC TR ON
TR.CODCOLDESTINO=T.CODCOLIGADA
AND TR.IDMOVDESTINO=T.IDMOV
INNER JOIN TMOV T2 ON 
T2.CODCOLIGADA=TR.CODCOLORIGEM
AND T2.IDMOV=TR.IDMOVORIGEM
WHERE T.CODTMV= '3.1.02' AND C.IDMOV_REQ IS NULL  AND ( ( T.HORARIOEMISSAO > CAST('2022-12-01' AS DATE)  AND TP.CODTB2FAT = '0185') OR ( T.HORARIOEMISSAO > CAST('2023-05-08' AS DATE)  AND TP.CODTB2FAT = '0184'))
ORDER BY IDMOV,NSEQITMMOV ASC

--SELECT * FROM TTB2



-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



;WITH CTE AS (SELECT R.*,T2.IDMOV BAIXA,T2.CODTMV COD_BAIXA,T2.HORARIOEMISSAO HORA_BAIXA
 FROM ( SELECT DISTINCT TI.CODCOLIGADA,T.CODTMV COD_REQ,TI.IDMOV IDMOV_REQ,TI.NSEQITMMOV,TI.IDPRD,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT GRUPO,TI.QUANTIDADE,T.HORARIOEMISSAO
 --,CONCAT(DATEPART(YEAR,T.HORARIOEMISSAO),'-',FORMAT(DATEPART(MONTH,T.HORARIOEMISSAO),'00'),'-',FORMAT(DATEPART(DAY,T.HORARIOEMISSAO),'00'),' ',FORMAT(DATEPART(HOUR,T.HORARIOEMISSAO),'00'),':',FORMAT(DATEPART(MINUTE,T.HORARIOEMISSAO),'00')) HORA_TRANSFERENCIA 
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
WHERE T.CODTMV='3.1.02' AND T.CODLOCDESTINO='23' AND T.HORARIOEMISSAO > CAST('2022-12-01' AS DATE)  ) R
INNER JOIN TMOV T2 ON 
T2.CODCOLIGADA=R.CODCOLIGADA
AND T2.HORARIOEMISSAO BETWEEN R.HORARIOEMISSAO AND DATEADD(MINUTE,2,R.HORARIOEMISSAO)
AND T2.CODTMV='2.2.18'
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T2.CODCOLIGADA 
AND TI.IDMOV=T2.IDMOV
AND TI.NSEQITMMOV=R.NSEQITMMOV
AND TI.IDPRD=R.IDPRD
AND TI.QUANTIDADE=R.QUANTIDADE

)

SELECT T.CODCOLIGADA,T.IDMOV,T2.CAMPOLIVRE1 OP,T2.CAMPOLIVRE2 IDATV,T.HORARIOEMISSAO,T.CODTMV,TI.NSEQITMMOV,TP.IDPRD,TIL.IDLOTE,TLP.NUMLOTE
,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT,TI.QUANTIDADE,TL.SALDOFISICO2 SALDO23 FROM TMOV T 
LEFT JOIN CTE C ON
C.IDMOV_REQ=T.IDMOV 
AND C.CODCOLIGADA=T.CODCOLIGADA 
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN TITMLOTEPRD TIL ON 
TIL.CODCOLIGADA=TI.CODCOLIGADA
AND TIL.IDMOV=TI.IDMOV
AND TIL.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TLOTEPRD TLP ON 
TLP.CODCOLIGADA=TIL.CODCOLIGADA
AND TLP.IDLOTE=TIL.IDLOTE
LEFT JOIN TPRDLOC TL ON
TL.CODCOLIGADA=TP.CODCOLIGADA 
AND TL.IDPRD=TP.IDPRD
AND TL.CODLOC='23'
INNER JOIN TMOVRELAC TR ON
TR.CODCOLDESTINO=T.CODCOLIGADA
AND TR.IDMOVDESTINO=T.IDMOV
INNER JOIN TMOV T2 ON 
T2.CODCOLIGADA=TR.CODCOLORIGEM
AND T2.IDMOV=TR.IDMOVORIGEM
WHERE T.CODTMV= '3.1.02' AND C.IDMOV_REQ IS NULL  AND ( ( T.HORARIOEMISSAO > CAST('2022-12-01' AS DATE)  AND TP.CODTB2FAT = '0185') OR ( T.HORARIOEMISSAO > CAST('2023-05-08' AS DATE)  AND TP.CODTB2FAT = '0184') )
UNION ALL
SELECT T.CODCOLIGADA,T2.IDMOV,Z.NUMPLANOCORTE OP,NULL IDATV,T.HORARIOEMISSAO,T.CODTMV,TI.NSEQITMMOV,TP.IDPRD,Z.IDLOTE,TLP.NUMLOTE
,TP.CODIGOPRD,TP.NOMEFANTASIA,TP.CODTB2FAT,TI2.QUANTIDADE,TL.SALDOFISICO2 SALDO23 FROM ZMDPLANOAPROVEITAMENTOCORTE Z
INNER JOIN TMOV T ON
T.CODCOLIGADA=Z.CODCOLIGADA
AND T.IDMOV=Z.IDMOVREQ
AND T.CAMPOLIVRE1=Z.CODORDEM
AND T.CAMPOLIVRE2=Z.IDATVORDEM
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=T.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN TLOTEPRD TLP ON 
TLP.CODCOLIGADA=Z.CODCOLIGADA
AND TLP.IDLOTE=Z.IDLOTE
LEFT JOIN TPRDLOC TL ON
TL.CODCOLIGADA=TP.CODCOLIGADA 
AND TL.IDPRD=TP.IDPRD
AND TL.CODLOC='23'
INNER JOIN TMOVRELAC TR ON
TR.CODCOLDESTINO=T.CODCOLIGADA
AND TR.IDMOVORIGEM=T.IDMOV
INNER JOIN TMOV T2 ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=TR.IDMOVDESTINO
INNER JOIN TITMMOV TI2 ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.IDMOV=T2.IDMOV
WHERE T.STATUS='F' AND ISNULL(Z.QTDEAPONTADA,0) = 0
ORDER BY IDMOV,NSEQITMMOV ASC

------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT T.IDPRD,T.CODIGOPRD,T.NOMEFANTASIA,TLL.IDLOTE,TR.IDMOVORIGEM
FROM TPRD T 
INNER JOIN TPRDLOC TL ON
TL.CODCOLIGADA=T.CODCOLIGADA
AND TL.IDPRD=T.IDPRD 

INNER JOIN TLOTEPRDLOC TLL ON
TL.CODCOLIGADA=TLL.CODCOLIGADA
AND TL.IDPRD=TLL.IDPRD
AND TL.CODLOC=TLL.CODLOC

INNER JOIN TMOV TM ON 
TM.CODCOLIGADA=T.CODCOLIGADA
AND TM.CODLOCDESTINO=23
AND TM.CODTMV='3.1.02'

INNER JOIN TITMMOV TIM ON
TIM.IDMOV=TM.IDMOV
AND TIM.CODCOLIGADA=TM.CODCOLIGADA
AND TIM.IDPRD=T.IDPRD

INNER JOIN TITMLOTEPRD TIML ON
TIML.CODCOLIGADA=TIM.CODCOLIGADA
AND TIML.IDMOV=TIM.IDMOV
AND TIML.NSEQITMMOV=TIM.NSEQITMMOV
AND TIML.IDLOTE=TLL.IDLOTE

INNER JOIN TMOVRELAC TR ON
TR.CODCOLDESTINO=TM.CODCOLIGADA
AND TR.IDMOVDESTINO=TM.IDMOV

INNER JOIN TITMMOVRELAC TRI ON
TRI.CODCOLDESTINO=TM.CODCOLIGADA
AND TRI.IDMOVDESTINO=TM.IDMOV
AND TRI.NSEQITMMOVDESTINO=TIM.NSEQITMMOV


WHERE T.CODTB2FAT IN ('0181','0184','0185') 
AND TL.SALDOFISICO2 > 0 AND TLL.CODLOC=23 and T.IDPRD=61083

ORDER BY IDPRD,IDLOTE


---------------------------------------------------------------------------------------------------------------------------------------------------------------



SELECT DISTINCT R.*,TL.NUMLOTE,T2.NUMEROMOV REQUISICAO,CONVERT(VARCHAR(20),T2.HORARIOEMISSAO,113) DATA,TP.CODIGOPRD,TP.NOMEFANTASIA,TI2.QUANTIDADEORIGINAL,
T2.CAMPOLIVRE1 CODORDEM,T2.CAMPOLIVRE2 IDATV,ISNULL(T2.CAMPOLIVRE3,'SEM PLANO') NUMPLANO FROM (
SELECT T.CODCOLIGADA,T.IDPRD,T.CODIGOPRD,T.NOMEFANTASIA,TLL.IDLOTE,TLL.SALDOFISICO2
FROM TPRD T 
INNER JOIN TPRDLOC TL ON
TL.CODCOLIGADA=T.CODCOLIGADA
AND TL.IDPRD=T.IDPRD 
INNER JOIN TLOTEPRDLOC TLL ON
TL.CODCOLIGADA=TLL.CODCOLIGADA
AND TL.IDPRD=TLL.IDPRD
AND TL.CODLOC=TLL.CODLOC
WHERE T.CODTB2FAT IN ('0181','0184','0185') 
AND TL.SALDOFISICO2 > 0 AND TLL.CODLOC=23 ) R
INNER JOIN TMOV TM ON 
TM.CODCOLIGADA=R.CODCOLIGADA
AND TM.CODLOCDESTINO=23
AND TM.CODTMV='3.1.02'
INNER JOIN TITMMOV TIM ON
TIM.IDMOV=TM.IDMOV
AND TIM.CODCOLIGADA=TM.CODCOLIGADA
AND TIM.IDPRD=R.IDPRD
INNER JOIN TITMLOTEPRD TIML ON
TIML.CODCOLIGADA=TIM.CODCOLIGADA
AND TIML.IDMOV=TIM.IDMOV
AND TIML.NSEQITMMOV=TIM.NSEQITMMOV
AND TIML.IDLOTE=R.IDLOTE
INNER JOIN TMOVRELAC TR ON
TR.CODCOLDESTINO=TM.CODCOLIGADA
AND TR.IDMOVDESTINO=TM.IDMOV
INNER JOIN TMOV T2 ON 
TM.CODCOLIGADA=R.CODCOLIGADA
AND T2.IDMOV=TR.IDMOVORIGEM
INNER JOIN TITMMOV TI2 ON 
TI2.CODCOLIGADA=R.CODCOLIGADA
AND TI2.IDMOV=T2.IDMOV
INNER JOIN TLOTEPRD TL ON 
TL.CODCOLIGADA=R.CODCOLIGADA
AND TL.IDLOTE=R.IDLOTE
INNER JOIN TPRD TP ON 
TP.CODCOLIGADA=R.CODCOLIGADA
AND TP.IDPRD=TI2.IDPRD
ORDER BY NUMPLANO,R.IDPRD,IDLOTE,T2.NUMEROMOV