 DECLARE @INICIO VARCHAR(20)
 SET @INICIO = '0001-01-01'

  DECLARE @FIM VARCHAR(20)
 SET @FIM = '2023-05-11'
 
 SELECT *,(APONTAMENTO_PAPC+APONTAMENTO+APONTAMENTO_SEM_PROG) TOTAL_SOLICITACOES, (OPS_PAPC+TOTAL_NUM_OPS+TOTAL_NUM_OPS_SEM_PROG) TOTAL_OPS FROM (
 SELECT CAST(CONCAT(SUBSTRING(PERIODO,0,CHARINDEX('/',PERIODO,0)),'-',SUBSTRING(PERIODO,CHARINDEX('/',PERIODO,0)+1,LEN(PERIODO)),'-','01') AS DATE) PERIODO2,
 --(SELECT LOGIN FROM FDN_USERTENANT WHERE  USER_CODE=R.USUARIOATUAL) LOGIN, 
 SUM(R.APONTAMENTO_PAPC) APONTAMENTO_PAPC, 
					 SUM(R.OPS_PAPC) OPS_PAPC,
					 SUM(R.APONTAMENTO) APONTAMENTO, 
					 ROUND(CAST(SUM(R.NUMO_OPS) AS FLOAT),4) TOTAL_NUM_OPS, 
					 SUM(R.APONTAMENTO_SEM_PROG) APONTAMENTO_SEM_PROG, 
					 ROUND(CAST(SUM(R.NUMO_OPS_SEM_PROG)AS FLOAT),4) TOTAL_NUM_OPS_SEM_PROG 
					 FROM ( 
							SELECT  PERIODO,USUARIOATUAL,COUNT(*) APONTAMENTO_PAPC,SUM(OPS_PAPC) OPS_PAPC,0 APONTAMENTO,0 NUMO_OPS ,0 APONTAMENTO_SEM_PROG,0 NUMO_OPS_SEM_PROG  FROM (
							 SELECT  CONCAT(DATEPART(YEAR,P.START_DATE),'/',DATEPART(MONTH,P.START_DATE)) PERIODO,USUARIOATUAL,AP.NUMPLANOCORTE,(SELECT COUNT(*) FROM CORPORE.DBO.ZMDPLANOAPROVEITAMENTOCORTE WHERE NUMPLANOCORTE=AP.NUMPLANOCORTE COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI ) OPS_PAPC,0 APONTAMENTO,0 NUMO_OPS ,0 APONTAMENTO_SEM_PROG,0 NUMO_OPS_SEM_PROG 
							 FROM ML001070(NOLOCK) AP  
							 INNER JOIN PROCES_WORKFLOW P ON 
							 P.NUM_PROCES=AP.NUMPROCESSO 
								WHERE ( CAST(P.START_DATE AS DATE) BETWEEN CAST(@INICIO AS DATE) AND CAST(@FIM AS DATE)
            					OR CAST(P.END_DATE AS DATE) BETWEEN CAST(@INICIO AS DATE) AND CAST(@FIM AS DATE))
								) A							 GROUP BY PERIODO,USUARIOATUAL

						 UNION ALL 

							 SELECT PERIODO,USUARIOATUAL,0,0,COUNT(R2.APONTAMENTO),SUM(NUMO_OPS),0,0 FROM ( 
								 SELECT CONCAT(DATEPART(YEAR,P.START_DATE),'/',DATEPART(MONTH,P.START_DATE)) PERIODO,USUARIOATUAL,0 APONTAMENTO_PAPC ,AP.DOCUMENTID APONTAMENTO,(SELECT COUNT(*) FROM ML001058 WHERE DOCUMENTID=AP.DOCUMENTID) NUMO_OPS,0 APONTAMENTO_SEM_PROG,0 NUMO_OPS_SEM_PROG 
								 FROM ML001057(NOLOCK) AP  
								 INNER JOIN PROCES_WORKFLOW P ON 
								 P.NUM_PROCES=AP.NUMPROCESSO 
								 INNER JOIN ML001060 MOV ON -- pega apontamentos que geraram movimentos no RM
								 MOV.COMPANYID=AP.COMPANYID
								 AND MOV.DOCUMENTID=AP.DOCUMENTID
								 AND MOV.VERSION=AP.VERSION
								 AND MOV.DOCUMENTID=AP.DOCUMENTID
									WHERE ( CAST(P.START_DATE AS DATE) BETWEEN CAST(@INICIO AS DATE) AND CAST(@FIM AS DATE)
            						OR CAST(P.END_DATE AS DATE) BETWEEN CAST(@INICIO AS DATE) AND CAST(@FIM AS DATE))
								 GROUP BY CONCAT(DATEPART(YEAR,P.START_DATE),'/',DATEPART(MONTH,P.START_DATE)),USUARIOATUAL,AP.DOCUMENTID 
								 ) R2 
							 GROUP BY PERIODO,USUARIOATUAL 
						UNION ALL 
							SELECT PERIODO, USUARIOATUAL,0,0,0,0,COUNT(R2.APONTAMENTO_SEM_PROG),SUM(NUMO_OPS_SEM_PROG) FROM ( 
								SELECT CONCAT(DATEPART(YEAR,P.START_DATE),'/',DATEPART(MONTH,P.START_DATE)) PERIODO,USUARIOATUAL,0 APONTAMENTO_PAPC,0 APONTAMENTO,0 NUMO_OPS,AP.DOCUMENTID APONTAMENTO_SEM_PROG,(SELECT COUNT(*) FROM ML001091 WHERE DOCUMENTID=AP.DOCUMENTID) NUMO_OPS_SEM_PROG 
								FROM ML001090 AP  
								INNER JOIN PROCES_WORKFLOW P ON 
								P.NUM_PROCES=AP.NUMPROCESSO 
								INNER JOIN ML001093 MOV ON -- pega apontamentos que geraram movimentos no RM
								MOV.COMPANYID=AP.COMPANYID
								AND MOV.DOCUMENTID=AP.DOCUMENTID
								AND MOV.VERSION=AP.VERSION
								AND MOV.DOCUMENTID=AP.DOCUMENTID
								WHERE ( CAST(P.START_DATE AS DATE) BETWEEN CAST(@INICIO AS DATE) AND CAST(@FIM AS DATE)
            					OR CAST(P.END_DATE AS DATE) BETWEEN CAST(@INICIO AS DATE) AND CAST(@FIM AS DATE))
								GROUP BY CONCAT(DATEPART(YEAR,P.START_DATE),'/',DATEPART(MONTH,P.START_DATE)),USUARIOATUAL,AP.DOCUMENTID 
							) R2 
							GROUP BY PERIODO,R2.USUARIOATUAL 
					 ) R 
					 GROUP BY PERIODO  
					) PRONTO ORDER BY PERIODO2

