SELECT K.CODCCUSTO,
K.CODORDEM,
KA.IDATVORDEM,

ROUND((CAST(KA.TEMPO AS FLOAT)/60)/
(SELECT COUNT(*) FROM KMAOOBRAALOC 
WHERE CODCOLIGADA=K.CODCOLIGADA
AND CODFILIAL=K.CODFILIAL
AND CODORDEM=K.CODORDEM
AND IDATVORDEM=KA.IDATVORDEM) ,2) PREVISTO,
ROUND(CAST(DATEDIFF(SECOND,KAL.DTHRINICIAL,KAL.DTHRFINAL) AS FLOAT)/3600,2) APONTADO, 
CASE WHEN KAC.RNCRR=1 THEN 'RNC' ELSE 'RR' END AS RNC_RR,
RETRABALHO, 
NUMERORNC2 NUMERORNC, 
CAUSADOR,C.DESCRICAO DSCPOSTO
FROM KORDEM K
INNER JOIN KATVORDEM KA ON
KA.CODCOLIGADA=K.CODCOLIGADA
AND KA.CODFILIAL=K.CODFILIAL
AND KA.CODORDEM=K.CODORDEM
INNER JOIN KMAOOBRAALOC KAL ON
KAL.CODCOLIGADA=K.CODCOLIGADA
AND KAL.CODFILIAL=K.CODFILIAL
AND KAL.CODORDEM=K.CODORDEM
AND KAL.IDATVORDEM=KA.IDATVORDEM
INNER JOIN KATVORDEMCOMPL KAC ON
KAC.CODCOLIGADA=K.CODCOLIGADA
AND KAC.CODFILIAL=K.CODFILIAL
AND KAC.CODORDEM=K.CODORDEM
AND KAC.IDATVORDEM=KA.IDATVORDEM
INNER JOIN MPRJ M ON
M.CODCOLIGADA=KA.CODCOLIGADA
AND M.CODFILIAL=KA.CODFILIAL
AND M.CODPRJ=K.CODCCUSTO
AND M.POSICAO IN ( 1,4)
INNER JOIN MTRF ML ON
ML.CODCOLIGADA=KA.CODCOLIGADA
AND ML.IDPRJ=M.IDPRJ
AND ML.CODTRFAUX=K.CODORDEM
INNER JOIN MTRFCOMPL MCL ON
MCL.CODCOLIGADA=M.CODCOLIGADA
AND MCL.IDPRJ=M.IDPRJ
AND MCL.IDTRF=ML.IDTRF
INNER JOIN GCONSIST C ON 
C.CODTABELA = 'CELULA'
AND C.APLICACAO = 'M'
AND C.CODINTERNO = MCL.CELULA
WHERE K.CODCCUSTO=:OS AND K.REPROCESSAMENTO=1
AND KAL.DTHRINICIAL >= :DATA_INICIAL AND KAL.DTHRFINAL<=:DATA_FINAL
ORDER BY CODORDEM

-----------------------------------------------------------------------------------------------------------------------------------------

declare @parametro varchar(100)
declare @data1 varchar(100)
declare @data2 varchar(100)
set @parametro = '7840'
set @data2 = '%'
set @data1 = '%'
set @parametro = concat(@parametro,',')

;with cte as 
		(	
			select left(@parametro,CHARINDEX(',',@parametro)-1) parametro,SUBSTRING(@parametro,CHARINDEX(',',@parametro)+1,LEN(@parametro)) parametro1 
			union all 
			select left(parametro1,CHARINDEX(',',parametro1)-1) parametro,SUBSTRING(parametro1,CHARINDEX(',',parametro1)+1,LEN(parametro1)) parametro1
			from cte  
			where len(parametro1)>1
		),cte2 as (SELECT CODPRJ parametro FROM MPRJ M INNER JOIN cte C ON M.CODPRJ LIKE CONCAT('%',C.parametro,'%.32.%') AND  M.POSICAO IN (1,4))
SELECT K.CODCCUSTO,
K.CODORDEM,
KA.IDATVORDEM,

ROUND((CAST(KA.TEMPO AS FLOAT)/60)/
(SELECT COUNT(*) FROM KMAOOBRAALOC 
WHERE CODCOLIGADA=K.CODCOLIGADA
AND CODFILIAL=K.CODFILIAL
AND CODORDEM=K.CODORDEM
AND IDATVORDEM=KA.IDATVORDEM) ,2) PREVISTO,

ROUND(CAST(DATEDIFF(SECOND,KAL.DTHRINICIAL,KAL.DTHRFINAL) AS FLOAT)/3600,2) APONTADO, 
CONCAT(CONVERT(VARCHAR(10),KAL.DTHRINICIAL,103),' ',CONVERT(VARCHAR(10),KAL.DTHRINICIAL,108)) DTHRINICIAL,
CONCAT(CONVERT(VARCHAR(10),KAL.DTHRFINAL,103),' ',CONVERT(VARCHAR(10),KAL.DTHRFINAL,108)) DTHRFINAL,
CASE WHEN KAC.RNCRR=1 THEN 'RNC' ELSE 'RR' END AS RNC_RR,
RETRABALHO, 
NUMERORNC2 NUMERORNC, 
CAUSADOR,C.DESCRICAO DSCPOSTO,KAL.CODMO,( SELECT DISTINCT NOME FROM PPESSOA WHERE CODIGO = (SELECT DISTINCT CODPESSOA FROM KMAOOBRA WHERE CODMO=KAL.CODMO)) NOME
FROM KORDEM K
INNER JOIN KATVORDEM KA ON
KA.CODCOLIGADA=K.CODCOLIGADA
AND KA.CODFILIAL=K.CODFILIAL
AND KA.CODORDEM=K.CODORDEM
INNER JOIN KMAOOBRAALOC KAL ON
KAL.CODCOLIGADA=K.CODCOLIGADA
AND KAL.CODFILIAL=K.CODFILIAL
AND KAL.CODORDEM=K.CODORDEM
AND KAL.IDATVORDEM=KA.IDATVORDEM
INNER JOIN KATVORDEMCOMPL KAC ON
KAC.CODCOLIGADA=K.CODCOLIGADA
AND KAC.CODFILIAL=K.CODFILIAL
AND KAC.CODORDEM=K.CODORDEM
AND KAC.IDATVORDEM=KA.IDATVORDEM
INNER JOIN MPRJ M ON
M.CODCOLIGADA=KA.CODCOLIGADA
AND M.CODFILIAL=KA.CODFILIAL
AND M.CODPRJ=K.CODCCUSTO
AND M.POSICAO IN ( 1,4)
INNER JOIN MTRF ML ON
ML.CODCOLIGADA=KA.CODCOLIGADA
AND ML.IDPRJ=M.IDPRJ
AND ML.CODTRFAUX=K.CODORDEM
INNER JOIN MTRFCOMPL MCL ON
MCL.CODCOLIGADA=M.CODCOLIGADA
AND MCL.IDPRJ=M.IDPRJ
AND MCL.IDTRF=ML.IDTRF
INNER JOIN GCONSIST C ON 
C.CODTABELA = 'CELULA'
AND C.APLICACAO = 'M'
AND C.CODINTERNO = MCL.CELULA 
WHERE ( (K.CODCCUSTO IN ( SELECT DISTINCT parametro FROM cte2 ) ) OR ( K.CODCCUSTO LIKE ( SELECT TOP 1 parametro FROM cte ) ) ) AND K.REPROCESSAMENTO=1
AND ( ( KAL.DTHRINICIAL >= CASE WHEN @data1 != '%' THEN CONVERT(DATETIME,@data1,103) ELSE cast(-53690 as datetime) END 
AND DATEADD(DAY,-1,KAL.DTHRFINAL)<= CASE WHEN @data1 != '%' THEN CONVERT(DATETIME,@data2,103) ELSE CONVERT(DATETIME,'9999-01-01',103) END AND @data2!='%' AND @data1!='%' ) OR
 ( KAL.DTHRINICIAL LIKE '%' AND KAL.DTHRFINAL LIKE '%' AND @data2='%' AND @data1='%'  ) 
 )
ORDER BY CODORDEM
