SELECT M.NUM_OS,W.NUM_PROCES,W.COD_DEF_PROCES,COALESCE((FORMAT(W.START_DATE,'D','pt-BR')+' '+CONVERT(VARCHAR(20),W.START_DATE,108)),'') DATAINICIO ,
* FROM ML001004 M INNER JOIN PROCES_WORKFLOW W
ON W.NR_DOCUMENTO_CARD=M.documentid
 WHERE W.STATUS=0-- Cadastro de Estrutura

SELECT M.NUM_OS,W.NUM_PROCES,W.COD_DEF_PROCES,COALESCE((FORMAT(W.START_DATE,'D','pt-BR')+' '+CONVERT(VARCHAR(20),W.START_DATE,108)),'') DATAINICIO ,* 
FROM ML001007 M INNER JOIN PROCES_WORKFLOW W
ON W.NR_DOCUMENTO_CARD=M.documentid
 WHERE W.STATUS=0-- Edição de Estrutura


SELECT M.NUM_OS,W.NUM_PROCES,W.COD_DEF_PROCES,COALESCE((FORMAT(W.START_DATE,'D','pt-BR')+' '+CONVERT(VARCHAR(20),W.START_DATE,108)),'') DATAINICIO ,* 
FROM ML001081 M INNER JOIN PROCES_WORKFLOW W
ON W.NR_DOCUMENTO_CARD=M.documentid
 WHERE W.STATUS=0-- Edição de Execução



SELECT M.NUM_OS,W.NUM_PROCES,W.COD_DEF_PROCES,COALESCE((FORMAT(W.START_DATE,'D','pt-BR')+' '+CONVERT(VARCHAR(20),W.START_DATE,108)),'') DATAINICIO ,* 
FROM ML001084 M INNER JOIN PROCES_WORKFLOW W
ON W.NR_DOCUMENTO_CARD=M.documentid
 WHERE W.STATUS=0-- Edição de Execução de Subconjunto de Estrutura


SELECT M.NUM_OS,W.NUM_PROCES,W.COD_DEF_PROCES,COALESCE((FORMAT(W.START_DATE,'D','pt-BR')+' '+CONVERT(VARCHAR(20),W.START_DATE,108)),'') DATAINICIO ,* 
FROM ML001020 M INNER JOIN PROCES_WORKFLOW W
ON W.NR_DOCUMENTO_CARD=M.documentid
 WHERE W.STATUS=0-- Edição de Subconjunto de Estrutura


SELECT M.NUM_OS,W.NUM_PROCES,W.COD_DEF_PROCES,COALESCE((FORMAT(W.START_DATE,'D','pt-BR')+' '+CONVERT(VARCHAR(20),W.START_DATE,108)),'') DATAINICIO ,* 
FROM ML001017 M INNER JOIN PROCES_WORKFLOW W
ON W.NR_DOCUMENTO_CARD=M.documentid
 WHERE W.STATUS=0-- Cadastro de Subconjunto de Estrutura
