SELECT IDREL, IDJOBLOG,
           CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), RELATORIO)) AS RELATORIO
FROM GRELBATCH
WHERE IDJOBLOG = (SELECT Max(IDJOBLOG)
                                   FROM GRELBATCH)