USE [CORPORE_DEV]
GO
/****** Object:  StoredProcedure [dbo].[SP_CRM_EDICAOESTRUTURA]    Script Date: 28/10/2023 16:46:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_CRM_EDICAOESTRUTURA] @NUMPROCESSO INT
AS
BEGIN
	print 'teste'

	DECLARE @CODCOLIGADA INT, @CODFILIAL INT, @IDPRJ INT;


	PRINT 'INICIO EDICAO'

-- VERIFICA SE PRODUTROS EXCLUIDOS QUE ESTAVAM NA Z_CRM_ITENSEXCLUIDO VOLTARAM PARA ESTRUTURA

	DELETE E 
	FROM FLUIG.dbo.Z_CRM_ITENSEXCLUIDOS E
	INNER JOIN FLUIG.dbo.Z_CRM_ML001005 M ON E.OS = M.OS AND E.IDPRD = M.IDPRD

-- INICIA COM AS EXCLUSÕES DAS EDIÇÕES


	UPDATE P SET INATIVO = 1, RECMODIFIEDON=GETDATE()
	FROM TPRODUTO P 
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = P.IDPRD AND Z.CODCOLIGADA = P.CODCOLPRD
	WHERE Z.PROCESSO = @NUMPROCESSO;

		
	
	UPDATE P SET STATUSESTR = 0, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA P 
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = P.IDPRODUTO AND Z.CODCOLIGADA = P.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;
	
	

	UPDATE O SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO; 
		
		

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN KORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;

	

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN KATVORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;

		
/*
	DELETE K
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN KMAOOBRAALOC K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM AND K.EFETIVADO = 0
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;

	

	DELETE K
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN KATVORDEMPROCESSO K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM AND K.EFETIVADO = 0
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;


*/

	-- FIM DAS EXCLUSÕES DAS ALTERAÇÕES


	-- INICIO DAS ALTERAÇÕES

	DECLARE @QTDORDEM INT, @NUMPROCESSO_ORIGINAL INT, @OS VARCHAR(MAX), @INDICE INT, @CODTRFPAI VARCHAR(MAX), @IDDISCIPLINA INT;

	
		
	
	DECLARE ORDENS CURSOR FOR 
						SELECT  O.NUMPROCESSO , CAST(ISNULL(I.EXECINTEGRADAS,0) AS int),I.CODCOLIGADA , I.CODFILIAL,  CAST(O.IDPRJ_OS AS int), CAST(I.INDICE AS int), O.NUM_OS, I.CODTRFPAI
						FROM FLUIG.DBO.ML001007 Z
							INNER JOIN FLUIG.DBO.ML001004 O ON Z.NUM_OS = O.NUM_OS
							INNER JOIN FLUIG.dbo.Z_CRM_ML001005 I on O.NUM_OS = I.OS
						WHERE Z.NUMPROCESSO = @NUMPROCESSO AND  I.NIVEL = '';
	OPEN ORDENS;

	FETCH NEXT FROM ORDENS INTO @NUMPROCESSO_ORIGINAL, @QTDORDEM, @CODCOLIGADA, @CODFILIAL, @IDPRJ, @INDICE, @OS, @CODTRFPAI;


	WHILE @@FETCH_STATUS = 0
	BEGIN
	
		

		SELECT @IDDISCIPLINA = IDDISCIPLINA FROM MDISCIPLINA WHERE CODCOLIGADA = @CODCOLIGADA AND IDPRJ = @IDPRJ AND CODIGO = '07';

		UPDATE P SET  P.INVENTARIOFISCAL = 1, P.TIPOTRIBUTACAO = 0, P.CODCOLCONTA = @CODCOLIGADA,
					P.SITUACAOMERCADORIA = CASE LEFT(I.CODIGOPRD,2) 
													WHEN '04' THEN '04' 
													WHEN '03' THEN '03'
													ELSE '02'  END, 
					P.CODCONTA = CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN '1.1.3.01.0003' ELSE  '1.1.3.01.0004' END 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN TPRDFISCAL (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA AND I.IDPRD = P.IDPRD
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;

		
	
		-- ALTERAÇÃO PARA NÃO ALTERAR A DESCRIÇÃO DO PRODUTO 04.024 - RAFAEL.GRANJA - 20/04/2023

		--UPDATE P SET P.DESCRICAO = CASE WHEN LEFT(P.CODIGOPRD,2) = '04' THEN ISNULL(I.DESCRICAO,'') ELSE ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,'') END, 
		--			 P.NOMEFANTASIA = CASE WHEN LEFT(P.CODIGOPRD,2) = '04' THEN ISNULL(I.DESCRICAO,'') ELSE LEFT(ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),120) END
		--FROM FLUIG.DBO.ML001004 (NOLOCK) M
		--	INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		--	INNER JOIN TPRODUTO (NOLOCK) P ON P.CODCOLPRD = 1 AND I.IDPRD = P.IDPRD
		--WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;


		-- NÃO ATUALIZA DESCRIÇÃO DO 04.024
		UPDATE P SET P.DESCRICAO = ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''), 
					 P.NOMEFANTASIA =  LEFT(ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),120)
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN TPRODUTO (NOLOCK) P ON P.CODCOLPRD = 1 AND I.IDPRD = P.IDPRD
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND LEFT(P.CODIGOPRD,2)!='04';

	
			

		UPDATE P SET P.NUMNOFABRIC = I.CODIGOPRD
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN TPRODUTODEF (NOLOCK) P ON P.CODCOLIGADA = 1 AND I.IDPRD = P.IDPRD
		WHERE  M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;

	
	
		-- ###### INCIADO INTEGRACAO COM O FACTOR ######

		-- INCLUSÃO DA ESTRUTURA
	
		INSERT INTO KESTRUTURA (CODCOLIGADA, CODESTRUTURA, CODTIPO, IDPRODUTO, QTDLOTE, STATUSESTR, CODCCUSTO, IDFASE, FASEVALIDADA, CODIGOULTALTERACAO, VALIDACAOSOLICITADA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA, I.CODIGOPRD, CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN 'A' ELSE 'S' END, I.IDPRD, I.DESQTDE*10000, 1, M.NUM_OS, 1, 1, 0, 0, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			LEFT JOIN KESTRUTURA E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE E.CODESTRUTURA IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
		ORDER BY I.NIVEL, I.INDICE;

		UPDATE E  SET CODTIPO = CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN 'A' ELSE 'S' END, QTDLOTE = ISNULL(I.DESQTDE,1)*10000, STATUSESTR= 1,  RECMODIFIEDON = GETDATE()
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KESTRUTURA E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
		
	

		INSERT INTO KLINHAEST (CODCOLIGADA, CODLINHA, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA, '001', I.CODIGOPRD, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			LEFT JOIN KLINHAEST E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE  E.CODESTRUTURA IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
		ORDER BY I.NIVEL, I.INDICE;

	

		INSERT INTO KESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODFILIAL, ELABORADOR2, ELABORADOR3, ELABORADOR, CAMDESENHO, NUMREVISAO, POSICAO, BITOLA, LARGURA, COMPRIMENTO, PESOBRUTO, PESOLIQUIDO, ESPECIFICACAOROSCA , RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT						 I.CODCOLIGADA, I.CODIGOPRD, I.CODFILIAL, NULL ELABORADOR2, NULL ELABORADOR3, NULL ELABORADOR, 
								CASE WHEN I.NUMDESENHO = '' THEN NULL ELSE I.NUMDESENHO END, 
								CASE WHEN I.REVISAODESENHO = '' THEN NULL ELSE I.REVISAODESENHO END, 
								CASE WHEN I.POSICAODESENHO = '' THEN NULL ELSE I.POSICAODESENHO END, 
								CAST( CASE WHEN I.BITOLA = '' OR I.BITOLA = 'null' THEN NULL ELSE REPLACE(I.BITOLA,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.LARGURA = '' OR I.LARGURA = 'null' THEN NULL ELSE REPLACE(I.LARGURA,',','.') END AS FLOAT),
								CAST( CASE WHEN I.COMPRIMENTO = '' OR I.COMPRIMENTO = 'null' THEN NULL ELSE REPLACE(I.COMPRIMENTO,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.PESOBRUTO = '' OR I.PESOBRUTO = 'null' THEN NULL ELSE REPLACE(I.PESOBRUTO,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.PESOLIQUIDO = '' OR I.PESOLIQUIDO = 'null' THEN NULL ELSE REPLACE(I.PESOLIQUIDO,',','.') END AS FLOAT), 
								CASE WHEN I.ESPROSCA = '' OR I.ESPROSCA = 'null' THEN NULL ELSE I.ESPROSCA END, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			LEFT JOIN KESTRUTURACOMPL K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE K.CODESTRUTURA IS NULL
		AND		M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
		ORDER BY I.NIVEL, I.INDICE;

	
	

		UPDATE K SET	CAMDESENHO =	CASE WHEN I.NUMDESENHO = '' THEN NULL ELSE I.NUMDESENHO END, 
						NUMREVISAO =		CASE WHEN I.REVISAODESENHO = '' THEN NULL ELSE I.REVISAODESENHO END, 
						POSICAO    =		CASE WHEN I.POSICAODESENHO = '' THEN NULL ELSE I.POSICAODESENHO END, 
						BITOLA     =		CAST( CASE WHEN I.BITOLA = '' THEN NULL ELSE REPLACE(I.BITOLA,',','.') END AS FLOAT), 
						LARGURA    =		CAST( CASE WHEN I.LARGURA = '' THEN NULL ELSE REPLACE(I.LARGURA,',','.') END AS FLOAT),
						COMPRIMENTO=		CAST( CASE WHEN I.COMPRIMENTO = '' THEN NULL ELSE REPLACE(I.COMPRIMENTO,',','.') END AS FLOAT), 
						PESOBRUTO  =		CAST( CASE WHEN I.PESOBRUTO = '' THEN NULL ELSE REPLACE(I.PESOBRUTO,',','.') END AS FLOAT), 
						PESOLIQUIDO=		CAST( CASE WHEN I.PESOLIQUIDO = '' THEN NULL ELSE REPLACE(I.PESOLIQUIDO,',','.') END AS FLOAT), 
						ESPECIFICACAOROSCA=		CASE WHEN I.ESPROSCA = '' THEN NULL ELSE I.ESPROSCA END, 
						RECMODIFIEDON = GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KESTRUTURACOMPL K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;

	
			
		DELETE K
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN KATVESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;

	

		DELETE K
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN KATVESTPOSTO (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
		
		
		
		DELETE K
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN KCOMPSUBSTITUTO K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
		
		

		DELETE K
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN KCOMPONENTECOMPL K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.IDPRD <> '';

		DELETE K
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN KCOMPONENTE K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.IDPRD <> '';
		
	

		DELETE K
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN KATVESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.IDPRD <> '';
		
		
		
		INSERT INTO KATVESTRUTURA
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, 1 HORAS, MIN( CAST(C.PRIORIDADE AS INT) ) ,
			SUM(	CAST( CASE WHEN C.FILA = '' THEN NULL ELSE REPLACE(C.FILA,',','.') END AS FLOAT) ), 
			SUM(	CAST( CASE WHEN C.CONFIGURACAO = '' THEN NULL ELSE REPLACE(C.CONFIGURACAO,',','.') END AS FLOAT) ), 
			SUM(	CAST( CASE WHEN C.PROCESSAMENTO = '' THEN NULL ELSE REPLACE(C.PROCESSAMENTO,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.DESAGREGACAO = '' THEN NULL ELSE REPLACE(C.DESAGREGACAO,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.ESPERA = '' THEN NULL ELSE REPLACE(C.ESPERA,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.MOVIMENTACAO = '' THEN NULL ELSE REPLACE(C.MOVIMENTACAO,',','.') END AS FLOAT)),
				1,0,'P',0,NULL,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
				LEFT JOIN KATVESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE  K.CODATIVIDADE IS NULL
			AND		M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
			GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE,I.CODFILIAL;

		
			-- INCLUSÃO DA ETAPAS AS ATIVIDADES PARA LINHA DE PRODUÇÃO O DISTINCT É PARA NÃO INCLUIR A MESMA ATIVIDADE NA TABELA E DAR ERRO


		INSERT INTO  KETPATIVIDADES 
			SELECT DISTINCT I.CODCOLIGADA,'ETP-GLOBAL',C.CODATIVIDADE,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
				LEFT JOIN KETPATIVIDADES (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE  K.CODATIVIDADE IS NULL
			AND		M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') 
			GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL

		

			INSERT INTO KATVESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODATIVIDADE,CODFILIAL, DETALHE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL, C.DESCPROCESSO , 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
				LEFT JOIN KATVESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI = K.CODATIVIDADE
			WHERE K.CODESTRUTURA IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
	
		
			

			INSERT INTO KATVESTPOSTO (CODCOLIGADA, CODPOSTO, CODATIVIDADE, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT DISTINCT K.CODCOLIGADA, K.CODPOSTO, C.CODATIVIDADE, I.CODIGOPRD, K.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
				INNER JOIN KPOSTO (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODPOSTO = C.CODPOSTO COLLATE SQL_Latin1_General_CP1_CI_AI
				LEFT JOIN KATVESTPOSTO (NOLOCK) KP ON KP.CODCOLIGADA = K.CODCOLIGADA AND KP.CODFILIAL = K.CODFILIAL AND KP.CODPOSTO = K.CODPOSTO AND KP.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND KP.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE KP.CODPOSTO IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.CODIGOPRD <> '';
		
		
	
			INSERT INTO KCOMPONENTE (CODCOLIGADA, CODESTRUTURA, IDPRODUTO, IDAUTOINC, QTDUSADA, CODATIVIDADE, OBRIGASERMATERIAPRIMA, FAZPARTEMODELOBASE, PERMITEEXCLUSAO, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON )
			SELECT  CODCOLIGADA, CODIGOPRD, IDPRD, (SELECT MAX(IDAUTOINC) FROM KCOMPONENTE)+ ROW_NUMBER () OVER (ORDER BY IDPRD), CAST(QTD AS float),
						ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
								) ATIVIDADE,
					1, 0, 0, COMPONENTES.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM (
				SELECT  I.CODIGOPRD, E.IDPRD,  1 QTD, I.NIVEL, I.INDICE, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA
				FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) E ON M.NUM_OS = E.OS AND I.INDICE = E.NIVEL
				WHERE  M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0 AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
		
				UNION ALL
		
				SELECT I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD, 1 QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA
				FROM FLUIG.DBO.ML001004 (NOLOCK) M
					INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND   M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL
			
				UNION ALL

					-- CODIGOS NÃO MANUFATURADO
				SELECT P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) * 10000 QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA
				FROM FLUIG.DBO.ML001004 (NOLOCK) M
					INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
					INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON M.NUM_OS = P.OS AND I.NIVEL = P.INDICE
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND  M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO = 'NAOMANUFATURADO'

			
			) AS COMPONENTES
			WHERE IDPRD <> ''
			AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			
			ORDER BY NIVEL, INDICE;

			-- INSERE OS PRODUTOS SUBSTITUTOS
			
				

			INSERT INTO  KCOMPSUBSTITUTO
				SELECT SUB.CODCOLIGADA, SUB.CODESTRUTURA, SUB.CODATIVIDADE, SUB.IDAUTOINC, SUB.IDPRD, SUB.IDPRDCOMPONENTES, SUB.QTDUSADA, NULL, NULL, 0,  SUB.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE()
				FROM (
						SELECT 'A' TIPO, I.NIVEL, I.INDICE, K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
						FROM FLUIG.DBO.ML001004 (NOLOCK) M
							INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
							INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) A ON I.OS = A.OSPROCESSO AND I.IDCRIACAO = A.IDCRIACAOPROCESSO
							INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND A.PRIORIDADE = C.PRIORIDADEATVCOMPONENTES
							INNER JOIN TPRD P ON P.CODCOLIGADA = I.CODCOLIGADA AND P.CODIGOPRD  COLLATE Latin1_General_CI_AS = C.SUBSTITUTOCOMPONENTES
							INNER JOIN KCOMPONENTE (NOLOCK) K ON  P.IDPRD = K.IDPRODUTO 	AND P.CODCOLIGADA = K.CODCOLIGADA AND K.CODESTRUTURA COLLATE Latin1_General_CI_AS = I.CODIGOPRD AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE COLLATE Latin1_General_CI_AS = A.CODATIVIDADE
							INNER JOIN KESTRUTURA (NOLOCK) E ON K.CODCOLIGADA = E.CODCOLIGADA AND K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA AND E.CODCCUSTO COLLATE Latin1_General_CI_AS = I.OS  AND E.RECCREATEDBY = 'fluig'
						WHERE C.PRIORIDADEATVCOMPONENTES <> 0 AND E.STATUSESTR = 1 AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> ''
		
				UNION ALL

						SELECT 'B' TIPO, I.NIVEL, I.INDICE,  K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
						FROM FLUIG.DBO.ML001004 (NOLOCK) M
							INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
							INNER JOIN KESTRUTURA (NOLOCK) E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODFILIAL = E.CODFILIAL AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA
							INNER JOIN KCOMPONENTE (NOLOCK) K ON  E.CODCOLIGADA = K.CODCOLIGADA AND  K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
							INNER JOIN TPRD (NOLOCK) P ON K.CODCOLIGADA = P.CODCOLIGADA AND K.IDPRODUTO = P.IDPRD
							INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND P.CODIGOPRD = C.SUBSTITUTOCOMPONENTES  COLLATE SQL_Latin1_General_CP1_CI_AI		
						WHERE C.PRIORIDADEATVCOMPONENTES = 0 AND E.STATUSESTR = 1 AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> ''
					) SUB
				LEFT JOIN KCOMPSUBSTITUTO (NOLOCK) S ON S.CODCOLIGADA = SUB.CODCOLIGADA AND S.CODFILIAL = SUB.CODFILIAL AND S.CODESTRUTURA = SUB.CODESTRUTURA AND S.CODATIVIDADE = SUB.CODATIVIDADE AND S.IDAUTOINC = SUB.IDAUTOINC AND S.IDPRDORIGEM = SUB.IDPRD AND S.IDPRD = SUB.IDPRDCOMPONENTES
				WHERE S.CODCOLIGADA IS NULL
				ORDER BY SUB.CODESTRUTURA, SUB.CODATIVIDADE, SUB.IDPRD, SUB.IDPRDCOMPONENTES;


			-- ATUALIZA AS QUANTIDADES

		

			UPDATE C SET C.QTDUSADA = COM.QUANTIDADE* 10000 
			FROM KCOMPONENTE C
				INNER JOIN (
							SELECT  CODCOLIGADA, CODIGOPRD, IDPRD, CAST(QTD AS float) QUANTIDADE, CODFILIAL
							FROM (
								SELECT I.CODCOLIGADA, I.CODIGOPRD, E.IDPRD,  E.DESQTDE QTD, I.NIVEL, I.INDICE, I.CODFILIAL
								FROM FLUIG.DBO.ML001004 (NOLOCK) M
									INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on  M.NUM_OS = I.OS
									INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) E ON  M.NUM_OS = E.OS AND I.INDICE = E.NIVEL
								WHERE  M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL
		
								UNION ALL
		
								SELECT I.CODCOLIGADA, I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD, CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.NIVEL, I.INDICE, I.CODFILIAL
								FROM FLUIG.DBO.ML001004 (NOLOCK) M
									INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
									INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
								WHERE  M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL
								
								UNION ALL
									-- CODIGOS NÃO MANUFATURADO
								SELECT P.CODCOLIGADA, P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD, CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.NIVEL, I.INDICE, I.CODFILIAL
								FROM FLUIG.DBO.ML001004 (NOLOCK) M
									INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
									INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
									INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON M.NUM_OS = P.OS AND I.NIVEL = P.INDICE
								WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND  M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO = 'NAOMANUFATURADO'
						
							) AS TESTE)AS COM ON COM.CODCOLIGADA = C.CODCOLIGADA AND COM.CODFILIAL = C.CODFILIAL AND COM.CODIGOPRD COLLATE Latin1_General_CI_AS = C.CODESTRUTURA AND COM.IDPRD = C.IDPRODUTO




	UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))



	-- CRIAÇÃO DAS ORDEMS DE PRODUTOS RESCEM CRIADOS EM TODAS AS EXECUÇÕES
		DECLARE @CONTADOR INT = 1, @DATACRIACAO DATETIME = GETDATE();

		UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))


		WHILE @QTDORDEM >= @CONTADOR
		BEGIN


	-- POPULANDO AS TABELAS DO FLUIG COM AS EXECUÇÕES
			
			-- ############################################################################################################################################
			--                           INICIO DA INCLUSÃO DO EX001005
			-- ############################################################################################################################################

			-- DELETA DA EX AS ML QUE NÃO TEM ORDEM DE PRODUÇÃO PARA ATUALIZAR AS EX COM AS MODIFICAÇÃO DA EDIÇÃO PRINCIPAL

			-- COMPONENTES
			DELETE E19
			FROM FLUIG.DBO.Z_CRM_EX001005 E5  
				INNER JOIN FLUIG.DBO.Z_CRM_EX001019 E19 ON E5.OS = E19.OSCOMPONENTES AND E5.IDCRIACAO = E19.IDCRIACAOCOMPONENTES AND E5.EXECUCAO = E19.EXECUCAO
				INNER JOIN FLUIG.DBO.Z_CRM_ML001005 M5 ON E5.OS = M5.OS AND E5.IDCRIACAO = M5.IDCRIACAO
				LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL
							 FROM KORDEM O
								INNER JOIN KORDEMCOMPL C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
								INNER JOIN KITEMORDEM I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
							 WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL ) ORDENS ON E5.CODCOLIGADA = ORDENS.CODCOLIGADA AND E5.CODFILIAL = ORDENS.CODFILIAL AND E5.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND E5.EXECUCAO = ORDENS.NUMEXEC
			WHERE ORDENS.CODORDEM IS NULL
			AND E5.OS = @OS
			AND E5.EXECUCAO = @CONTADOR
			AND E5.ITEMEXCLUSIVO <> 2

			-- ATIVIADES
			DELETE E21
			FROM FLUIG.DBO.Z_CRM_EX001005 E5
				INNER JOIN FLUIG.DBO.Z_CRM_EX001021 E21 ON E5.OS = E21.OSPROCESSO AND E5.IDCRIACAO = E21.IDCRIACAOPROCESSO AND E5.EXECUCAO = E21.EXECUCAO
				INNER JOIN FLUIG.DBO.Z_CRM_ML001005 M5 ON E5.OS = M5.OS AND E5.IDCRIACAO = M5.IDCRIACAO
				LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL
							 FROM KORDEM O
								INNER JOIN KORDEMCOMPL C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
								INNER JOIN KITEMORDEM I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
							 WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL ) ORDENS ON E5.CODCOLIGADA = ORDENS.CODCOLIGADA AND E5.CODFILIAL = ORDENS.CODFILIAL AND E5.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND E5.EXECUCAO = ORDENS.NUMEXEC
			WHERE ORDENS.CODORDEM IS NULL
			AND E5.OS = @OS
			AND E5.EXECUCAO = @CONTADOR
			AND E5.ITEMEXCLUSIVO <> 2

			-- ATUALIZAR ESTRUTURAS SEM OPs
			UPDATE E SET
						TITULOITEM= M.TITULOITEM, 
						--NIVEL= M.NIVEL, 
						POSICAO= M.POSICAO, 
						DESCRICAO= M.DESCRICAO, 
						NUMDESENHO= M.NUMDESENHO, 
						REVISAODESENHO= M.REVISAODESENHO, 
						NUMDBI= M.NUMDBI, 
						REVISAODBI= M.REVISAODBI, 
						DESQTDE= M.DESQTDE, 
						TOTALQTDE= M.TOTALQTDE, 
						BITOLAESP= M.BITOLAESP, 
						LARGURAMASSA= M.LARGURAMASSA, 
						ESPLARGURAROSCA= M.ESPLARGURAROSCA, 
						COMPRIMENTO= M.COMPRIMENTO, 
						MATERIAL= M.MATERIAL, 
						PESO= M.PESO, 
						OBSERVACOES= M.OBSERVACOES, 
						TIPO= M.TIPO, 
						SEQ= M.SEQ, 
						masterid= M.masterid, 
						PESOMATERIAL= M.PESOMATERIAL, 
						OS= M.OS, 
						DATAREVISAO= M.DATAREVISAO, 
						PESOBRUTO= M.PESOBRUTO, 
						PESOLIQUIDO= M.PESOLIQUIDO, 
						OBSERVACOESDESENHO= M.OBSERVACOESDESENHO, 
						PERIMETROCORTE= M.PERIMETROCORTE, 
						AREAPINTURA= M.AREAPINTURA, 
						OBSPROCESSO= M.OBSPROCESSO, 
						OBSGERAL= M.OBSGERAL, 
						QUANTIDADEMATERIAL= M.QUANTIDADEMATERIAL, 
						TIPODESENHO= M.TIPODESENHO, 
						POSICAOCOMPLETA= M.POSICAOCOMPLETA, 
						ESPESSURA= M.ESPESSURA, 
						BITOLA= M.BITOLA, 
						LARGURA= M.LARGURA, 
						MASSALINEAR= M.MASSALINEAR, 
						DIAMETROEXTERNO= M.DIAMETROEXTERNO, 
						DIAMETROINTERNO= M.DIAMETROINTERNO, 
						ESPROSCA= M.ESPROSCA, 
						POSICAOCOMPLETAANTIGA= M.POSICAOCOMPLETAANTIGA,
						NOVOMATERIAL= M.NOVOMATERIAL, 
						MATERIAL_ZOOM= M.MATERIAL_ZOOM, 
						IDMATERIAL= M.IDMATERIAL, 
						CODIGOPRD= M.CODIGOPRD, 
						--INDICE= M.INDICE, 
						POSICAOESTRUTURA= M.POSICAOESTRUTURA, 
						POSICAODESENHO= M.POSICAODESENHO, 
						AREASECAO= M.AREASECAO, 
						ALTURA= M.ALTURA, 
						LARGURAMESA= M.LARGURAMESA, 
						ESPALMA= M.ESPALMA, 
						ESPMESA= M.ESPMESA, 
						--POSICAOINDICE= M.POSICAOINDICE, 
						INDICEANTIGO= M.INDICEANTIGO, 
						IDCRIACAO= M.IDCRIACAO,
						IDCRIACAOPAI = M.IDCRIACAOPAI,
						PRODUTORM= M.PRODUTORM, 
						IDPRD= M.IDPRD, 
						EXPANSOR= M.EXPANSOR, 
						CODIGOPRDMATERIAL= M.CODIGOPRDMATERIAL, 
						CODTRFOS= M.CODTRFOS, 
						UNDMEDIDA= M.UNDMEDIDA, 
						ORDEM= M.ORDEM, 
						LARGURAABA= M.LARGURAABA, 
						ESPABA= M.ESPABA, 
						INTEGRADO= M.INTEGRADO, 
						DSCTRFOS= M.DSCTRFOS,
						SOLICITACAO= M.SOLICITACAO, 
						PAIDETALHADO= M.PAIDETALHADO, 
						COMPORLISTA= M.COMPORLISTA, 
						CODTRFITEM= M.CODTRFITEM, 
						IDTRFITEM= M.IDTRFITEM, 
						NOMETRFITEM= M.NOMETRFITEM, 
						CODIGOTAREFADESC= M.CODIGOTAREFADESC, 
						IDPRJOS= M.IDPRJOS,
						DESCOS= M.DESCOS, 
						DETALHADO= M.DETALHADO, 
						NUMDOCDELP= M.NUMDOCDELP, 
						REVISAODOCDELP= M.REVISAODOCDELP, 
						CODCOLIGADA= M.CODCOLIGADA, 
						DIAMETROEXTERNODISCO= M.DIAMETROEXTERNODISCO,
						DIAMETROINTERNODISCO= M.DIAMETROINTERNODISCO,
						CHECKUSINAGEM= M.CHECKUSINAGEM, 
						CHECKCALDERARIA= M.CHECKCALDERARIA, 
						CODFILIAL= M.CODFILIAL, 
						--CODTRFPAI= M.CODTRFPAI, 
						EXECINTEGRADAS= M.EXECINTEGRADAS, 
						--IDTRFPAI= M.IDTRFPAI, 
						--NOMETRFPAI= M.NOMETRFPAI, 
						EXECUCOES= M.EXECUCOES, 
						PESOUNITARIO= M.PESOUNITARIO, 
						OPSUNITARIAS= M.OPSUNITARIAS, 
						QTDEUNCOMP= M.QTDEUNCOMP, 
						ITEMEXCLUSIVO= 0,
						RECCREATEDBY= M.RECCREATEDBY,
						RECCREATEDON= M.RECCREATEDON,
						RECMODIFIEDBY= M.RECMODIFIEDBY,
						RECMODIFIEDON = M.RECMODIFIEDON
			FROM FLUIG.DBO.Z_CRM_EX001005 E  
							INNER JOIN FLUIG.DBO.Z_CRM_ML001005 M ON E.OS = M.OS AND E.IDCRIACAO = M.IDCRIACAO
							LEFT JOIN (SELECT O.CODCOLIGADA , O.CODFILIAL, I.CODESTRUTURA, C.NUMEXEC, O.CODORDEM, O.STATUS, O.RESPONSAVEL
										 FROM KORDEM O
											INNER JOIN KORDEMCOMPL C ON O.CODCOLIGADA = C.CODCOLIGADA AND O.CODFILIAL = C.CODFILIAL AND O.CODORDEM = C.CODORDEM
											INNER JOIN KITEMORDEM I ON  O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
										 WHERE ISNULL(REPROCESSAMENTO,0) <> 1 AND CHARINDEX(';',O.RESPONSAVEL) <> 0 AND C.NUMEXEC IS NOT NULL ) ORDENS ON E.CODCOLIGADA = ORDENS.CODCOLIGADA AND E.CODFILIAL = ORDENS.CODFILIAL AND E.CODIGOPRD = ORDENS.CODESTRUTURA COLLATE SQL_Latin1_General_CP1_CI_AI AND E.EXECUCAO = ORDENS.NUMEXEC
			WHERE ORDENS.CODORDEM IS NULL
			AND E.OS = @OS
			AND E.EXECUCAO = @CONTADOR
			AND E.ITEMEXCLUSIVO <> 2
			


				DECLARE  @ID INT, @IDCRIACAOPAI INT, @NIVEL VARCHAR(MAX), @IDCRIACAO INT, @POSICAOINDICE INT
							-- CRIA CÓPIA DA EXECUÇÃO


				--RENUMERA

				DECLARE EXECUCAO CURSOR FOR

											SELECT	M.ID, M.IDCRIACAO, M.IDCRIACAOPAI
											FROM FLUIG.dbo.Z_CRM_ML001005 M (NOLOCK)
												LEFT JOIN FLUIG.dbo.Z_CRM_EX001005 E (NOLOCK) ON M.ID = E.ID AND M.OS = E.OS AND E.EXECUCAO = @CONTADOR
											WHERE E.ID IS NULL AND  M.OS = @OS AND CASE WHEN CHARINDEX('.',M.INDICE) <> 0 THEN CAST(LEFT(M.INDICE,CHARINDEX('.',M.INDICE)-1) AS int) ELSE CAST(M.INDICE AS int) END =  @INDICE
											ORDER BY CAST('/' + REPLACE(M.INDICE, '.', '/') + '/' AS HIERARCHYID)

		
				OPEN EXECUCAO

				FETCH NEXT FROM EXECUCAO INTO @ID, @IDCRIACAO, @IDCRIACAOPAI

				WHILE @@FETCH_STATUS = 0
				BEGIN

					-- ATUALIZA ITENS EXCLUSIVOS QUE JÁ ESTAVAM CADASTRADOS NO EX PARA NÃO TEMOS PROBLEAMAS
					/*
							UPDATE I SET ITEMEXCLUSIVO = CASE WHEN O.CODORDEM IS NULL THEN 0 ELSE CASE WHEN ITEMEXCLUSIVO = 2 THEN 2 ELSE 1 END END
							FROM FLUIG.DBO.ML001004 (NOLOCK) M
								INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS AND I.EXECUCAO = @CONTADOR
								LEFT JOIN KITEMORDEM (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
								LEFT JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI+'%'
							WHERE M.NUMPROCESSO = @NUMPROCESSO 
					*/

						-- INSERE ITENS EXCLUIVOS CORRETAMENTE
						INSERT INTO FLUIG.dbo.Z_CRM_EX001005  (	 ID, companyid, cardid, documentid, version, tableid, TITULOITEM, NIVEL, POSICAO, DESCRICAO, NUMDESENHO, REVISAODESENHO, NUMDBI, REVISAODBI, DESQTDE, TOTALQTDE, BITOLAESP, LARGURAMASSA, 
																 ESPLARGURAROSCA, COMPRIMENTO, MATERIAL, PESO, OBSERVACOES, TIPO, SEQ, masterid, PESOMATERIAL, OS, DATAREVISAO, PESOBRUTO, PESOLIQUIDO, OBSERVACOESDESENHO, PERIMETROCORTE, AREAPINTURA, 
																 OBSPROCESSO, OBSGERAL, QUANTIDADEMATERIAL, TIPODESENHO, POSICAOCOMPLETA, ESPESSURA, BITOLA, LARGURA, MASSALINEAR, DIAMETROEXTERNO, DIAMETROINTERNO, ESPROSCA, POSICAOCOMPLETAANTIGA, 
																 NOVOMATERIAL, MATERIAL_ZOOM, IDMATERIAL, CODIGOPRD,  POSICAOINDICE,  POSICAOESTRUTURA, POSICAODESENHO, AREASECAO, ALTURA, LARGURAMESA, ESPALMA, ESPMESA, INDICE, INDICEANTIGO, IDCRIACAO, 
																 PRODUTORM, IDPRD, EXPANSOR, CODIGOPRDMATERIAL, CODTRFOS, UNDMEDIDA, ORDEM, LARGURAABA, ESPABA, INTEGRADO, DSCTRFOS, SOLICITACAO, PAIDETALHADO, COMPORLISTA, CODTRFITEM, IDTRFITEM, 
																 NOMETRFITEM, CODIGOTAREFADESC, IDPRJOS, DESCOS, DETALHADO, NUMDOCDELP, REVISAODOCDELP, CODCOLIGADA, DIAMETROEXTERNODISCO, DIAMETROINTERNODISCO, CHECKUSINAGEM, CHECKCALDERARIA, CODFILIAL, 
																 CODTRFPAI, EXECINTEGRADAS, IDTRFPAI, NOMETRFPAI, EXECUCOES, PESOUNITARIO, OPSUNITARIAS, QTDEUNCOMP, OP, EXECUCAO, CODTRFEX, IDCRIACAOPAI,ITEMEXCLUSIVO, RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)

							
							SELECT	M.ID, M.companyid, M.cardid, M.documentid, M.version, M.tableid, M.TITULOITEM, 
									ISNULL((   SELECT TOP 1 INDICE
												FROM (
													SELECT INDICE , 1 ORDEM FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) WHERE OS = M.OS AND IDCRIACAO = M.IDCRIACAOPAI AND EXECUCAO = @CONTADOR
													UNION ALL 
													SELECT INDICE , 2 ORDEM FROM FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) WHERE OS = M.OS AND IDCRIACAO = M.IDCRIACAOPAI
											) AS NIVEL ORDER BY ORDEM ), M.NIVEL) NIVEL, 
								M.POSICAO, M.DESCRICAO, M.NUMDESENHO, M.REVISAODESENHO, M.NUMDBI, M.REVISAODBI, M.DESQTDE, 
								M.TOTALQTDE, M.BITOLAESP, M.LARGURAMASSA, M.ESPLARGURAROSCA, M.COMPRIMENTO, M.MATERIAL, M.PESO, M.OBSERVACOES, M.TIPO, M.SEQ, M.masterid, M.PESOMATERIAL, M.OS, M.DATAREVISAO, M.PESOBRUTO, 
								M.PESOLIQUIDO, M.OBSERVACOESDESENHO, M.PERIMETROCORTE, M.AREAPINTURA, M.OBSPROCESSO, M.OBSGERAL, M.QUANTIDADEMATERIAL, M.TIPODESENHO, M.POSICAOCOMPLETA, M.ESPESSURA, M.BITOLA, M.LARGURA, 
								M.MASSALINEAR, M.DIAMETROEXTERNO, M.DIAMETROINTERNO, M.ESPROSCA, M.POSICAOCOMPLETAANTIGA, M.NOVOMATERIAL, M.MATERIAL_ZOOM, M.IDMATERIAL, M.CODIGOPRD, 
								ISNULL((   SELECT MAX(CAST(POSICAOINDICE AS INT))
										   FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK)
										   WHERE OS = M.OS AND IDCRIACAOPAI = M.IDCRIACAOPAI AND EXECUCAO = @CONTADOR ),0) +1 POSICAOINDICE, M.POSICAOESTRUTURA, 
								M.POSICAODESENHO, M.AREASECAO, M.ALTURA, M.LARGURAMESA, M.ESPALMA, M.ESPMESA, ISNULL(( SELECT TOP 1 INDICE
																														FROM (
																															SELECT INDICE , 1 ORDEM FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) WHERE  OS = M.OS AND IDCRIACAO = M.IDCRIACAOPAI AND EXECUCAO = @CONTADOR
																															UNION ALL 
																															SELECT INDICE , 2 ORDEM FROM FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) WHERE  OS = M.OS AND IDCRIACAO = M.IDCRIACAOPAI
																													) AS NIVEL ORDER BY ORDEM )
																														+'.'+
																														CAST(ISNULL((   SELECT MAX(CAST(POSICAOINDICE AS INT))
																																		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK)
																																		WHERE OS = M.OS AND IDCRIACAOPAI = M.IDCRIACAOPAI AND EXECUCAO = @CONTADOR ),0) +1 AS VARCHAR(MAX)),M.INDICE) INDICE, 
								M.INDICEANTIGO, M.IDCRIACAO, M.PRODUTORM, M.IDPRD, M.EXPANSOR, M.CODIGOPRDMATERIAL, M.CODTRFOS, M.UNDMEDIDA, M.ORDEM, M.LARGURAABA, M.ESPABA, M.INTEGRADO, M.DSCTRFOS, M.SOLICITACAO, NULL PAIDETALHADO, 
								M.COMPORLISTA, M.CODTRFITEM, M.IDTRFITEM, M.NOMETRFITEM, M.CODIGOTAREFADESC, M.IDPRJOS, M.DESCOS, NULL DETALHADO, M.NUMDOCDELP, M.REVISAODOCDELP, M.CODCOLIGADA, M.DIAMETROEXTERNODISCO, M.DIAMETROINTERNODISCO, 
								M.CHECKUSINAGEM, M.CHECKCALDERARIA, M.CODFILIAL, M.CODTRFPAI, M.EXECINTEGRADAS, M.IDTRFPAI, M.NOMETRFPAI, M.EXECUCOES, M.PESOUNITARIO, M.OPSUNITARIAS, M.QTDEUNCOMP, NULL, @CONTADOR, NULL , M.IDCRIACAOPAI, 0,
								M.RECCREATEDBY, M.RECCREATEDON, M.RECMODIFIEDBY, M.RECMODIFIEDON
						FROM FLUIG.DBO.Z_CRM_ML001005 M (NOLOCK)
						WHERE  M.OS = @OS AND IDCRIACAO = @IDCRIACAO
		
						FETCH NEXT FROM EXECUCAO INTO @ID, @IDCRIACAO, @IDCRIACAOPAI

				END

				CLOSE EXECUCAO
				DEALLOCATE EXECUCAO


							   
			-- ############################################################################################################################################
			--                           FIM DA INCLUSÃO DO EX001005
			-- ############################################################################################################################################
				UPDATE FLUIG.dbo.Z_CRM_EX001005 SET CODTRFPAI = @CODTRFPAI
				WHERE OS = @OS AND EXECUCAO = @CONTADOR AND  CASE WHEN CHARINDEX('.',INDICE) <> 0 THEN CAST(LEFT(INDICE,CHARINDEX('.',INDICE)-1) AS int) ELSE CAST(INDICE AS int) END =  @INDICE;

		
				INSERT INTO FLUIG.dbo.Z_CRM_EX001021  
				SELECT  M.ID,M.companyid,M.cardid,M.documentid,M.version,M.tableid,M.PRIORIDADE,M.IDCRIACAOPROCESSO,M.CODATIVIDADE,M.OSPROCESSO,M.IDPROCESSO,M.DESCATIVIDADE,
						M.HABILIDADEREQUERIDA,M.CODHABILIDADE,M.CODPOSTO,M.DESCPOSTO,M.FILA,M.CONFIGURACAO,M.PROCESSAMENTO,M.DESAGREGACAO,M.ESPERA,M.MOVIMENTACAO,M.MINUTOSGASTOS,
						M.DESCPROCESSO,M.DOCAPOIOATV1,M.DOCAPOIOATV2,M.DOCAPOIOATV3,M.DOCAPOIOATV4,M.masterid,M.SOLICITACAOPROCESSO,M.FORNPARA,M.INTEGRADOPROCESSO,I.EXECUCAO , NULL,
						M.RECCREATEDBY,M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
				FROM  FLUIG.dbo.Z_CRM_ML001021 M (NOLOCK)
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK)  ON I.OS = M.OSPROCESSO AND M.IDCRIACAOPROCESSO = I.IDCRIACAO
					LEFT JOIN FLUIG.dbo.Z_CRM_EX001021 E (NOLOCK) ON M.IDCRIACAOPROCESSO = E.IDCRIACAOPROCESSO AND M.CODATIVIDADE = E.CODATIVIDADE AND I.OS = E.OSPROCESSO AND E.EXECUCAO = I.EXECUCAO
				WHERE E.ID IS NULL AND I.ITEMEXCLUSIVO = 0 AND M.OSPROCESSO = @OS AND  CASE WHEN CHARINDEX('.',I.INDICE) <> 0 THEN CAST(LEFT(I.INDICE,CHARINDEX('.',I.INDICE)-1) AS int) ELSE CAST(I.INDICE AS int) END =  @INDICE AND I.EXECUCAO = @CONTADOR


				INSERT INTO FLUIG.dbo.Z_CRM_EX001019 
				SELECT M.ID,M.companyid,M.cardid,M.documentid,M.version,M.tableid,M.PRODUTOCOMPONENTES,M.IDPRDCOMPONENTES,M.CODIGOPRDCOMPONENTES,M.CODUNDCOMPONENTES,
						M.IDCRIACAOCOMPONENTES,M.QTDEUNCOMPONENTES,M.QTDETOTALCOMPONENTES,M.SUBSTITUTOCOMPONENTES,M.INSUMOCOMPONENTES,M.LISTACOMPONENTES,M.masterid,
						M.IDCOMPONENTES,M.OSCOMPONENTES,M.SOLICITACAOCOMPONENTES,M.INTEGRADOCOMPONENTES,M.PRIORIDADEATVCOMPONENTES, I.EXECUCAO, NULL,M.RECCREATEDBY,
						M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
				FROM  FLUIG.dbo.Z_CRM_ML001019 M  (NOLOCK)
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK) ON I.OS = M.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = I.IDCRIACAO
					INNER JOIN FLUIG.dbo.Z_CRM_EX001021 P (NOLOCK) ON  I.OS = P.OSPROCESSO AND P.IDCRIACAOPROCESSO = I.IDCRIACAO AND M.PRIORIDADEATVCOMPONENTES = P.PRIORIDADE AND P.EXECUCAO = I.EXECUCAO
					LEFT JOIN FLUIG.dbo.Z_CRM_EX001019 E (NOLOCK) ON M.OSCOMPONENTES = E.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = E.IDCRIACAOCOMPONENTES AND M.PRIORIDADEATVCOMPONENTES = E.PRIORIDADEATVCOMPONENTES AND M.IDPRDCOMPONENTES = E.IDPRDCOMPONENTES  AND E.EXECUCAO = P.EXECUCAO
				WHERE E.ID IS NULL AND I.ITEMEXCLUSIVO = 0 AND M.OSCOMPONENTES = @OS AND  CASE WHEN CHARINDEX('.',I.INDICE) <> 0 THEN CAST(LEFT(I.INDICE,CHARINDEX('.',I.INDICE)-1) AS int) ELSE CAST(I.INDICE AS int) END =  @INDICE AND I.EXECUCAO = @CONTADOR
		
				INSERT INTO FLUIG.dbo.Z_CRM_EX001019 
				SELECT M.ID,M.companyid,M.cardid,M.documentid,M.version,M.tableid,M.PRODUTOCOMPONENTES,M.IDPRDCOMPONENTES,M.CODIGOPRDCOMPONENTES,M.CODUNDCOMPONENTES,
						M.IDCRIACAOCOMPONENTES,M.QTDEUNCOMPONENTES,M.QTDETOTALCOMPONENTES,M.SUBSTITUTOCOMPONENTES,M.INSUMOCOMPONENTES,M.LISTACOMPONENTES,M.masterid,
						M.IDCOMPONENTES,M.OSCOMPONENTES,M.SOLICITACAOCOMPONENTES,M.INTEGRADOCOMPONENTES,M.PRIORIDADEATVCOMPONENTES, I.EXECUCAO, NULL,M.RECCREATEDBY,
						M.RECCREATEDON,M.RECMODIFIEDBY,M.RECMODIFIEDON
				FROM  FLUIG.dbo.Z_CRM_ML001019 M  (NOLOCK)
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 I (NOLOCK) ON I.OS = M.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = I.IDCRIACAO
					LEFT JOIN FLUIG.dbo.Z_CRM_EX001021 P (NOLOCK) ON  I.OS = P.OSPROCESSO AND P.IDCRIACAOPROCESSO = I.IDCRIACAO AND M.PRIORIDADEATVCOMPONENTES = P.PRIORIDADE AND P.EXECUCAO = I.EXECUCAO
					LEFT JOIN FLUIG.dbo.Z_CRM_EX001019 E (NOLOCK) ON M.OSCOMPONENTES = E.OSCOMPONENTES AND M.IDCRIACAOCOMPONENTES = E.IDCRIACAOCOMPONENTES AND M.PRIORIDADEATVCOMPONENTES = E.PRIORIDADEATVCOMPONENTES AND M.IDPRDCOMPONENTES = E.IDPRDCOMPONENTES  AND E.EXECUCAO = I.EXECUCAO
				WHERE P.ID IS NULL AND  E.ID IS NULL AND I.ITEMEXCLUSIVO = 0 AND M.OSCOMPONENTES = @OS AND  CASE WHEN CHARINDEX('.',I.INDICE) <> 0 THEN CAST(LEFT(I.INDICE,CHARINDEX('.',I.INDICE)-1) AS int) ELSE CAST(I.INDICE AS int) END =  @INDICE AND I.EXECUCAO = @CONTADOR
			
		
			SET @CONTADOR += 1;

		END;

		FETCH NEXT FROM ORDENS INTO @NUMPROCESSO_ORIGINAL, @QTDORDEM, @CODCOLIGADA, @CODFILIAL, @IDPRJ, @INDICE, @OS, @CODTRFPAI;

		
	END;

	CLOSE ORDENS;
	DEALLOCATE ORDENS;

	-- NÚMERO DA EXECUÇÃO NA ORDEM DE PRODUÇÃO

	INSERT INTO KORDEMCOMPL (CODCOLIGADA, CODORDEM, CODFILIAL, NUMEXEC, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT K.CODCOLIGADA, K.CODORDEM, K.CODFILIAL, CAST( SUBSTRING (K.RESPONSAVEL, CHARINDEX('-',K.RESPONSAVEL)+1, CHARINDEX('/',K.RESPONSAVEL)-CHARINDEX('-',K.RESPONSAVEL) -1) AS int), K.RECCREATEDBY, K.RECCREATEDON, K.RECMODIFIEDBY, K.RECMODIFIEDON
		FROM KORDEM (NOLOCK) K
			LEFT JOIN KORDEMCOMPL (NOLOCK) C ON K.CODCOLIGADA = C.CODCOLIGADA AND K.CODFILIAL = C.CODFILIAL AND K.CODORDEM = C.CODORDEM
		WHERE C.CODORDEM IS NULL
		AND CHARINDEX(';',K.RESPONSAVEL) <> 0

 -- FIM DA CRIAÇÃO DAS ORDENS
 
 --########################################## ATUALIZAÇÃO DO CRONOGRAMA DO SOLUM ############################################
 
 		SELECT T.CODCOLIGADA , T.IDPRJ, LEFT(T.CODTRF,4) CODTRFPAI, T.CODTRFAUX, T.NOME, T.DESCRICAO, T.DATAINICIOCALC, T.DATAINICIOPLAN , T.DATAINICIOREAL ,
		T.DATAFIMCALC, T.DATAFIMPLAN , T.DATAFIMREAL,
		T.DURACAOCALC, T.DURACAOPLAN, T.DURACAOREAL,
		T.PERCCONCLUIDO,
		C.CELULA, C.TAG  , C.STATUS_FABRICACAO INTO #Z_CRM_LOGPRJ
		FROM MTAREFA T
			INNER JOIN MTRFCOMPL C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF
		WHERE T.CODCOLIGADA = @CODCOLIGADA AND T.IDPRJ = @IDPRJ AND ISNULL(T.CODTRFAUX,'') <> '' --AND T.CODTRF LIKE @CODTRFPAI+'%'
		ORDER BY T.CODTRF;
			   		 	

	 -- SALVAMOS AS TAREFAS SUMARIZADORAS

		SELECT CODCOLIGADA, IDPRJ, LEFT(CODTRFAUX, CHARINDEX('-',CODTRFAUX)-1) CODORDEM INTO #Z_CRM_TRFSUM
		FROM MTAREFA  (NOLOCK)
		WHERE CODCOLIGADA = @CODCOLIGADA AND IDPRJ = @IDPRJ AND CODTRFAUX LIKE '%-SUM' AND QUANTIDADE IS NULL;


-- RECRIANDO O CRONOGRAMA DO SOLUM

		DECLARE @IDTRF INT, @QTDREPETICOES INT

		DECLARE SOLUM CURSOR FOR SELECT ISNULL(I.EXECINTEGRADAS,0),  T.IDTRF
								 FROM FLUIG.DBO.ML001004 O 
									INNER JOIN FLUIG.dbo.Z_CRM_ML001005 I on O.NUM_OS = I.OS
									INNER JOIN MTAREFA T ON T.CODCOLIGADA = I.CODCOLIGADA AND T.IDPRJ = O.IDPRJ_OS AND I.CODTRFPAI = T.CODTRF COLLATE Latin1_General_CI_AS
								 WHERE	T.CODCOLIGADA = @CODCOLIGADA
								 AND		T.IDPRJ = @IDPRJ
								 AND		I.NIVEL = ''
								 AND		T.TIPOPLANILHA = 0
								 --AND		CASE WHEN CHARINDEX('.',I.INDICE) <> 0 THEN CAST(LEFT(I.INDICE,CHARINDEX('.',I.INDICE)-1) AS int) ELSE CAST(I.INDICE AS int) END =  @INDICE
								 AND		ISNULL(I.EXECINTEGRADAS,0) <> 0;


		OPEN SOLUM;

		FETCH NEXT FROM SOLUM INTO @QTDREPETICOES , @IDTRF;

		WHILE @@FETCH_STATUS = 0
		BEGIN

		EXEC SP_CRM_INTEGRACAOREPETICAO  @CODCOLIGADA , @IDPRJ , @IDTRF , 0 , 'S' ;
		
		FETCH NEXT FROM SOLUM INTO @QTDREPETICOES , @IDTRF;

		END;

		CLOSE SOLUM;
		DEALLOCATE SOLUM;


 -- RESTAURANDO INFORMAÇÕES DO PROJETOS

 		-- RECRIANDO AS TAREFAS SUMARIZADORAS
		DECLARE @IDTRF_SUM INT;

		 DECLARE SUMARIZACAO CURSOR FOR  SELECT IDTRF 
										  FROM #Z_CRM_TRFSUM Z
											INNER JOIN MTAREFA (NOLOCK) M ON Z.CODCOLIGADA = M.CODCOLIGADA 
																		 AND Z.IDPRJ = M.IDPRJ 
																		 AND Z.CODORDEM = M.CODTRFAUX;

		OPEN SUMARIZACAO;

		FETCH NEXT FROM SUMARIZACAO INTO @IDTRF_SUM;

		WHILE @@FETCH_STATUS = 0
		BEGIN

			EXEC SP_CRM_CRIATRFSUMARIZADORA @CODCOLIGADA , @IDPRJ , @IDTRF_SUM;

			FETCH NEXT FROM SUMARIZACAO INTO @IDTRF_SUM;

		END;

		CLOSE SUMARIZACAO;
		DEALLOCATE SUMARIZACAO;

		-- RECRIANDO AS ORDENS DE RETRABALHO

	DECLARE @CODTRF_NEW VARCHAR(50), @PROCESSO INT, @CODTRF VARCHAR(MAX) ,@IDPAI INT;

	DECLARE FLUIG26 CURSOR FOR SELECT M.NUMPROCESSO
								FROM FLUIG.dbo.ML001026 M (NOLOCK)
									INNER JOIN FLUIG.DBO.ML001004 I (NOLOCK) ON M.NUM_OS = I.NUM_OS
								WHERE I.NUM_OS = @OS
 
	OPEN FLUIG26;

	FETCH NEXT FROM FLUIG26 INTO @PROCESSO;

	WHILE @@FETCH_STATUS = 0
	BEGIN

		DECLARE RETRABALHO CURSOR FOR 		SELECT   P.IDPRJ,  T.IDPAI,  T.CODTRF,  LEFT(T.CODTRF,LEN(T.CODTRF)-3) + RIGHT(REPLICATE('0',3)+CAST(CAST(RIGHT(T.CODTRF,3) AS int)+1 AS varchar(4)),3)
											FROM FLUIG.dbo.ML001026 M (NOLOCK)
												INNER JOIN MPRJ P (NOLOCK) ON P.CODPRJ = M.NUM_OS COLLATE Latin1_General_CI_AS AND P.POSICAO IN (1,4)
												INNER JOIN MTRF T (NOLOCK) ON P.CODCOLIGADA = T.CODCOLIGADA AND P.IDPRJ = T.IDPRJ AND T.CODTRFAUX = M.CODORDEM COLLATE Latin1_General_CI_AS
											WHERE M.NUMPROCESSO = @PROCESSO
											AND	  M.EXCLUSIVO1 = 'FINALIZAR';

		OPEN RETRABALHO;

		FETCH NEXT FROM RETRABALHO INTO @IDPRJ, @IDPAI, @CODTRF, @CODTRF_NEW;

		WHILE @@FETCH_STATUS = 0
		BEGIN

		UPDATE MTRF SET CODTRF = LEFT(CODTRF,LEN(CODTRF)-3) + RIGHT(REPLICATE('0',3)+CAST(CAST(RIGHT(CODTRF,3) AS int)+1 AS varchar(4)),3)
		WHERE IDPRJ = @IDPRJ AND IDPAI = @IDPAI AND CODTRF > @CODTRF
	

		INSERT INTO MTAREFA (CODCOLIGADA, IDPRJ, IDTRF, CODTRF, CODTRFAUX, NOME, DESCRICAO, IDPAI, QUANTIDADE, CODUND, ATIVA, VALOR, BLOQUEADA, SERVICO, BDI, UTILIZARVALOR, INDIRETO, IDDISCIPLINA, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT O.CODCOLIGADA, @IDPRJ, ROW_NUMBER() OVER (ORDER BY O.CODORDEM DESC)+ISNULL((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'M' AND	CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))),0),
				@CODTRF_NEW, O.CODORDEM, LEFT('RETRABALHO: ' + I.F_DESCRICAO+ ' - POS. '+I.F_POSICAODESENHO,90), 'RETRABALHO: ' + I.F_DESCRICAO+ ' - POS. '+I.F_POSICAODESENHO , @IDPAI, 
					((SELECT SUM( CAST(ISNULL(A.VIEWMINUTOSGASTOS,0) AS FLOAT)) FROM FLUIG.DBO.ML001028 A (NOLOCK) WHERE I.DOCUMENTID = A.DOCUMENTID AND I.VERSION = A.VERSION)*CAST(I.F_DESQTDE AS FLOAT))/60.00, 
				'H', 1, 0, 0, 1,1,1,1, @IDDISCIPLINA, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001026 (NOLOCK) I
			INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.F_CODIGOPRD+';'+I.NUMPROCESSO COLLATE Latin1_General_CI_AS+'- RETRABALHO'
		WHERE I.NUMPROCESSO = @PROCESSO


		UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDTRF) FROM MTAREFA WHERE CODCOLIGADA = 1 AND IDPRJ = @IDPRJ) WHERE CODSISTEMA = 'M' AND CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))


		FETCH NEXT FROM RETRABALHO INTO @IDPRJ, @IDPAI, @CODTRF, @CODTRF_NEW;
		END;

		CLOSE RETRABALHO;
		DEALLOCATE RETRABALHO;

		FETCH NEXT FROM FLUIG26 INTO @PROCESSO;

	END

	CLOSE FLUIG26
	DEALLOCATE FLUIG26

		
-- FIM DA CRIAÇÃO DOS RETRABALHOS
-- CRIA O REGISTRO DA COMPL
		
-- TERMINA DE CRIAR

-- FIM DA RECRICAOÇÃO DO CRONOGRAMA SOLUM
	
			INSERT INTO MTRFCOMPL (CODCOLIGADA, IDPRJ, IDTRF, NUMFLUIG,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT T.CODCOLIGADA, T.IDPRJ, T.IDTRF, @NUMPROCESSO_ORIGINAL,  T.RECCREATEDBY, T.RECCREATEDON, T.RECMODIFIEDBY, T.RECMODIFIEDON
			FROM MTAREFA (NOLOCK) T
				LEFT JOIN MTRFCOMPL (NOLOCK) C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF
			WHERE C.IDPRJ IS NULL
			AND T.IDPRJ = @IDPRJ
			AND		T.CODCOLIGADA = @CODCOLIGADA;
		

			-- RESTAURANDO INFORMAÇÕES DO PROJETOS

		UPDATE T SET	
				T.NOME = CASE WHEN T.CODTRFAUX LIKE '%-SUM' THEN Z.NOME ELSE CASE WHEN T.CODTRFAUX LIKE 'EXEC%' THEN Z.NOME ELSE T.NOME END END, 
				T.DESCRICAO = CASE WHEN T.CODTRFAUX LIKE '%-SUM' THEN Z.DESCRICAO ELSE CASE WHEN T.CODTRFAUX LIKE 'EXEC%' THEN Z.DESCRICAO ELSE T.DESCRICAO END END, 
				T.DATAINICIOCALC = Z.DATAINICIOCALC, T.DATAINICIOPLAN = Z.DATAINICIOPLAN , T.DATAINICIOREAL = Z.DATAINICIOREAL ,
				T.DATAFIMCALC = Z.DATAFIMCALC, T.DATAFIMPLAN = Z.DATAFIMPLAN , T.DATAFIMREAL = Z.DATAFIMREAL,
				T.DURACAOCALC = Z.DURACAOCALC, T.DURACAOPLAN = Z.DURACAOPLAN, T.DURACAOREAL = Z.DURACAOREAL,
				T.PERCCONCLUIDO = Z.PERCCONCLUIDO
		FROM #Z_CRM_LOGPRJ  Z
			INNER JOIN MTAREFA (NOLOCK) T ON T.CODCOLIGADA = Z.CODCOLIGADA AND T.IDPRJ = Z.IDPRJ AND T.CODTRFAUX = Z.CODTRFAUX 


		UPDATE C SET
				C.CELULA = Z.CELULA, C.TAG = Z.TAG, C.STATUS_FABRICACAO = Z.STATUS_FABRICACAO
		FROM #Z_CRM_LOGPRJ Z
			INNER JOIN MTAREFA (NOLOCK) T ON T.CODCOLIGADA = Z.CODCOLIGADA AND T.IDPRJ = Z.IDPRJ AND T.CODTRFAUX = Z.CODTRFAUX 
			INNER JOIN MTRFCOMPL (NOLOCK) C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF

		-- FIM DAS RESTAURAÇÕES

 -- FIM DA ATUALIZAÇÃO DO CRONOGRAMA DO SOLUM

 -- TRANSFORMANDO ITENS DAS EXE EM EXCLUSIVOS
 
	UPDATE FLUIG.dbo.Z_CRM_EX001005 SET ITEMEXCLUSIVO = 1
	WHERE OS = @OS AND ITEMEXCLUSIVO = 0;


 -- LIMPA A TABELA DE ITENS EXCLUIDOS
  DELETE FLUIG.dbo.Z_CRM_ITENSEXCLUIDOS WHERE OS = @OS;

END;


