USE [CORPORE_DEV]
GO
/****** Object:  StoredProcedure [dbo].[SP_CRM_EDICAOEXECUCAO]    Script Date: 28/10/2023 16:46:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_CRM_EDICAOEXECUCAO] @NUMPROCESSO INT, @CODTRFPAI VARCHAR(30) , @EXECUCAO INT
AS
BEGIN
	print 'teste'
	
	DECLARE @CODCOLIGADA INT, @CODFILIAL INT, @IDPRJ INT, @NUM_OS VARCHAR(MAX), @QTDORDEM INT ;

	-- INICIO DAS ALTERAÇÕES

	SELECT @IDPRJ = CAST(IDPRJ_OS AS int), @NUM_OS = NUM_OS FROM FLUIG.DBO.ML001081 (NOLOCK) WHERE  NUMPROCESSO = @NUMPROCESSO AND EXCLUSIVO1 = 'FINALIZAR';

	SELECT @QTDORDEM = CAST(ISNULL(I.EXECINTEGRADAS,0) AS int), @CODCOLIGADA = I.CODCOLIGADA , @CODFILIAL = I.CODFILIAL
	FROM FLUIG.dbo.Z_CRM_ML001005 I  (NOLOCK)
	WHERE  @NUM_OS = I.OS AND @CODTRFPAI = I.CODTRFPAI AND I.NIVEL = '';
	
-- VERIFICA SE PRODUTROS EXCLUIDOS QUE ESTAVAM NA Z_CRM_ITENSEXCLUIDO VOLTARAM PARA ESTRUTURA

	DELETE E 
	FROM FLUIG.DBO.Z_CRM_EXITENSEXCLUIDOS E
	INNER JOIN FLUIG.dbo.Z_CRM_EX001005 M ON E.OS = M.OS AND E.IDPRD = M.IDPRD AND E.EXECUCAO = M.EXECUCAO
	WHERE M.ITEMEXCLUSIVO <> 2 AND E.OS = @NUM_OS AND E.EXECUCAO = @EXECUCAO

-- INICIA COM AS EXCLUSÕES DAS EDIÇÕES
	

	UPDATE O SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM FLUIG.DBO.Z_CRM_EXITENSEXCLUIDOS Z 
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 I ON Z.OS = I.OS AND I.IDCRIACAO = Z.IDCRIACAO AND I.EXECUCAO = Z.EXECUCAO
		INNER JOIN KITEMORDEM O ON I.CODCOLIGADA = O.CODCOLIGADA AND I.CODFILIAL = O.CODFILIAL AND O.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN KORDEMCOMPL C ON C.CODCOLIGADA = O.CODCOLIGADA AND C.CODFILIAL = O.CODFILIAL AND C.CODORDEM = O.CODORDEM AND I.EXECUCAO = C.NUMEXEC
	WHERE I.OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO ; 
		
		

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM FLUIG.DBO.Z_CRM_EXITENSEXCLUIDOS Z 
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 I ON Z.OS = I.OS AND I.IDCRIACAO = Z.IDCRIACAO AND I.EXECUCAO = Z.EXECUCAO
		INNER JOIN KITEMORDEM O ON I.CODCOLIGADA = O.CODCOLIGADA AND I.CODFILIAL = O.CODFILIAL AND O.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN KORDEMCOMPL C ON C.CODCOLIGADA = O.CODCOLIGADA AND C.CODFILIAL = O.CODFILIAL AND C.CODORDEM = O.CODORDEM AND I.EXECUCAO = C.NUMEXEC
		INNER JOIN KATVORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
	WHERE I.OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO ; 

	

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM FLUIG.DBO.Z_CRM_EXITENSEXCLUIDOS Z 
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 I ON Z.OS = I.OS AND I.IDCRIACAO = Z.IDCRIACAO AND I.EXECUCAO = Z.EXECUCAO
		INNER JOIN KITEMORDEM O ON I.CODCOLIGADA = O.CODCOLIGADA AND I.CODFILIAL = O.CODFILIAL AND O.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN KORDEMCOMPL C ON C.CODCOLIGADA = O.CODCOLIGADA AND C.CODFILIAL = O.CODFILIAL AND C.CODORDEM = O.CODORDEM AND I.EXECUCAO = C.NUMEXEC
		INNER JOIN KORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
	WHERE I.OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO ; 


	-- ATUALZIAÇÃO DOS PRODUTOS

		
		UPDATE P SET  P.INVENTARIOFISCAL = 1, P.TIPOTRIBUTACAO = 0, P.CODCOLCONTA = @CODCOLIGADA,
					P.SITUACAOMERCADORIA = CASE LEFT(I.CODIGOPRD,2) 
													WHEN '04' THEN '04' 
													WHEN '03' THEN '03'
													ELSE '02'  END, 
					P.CODCONTA = CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN '1.1.3.01.0003' ELSE  '1.1.3.01.0004' END 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
			INNER JOIN TPRDFISCAL (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA AND I.IDPRD = P.IDPRD
		WHERE @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI;

		-- ALTERAÇÃO PARA NÃO ALTERAR A DESCRIÇÃO DO PRODUTO 04.024 - RAFAEL.GRANJA - 20/04/2023

		-- ATUALIZA DESCRIÇÃO DO 04.024
		--UPDATE P SET P.DESCRICAO = CASE WHEN LEFT(P.CODIGOPRD,2) = '04' THEN ISNULL(I.DESCRICAO,'') ELSE ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,'') END, 
		--			 P.NOMEFANTASIA = CASE WHEN LEFT(P.CODIGOPRD,2) = '04' THEN ISNULL(I.DESCRICAO,'') ELSE LEFT(ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),120) END
		--FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
		--	INNER JOIN TPRODUTO (NOLOCK) P ON P.CODCOLPRD = 1 AND I.IDPRD = P.IDPRD
		--WHERE @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI;

		-- NÃO ATUALIZA DESCRIÇÃO DO 04.024
		UPDATE P SET P.DESCRICAO = ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''), 
					 P.NOMEFANTASIA = LEFT(ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),120)
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN TPRODUTO (NOLOCK) P ON P.CODCOLPRD = 1 AND I.IDPRD = P.IDPRD
		WHERE @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND LEFT(P.CODIGOPRD,2)!='04';

		
		UPDATE P SET P.NUMNOFABRIC = I.CODIGOPRD
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN TPRODUTODEF (NOLOCK) P ON P.CODCOLIGADA = 1 AND I.IDPRD = P.IDPRD
		WHERE @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI;

		
		-- ###### INCIADO INTEGRACAO COM O FACTOR ######

		-- INCLUSÃO DA ESTRUTURA
	
		-- COLOCADO A ML005 PARA SÓ INCLUIR EXTRUTURA CASO SEJA CASTRADO ITEM NOVO NA EXECUCAO
		INSERT INTO KESTRUTURA (CODCOLIGADA, CODESTRUTURA, CODTIPO, IDPRODUTO, QTDLOTE, STATUSESTR, CODCCUSTO, IDFASE, FASEVALIDADA, CODIGOULTALTERACAO, VALIDACAOSOLICITADA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA, I.CODIGOPRD, CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN 'A' ELSE 'S' END, I.IDPRD, I.DESQTDE*10000, 1, I.OS, 1, 1, 0, 0, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
			LEFT JOIN KESTRUTURA E (NOLOCK) ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE P.ID IS NULL AND E.CODESTRUTURA IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO )
		ORDER BY I.NIVEL, I.INDICE;

		INSERT INTO KLINHAEST (CODCOLIGADA, CODLINHA, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA, '001', I.CODIGOPRD, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
			LEFT JOIN KLINHAEST E (NOLOCK) ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE  P.ID IS NULL AND   E.CODESTRUTURA IS NULL AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
		ORDER BY I.NIVEL, I.INDICE;

		INSERT INTO KESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODFILIAL, ELABORADOR2, ELABORADOR3, ELABORADOR, CAMDESENHO, NUMREVISAO, POSICAO, BITOLA, LARGURA, COMPRIMENTO, PESOBRUTO, PESOLIQUIDO, ESPECIFICACAOROSCA , RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT						 I.CODCOLIGADA, I.CODIGOPRD, I.CODFILIAL, NULL ELABORADOR2, NULL ELABORADOR3, NULL ELABORADOR, 
								CASE WHEN I.NUMDESENHO = '' THEN NULL ELSE I.NUMDESENHO END, 
								CASE WHEN I.REVISAODESENHO = '' THEN NULL ELSE I.REVISAODESENHO END, 
								CASE WHEN I.POSICAODESENHO = '' THEN NULL ELSE I.POSICAODESENHO END, 
								CAST( CASE WHEN I.BITOLA = '' OR I.BITOLA = 'null' THEN NULL ELSE REPLACE(I.BITOLA,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.LARGURA = '' OR I.LARGURA = 'null' THEN NULL ELSE REPLACE(I.LARGURA,',','.') END AS FLOAT),
								CAST( CASE WHEN I.COMPRIMENTO = '' OR I.COMPRIMENTO = 'null' THEN NULL ELSE REPLACE(I.COMPRIMENTO,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.PESOBRUTO = '' OR I.PESOBRUTO = 'null' THEN NULL ELSE REPLACE(I.PESOBRUTO,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.PESOLIQUIDO = '' OR I.PESOLIQUIDO = 'null' THEN NULL ELSE REPLACE(I.PESOLIQUIDO,',','.') END AS FLOAT), 
								CASE WHEN I.ESPROSCA = '' OR I.ESPROSCA = 'null' THEN NULL ELSE I.ESPROSCA END, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
			LEFT JOIN KESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE  P.ID IS NULL AND  K.CODESTRUTURA IS NULL
		AND		 I.ITEMEXCLUSIVO <> 2 AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
		ORDER BY I.NIVEL, I.INDICE;


		PRINT 'ATIVIDADES'		
		INSERT INTO KATVESTRUTURA
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, 1 HORAS, MIN( CAST(C.PRIORIDADE AS INT) ) ,
			SUM(	CAST( CASE WHEN C.FILA = '' THEN NULL ELSE REPLACE(C.FILA,',','.') END AS FLOAT) ), 
			SUM(	CAST( CASE WHEN C.CONFIGURACAO = '' THEN NULL ELSE REPLACE(C.CONFIGURACAO,',','.') END AS FLOAT) ), 
			SUM(	CAST( CASE WHEN C.PROCESSAMENTO = '' THEN NULL ELSE REPLACE(C.PROCESSAMENTO,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.DESAGREGACAO = '' THEN NULL ELSE REPLACE(C.DESAGREGACAO,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.ESPERA = '' THEN NULL ELSE REPLACE(C.ESPERA,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.MOVIMENTACAO = '' THEN NULL ELSE REPLACE(C.MOVIMENTACAO,',','.') END AS FLOAT)),
				1,0,'P',0,NULL,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
				LEFT JOIN KATVESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE  P.ID IS NULL AND  K.CODATIVIDADE IS NULL
			AND		 @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE,I.CODFILIAL;
		
		PRINT 'FIM ATIVIDADES'	
			-- INCLUSÃO DA ETAPAS AS ATIVIDADES PARA LINHA DE PRODUÇÃO O DISTINCT É PARA NÃO INCLUIR A MESMA ATIVIDADE NA TABELA E DAR ERRO

		INSERT INTO  KETPATIVIDADES 
			SELECT DISTINCT I.CODCOLIGADA,'ETP-GLOBAL',C.CODATIVIDADE,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
				LEFT JOIN KETPATIVIDADES (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE  P.ID IS NULL AND  K.CODATIVIDADE IS NULL
			AND		 @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') 
			GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL

			
			INSERT INTO KATVESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODATIVIDADE,CODFILIAL, DETALHE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL, C.DESCPROCESSO , 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND I.EXECUCAO = C.EXECUCAO
				LEFT JOIN KATVESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI = K.CODATIVIDADE
			WHERE  P.ID IS NULL AND K.CODESTRUTURA IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI ;
	
			
			INSERT INTO KATVESTPOSTO (CODCOLIGADA, CODPOSTO, CODATIVIDADE, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT DISTINCT K.CODCOLIGADA, K.CODPOSTO, C.CODATIVIDADE, I.CODIGOPRD, K.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) PN ON I.OS = PN.OS AND I.IDCRIACAO = PN.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
				INNER JOIN KPOSTO (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODPOSTO = C.CODPOSTO COLLATE SQL_Latin1_General_CP1_CI_AI
				LEFT JOIN KATVESTPOSTO (NOLOCK) P ON P.CODCOLIGADA = K.CODCOLIGADA AND P.CODFILIAL = K.CODFILIAL AND P.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND P.CODPOSTO = K.CODPOSTO
			WHERE  PN.ID IS NULL AND P.CODCOLIGADA IS NULL AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI ;
		
			PRINT 'COMPONENTES'	
			INSERT INTO KCOMPONENTE (CODCOLIGADA, CODESTRUTURA, IDPRODUTO, IDAUTOINC, QTDUSADA, CODATIVIDADE, OBRIGASERMATERIAPRIMA, FAZPARTEMODELOBASE, PERMITEEXCLUSAO, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON )

			SELECT  COMPONENTES.CODCOLIGADA, CODIGOPRD, IDPRD, (SELECT MAX(IDAUTOINC) FROM KCOMPONENTE)+ ROW_NUMBER () OVER (ORDER BY IDPRD), COMPONENTES.QTD* 10000,
						ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
								) ATIVIDADE,
					1, 0, 0, COMPONENTES.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM (
				SELECT  I.CODIGOPRD, E.IDPRD,  CAST(E.DESQTDE AS float) QTD, I.NIVEL, I.INDICE, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) E ON I.OS = E.OS AND I.INDICE = E.NIVEL  AND E.EXECUCAO = I.EXECUCAO
				WHERE  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0 AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO )
		
				UNION ALL
		
				SELECT I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO 
				FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND   @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI 
			
				UNION ALL

					-- CODIGOS NÃO MANUFATURADO
				SELECT P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT)  QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO
				FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) P ON I.OS = P.OS AND I.NIVEL = P.INDICE  AND P.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND   @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO = 'NAOMANUFATURADO' 


			
			) AS COMPONENTES
			LEFT JOIN KCOMPONENTE (NOLOCK) C ON COMPONENTES.CODCOLIGADA = C.CODCOLIGADA 
											AND COMPONENTES.CODFILIAL = C.CODFILIAL 
											AND COMPONENTES.CODIGOPRD = C.CODESTRUTURA COLLATE Latin1_General_CI_AS 
											AND COMPONENTES.IDPRD = C.IDPRODUTO
											AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
								) = C.CODATIVIDADE
			WHERE C.IDPRODUTO IS NULL AND  IDPRD <> '' 
			AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			
			ORDER BY NIVEL, INDICE;

			PRINT ' FIM COMPONENTES'

			-- INSERE OS PRODUTOS SUBSTITUTOS
		
			INSERT INTO  KCOMPSUBSTITUTO
			SELECT   K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, NULL, NULL, 0,  K.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) A ON I.OS = A.OSPROCESSO AND I.IDCRIACAO = A.IDCRIACAOPROCESSO AND I.EXECUCAO = A.EXECUCAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO AND A.PRIORIDADE = C.PRIORIDADEATVCOMPONENTES
				INNER JOIN TPRD (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA AND P.CODIGOPRD  COLLATE Latin1_General_CI_AS = C.SUBSTITUTOCOMPONENTES
				INNER JOIN KCOMPONENTE (NOLOCK) K ON  P.IDPRD = K.IDPRODUTO 	AND P.CODCOLIGADA = K.CODCOLIGADA AND K.CODESTRUTURA COLLATE Latin1_General_CI_AS = I.CODIGOPRD AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE COLLATE Latin1_General_CI_AS = A.CODATIVIDADE
				INNER JOIN KESTRUTURA (NOLOCK) E ON K.CODCOLIGADA = E.CODCOLIGADA AND K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA AND E.CODCCUSTO COLLATE Latin1_General_CI_AS = I.OS AND E.RECCREATEDBY = 'fluig'
				LEFT JOIN KCOMPSUBSTITUTO (NOLOCK) S ON S.CODCOLIGADA = K.CODCOLIGADA AND S.CODFILIAL = K.CODFILIAL AND S.CODESTRUTURA = K.CODESTRUTURA AND S.CODATIVIDADE = K.CODATIVIDADE AND S.IDAUTOINC = K.IDAUTOINC AND S.IDPRDORIGEM = P.IDPRD AND S.IDPRD = C.IDPRDCOMPONENTES

			WHERE S.CODCOLIGADA IS NULL AND E.STATUSESTR = 1 AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> ''
			ORDER BY NIVEL, INDICE;

	UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM (NOLOCK) WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	
	-- GERANDO ORDENS E CRONOGRAMA
	
			INSERT INTO KORDEM (CODCOLIGADA, CODCCUSTO,  CODORDEM, DSCORDEM, RESPONSAVEL, DTHRINICIALPREV, STATUS, DTHRFINALPREV, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA, I.OS, RIGHT(REPLICATE('0',5) +CAST( ROW_NUMBER() OVER (ORDER BY I.INDICE) + (SELECT VALAUTOINC FROM GAUTOINC WHERE CODAUTOINC = 'KORDEM-'+CAST(I.CODFILIAL AS VARCHAR(2))) AS varchar(MAX)),5)+'/'+RIGHT(CAST(YEAR(GETDATE()) AS varchar(MAX)),2),
						LEFT(P.DESCRICAO,80), P.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI , GETDATE(), 0, GETDATE(), I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN TPRD (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA  AND I.IDPRD = P.IDPRD
					INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.IDPRODUTO = P.IDPRD AND K.CODESTRUTURA = P.CODIGOPRD				
					LEFT JOIN ( SELECT OI.CODCOLIGADA , OI.CODFILIAL, OI.CODESTRUTURA, O.RESPONSAVEL, O.CODORDEM
								FROM KITEMORDEM (NOLOCK) OI
									INNER JOIN KORDEM (NOLOCK) O ON  O.CODCOLIGADA = OI.CODCOLIGADA AND O.CODFILIAL = OI.CODFILIAL AND O.CODORDEM = OI.CODORDEM
								WHERE CHARINDEX(';',RESPONSAVEL) <> 0 ) ORDEM ON K.CODCOLIGADA = ORDEM.CODCOLIGADA AND K.CODFILIAL = ORDEM.CODFILIAL AND K.CODESTRUTURA = ORDEM.CODESTRUTURA AND ORDEM.RESPONSAVEL = P.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI
			WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND ORDEM.CODORDEM IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND  I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			ORDER BY I.INDICE
		
					

			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM  (NOLOCK) WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	

			INSERT INTO KMODELO
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, 'Base','Modelo Base',I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM   FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN KESTRUTURA E ON E.CODCOLIGADA = I.CODCOLIGADA AND E.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
					LEFT JOIN KMODELO (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
			WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND K.CODESTRUTURA IS NULL
			AND	@NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			ORDER BY I.NIVEL, I.INDICE;
		

			INSERT INTO KITEMORDEM(CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, CODLINHA, STATUS, QTDEPLANEJADA, DTHRINICIALPREV, DTHRFINALPREV, IDITEMORDEM, TIPOAPONTAMENTO, CODFILIAL, CODCCUSTO,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA, O.CODORDEM,
					K.CODESTRUTURA, 'base', '001', 0,CASE WHEN LEFT(K.CODESTRUTURA,2) = '04' THEN 1 ELSE CAST(I.TOTALQTDE AS float) END, GETDATE(), GETDATE(), ROW_NUMBER() OVER (ORDER BY K.CODESTRUTURA)+(SELECT MAX(IDITEMORDEM) FROM KITEMORDEM), 1, I.CODFILIAL, I.OS, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
					INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI
					LEFT JOIN KITEMORDEM (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND K.CODESTRUTURA = OI.CODESTRUTURA AND OI.CODORDEM = O.CODORDEM
			WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND OI.CODORDEM IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			ORDER BY I.INDICE;

		
		-- ATUALIZA AS ITEM ORDENS JÁ CADASTRADAS

		UPDATE  OI SET QTDEPLANEJADA = CASE WHEN LEFT(K.CODESTRUTURA,2) = '04' THEN 1 ELSE CAST(I.TOTALQTDE AS float) END, RECCREATEDBY='fluig',RECCREATEDON= GETDATE(),RECMODIFIEDBY='fluig', RECMODIFIEDON=GETDATE() 
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
			INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
			INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS
			INNER JOIN KITEMORDEM (NOLOCK) OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND K.CODESTRUTURA = OI.CODESTRUTURA AND OI.CODORDEM = O.CODORDEM
		WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  );

		UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	
		INSERT INTO KORDEMCOMPL (CODCOLIGADA, CODORDEM, CODFILIAL, NUMEXEC, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
				SELECT I.CODCOLIGADA, O.CODORDEM, O.CODFILIAL, I.EXECUCAO, 'fluig', GETDATE(),'fluig', GETDATE() 
				FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
					INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS
					LEFT JOIN KORDEMCOMPL (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND OI.CODORDEM = O.CODORDEM
				WHERE  OI.CODORDEM IS NULL AND ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
				ORDER BY I.INDICE;

		
-- CRIAR ORDENS INDIVIDUAIS

			DECLARE @CODESTRUTURA VARCHAR(MAX), @QTDDESENHO INT, @NUMPROCESSO_ORIGINAL INT

			DECLARE INDIVIDUAL CURSOR FOR 	SELECT DISTINCT K.CODESTRUTURA,  CAST(I.TOTALQTDE AS float) , M.NUMPROCESSO
											FROM FLUIG.DBO.ML001004 (NOLOCK) M
												INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
												INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
											WHERE ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
											ORDER BY K.CODESTRUTURA;
			
			
			OPEN INDIVIDUAL;

			FETCH NEXT FROM INDIVIDUAL INTO @CODESTRUTURA, @QTDDESENHO, @NUMPROCESSO_ORIGINAL;

			WHILE @@FETCH_STATUS = 0 
			BEGIN
				DECLARE @INDIVIDUAL INT = 1;
				WHILE @INDIVIDUAL <= @QTDDESENHO
				BEGIN
							
					INSERT INTO KORDEM (CODCOLIGADA, CODCCUSTO,  CODORDEM, DSCORDEM, RESPONSAVEL, DTHRINICIALPREV, STATUS, DTHRFINALPREV, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
					SELECT I.CODCOLIGADA, M.NUM_OS, RIGHT(REPLICATE('0',5) +CAST( ROW_NUMBER() OVER (ORDER BY I.INDICE) + (SELECT VALAUTOINC FROM GAUTOINC WHERE CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))) AS varchar(MAX)),5)+'/'+RIGHT(CAST(YEAR(GETDATE()) AS varchar(MAX)),2),
								LEFT(P.DESCRICAO,80), P.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX)), GETDATE(), 0, GETDATE(), I.CODFILIAL,'fluig', GETDATE(),'fluig',GETDATE()
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
							INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on M.NUM_OS = I.OS
							INNER JOIN TPRD (NOLOCK) P ON P.CODCOLIGADA = i.CODCOLIGADA  AND I.IDPRD = P.IDPRD
							INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.IDPRODUTO = P.IDPRD					
							LEFT JOIN ( SELECT OI.CODCOLIGADA , OI.CODFILIAL, OI.CODESTRUTURA, O.RESPONSAVEL, O.CODORDEM
										FROM KITEMORDEM (NOLOCK) OI
											INNER JOIN KORDEM (NOLOCK) O ON  O.CODCOLIGADA = OI.CODCOLIGADA AND O.CODFILIAL = OI.CODFILIAL AND O.CODORDEM = OI.CODORDEM
										WHERE O.RESPONSAVEL =  OI.CODESTRUTURA+';'+CAST(@NUMPROCESSO_ORIGINAL AS VARCHAR(10))+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX))) ORDEM ON K.CODCOLIGADA = ORDEM.CODCOLIGADA AND K.CODFILIAL = ORDEM.CODFILIAL AND K.CODESTRUTURA = ORDEM.CODESTRUTURA
							LEFT JOIN KORDEM (NOLOCK) Z ON Z.CODCOLIGADA = ORDEM.CODCOLIGADA AND Z.CODFILIAL = ORDEM.CODFILIAL AND Z.CODORDEM = ORDEM.CODORDEM
					WHERE ORDEM.CODORDEM IS NULL AND K.CODESTRUTURA = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
					ORDER BY I.INDICE
		
				
					UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	

					INSERT INTO KMODELO
					SELECT I.CODCOLIGADA,  I.CODIGOPRD, 'Base','Modelo Base',I.CODFILIAL, 'fluig', GETDATE(),'fluig',GETDATE() 
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on M.NUM_OS = I.OS
						LEFT JOIN KMODELO (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
					WHERE I.CODIGOPRD = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND K.CODESTRUTURA IS NULL
					AND	I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
					ORDER BY I.NIVEL, I.INDICE;
			
						
					INSERT INTO KITEMORDEM(CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, CODLINHA, STATUS, QTDEPLANEJADA, DTHRINICIALPREV, DTHRFINALPREV, IDITEMORDEM, TIPOAPONTAMENTO, CODFILIAL, CODCCUSTO,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
					SELECT I.CODCOLIGADA, O.CODORDEM,
							K.CODESTRUTURA, 'base', '001', 0, 1 QTDE_INDIVIDUAL, GETDATE(), GETDATE(), ROW_NUMBER() OVER (ORDER BY K.CODESTRUTURA)+(SELECT MAX(IDITEMORDEM) FROM KITEMORDEM), 1, I.CODFILIAL, M.NUM_OS, 'fluig', GETDATE(),'fluig', GETDATE()
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
						INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
						INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX))
						LEFT JOIN KITEMORDEM (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND K.CODESTRUTURA = OI.CODESTRUTURA AND OI.CODORDEM = O.CODORDEM
					WHERE K.CODESTRUTURA = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND OI.CODORDEM IS NULL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
					ORDER BY I.INDICE;


					INSERT INTO KORDEMCOMPL (CODCOLIGADA, CODORDEM, CODFILIAL, NUMEXEC, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
					SELECT I.CODCOLIGADA, O.CODORDEM, O.CODFILIAL, @EXECUCAO, 'fluig', GETDATE(),'fluig',GETDATE()
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
						INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
						INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX))
						LEFT JOIN KORDEMCOMPL (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND OI.CODORDEM = O.CODORDEM
					WHERE K.CODESTRUTURA = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND OI.CODORDEM IS NULL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
					ORDER BY I.INDICE;

			 
			
				 SET @INDIVIDUAL += 1;
				END;
				
				FETCH NEXT FROM INDIVIDUAL INTO @CODESTRUTURA, @QTDDESENHO, @NUMPROCESSO_ORIGINAL;
			END
			CLOSE INDIVIDUAL;
			DEALLOCATE INDIVIDUAL;
	
	
	DELETE MP
	FROM   FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KATVORDEMMP (NOLOCK) MP ON MP.CODCOLIGADA = O.CODCOLIGADA AND MP.CODFILIAL = O.CODFILIAL AND MP.CODORDEM = O.CODORDEM 
	WHERE ISNULL(O.REPROCESSAMENTO,0) <> 1 AND MP.EFETIVADO = 0 AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI

	PRINT 'DELETA MP ADICIONAIS '+CAST(@@ROWCOUNT AS VARCHAR(MAX));

	DELETE C 
	FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KATVORDEM (NOLOCK) K ON O.CODCOLIGADA = K.CODCOLIGADA AND O.CODORDEM = K.CODORDEM AND O.CODFILIAL = K.CODFILIAL
		INNER JOIN KATVORDEMCOMPL (NOLOCK) C ON C.CODCOLIGADA = K.CODCOLIGADA AND C.CODORDEM = K.CODORDEM AND C.CODFILIAL = K.CODFILIAL AND C.IDATVORDEM = K.IDATVORDEM
	WHERE ISNULL(O.REPROCESSAMENTO,0) <> 1 AND K.STATUS = 0 AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI 
	
	PRINT 'DELETA CAMPO COMPLEMENTARES ADICIONAIS '+CAST(@@ROWCOUNT AS VARCHAR(MAX));

	DELETE K 
	FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KATVORDEM (NOLOCK) K ON O.CODCOLIGADA = K.CODCOLIGADA AND O.CODORDEM = K.CODORDEM AND O.CODFILIAL = K.CODFILIAL
	WHERE ISNULL(O.REPROCESSAMENTO,0) <> 1 AND K.STATUS = 0 AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI 

	PRINT 'DELETA KATVORDEM  ADICIONAIS '+CAST(@@ROWCOUNT AS VARCHAR(MAX));

	INSERT INTO  KATVORDEM (CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, CODATIVIDADE, CODETAPA, CODESTRUTURAFEITA, CODPOSTO, DTHRINICIOPREV, DTHRFINALPREV, QTESTOQUE, QTPREVISTA, QUANTIDADE,PERCENTUAL, STATUS, IDATVORDEM, IDATVDEPEND, TEMPO, DTHORAIDEAL, TIPODELAY, CODMODELOFEITO, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT O.CODCOLIGADA, O.CODORDEM, I.CODESTRUTURA, I.CODMODELO, C.CODATIVIDADE, 'ETP-GLOBAL' , I.CODESTRUTURA, C.CODPOSTO, I.DTHRINICIALPREV, I.DTHRFINALPREV, 0, I.QTDEPLANEJADA, 0, 0, 0,ROW_NUMBER() OVER ( PARTITION BY O.CODCOLIGADA, O.CODORDEM ORDER BY O.CODCOLIGADA, O.CODORDEM, C.PRIORIDADE)+ISNULL((SELECT MAX(IDATVORDEM) FROM KATVORDEM ATV WHERE ATV.CODCOLIGADA = O.CODCOLIGADA AND ATV.CODFILIAL = O.CODFILIAL AND ATV.CODORDEM = O.CODORDEM),0), -1, (ISNULL(C.FILA,0)+ISNULL(C.CONFIGURACAO,0)+ISNULL(CAST(C.PROCESSAMENTO AS INT),0)+ISNULL(C.DESAGREGACAO,0)+ISNULL(C.ESPERA,0)+ISNULL(C.MOVIMENTACAO,0)) * I.QTDEPLANEJADA,I.DTHRFINALPREV, -1, I.CODMODELO, I.CODFILIAL, 'fluig',getdate(),'fluig',getdate() 
	FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I5 
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I5.OS
		INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I5.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I5.IDCRIACAO  AND C.EXECUCAO = I5.EXECUCAO
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I5.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I5.EXECUCAO AS varchar(10))+'/'+I5.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
		LEFT JOIN KATVORDEM (NOLOCK) AO ON AO.CODCOLIGADA = O.CODCOLIGADA AND AO.CODFILIAL = O.CODFILIAL AND AO.CODORDEM = O.CODORDEM AND AO.CODESTRUTURA = I.CODESTRUTURA AND AO.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE AO.CODATIVIDADE IS NULL AND @NUM_OS = I5.OS AND @EXECUCAO = I5.EXECUCAO AND @CODTRFPAI = I5.CODTRFPAI
	ORDER BY O.CODCOLIGADA, O.CODORDEM, C.PRIORIDADE;

	PRINT 'INSERE KATVORDEM  ADICIONAIS'+CAST(@@ROWCOUNT AS VARCHAR(MAX));


	-- ATUALIZA OS TEMPOS (CAMPO TEMPO) DAS ATIVIDADES DAS ORDENS DE PRODUÇÃO (COM STATUS 0,2 E 3) COM BASE NOS TEMPOS (CAMPO PROCESSAMENTO) DA EX0010213
	-- INSERIDO PELO WAGNER NOBRE DIA 22/11/2022

	UPDATE AO SET TEMPO = (AO.QTPREVISTA * C.PROCESSAMENTO) 
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I5 
			INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I5.OS
			INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I5.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I5.IDCRIACAO  AND C.EXECUCAO = I5.EXECUCAO
			INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I5.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I5.EXECUCAO AS varchar(10))+'/'+I5.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
			INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
			INNER JOIN KATVORDEM (NOLOCK) AO ON AO.CODCOLIGADA = O.CODCOLIGADA AND AO.CODFILIAL = O.CODFILIAL AND AO.CODORDEM = O.CODORDEM AND AO.CODESTRUTURA = I.CODESTRUTURA AND AO.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE  I5.OS = @NUM_OS AND I5.CODTRFPAI = @CODTRFPAI AND I5.EXECUCAO = @EXECUCAO AND AO.STATUS IN (0,2,3)


	-- MATERIA PRIMA DAS ATIVIDADES DA ORDENS

	INSERT INTO KATVORDEMMP
		SELECT 
		(SELECT VALAUTOINC 
		FROM GAUTOINC  (NOLOCK)
		WHERE CODAUTOINC = 'IDATVORDEMMATERIAPRIMA' 
		AND CODSISTEMA = 'K' 
		AND CODCOLIGADA = 0) + ROW_NUMBER() OVER (ORDER BY C.CODCOLIGADA) ID, 
	A.CODCOLIGADA, A.CODORDEM, A.CODESTRUTURA, A.CODMODELO, A.IDATVORDEM, A.DTHRINICIOPREV DTAPONTAMENTO, C.IDPRD, NULL NSEQITMGRD, ISNULL(C.QTD,0) * ISNULL(I.QTDEPLANEJADA,0) QTD,
	0 EFETIVADO, NULL IDLOTE, A.CODFILIAL, ISNULL(C.QTD,0), 0 QTFIXA, 
		ISNULL((SELECT SALDOGERALFISICO FROM TPRD (NOLOCK) WHERE CODCOLIGADA = A.CODCOLIGADA AND  IDPRD = C.IDPRD),0) ESTOQUE, 'fluig',GETDATE(), 'fluig', GETDATE(),
	NULL ESTOQUETERCEIRO, NULL CODCOLCFO, NULL CODCFO, NULL CODFILIALMP, NULL CODLOCAL
	FROM (
			SELECT  CODCOLIGADA, CODIGOPRD, IDPRD, QTD,
										ISNULL((SELECT TOP 1 CODATIVIDADE FROM FLUIG.DBO.Z_CRM_EX001021 E21 WHERE E21.OSPROCESSO = COMPONENTES.OS AND E21.IDCRIACAOPROCESSO = COMPONENTES.IDCRIACAO AND E21.EXECUCAO = COMPONENTES.EXECUCAO AND E21.PRIORIDADE = COMPONENTES.PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM FLUIG.DBO.Z_CRM_EX001021 E21 WHERE E21.OSPROCESSO = COMPONENTES.OS AND E21.IDCRIACAOPROCESSO = COMPONENTES.IDCRIACAO AND E21.EXECUCAO = COMPONENTES.EXECUCAO ORDER BY E21.PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM FLUIG.DBO.Z_CRM_EX001021 E21 WHERE E21.OSPROCESSO = COMPONENTES.OS AND E21.IDCRIACAOPROCESSO = COMPONENTES.IDCRIACAO AND E21.EXECUCAO = COMPONENTES.EXECUCAO ORDER BY E21.PRIORIDADE ) END
								) CODATIVIDADE,
					COMPONENTES.CODFILIAL, EXECUCAO, CODTRFPAI, NUMPROCESSO 
			FROM (
				SELECT  I.CODIGOPRD, E.IDPRD,  CAST(E.DESQTDE AS float) QTD, I.NIVEL, I.INDICE, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO, I.OS, I.IDCRIACAO
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) E ON I.OS = E.OS AND I.INDICE = E.NIVEL  AND E.EXECUCAO = I.EXECUCAO
				WHERE E.ITEMEXCLUSIVO <> 2 AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0 
				AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
		
				UNION ALL
		
				SELECT I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO , I.OS, I.IDCRIACAO
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI
			
				UNION ALL

					-- CODIGOS NÃO MANUFATURADO
				SELECT P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT)  QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO, I.OS, P.IDCRIACAO
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) P ON I.OS = P.OS AND I.NIVEL = P.INDICE  AND P.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO = 'NAOMANUFATURADO' 

			
			) AS COMPONENTES
			WHERE IDPRD <> ''
			AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			) AS C

			INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE C.CODIGOPRD+';'+C.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(C.EXECUCAO AS varchar(10))+'/'+C.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
			INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
			INNER JOIN KATVORDEM (NOLOCK) A ON O.CODCOLIGADA = A.CODCOLIGADA AND O.CODFILIAL = A.CODFILIAL AND O.CODORDEM = A.CODORDEM AND C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI = A.CODATIVIDADE
			LEFT JOIN KATVORDEMMP (NOLOCK) MP ON MP.CODCOLIGADA = O.CODCOLIGADA AND MP.CODFILIAL = O.CODFILIAL AND MP.CODORDEM = O.CODORDEM AND A.IDATVORDEM = MP.IDATIVIDADE AND MP.IDPRODUTO = C.IDPRD AND MP.EFETIVADO = 0
		WHERE MP.CODCOLIGADA IS NULL
	
	UPDATE GAUTOINC SET VALAUTOINC  = (SELECT MAX(IDATVORDEMMATERIAPRIMA) FROM KATVORDEMMP)
	WHERE CODAUTOINC = 'IDATVORDEMMATERIAPRIMA' 
	AND CODSISTEMA = 'K' 
	AND CODCOLIGADA = 0;

	INSERT INTO KATVORDEMCOMPL (CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, IDATVORDEM, CODFILIAL, CAUSADOR, NUMERORNC2, RNCRR, RETRABALHO, PRIORIDADE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON )
	SELECT O.CODCOLIGADA, O.CODORDEM, I.CODESTRUTURA, I.CODMODELO, Z.IDATVORDEM, O.CODFILIAL, NULL CODCLIENTECAUSADOR, NULL NUMRNC,  NULL CODCLIENTERNCRR,  NULL CODCLIENTECAUSA, A.PRIORIDADE, 'fluig',getdate(),'fluig',getdate() 
	FROM KORDEM O (NOLOCK)
		INNER JOIN KITEMORDEM I (NOLOCK) ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
		INNER JOIN FLUIG.DBO.ML001004 F (NOLOCK) ON F.NUM_OS = O.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 M (NOLOCK) ON F.NUM_OS = M.OS AND O.RESPONSAVEL LIKE M.CODIGOPRD+';'+F.NUMPROCESSO COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN FLUIG.DBO.Z_CRM_EX001021 A (NOLOCK) ON M.OS = A.OSPROCESSO AND M.IDCRIACAO = A.IDCRIACAOPROCESSO AND M.EXECUCAO = A.EXECUCAO
		INNER JOIN KATVORDEM Z (NOLOCK) ON Z.CODCOLIGADA = O.CODCOLIGADA AND Z.CODFILIAL = O.CODFILIAL AND Z.CODORDEM = O.CODORDEM AND Z.CODATIVIDADE = A.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
		LEFT JOIN KATVORDEMCOMPL L (NOLOCK) ON L.CODCOLIGADA = Z.CODCOLIGADA AND L.CODFILIAL = Z.CODFILIAL AND L.CODORDEM = Z.CODORDEM AND L.IDATVORDEM = Z.IDATVORDEM
	WHERE L.IDATVORDEM IS NULL AND @NUM_OS = M.OS AND @EXECUCAO = M.EXECUCAO AND @CODTRFPAI = M.CODTRFPAI

-- FIM DA RECRIAÇÃO DAS ORDENS

-- SALVANDO OS DADOS DO CRONOGRAMA

 		SELECT T.CODCOLIGADA , T.IDPRJ, LEFT(T.CODTRF,4) CODTRFPAI, T.CODTRFAUX, T.NOME, T.DESCRICAO, T.DATAINICIOCALC, T.DATAINICIOPLAN , T.DATAINICIOREAL ,
		T.DATAFIMCALC, T.DATAFIMPLAN , T.DATAFIMREAL,
		T.DURACAOCALC, T.DURACAOPLAN, T.DURACAOREAL,
		T.PERCCONCLUIDO,
		C.CELULA, C.TAG  , C.STATUS_FABRICACAO INTO #Z_CRM_LOGPRJ
		FROM MTAREFA T
			INNER JOIN MTRFCOMPL C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF
		WHERE T.CODCOLIGADA = @CODCOLIGADA AND T.IDPRJ = @IDPRJ AND ISNULL(T.CODTRFAUX,'') <> '' AND  LEFT(T.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)
		ORDER BY T.CODTRF;
			   		 	
 -- SALVAMOS AS TAREFAS SUMARIZADORAS

		SELECT CODCOLIGADA, IDPRJ, LEFT(CODTRFAUX, CHARINDEX('-',CODTRFAUX)-1) CODORDEM INTO #Z_CRM_TRFSUM
		FROM MTAREFA  (NOLOCK)
		WHERE CODCOLIGADA = @CODCOLIGADA AND IDPRJ = @IDPRJ AND CODTRFAUX LIKE '%-SUM' AND QUANTIDADE IS NULL AND LEFT(CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3);


-- FIM DO SALVAMENTO DOS DADOS

	DELETE D
	FROM MTAREFA (NOLOCK) K
		INNER JOIN MTRFDESC (NOLOCK) D ON D.CODCOLIGADA = K.CODCOLIGADA AND D.IDPRJ = K.IDPRJ AND D.IDTRF = K.IDTRF
	WHERE K.CODCOLIGADA = @CODCOLIGADA AND K.IDPRJ = @IDPRJ AND LEFT(K.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)
	
	DELETE D
	FROM MTAREFA (NOLOCK) K
		INNER JOIN MTRFPLAN(NOLOCK) D ON D.CODCOLIGADA = K.CODCOLIGADA AND D.IDPRJ = K.IDPRJ AND D.IDTRF = K.IDTRF
	WHERE K.CODCOLIGADA = @CODCOLIGADA AND K.IDPRJ = @IDPRJ AND LEFT(K.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)
	
	DELETE D
	FROM MTAREFA (NOLOCK) K
		INNER JOIN MTRFCOMPL (NOLOCK) D ON D.CODCOLIGADA = K.CODCOLIGADA AND D.IDPRJ = K.IDPRJ AND D.IDTRF = K.IDTRF
	WHERE K.CODCOLIGADA = @CODCOLIGADA AND K.IDPRJ = @IDPRJ AND LEFT(K.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)
				
	DELETE D
	FROM MTAREFA (NOLOCK) K
		INNER JOIN MTRFSUC (NOLOCK) D ON D.CODCOLIGADA = K.CODCOLIGADA AND D.IDPRJ = K.IDPRJ AND D.IDTRF = K.IDTRF
	WHERE K.CODCOLIGADA = @CODCOLIGADA AND K.IDPRJ = @IDPRJ AND LEFT(K.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)
	
	DELETE D
	FROM MTAREFA (NOLOCK) K
		INNER JOIN MTRFSUC (NOLOCK) D ON D.CODCOLIGADA = K.CODCOLIGADA AND D.IDPRJ = K.IDPRJ AND D.IDTRFSUC = K.IDTRF
	WHERE K.CODCOLIGADA = @CODCOLIGADA AND K.IDPRJ = @IDPRJ AND LEFT(K.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)

	DELETE K
	FROM MTAREFA (NOLOCK) K
	WHERE K.CODCOLIGADA = @CODCOLIGADA AND K.IDPRJ = @IDPRJ AND LEFT(K.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)

	-- REFAZ A INTEGRAÇÃO COM O SOLUM

		DECLARE @IDPAI INT, @IDPAIEXEC INT, @DSCEXECUCAO VARCHAR(MAX), @DATAINICIAL DATE, @IDDISCIPLINA INT;

		SELECT @DSCEXECUCAO = I.DESCRICAO, @QTDORDEM = I.EXECUCAO , @CODTRFPAI = I.CODTRFPAI, @IDPRJ = CAST(Z.IDPRJ_OS AS int)
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		WHERE  I.NIVEL = '' AND ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI;

		SELECT @IDPAI = IDTRF, @DATAINICIAL = ISNULL(DATAINICIOCALC, CAST(GETDATE() AS DATE))
		FROM MTRF (NOLOCK)
		WHERE CODCOLIGADA = 1 
		AND IDPRJ = @IDPRJ 
		AND CODTRF = @CODTRFPAI;

		SELECT @IDDISCIPLINA = IDDISCIPLINA FROM MDISCIPLINA (NOLOCK) WHERE CODCOLIGADA = @CODCOLIGADA AND IDPRJ = @IDPRJ AND CODIGO = '07';
			
		-- REFAZ A INTEGRAÇÃO COM O SOLUM
				INSERT INTO MTAREFA (CODCOLIGADA, IDPRJ, IDTRF, CODTRF, CODTRFAUX, NOME, DESCRICAO, IDPAI, ATIVA, VALOR, BLOQUEADA, SERVICO, UTILIZARVALOR,IDDISCIPLINA, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
							  VALUES( 1, @IDPRJ,ISNULL((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'M' AND	CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))),0)+1,
										 @CODTRFPAI+'.'+RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS VARCHAR(5)),3),'EXEC'+CAST(@EXECUCAO AS VARCHAR(4))+'-'+@CODTRFPAI, 
										 LEFT('FABRICAÇÃO '+CAST(@EXECUCAO AS VARCHAR(4))+' - '+@DSCEXECUCAO,90),'FABRICAÇÃO '+CAST(@EXECUCAO AS VARCHAR(4))+' - '+@DSCEXECUCAO,@IDPAI, 1,  0, 0, 0, 0, @IDDISCIPLINA, 'fluig', GETDATE(),'fluig', GETDATE() )
				
				SELECT @IDPAIEXEC = IDTRF FROM MTRF WHERE CODCOLIGADA = 1 AND IDPRJ = @IDPRJ AND CODTRF = @CODTRFPAI+'.'+RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS VARCHAR(5)),3);

					-- ATUALIZA OS ID
				UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDTRF) FROM MTAREFA WHERE CODCOLIGADA = @CODCOLIGADA AND IDPRJ = @IDPRJ) WHERE CODSISTEMA = 'M' AND CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))


				-- INCLUSAO DAS TAREFAS DO SOLUM
				INSERT INTO MTAREFA (CODCOLIGADA, IDPRJ, IDTRF, CODTRF, CODTRFAUX, NOME, DESCRICAO, IDPAI, ATIVA, VALOR, BLOQUEADA, SERVICO, UTILIZARVALOR,IDDISCIPLINA, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
				SELECT O.CODCOLIGADA, @IDPRJ, ROW_NUMBER() OVER (ORDER BY CAST('/' + REPLACE(I.INDICE, '.', '/') + '/' AS HIERARCHYID))+ISNULL((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'M' AND	CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))),0),
						@CODTRFPAI+'.'+RIGHT(REPLICATE('0',3)+CAST(I.EXECUCAO AS VARCHAR(5)),3)+'.'+RIGHT(REPLICATE('0',3)+ CAST(ROW_NUMBER() OVER (ORDER BY CAST('/' + REPLACE(I.INDICE, '.', '/') + '/' AS HIERARCHYID)) AS varchar(MAX)),3), 
						O.CODORDEM, LEFT(ISNULL(I.DESCRICAO,'')+' - POS. '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),90), ISNULL(I.DESCRICAO,'')+' - POS. '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,'') , @IDPAIEXEC, 1, 0, 0, 0, 0,@IDDISCIPLINA, 'fluig', GETDATE(),'fluig', GETDATE() 
				 FROM FLUIG.DBO.ML001004 (NOLOCK) M
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
					INNER JOIN KITEMORDEM (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
					INNER JOIN KORDEM (NOLOCK) O ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM AND O.RESPONSAVEL like I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS VARCHAR(MAX))+'/'+@CODTRFPAI+'%'
				WHERE I.OS = @NUM_OS
				AND I.CODTRFPAI = @CODTRFPAI
				AND I.EXECUCAO = @EXECUCAO
				AND I.ITEMEXCLUSIVO <> 2
				AND O.STATUS <> 6
				ORDER BY CAST('/' + REPLACE(I.INDICE, '.', '/') + '/' AS HIERARCHYID)
			
				-- ATUALIZA OS ID
				UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDTRF) FROM MTAREFA WHERE CODCOLIGADA = 1 AND IDPRJ = @IDPRJ) WHERE CODSISTEMA = 'M' AND CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))
	
			INSERT INTO MTRFCOMPL (CODCOLIGADA, IDPRJ, IDTRF, NUMFLUIG,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT T.CODCOLIGADA, T.IDPRJ, T.IDTRF, (SELECT TOP 1 NUMPROCESSO FROM FLUIG.DBO.ML001004 WHERE NUM_OS = @NUM_OS), T.RECCREATEDBY, T.RECCREATEDON, T.RECMODIFIEDBY, T.RECMODIFIEDON
			FROM MTAREFA (NOLOCK) T
				LEFT JOIN MTRFCOMPL (NOLOCK) C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF
			WHERE C.IDPRJ IS NULL
			AND T.IDPRJ = @IDPRJ
			AND		T.CODCOLIGADA = @CODCOLIGADA;

		UPDATE P SET  QUANTIDADE = (SELECT SUM(ROUND((ISNULL(FILA,0)+ISNULL(CONFIGURACAO,0)+ISNULL(PROCESSA,0)+ISNULL(DESAGREGACAO,0)+ISNULL(ESPERA,0)+ISNULL(MOVIMENTACAO,0))/60,2)*K.QTDEPLANEJADA)
									FROM KITEMORDEM (NOLOCK) K
										INNER JOIN KATVESTRUTURA (NOLOCK) A ON A.CODCOLIGADA = K.CODCOLIGADA AND A.CODESTRUTURA = K.CODESTRUTURA AND A.CODFILIAL = K.CODFILIAL
									WHERE K.CODCOLIGADA = P.CODCOLIGADA AND K.CODFILIAL = M.CODFILIAL AND K.CODORDEM = P.CODTRFAUX ) ,
				CODUND = 'H' , SERVICO = 1, BDI = 1, UTILIZARVALOR = 1, BLOQUEADA = NULL, SUBOBRA = 0
		FROM MTAREFA (NOLOCK) P 
			INNER JOIN MPRJ (NOLOCK) M ON M.CODCOLIGADA = P.CODCOLIGADA AND M.IDPRJ = P.IDPRJ
		WHERE P.IDPRJ =  @IDPRJ AND LEFT(P.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3) AND LEN(P.CODTRF) = 12
		AND		P.CODCOLIGADA = @CODCOLIGADA


			UPDATE C SET C.NUMFLUIG = M.NUMPROCESSO, C.NIVEL =  RIGHT(REPLICATE('0',3)+CAST(LEN(I.INDICE)-LEN(REPLACE(I.INDICE,'.','')) AS varchar(3)),3) , 
						C.INDICE = CASE WHEN I.COMPORLISTA = 'SIM' THEN 'P' ELSE 'S' END, C.CELULA = CASE WHEN I.COMPORLISTA = 'SIM' THEN '09' END
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
				INNER JOIN KITEMORDEM (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
				INNER JOIN KORDEM (NOLOCK) O ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM AND O.RESPONSAVEL LIKE I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS VARCHAR(MAX))+'/%'
				INNER JOIN MTAREFA (NOLOCK) T ON O.CODCOLIGADA = T.CODCOLIGADA AND T.IDPRJ = M.IDPRJ_OS AND T.CODTRFAUX = O.CODORDEM
				INNER JOIN MTRFCOMPL (NOLOCK) C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF
			WHERE M.NUM_OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO AND LEFT(T.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3);


				-- ATUALIZA O NIVEL DE ORDEM DE PRODUÇÃO
				UPDATE MTAREFA SET MTAREFA.DURACAOCALC = CASE WHEN  (MTAREFA.QUANTIDADE/8)  - FLOOR(MTAREFA.QUANTIDADE/8)  <> 0.00000 THEN FLOOR(MTAREFA.QUANTIDADE/8)+1 ELSE FLOOR(MTAREFA.QUANTIDADE/8) END,
								MTAREFA.PROGRAMADA = 1 , MTAREFA.DATAINICIOPLAN = @DATAINICIAL, MTAREFA.DATAFIMPLAN = @DATAINICIAL, 
								MTAREFA.DATAINICIOCALC = @DATAINICIAL, MTAREFA.DATAFIMCALC = @DATAINICIAL
				FROM MTAREFA 
				WHERE  IDPRJ =  @IDPRJ AND LEFT(CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3) AND LEN(CODTRF) = 12  AND CODCOLIGADA = @CODCOLIGADA;
				

				UPDATE M SET M.DURACAOCALC = (SELECT SUM(DURACAOCALC) FROM MTRF A WHERE A.IDPRJ = M.IDPRJ AND A.IDPAI = M.IDTRF), M.DURACAOPLAN = (SELECT SUM(DURACAOPLAN) FROM MTRF A WHERE A.IDPRJ = M.IDPRJ AND A.IDPAI = M.IDTRF), PROGRAMADA = 1 , M.DATAINICIOPLAN = @DATAINICIAL, M.DATAFIMPLAN = @DATAINICIAL, M.DATAINICIOCALC = @DATAINICIAL, M.DATAFIMCALC = @DATAINICIAL
				FROM MTRF M
				WHERE IDPRJ = @IDPRJ AND LEFT(CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3) AND LEN(CODTRF) = 8  AND CODCOLIGADA = @CODCOLIGADA; 


				-- ATUALIZA O NIVEL DE FABRICAÇÃO

				UPDATE M SET M.DURACAOCALC = (SELECT SUM(DURACAOCALC) FROM MTRF A WHERE A.IDPRJ = M.IDPRJ AND A.IDPAI = M.IDTRF), M.DURACAOPLAN = (SELECT SUM(DURACAOPLAN) FROM MTRF A WHERE A.IDPRJ = M.IDPRJ AND A.IDPAI = M.IDTRF), PROGRAMADA = 1 , M.DATAINICIOPLAN = @DATAINICIAL, M.DATAFIMPLAN = @DATAINICIAL, M.DATAINICIOCALC = @DATAINICIAL, M.DATAFIMCALC = @DATAINICIAL
				FROM MTRF M
				WHERE IDPRJ = @IDPRJ AND CODTRF LIKE @CODTRFPAI+'%' AND LEN(CODTRF) =4  AND CODCOLIGADA = @CODCOLIGADA;
						
		
		-- ATUALIZAÇÃO DATA FINAL PARA CORRETO CALCULO DO SOLUM
		UPDATE M SET DATAFIMCALC = DATAINICIOCALC+DURACAOCALC
		FROM MTRF M
		WHERE IDPRJ = @IDPRJ AND CODTRF LIKE @CODTRFPAI+'%'  AND CODCOLIGADA = @CODCOLIGADA;


		-- RECRIANDO AS TAREFAS SUMARIZADORAS

		-- SALVAMOS AS TAREFAS SUMARIZADORAS
		DECLARE @IDTRF_SUM INT;

		 DECLARE SUMARIZACAO CURSOR FOR  SELECT IDTRF 
										  FROM #Z_CRM_TRFSUM  Z
											INNER JOIN MTAREFA (NOLOCK) M ON Z.CODCOLIGADA = M.CODCOLIGADA 
																		 AND Z.IDPRJ = M.IDPRJ 
																		 AND Z.CODORDEM = M.CODTRFAUX
										  WHERE LEFT(M.CODTRF,8) = @CODTRFPAI+'.'+ RIGHT(REPLICATE('0',3)+CAST(@EXECUCAO AS varchar(3)),3)

		OPEN SUMARIZACAO;

		FETCH NEXT FROM SUMARIZACAO INTO @IDTRF_SUM;

		WHILE @@FETCH_STATUS = 0
		BEGIN

			EXEC SP_CRM_CRIATRFSUMARIZADORA @CODCOLIGADA , @IDPRJ , @IDTRF_SUM;

			FETCH NEXT FROM SUMARIZACAO INTO @IDTRF_SUM;

		END;

		CLOSE SUMARIZACAO;
		DEALLOCATE SUMARIZACAO;


-- FIM DO CRONOGRAMA SOLUM




-- RECRIANDO AS ORDENS DE RETRABALHO

	DECLARE @CODTRF_NEW VARCHAR(50), @PROCESSO INT, @CODTRF VARCHAR(MAX);

	DECLARE FLUIG26 CURSOR FOR SELECT M.NUMPROCESSO
								FROM FLUIG.dbo.ML001026 M (NOLOCK)
									INNER JOIN FLUIG.DBO.ML001004 I (NOLOCK) ON M.NUM_OS = I.NUM_OS
								WHERE I.NUM_OS = @NUM_OS
 
	OPEN FLUIG26;

	FETCH NEXT FROM FLUIG26 INTO @PROCESSO;

	WHILE @@FETCH_STATUS = 0
	BEGIN

		DECLARE RETRABALHO CURSOR FOR 		SELECT   P.IDPRJ,  T.IDPAI,  T.CODTRF,  LEFT(T.CODTRF,LEN(T.CODTRF)-3) + RIGHT(REPLICATE('0',3)+CAST(CAST(RIGHT(T.CODTRF,3) AS int)+1 AS varchar(4)),3)
											FROM FLUIG.dbo.ML001026 M (NOLOCK)
												INNER JOIN MPRJ P (NOLOCK) ON P.CODPRJ = M.NUM_OS COLLATE Latin1_General_CI_AS AND P.POSICAO IN (1,4)
												INNER JOIN MTRF T (NOLOCK) ON P.CODCOLIGADA = T.CODCOLIGADA AND P.IDPRJ = T.IDPRJ AND T.CODTRFAUX = M.CODORDEM COLLATE Latin1_General_CI_AS
												INNER JOIN KORDEMCOMPL C (NOLOCK) ON C.CODCOLIGADA = M.CODCOLIGADA AND C.CODFILIAL = M.CODFILIAL AND C.CODORDEM = M.CODORDEM COLLATE Latin1_General_CI_AS
											WHERE M.NUMPROCESSO = @PROCESSO AND C.NUMEXEC = @EXECUCAO AND LEFT(T.CODTRF,4) = @CODTRFPAI
											AND	  M.EXCLUSIVO1 = 'FINALIZAR';

		OPEN RETRABALHO;

		FETCH NEXT FROM RETRABALHO INTO @IDPRJ, @IDPAI, @CODTRF, @CODTRF_NEW;

		WHILE @@FETCH_STATUS = 0
		BEGIN

		UPDATE MTRF SET CODTRF = LEFT(CODTRF,LEN(CODTRF)-3) + RIGHT(REPLICATE('0',3)+CAST(CAST(RIGHT(CODTRF,3) AS int)+1 AS varchar(4)),3)
		WHERE IDPRJ = @IDPRJ AND IDPAI = @IDPAI AND CODTRF > @CODTRF
	

		INSERT INTO MTAREFA (CODCOLIGADA, IDPRJ, IDTRF, CODTRF, CODTRFAUX, NOME, DESCRICAO, IDPAI, QUANTIDADE, CODUND, ATIVA, VALOR, BLOQUEADA, SERVICO, BDI, UTILIZARVALOR, INDIRETO, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT O.CODCOLIGADA, @IDPRJ, ROW_NUMBER() OVER (ORDER BY O.CODORDEM DESC)+ISNULL((SELECT VALAUTOINC FROM GAUTOINC WHERE CODSISTEMA = 'M' AND	CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))),0),
				@CODTRF_NEW, O.CODORDEM, LEFT('RETRABALHO: ' + I.F_DESCRICAO+ ' - POS. '+I.F_POSICAODESENHO,90), 'RETRABALHO: ' + I.F_DESCRICAO+ ' - POS. '+I.F_POSICAODESENHO , @IDPAI, 
					((SELECT SUM( CAST(ISNULL(A.VIEWMINUTOSGASTOS,0) AS FLOAT)) FROM FLUIG.DBO.ML001028 A (NOLOCK) WHERE I.DOCUMENTID = A.DOCUMENTID AND I.VERSION = A.VERSION)*CAST(I.F_DESQTDE AS FLOAT))/60.00, 
				'H', 1, 0, 0, 1,1,1,1, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001026 (NOLOCK) I
			INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.F_CODIGOPRD+';'+I.NUMPROCESSO COLLATE Latin1_General_CI_AS+'- RETRABALHO'
		WHERE I.NUMPROCESSO = @PROCESSO

		UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(IDTRF) FROM MTAREFA WHERE CODCOLIGADA = 1 AND IDPRJ = @IDPRJ) WHERE CODSISTEMA = 'M' AND CODAUTOINC = 'IDTRF-'+CAST(@IDPRJ AS varchar(MAX))


		FETCH NEXT FROM RETRABALHO INTO @IDPRJ, @IDPAI, @CODTRF, @CODTRF_NEW;
		END;

		CLOSE RETRABALHO;
		DEALLOCATE RETRABALHO;

		FETCH NEXT FROM FLUIG26 INTO @PROCESSO;

	END

	CLOSE FLUIG26
	DEALLOCATE FLUIG26
		
-- FIM DA CRIAÇÃO DOS RETRABALHOS

-- FIM DA RECRICAOÇÃO DO CRONOGRAMA SOLUM
	
			INSERT INTO MTRFCOMPL (CODCOLIGADA, IDPRJ, IDTRF, NUMFLUIG,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT T.CODCOLIGADA, T.IDPRJ, T.IDTRF, @NUMPROCESSO_ORIGINAL,  T.RECCREATEDBY, T.RECCREATEDON, T.RECMODIFIEDBY, T.RECMODIFIEDON
			FROM MTAREFA (NOLOCK) T
				LEFT JOIN MTRFCOMPL (NOLOCK) C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF
			WHERE C.IDPRJ IS NULL
			AND T.IDPRJ = @IDPRJ
			AND		T.CODCOLIGADA = @CODCOLIGADA;
		

			-- RESTAURANDO INFORMAÇÕES DO PROJETOS

		UPDATE T SET	
				T.NOME = CASE WHEN T.CODTRFAUX LIKE '%-SUM' THEN Z.NOME ELSE CASE WHEN T.CODTRFAUX LIKE 'EXEC%' THEN Z.NOME ELSE T.NOME END END, 
				T.DESCRICAO = CASE WHEN T.CODTRFAUX LIKE '%-SUM' THEN Z.DESCRICAO ELSE CASE WHEN T.CODTRFAUX LIKE 'EXEC%' THEN Z.DESCRICAO ELSE T.DESCRICAO END END, 
				T.DATAINICIOCALC = Z.DATAINICIOCALC, T.DATAINICIOPLAN = Z.DATAINICIOPLAN , T.DATAINICIOREAL = Z.DATAINICIOREAL ,
				T.DATAFIMCALC = Z.DATAFIMCALC, T.DATAFIMPLAN = Z.DATAFIMPLAN , T.DATAFIMREAL = Z.DATAFIMREAL,
				T.DURACAOCALC = Z.DURACAOCALC, T.DURACAOPLAN = Z.DURACAOPLAN, T.DURACAOREAL = Z.DURACAOREAL,
				T.PERCCONCLUIDO = Z.PERCCONCLUIDO
		FROM #Z_CRM_LOGPRJ  Z
			INNER JOIN MTAREFA (NOLOCK) T ON T.CODCOLIGADA = Z.CODCOLIGADA AND T.IDPRJ = Z.IDPRJ AND T.CODTRFAUX = Z.CODTRFAUX 


		UPDATE C SET
				C.CELULA = Z.CELULA, C.TAG = Z.TAG, C.STATUS_FABRICACAO = Z.STATUS_FABRICACAO
		FROM #Z_CRM_LOGPRJ Z
			INNER JOIN MTAREFA (NOLOCK) T ON T.CODCOLIGADA = Z.CODCOLIGADA AND T.IDPRJ = Z.IDPRJ AND T.CODTRFAUX = Z.CODTRFAUX 
			INNER JOIN MTRFCOMPL (NOLOCK) C ON T.CODCOLIGADA = C.CODCOLIGADA AND T.IDPRJ = C.IDPRJ AND T.IDTRF = C.IDTRF

		-- FIM DAS RESTAURAÇÕES

-- CORRIG COMPONENTES DAS ESTRUTURA QUE NÃO SÃO DA EXECUÇÃO, MAS SÃO DA ESTURUTRA GERAL

DELETE CC
FROM KCOMPONENTE C
	INNER JOIN KCOMPONENTECOMPL (NOLOCK) CC ON C.CODCOLIGADA = CC.CODCOLIGADA AND C.CODESTRUTURA = CC.CODESTRUTURA AND C.IDPRODUTO = CC.IDPRODUTO
	INNER JOIN KESTRUTURA  (NOLOCK) E ON C.CODCOLIGADA = E.CODCOLIGADA AND C.CODFILIAL = E.CODFILIAL AND C.CODESTRUTURA = E.CODESTRUTURA
	INNER JOIN TPRD  (NOLOCK)  P ON P.CODCOLIGADA = C.CODCOLIGADA AND P.IDPRD = C.IDPRODUTO
	LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I ON I.CODCOLIGADA = C.CODCOLIGADA AND I.IDPRD = C.IDPRODUTO AND E.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE LEFT(P.CODIGOPRD,2) IN ('04', '03') AND   E.CODCCUSTO = @NUM_OS AND I.CODCOLIGADA IS NULL AND CC.RECCREATEDBY = 'fluig'

DELETE  C
FROM KCOMPONENTE (NOLOCK) C 
	INNER JOIN KESTRUTURA  (NOLOCK) E ON C.CODCOLIGADA = E.CODCOLIGADA AND C.CODFILIAL = E.CODFILIAL AND C.CODESTRUTURA = E.CODESTRUTURA
	INNER JOIN TPRD  (NOLOCK)  P ON P.CODCOLIGADA = C.CODCOLIGADA AND P.IDPRD = C.IDPRODUTO
	LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I ON I.CODCOLIGADA = C.CODCOLIGADA AND I.IDPRD = C.IDPRODUTO AND E.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE LEFT(P.CODIGOPRD,2) IN ('04', '03') AND   E.CODCCUSTO =  @NUM_OS AND C.RECCREATEDBY = 'fluig' AND I.CODCOLIGADA IS NULL 

-- FIM DO AJUSTE

 -- LIMPA A TABELA DE ITENS EXCLUIDOS
  DELETE FLUIG.DBO.Z_CRM_EXITENSEXCLUIDOS WHERE OS = @NUM_OS AND EXECUCAO = @EXECUCAO;

END;
