USE [CORPORE_DEV]
GO
/****** Object:  StoredProcedure [dbo].[SP_DELP_EDICAOESTRUTURA]    Script Date: 28/10/2023 16:38:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[SP_DELP_EDICAOESTRUTURA] @NUMPROCESSO INT
AS
BEGIN

	DECLARE @CODCOLIGADA INT, @CODFILIAL INT, @IDPRJ INT;


	PRINT 'INICIO EDICAO'

-- VERIFICA SE PRODUTROS EXCLUIDOS QUE ESTAVAM NA Z_CRM_ITENSEXCLUIDO VOLTARAM PARA ESTRUTURA

	DELETE E 
	FROM FLUIG.dbo.Z_CRM_ITENSEXCLUIDOS E
	INNER JOIN FLUIG.dbo.Z_CRM_ML001005 M ON E.OS = M.OS AND E.IDPRD = M.IDPRD

-- INICIA COM AS EXCLUSÕES DAS EDIÇÕES


	UPDATE P SET INATIVO = 1, RECMODIFIEDON=GETDATE()
	FROM TPRODUTO P 
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = P.IDPRD AND Z.CODCOLIGADA = P.CODCOLPRD
	WHERE Z.PROCESSO = @NUMPROCESSO;

		
	
	UPDATE P SET STATUSESTR = 0, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA P 
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = P.IDPRODUTO AND Z.CODCOLIGADA = P.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;
	
	

	UPDATE O SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO; 
		
		

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN KORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;

	

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA E 
		INNER JOIN KITEMORDEM O ON E.CODCOLIGADA = O.CODCOLIGADA AND E.CODFILIAL = O.CODFILIAL AND E.CODESTRUTURA = O.CODESTRUTURA
		INNER JOIN KATVORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
		INNER JOIN FLUIG.DBO.Z_CRM_ITENSEXCLUIDOS Z ON Z.IDPRD = E.IDPRODUTO AND Z.CODCOLIGADA = E.CODCOLIGADA
	WHERE Z.PROCESSO = @NUMPROCESSO;

	-- FIM DAS EXCLUSÕES DAS ALTERAÇÕES


	-- INICIO DAS ALTERAÇÕES

	DECLARE @NUMPROCESSO_ORIGINAL INT, @OS VARCHAR(MAX), @INDICE INT, @CODTRFPAI VARCHAR(MAX), @IDDISCIPLINA INT;

	SELECT  @NUMPROCESSO_ORIGINAL=O.NUMPROCESSO ,@CODCOLIGADA=I.CODCOLIGADA 
	, @CODFILIAL=I.CODFILIAL,  @IDPRJ=CAST(O.IDPRJ_OS AS int), @INDICE=CAST(I.INDICE AS int), @OS=O.NUM_OS, @CODTRFPAI=I.CODTRFPAI
	FROM FLUIG.DBO.ML001007 Z
		INNER JOIN FLUIG.DBO.ML001004 O ON Z.NUM_OS = O.NUM_OS
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 I on O.NUM_OS = I.OS
	WHERE Z.NUMPROCESSO = @NUMPROCESSO AND  I.NIVEL = '';

	
		

	SELECT @IDDISCIPLINA = IDDISCIPLINA FROM MDISCIPLINA WHERE CODCOLIGADA = @CODCOLIGADA AND IDPRJ = @IDPRJ AND CODIGO = '07';

	UPDATE P SET  P.INVENTARIOFISCAL = 1, P.TIPOTRIBUTACAO = 0, P.CODCOLCONTA = @CODCOLIGADA,
				P.SITUACAOMERCADORIA = CASE LEFT(I.CODIGOPRD,2) 
												WHEN '04' THEN '04' 
												WHEN '03' THEN '03'
												ELSE '02'  END, 
				P.CODCONTA = CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN '1.1.3.01.0003' ELSE  '1.1.3.01.0004' END 
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		INNER JOIN TPRDFISCAL (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA AND I.IDPRD = P.IDPRD
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;

	-- NÃO ATUALIZA DESCRIÇÃO DO 04.024
	UPDATE P SET P.DESCRICAO = ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''), 
					P.NOMEFANTASIA =  LEFT(ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),120)
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		INNER JOIN TPRODUTO (NOLOCK) P ON P.CODCOLPRD = 1 AND I.IDPRD = P.IDPRD
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND LEFT(P.CODIGOPRD,2)!='04';

	UPDATE P SET P.NUMNOFABRIC = I.CODIGOPRD
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		INNER JOIN TPRODUTODEF (NOLOCK) P ON P.CODCOLIGADA = 1 AND I.IDPRD = P.IDPRD
	WHERE  M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
	
	-- ###### INCIADO INTEGRACAO COM O FACTOR ######

	-- INCLUSÃO DA ESTRUTURA
	
	INSERT INTO KESTRUTURA (CODCOLIGADA, CODESTRUTURA, CODTIPO, IDPRODUTO, QTDLOTE, STATUSESTR, CODCCUSTO, IDFASE, FASEVALIDADA, CODIGOULTALTERACAO, VALIDACAOSOLICITADA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT I.CODCOLIGADA, I.CODIGOPRD, CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN 'A' ELSE 'S' END, I.IDPRD, I.DESQTDE*10000, 1, M.NUM_OS, 1, 1, 0, 0, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		LEFT JOIN KESTRUTURA E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
	WHERE E.CODESTRUTURA IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
	ORDER BY I.NIVEL, I.INDICE;

	UPDATE E  SET CODTIPO = CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN 'A' ELSE 'S' END, QTDLOTE = ISNULL(I.DESQTDE,1)*10000, STATUSESTR= 1,  RECMODIFIEDON = GETDATE()
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		INNER JOIN KESTRUTURA E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
		

	INSERT INTO KLINHAEST (CODCOLIGADA, CODLINHA, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT I.CODCOLIGADA, '001', I.CODIGOPRD, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		LEFT JOIN KLINHAEST E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
	WHERE  E.CODESTRUTURA IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
	ORDER BY I.NIVEL, I.INDICE;

	INSERT INTO KESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODFILIAL, ELABORADOR2, ELABORADOR3, ELABORADOR, CAMDESENHO, NUMREVISAO, POSICAO, BITOLA, LARGURA, COMPRIMENTO, PESOBRUTO, PESOLIQUIDO, ESPECIFICACAOROSCA , RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT						 I.CODCOLIGADA, I.CODIGOPRD, I.CODFILIAL, NULL ELABORADOR2, NULL ELABORADOR3, NULL ELABORADOR, 
							CASE WHEN I.NUMDESENHO = '' THEN NULL ELSE I.NUMDESENHO END, 
							CASE WHEN I.REVISAODESENHO = '' THEN NULL ELSE I.REVISAODESENHO END, 
							CASE WHEN I.POSICAODESENHO = '' THEN NULL ELSE I.POSICAODESENHO END, 
							CAST( CASE WHEN I.BITOLA = '' OR I.BITOLA = 'null' THEN NULL ELSE REPLACE(I.BITOLA,',','.') END AS FLOAT), 
							CAST( CASE WHEN I.LARGURA = '' OR I.LARGURA = 'null' THEN NULL ELSE REPLACE(I.LARGURA,',','.') END AS FLOAT),
							CAST( CASE WHEN I.COMPRIMENTO = '' OR I.COMPRIMENTO = 'null' THEN NULL ELSE REPLACE(I.COMPRIMENTO,',','.') END AS FLOAT), 
							CAST( CASE WHEN I.PESOBRUTO = '' OR I.PESOBRUTO = 'null' THEN NULL ELSE REPLACE(I.PESOBRUTO,',','.') END AS FLOAT), 
							CAST( CASE WHEN I.PESOLIQUIDO = '' OR I.PESOLIQUIDO = 'null' THEN NULL ELSE REPLACE(I.PESOLIQUIDO,',','.') END AS FLOAT), 
							CASE WHEN I.ESPROSCA = '' OR I.ESPROSCA = 'null' THEN NULL ELSE I.ESPROSCA END, 'fluig', GETDATE(),'fluig', GETDATE() 
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		LEFT JOIN KESTRUTURACOMPL K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE K.CODESTRUTURA IS NULL
	AND		M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
	ORDER BY I.NIVEL, I.INDICE;


	UPDATE K SET	CAMDESENHO =	CASE WHEN I.NUMDESENHO = '' THEN NULL ELSE I.NUMDESENHO END, 
					NUMREVISAO =		CASE WHEN I.REVISAODESENHO = '' THEN NULL ELSE I.REVISAODESENHO END, 
					POSICAO    =		CASE WHEN I.POSICAODESENHO = '' THEN NULL ELSE I.POSICAODESENHO END, 
					BITOLA     =		CAST( CASE WHEN I.BITOLA = '' THEN NULL ELSE REPLACE(I.BITOLA,',','.') END AS FLOAT), 
					LARGURA    =		CAST( CASE WHEN I.LARGURA = '' THEN NULL ELSE REPLACE(I.LARGURA,',','.') END AS FLOAT),
					COMPRIMENTO=		CAST( CASE WHEN I.COMPRIMENTO = '' THEN NULL ELSE REPLACE(I.COMPRIMENTO,',','.') END AS FLOAT), 
					PESOBRUTO  =		CAST( CASE WHEN I.PESOBRUTO = '' THEN NULL ELSE REPLACE(I.PESOBRUTO,',','.') END AS FLOAT), 
					PESOLIQUIDO=		CAST( CASE WHEN I.PESOLIQUIDO = '' THEN NULL ELSE REPLACE(I.PESOLIQUIDO,',','.') END AS FLOAT), 
					ESPECIFICACAOROSCA=		CASE WHEN I.ESPROSCA = '' THEN NULL ELSE I.ESPROSCA END, 
					RECMODIFIEDON = GETDATE() 
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
		INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
		INNER JOIN KESTRUTURACOMPL K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;


	DELETE K
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KATVESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;

	

	DELETE K
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KATVESTPOSTO (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
		

		
	DELETE K
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KCOMPSUBSTITUTO K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
		
		

	DELETE K
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KCOMPONENTECOMPL K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.IDPRD <> '';



	DELETE K
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KCOMPONENTE K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.IDPRD <> '';
		
	

	DELETE K
	FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN KATVESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.IDPRD <> '';
		
		
		
	INSERT INTO KATVESTRUTURA
		SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, 1 HORAS, MIN( CAST(C.PRIORIDADE AS INT) ) ,
		SUM(	CAST( CASE WHEN C.FILA = '' THEN NULL ELSE REPLACE(C.FILA,',','.') END AS FLOAT) ), 
		SUM(	CAST( CASE WHEN C.CONFIGURACAO = '' THEN NULL ELSE REPLACE(C.CONFIGURACAO,',','.') END AS FLOAT) ), 
		SUM(	CAST( CASE WHEN C.PROCESSAMENTO = '' THEN NULL ELSE REPLACE(C.PROCESSAMENTO,',','.') END AS FLOAT)), 
		SUM(	CAST( CASE WHEN C.DESAGREGACAO = '' THEN NULL ELSE REPLACE(C.DESAGREGACAO,',','.') END AS FLOAT)), 
		SUM(	CAST( CASE WHEN C.ESPERA = '' THEN NULL ELSE REPLACE(C.ESPERA,',','.') END AS FLOAT)), 
		SUM(	CAST( CASE WHEN C.MOVIMENTACAO = '' THEN NULL ELSE REPLACE(C.MOVIMENTACAO,',','.') END AS FLOAT)),
			1,0,'P',0,NULL,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
			LEFT JOIN KATVESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE  K.CODATIVIDADE IS NULL
		AND		M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
		GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE,I.CODFILIAL;

		
		-- INCLUSÃO DA ETAPAS AS ATIVIDADES PARA LINHA DE PRODUÇÃO O DISTINCT É PARA NÃO INCLUIR A MESMA ATIVIDADE NA TABELA E DAR ERRO


	INSERT INTO  KETPATIVIDADES 
		SELECT DISTINCT I.CODCOLIGADA,'ETP-GLOBAL',C.CODATIVIDADE,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
			LEFT JOIN KETPATIVIDADES (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE  K.CODATIVIDADE IS NULL
		AND		M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') 
		GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL

		

		INSERT INTO KATVESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODATIVIDADE,CODFILIAL, DETALHE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL, C.DESCPROCESSO , 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
			LEFT JOIN KATVESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI = K.CODATIVIDADE
		WHERE K.CODESTRUTURA IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL;
	
		
			

		INSERT INTO KATVESTPOSTO (CODCOLIGADA, CODPOSTO, CODATIVIDADE, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT DISTINCT K.CODCOLIGADA, K.CODPOSTO, C.CODATIVIDADE, I.CODIGOPRD, K.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO
			INNER JOIN KPOSTO (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODPOSTO = C.CODPOSTO COLLATE SQL_Latin1_General_CP1_CI_AI
			LEFT JOIN KATVESTPOSTO (NOLOCK) KP ON KP.CODCOLIGADA = K.CODCOLIGADA AND KP.CODFILIAL = K.CODFILIAL AND KP.CODPOSTO = K.CODPOSTO AND KP.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND KP.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE KP.CODPOSTO IS NULL AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND I.CODIGOPRD <> '';
		
		
	
		INSERT INTO KCOMPONENTE (CODCOLIGADA, CODESTRUTURA, IDPRODUTO, IDAUTOINC, QTDUSADA , CODATIVIDADE, OBRIGASERMATERIAPRIMA, FAZPARTEMODELOBASE, PERMITEEXCLUSAO, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON )
		SELECT  CODCOLIGADA, CODIGOPRD, IDPRD, (SELECT MAX(IDAUTOINC) FROM KCOMPONENTE)+ ROW_NUMBER () OVER (ORDER BY IDPRD), CAST(QTD AS float)*10000,
					ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
						CASE WHEN LEFT(CODIGOPRD,2) <> '03'
							THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
							ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
							) ATIVIDADE,
				1, 0, 0, COMPONENTES.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM (
			SELECT  I.CODIGOPRD, E.IDPRD,  1 QTD, I.NIVEL, I.INDICE, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
			INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) E ON M.NUM_OS = E.OS AND I.INDICE = E.NIVEL
			WHERE  M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0 AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
		
			UNION ALL
		
			SELECT I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD, 1 QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
			WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND   M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL
			
			UNION ALL

				-- CODIGOS NÃO MANUFATURADO
			SELECT P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) * 10000 QTD, I.NIVEL, I.INDICE, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA
			FROM FLUIG.DBO.ML001004 (NOLOCK) M
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
				INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON M.NUM_OS = P.OS AND I.NIVEL = P.INDICE
			WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND  M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO = 'NAOMANUFATURADO'

			
		) AS COMPONENTES
		WHERE IDPRD <> ''
		AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
						(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			
		ORDER BY NIVEL, INDICE;

		-- INSERE OS PRODUTOS SUBSTITUTOS

		INSERT INTO  KCOMPSUBSTITUTO
			SELECT SUB.CODCOLIGADA, SUB.CODESTRUTURA, SUB.CODATIVIDADE, SUB.IDAUTOINC, SUB.IDPRD, SUB.IDPRDCOMPONENTES, SUB.QTDUSADA*10000, NULL, NULL, 0,  SUB.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE()
			FROM (
					SELECT 'A' TIPO, I.NIVEL, I.INDICE, K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
						INNER JOIN FLUIG.dbo.Z_CRM_ML001021 (NOLOCK) A ON I.OS = A.OSPROCESSO AND I.IDCRIACAO = A.IDCRIACAOPROCESSO
						INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND A.PRIORIDADE = C.PRIORIDADEATVCOMPONENTES
						INNER JOIN TPRD P ON P.CODCOLIGADA = I.CODCOLIGADA AND P.CODIGOPRD  COLLATE Latin1_General_CI_AS = C.SUBSTITUTOCOMPONENTES
						INNER JOIN KCOMPONENTE (NOLOCK) K ON  P.IDPRD = K.IDPRODUTO 	AND P.CODCOLIGADA = K.CODCOLIGADA AND K.CODESTRUTURA COLLATE Latin1_General_CI_AS = I.CODIGOPRD AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE COLLATE Latin1_General_CI_AS = A.CODATIVIDADE
						INNER JOIN KESTRUTURA (NOLOCK) E ON K.CODCOLIGADA = E.CODCOLIGADA AND K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA AND E.CODCCUSTO COLLATE Latin1_General_CI_AS = I.OS  AND E.RECCREATEDBY = 'fluig'
					WHERE C.PRIORIDADEATVCOMPONENTES <> 0 AND E.STATUSESTR = 1 AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> ''
		
			UNION ALL

					SELECT 'B' TIPO, I.NIVEL, I.INDICE,  K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
						INNER JOIN KESTRUTURA (NOLOCK) E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODFILIAL = E.CODFILIAL AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA
						INNER JOIN KCOMPONENTE (NOLOCK) K ON  E.CODCOLIGADA = K.CODCOLIGADA AND  K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
						INNER JOIN TPRD (NOLOCK) P ON K.CODCOLIGADA = P.CODCOLIGADA AND K.IDPRODUTO = P.IDPRD
						INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND P.CODIGOPRD = C.SUBSTITUTOCOMPONENTES  COLLATE SQL_Latin1_General_CP1_CI_AI		
					WHERE C.PRIORIDADEATVCOMPONENTES = 0 AND E.STATUSESTR = 1 AND M.NUMPROCESSO = @NUMPROCESSO_ORIGINAL AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> ''
				
			UNION ALL 

					SELECT 'A' TIPO, I.NIVEL, I.INDICE, K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P2.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I on M.NUM_OS = I.OS
						INNER JOIN FLUIG.dbo.Z_CRM_ML001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO
						INNER JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON M.NUM_OS = P.OS AND I.NIVEL = P.INDICE
						INNER JOIN KESTRUTURA (NOLOCK) E ON P.CODCOLIGADA = E.CODCOLIGADA AND P.CODFILIAL = E.CODFILIAL AND P.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA
						INNER JOIN KCOMPONENTE (NOLOCK) K ON  E.CODCOLIGADA = K.CODCOLIGADA AND  K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
						INNER JOIN TPRD (NOLOCK) P2 ON K.CODCOLIGADA = P2.CODCOLIGADA AND K.IDPRODUTO = P2.IDPRD
					WHERE  ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> '' AND  M.NUMPROCESSO =  @NUMPROCESSO_ORIGINAL  AND I.TIPODESENHO = 'NAOMANUFATURADO'

				) SUB
			LEFT JOIN KCOMPSUBSTITUTO (NOLOCK) S ON S.CODCOLIGADA = SUB.CODCOLIGADA AND S.CODFILIAL = SUB.CODFILIAL AND S.CODESTRUTURA = SUB.CODESTRUTURA AND S.CODATIVIDADE = SUB.CODATIVIDADE AND S.IDAUTOINC = SUB.IDAUTOINC AND S.IDPRDORIGEM = SUB.IDPRD AND S.IDPRD = SUB.IDPRDCOMPONENTES
			WHERE S.CODCOLIGADA IS NULL
			ORDER BY SUB.CODESTRUTURA, SUB.CODATIVIDADE, SUB.IDPRD, SUB.IDPRDCOMPONENTES;


	UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))

 -- FIM DA CRIAÇÃO DAS ORDENS

 -- LIMPA A TABELA DE ITENS EXCLUIDOS
  DELETE FLUIG.dbo.Z_CRM_ITENSEXCLUIDOS WHERE OS = @OS;

END;



