USE [CORPORE_DEV]
GO

/****** Object:  StoredProcedure [dbo].[SP_DELP_INTEGRAPEDIDOCOMPRAFLUIG]    Script Date: 10/04/2024 07:23:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		RAFAEL.GRANJA
-- CREATE DATE: 23/03/2024
-- DESCRIPTION:	BUSCA O PEDIDO DE COMPRA GERADO NO FLUIG E INSERE NO RM
-- =============================================
CREATE PROCEDURE [dbo].[SP_DELP_INTEGRAPEDIDOCOMPRAFLUIG](@NUMPROCESSO INT)
AS
BEGIN
	
	SET NOCOUNT ON

	DECLARE @IDPEDIDO INT,@IDITEMPEDIDO INT,@ATIVIDADE INT,@CODIGO VARCHAR(15),@CODCOLIGADA INT,@IDPRJ INT,@LOGIN VARCHAR(50),@LOGIN2 VARCHAR(50)

	SELECT TOP 1 @ATIVIDADE=M1.ATIVIDADE,@IDPEDIDO=M1.IDPEDIDO,@CODCOLIGADA=M1.CODCOLIGADA,@IDPRJ=M1.IDPRJ_OS,@LOGIN=M1.USUARIOATUAL,@LOGIN2=M1.SOLICITANTE
	FROM FLUIG.DBO.ML001243 M1
	INNER JOIN FLUIG.DBO.ML001244 M2 ON
	M1.DOCUMENTID=M2.DOCUMENTID
	AND M1.VERSION=M2.VERSION
	INNER JOIN FLUIG.DBO.PROCES_WORKFLOW P ON 
	P.NR_DOCUMENTO_CARD=M1.DOCUMENTID
	WHERE P.NUM_PROCES=@NUMPROCESSO 
	ORDER BY M1.VERSION DESC

	IF @ATIVIDADE=0 OR @ATIVIDADE=4 OR @ATIVIDADE=18 -- PRIMEIRA ATIVIDADE DE INICIO DE PROCESSO
		BEGIN

				UPDATE MPEDIDOMATEXTRA SET CODUSUARIO=@LOGIN,RECMODIFIEDBY=@LOGIN WHERE CODCOLIGADA=@CODCOLIGADA AND IDPRJ=@IDPRJ AND IDPEDIDOEXTRA=@IDPEDIDO
				UPDATE MITEMPEDIDOMATEXTRA SET RECCREATEDBY=@LOGIN,RECMODIFIEDBY=@LOGIN WHERE CODCOLIGADA=@CODCOLIGADA AND IDPRJ=@IDPRJ AND IDPEDIDOEXTRA=@IDPEDIDO

		END
	IF @ATIVIDADE=5 -- PRIMEIRA ATIVIDADE DE INICIO DE PROCESSO
	BEGIN

			UPDATE MITEMPEDIDOMATEXTRA SET CODAPROVADOR=@LOGIN,RECMODIFIEDBY=@LOGIN WHERE CODCOLIGADA=@CODCOLIGADA AND IDPRJ=@IDPRJ AND IDPEDIDOEXTRA=@IDPEDIDO

	END

	UPDATE T SET USUARIOCRIACAO=@LOGIN,CODUSUARIO=@LOGIN
	FROM MPEDIDOMATEXTRA M
	INNER JOIN MITEMPEDIDOMATEXTRA MI ON
	M.IDPRJ=MI.IDPRJ
	AND M.IDPEDIDOEXTRA=MI.IDPEDIDOEXTRA
	AND M.CODCOLIGADA=MI.CODCOLIGADA
	INNER JOIN TMOV T ON
	T.CODCOLIGADA=M.CODCOLIGADA
	AND T.IDMOV=MI.IDMOV
	WHERE M.IDPEDIDOEXTRA=@IDPEDIDO

	UPDATE MPEDIDOMATEXTRA SET CODUSUARIO=@LOGIN2 WHERE CODCOLIGADA=@CODCOLIGADA AND IDPRJ=@IDPRJ AND IDPEDIDOEXTRA=@IDPEDIDO

END
GO




SELECT 	
		C.CODCOLIGADA, J.CODFILIAL, C.IDPRJ, C.IDTRF,
		CASE WHEN C.TIPOPLANILHA = 1 THEN 1 ELSE 2 END PAGREC, 
		CASE WHEN C.TIPOPLANILHA = 1 THEN J.CODCOLCFO ELSE 1 END CODCOLCFO , 
		CASE WHEN C.TIPOPLANILHA = 1 THEN J.CODCLIENTE ELSE 'F00796' END CODCFO, 
		ISNULL(L.DT1,C.DTINICIO) DATAEMISSAO ,
		CP.PRAZO1,
		(C.DTINICIO+CP.PRAZO1) AS DT_VENC_REAL,
		(C.DTINICIO+CP.PRAZO1) DATAVENCIMENTO,
		C.VALORPLANEJADO VALORORIGINAL, 
		J.CODCCUSTO,
		CASE WHEN T.IDCENARIO = 0 THEN '030' ELSE '075' END CODTDO,
		
		RIGHT(REPLICATE('0',4)+CAST(T.IDPRJ AS varchar(4)),4)+RIGHT(REPLICATE('0',4)+CAST(T.IDTRF AS varchar(4)),4)+RIGHT(REPLICATE('0',3)+CAST(C.IDPERIODO AS varchar(3)),3) NUMERODOCUMENTO,
		CASE WHEN T.IDCENARIO = 1 THEN 'LINHA BASE +' ELSE '' END + T.CODTRF + ' - ' + T.NOME   HISTORICO
FROM MXMTAREFACRONOG C 
	INNER JOIN MPRJ J ON J.CODCOLIGADA = C.CODCOLIGADA AND J.IDPRJ = C.IDPRJ
	INNER JOIN MTAREFA T ON C.CODCOLIGADA = T.CODCOLIGADA AND C.IDPRJ = T.IDPRJ AND C.IDTRF = T.IDTRF
	LEFT JOIN MTRFCOMPL L ON L.CODCOLIGADA = T.CODCOLIGADA AND L.IDPRJ = T.IDPRJ AND L.IDTRF = T.IDTRF
	LEFT JOIN TCPG CP ON T.CODCOLIGADA = CP.CODCOLIGADA AND T.CODCPG = CP.CODCPG
	LEFT JOIN MISM I ON T.CODCOLIGADA = I.CODCOLIGADA AND T.IDPRJREC = I.IDPRJ AND T.IDISM = I.IDISM
	LEFT JOIN MGIS G ON I.CODCOLIGADA = G.CODCOLIGADA AND G.IDPRJ = I.IDPRJ AND I.IDGIS = G.IDGIS
WHERE 	C.CODCOLIGADA = :CODCOLIGADA
AND		C.IDPRJ = :IDPRJ
AND		T.IDCENARIO = 0
AND 	T.TIPOPLANILHA = :TIPOPLANILHA
AND		T.TIPOPLANILHA IN (0,1)
AND		ISNULL(C.VALORPLANEJADO,0) <> 0
AND		ISNULL(G.CODGIS,0) <> '01.06' /* AS TAREFAS DE HORAS NÃO DEVEM TER LANÇAMENTOS FINANCEIROS PREVISTOS */
AND 	ISNULL(I.CODISM,0) NOT IN ('01.09.01.03','01.09.01.04','01.06.01.01','01.09.01.01','01.09.01.02')
				 /* AS TAREFAS DE CUSTOS FINANCEIROS, CONTIGÊNCIA, ENGENHARIA, COMISSAO REPRESENTANTE DIRETO DELP, CARTA DE FIANCA/SEGURO GARANTIA NÃO DEVEM TER LANÇAMENTOS FINANCEIROS PREVISTOS */



SELECT CODCOLIGADA, IDLAN,DATAVENCIMENTO-1 DATACANCELAMENTO, CASE WHEN DATAVENCIMENTO < CAST(GETDATE() AS DATE) THEN GETDATE() ELSE DATAVENCIMENTO END DATAEXCLUSAO, STATUSLAN
FROM FLAN L
WHERE CODTDO = '030' AND STATUSLAN <> 2 AND CAMPOALFAOP1 LIKE RIGHT(REPLICATE('0',4)+CAST(:IDPRJ AS varchar(4)),4)+'%'
AND PAGREC = CASE WHEN 1=:TIPOPLANILHA THEN 1 ELSE 2 END
AND CODCOLIGADA=:CODCOLIGADA