USE [CORPORE_DEV]
GO
/****** Object:  StoredProcedure [dbo].[SP_DELP_EDICAOEXECUCAO]    Script Date: 31/10/2023 08:33:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SP_DELP_EDICAOEXECUCAO] @NUMPROCESSO INT
AS
BEGIN
	
	DECLARE @CODCOLIGADA INT, @CODFILIAL INT, @IDPRJ INT, @CODTRFPAI VARCHAR(30) , @EXECUCAO INT, @NUM_OS VARCHAR(30)=NULL;

	SELECT @CODCOLIGADA=CODCOLIGADA,@CODFILIAL=CODFILIAL,@NUM_OS=NUM_OS,@IDPRJ=IDPRJ_OS,
	@CODTRFPAI=CASE WHEN CODTRFEX='' THEN NULL ELSE CODTRFEX END,@EXECUCAO=CASE WHEN EXECUCAO_INFO='' THEN NULL ELSE EXECUCAO_INFO END
	FROM FLUIG.DBO.ML001007 WHERE NUMPROCESSO=@NUMPROCESSO

	-- INICIO DAS ALTERAÇÕES
	IF @NUM_OS IS NOT NULL
		BEGIN
			SELECT @IDPRJ = CAST(IDPRJ AS int), @NUM_OS = CODPRJ FROM MPRJ (NOLOCK) WHERE  CODPRJ = @NUM_OS AND POSICAO IN (1,4);
		END
	ELSE
		BEGIN
			SELECT @IDPRJ = CAST(IDPRJ_OS AS int), @NUM_OS = NUM_OS FROM FLUIG.DBO.ML001081 (NOLOCK) WHERE  NUMPROCESSO = @NUMPROCESSO AND EXCLUSIVO1 = 'FINALIZAR';	
		END


-- INICIA COM AS EXCLUSÕES DAS EDIÇÕES
	

	UPDATE O SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM FLUIG.DBO.Z_CRM_EX001005 I
		INNER JOIN KITEMORDEM O ON I.CODCOLIGADA = O.CODCOLIGADA AND I.CODFILIAL = O.CODFILIAL AND O.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND O.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI 
		INNER JOIN KORDEMCOMPL C ON C.CODCOLIGADA = O.CODCOLIGADA AND C.CODFILIAL = O.CODFILIAL AND C.CODORDEM = O.CODORDEM AND I.EXECUCAO = C.NUMEXEC
		LEFT JOIN FLUIG.DBO.Z_DELP_NECESSIDADEPAPC P ON P.CODCOLIGADA=O.CODCOLIGADA AND P.CODFILIAL=O.CODFILIAL AND P.CODORDEM=O.CODORDEM
	WHERE I.OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO AND I.CODTRFEX=@CODTRFPAI AND I.ITEMEXCLUSIVO=2 AND O.STATUS=1 AND P.NSEQPEDIDO IS NULL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO'); 
		
	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM FLUIG.DBO.Z_CRM_EX001005 I
		INNER JOIN KITEMORDEM O ON I.CODCOLIGADA = O.CODCOLIGADA AND I.CODFILIAL = O.CODFILIAL AND O.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND O.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI 
		INNER JOIN KORDEMCOMPL C ON C.CODCOLIGADA = O.CODCOLIGADA AND C.CODFILIAL = O.CODFILIAL AND C.CODORDEM = O.CODORDEM AND I.EXECUCAO = C.NUMEXEC
		INNER JOIN KORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
		LEFT JOIN FLUIG.DBO.Z_DELP_NECESSIDADEPAPC P ON P.CODCOLIGADA=O.CODCOLIGADA AND P.CODFILIAL=O.CODFILIAL AND P.CODORDEM=O.CODORDEM
	WHERE I.OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO  AND I.CODTRFEX=@CODTRFPAI AND I.ITEMEXCLUSIVO=2 AND O.STATUS=1 AND P.NSEQPEDIDO IS NULL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO'); 

	UPDATE K SET STATUS = 6, RECMODIFIEDON=GETDATE()
	FROM FLUIG.DBO.Z_CRM_EX001005 I 
		INNER JOIN KITEMORDEM O ON I.CODCOLIGADA = O.CODCOLIGADA AND I.CODFILIAL = O.CODFILIAL AND O.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND O.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI 
		INNER JOIN KORDEMCOMPL C ON C.CODCOLIGADA = O.CODCOLIGADA AND C.CODFILIAL = O.CODFILIAL AND C.CODORDEM = O.CODORDEM AND I.EXECUCAO = C.NUMEXEC
		INNER JOIN KATVORDEM K ON K.CODCOLIGADA = O.CODCOLIGADA AND K.CODFILIAL = O.CODFILIAL AND K.CODORDEM = O.CODORDEM
		LEFT JOIN FLUIG.DBO.Z_DELP_NECESSIDADEPAPC P ON P.CODCOLIGADA=O.CODCOLIGADA AND P.CODFILIAL=O.CODFILIAL AND P.CODORDEM=O.CODORDEM
	WHERE I.OS = @NUM_OS AND I.EXECUCAO = @EXECUCAO  AND I.CODTRFEX=@CODTRFPAI AND I.ITEMEXCLUSIVO=2 AND O.STATUS=1 AND P.NSEQPEDIDO IS NULL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO'); 

	UPDATE P SET INATIVO = 1, RECMODIFIEDON=GETDATE()
	FROM TPRODUTO P 
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 I ON I.IDPRD = P.IDPRD AND I.CODCOLIGADA = P.CODCOLPRD
		LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I2 ON I.OS = I2.OS AND I.IDCRIACAO = I2.IDCRIACAO
	WHERE I.OS = @NUM_OS AND I.EXECUCAO=@EXECUCAO AND I.CODTRFPAI=@CODTRFPAI AND I.ITEMEXCLUSIVO=2 AND I2.IDCRIACAO IS NULL AND NOT EXISTS( SELECT IDPRD FROM FLUIG.DBO.Z_CRM_EX001005 WHERE IDPRD=P.IDPRD AND ITEMEXCLUSIVO!=2 UNION SELECT IDPRD FROM FLUIG.DBO.Z_CRM_ML001005 WHERE IDPRD=P.IDPRD AND ITEMEXCLUSIVO!=2);
		
	UPDATE P SET STATUSESTR = 0, RECMODIFIEDON=GETDATE()
	FROM KESTRUTURA P 
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 I ON I.IDPRD = P.IDPRODUTO AND I.CODCOLIGADA = P.CODCOLIGADA
		LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I2 ON I.OS = I2.OS AND I.IDCRIACAO = I2.IDCRIACAO
	WHERE I.OS = @NUM_OS AND I.EXECUCAO=@EXECUCAO AND I.CODTRFPAI=@CODTRFPAI AND I.ITEMEXCLUSIVO=2 AND I2.IDCRIACAO IS NULL AND NOT EXISTS( SELECT IDPRD FROM FLUIG.DBO.Z_CRM_EX001005 WHERE IDPRD=P.IDPRODUTO AND ITEMEXCLUSIVO!=2 UNION SELECT IDPRD FROM FLUIG.DBO.Z_CRM_ML001005 WHERE IDPRD=P.IDPRODUTO AND ITEMEXCLUSIVO!=2);
		
	DELETE C FROM FLUIG.DBO.Z_CRM_EX001005 E
	LEFT JOIN FLUIG.DBO.Z_CRM_EX001019 C ON C.OSCOMPONENTES=E.OS AND C.EXECUCAO=E.OS AND C.IDCRIACAOCOMPONENTES=E.IDCRIACAO
	WHERE E.OS=@NUM_OS AND E.EXECUCAO=@EXECUCAO AND E.CODTRFPAI=@CODTRFPAI AND E.ITEMEXCLUSIVO=2

	DELETE A FROM FLUIG.DBO.Z_CRM_EX001005 E
	LEFT JOIN FLUIG.DBO.Z_CRM_EX001021 A ON A.OSPROCESSO=E.OS AND A.EXECUCAO=E.OS AND A.IDCRIACAOPROCESSO=E.IDCRIACAO
	WHERE E.OS=@NUM_OS AND E.EXECUCAO=@EXECUCAO AND E.CODTRFPAI=@CODTRFPAI AND E.ITEMEXCLUSIVO=2

	DELETE E FROM FLUIG.DBO.Z_CRM_EX001005 E
	WHERE E.OS=@NUM_OS AND E.EXECUCAO=@EXECUCAO AND E.CODTRFPAI=@CODTRFPAI AND E.ITEMEXCLUSIVO=2


	-- ATUALZIAÇÃO DOS PRODUTOS

		
		UPDATE P SET  P.INVENTARIOFISCAL = 1, P.TIPOTRIBUTACAO = 0, P.CODCOLCONTA = @CODCOLIGADA,
					P.SITUACAOMERCADORIA = CASE LEFT(I.CODIGOPRD,2) 
													WHEN '04' THEN '04' 
													WHEN '03' THEN '03'
													ELSE '02'  END, 
					P.CODCONTA = CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN '1.1.3.01.0003' ELSE  '1.1.3.01.0004' END 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
			INNER JOIN TPRDFISCAL (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA AND I.IDPRD = P.IDPRD
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) T ON I.OS = T.OS AND I.IDCRIACAO = T.IDCRIACAO
		WHERE T.ID IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI;

		-- NÃO ATUALIZA DESCRIÇÃO DO 04.024
		UPDATE P SET P.DESCRICAO = ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''), 
					 P.NOMEFANTASIA = LEFT(ISNULL(I.DESCRICAO,'')+' - '+ISNULL(I.POSICAODESENHO,'')+' - '+ISNULL(I.NUMDESENHO,''),120)
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN TPRODUTO (NOLOCK) P ON P.CODCOLPRD = 1 AND I.IDPRD = P.IDPRD
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) T ON I.OS = T.OS AND I.IDCRIACAO = T.IDCRIACAO
		WHERE T.ID IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND LEFT(P.CODIGOPRD,2)!='04';

		
		UPDATE P SET P.NUMNOFABRIC = I.CODIGOPRD
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN TPRODUTODEF (NOLOCK) P ON P.CODCOLIGADA = 1 AND I.IDPRD = P.IDPRD
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) T ON I.OS = T.OS AND I.IDCRIACAO = T.IDCRIACAO
		WHERE T.ID IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI;

		
		-- ###### INCIADO INTEGRACAO COM O FACTOR ######

		-- INCLUSÃO DA ESTRUTURA
	
		-- COLOCADO A ML005 PARA SÓ INCLUIR EXTRUTURA CASO SEJA CASTRADO ITEM NOVO NA EXECUCAO
		INSERT INTO KESTRUTURA (CODCOLIGADA, CODESTRUTURA, CODTIPO, IDPRODUTO, QTDLOTE, STATUSESTR, CODCCUSTO, IDFASE, FASEVALIDADA, CODIGOULTALTERACAO, VALIDACAOSOLICITADA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA, I.CODIGOPRD, CASE WHEN LEFT(I.CODIGOPRD,2) = '04' THEN 'A' ELSE 'S' END, I.IDPRD, I.DESQTDE*10000, 1, I.OS, 1, 1, 0, 0, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
			LEFT JOIN KESTRUTURA E (NOLOCK) ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE P.ID IS NULL AND E.CODESTRUTURA IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO )
		ORDER BY I.IDCRIACAO;

		INSERT INTO KLINHAEST (CODCOLIGADA, CODLINHA, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT I.CODCOLIGADA, '001', I.CODIGOPRD, I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
			LEFT JOIN KLINHAEST E (NOLOCK) ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA AND E.CODFILIAL = I.CODFILIAL
		WHERE  P.ID IS NULL AND   E.CODESTRUTURA IS NULL AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
		ORDER BY I.IDCRIACAO;

		INSERT INTO KESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODFILIAL, ELABORADOR2, ELABORADOR3, ELABORADOR, CAMDESENHO, NUMREVISAO, POSICAO, BITOLA, LARGURA, COMPRIMENTO, PESOBRUTO, PESOLIQUIDO, ESPECIFICACAOROSCA , RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
		SELECT						 I.CODCOLIGADA, I.CODIGOPRD, I.CODFILIAL, NULL ELABORADOR2, NULL ELABORADOR3, NULL ELABORADOR, 
								CASE WHEN I.NUMDESENHO = '' THEN NULL ELSE I.NUMDESENHO END, 
								CASE WHEN I.REVISAODESENHO = '' THEN NULL ELSE I.REVISAODESENHO END, 
								CASE WHEN I.POSICAODESENHO = '' THEN NULL ELSE I.POSICAODESENHO END, 
								CAST( CASE WHEN I.BITOLA = '' OR I.BITOLA = 'null' THEN NULL ELSE REPLACE(I.BITOLA,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.LARGURA = '' OR I.LARGURA = 'null' THEN NULL ELSE REPLACE(I.LARGURA,',','.') END AS FLOAT),
								CAST( CASE WHEN I.COMPRIMENTO = '' OR I.COMPRIMENTO = 'null' THEN NULL ELSE REPLACE(I.COMPRIMENTO,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.PESOBRUTO = '' OR I.PESOBRUTO = 'null' THEN NULL ELSE REPLACE(I.PESOBRUTO,',','.') END AS FLOAT), 
								CAST( CASE WHEN I.PESOLIQUIDO = '' OR I.PESOLIQUIDO = 'null' THEN NULL ELSE REPLACE(I.PESOLIQUIDO,',','.') END AS FLOAT), 
								CASE WHEN I.ESPROSCA = '' OR I.ESPROSCA = 'null' THEN NULL ELSE I.ESPROSCA END, 'fluig', GETDATE(),'fluig', GETDATE() 
		FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
			LEFT JOIN KESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE  P.ID IS NULL AND  K.CODESTRUTURA IS NULL
		AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
		ORDER BY I.IDCRIACAO;


		PRINT 'ATIVIDADES'		
		INSERT INTO KATVESTRUTURA
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, 1 HORAS, MIN( CAST(C.PRIORIDADE AS INT) ) ,
			SUM(	CAST( CASE WHEN C.FILA = '' THEN NULL ELSE REPLACE(C.FILA,',','.') END AS FLOAT) ), 
			SUM(	CAST( CASE WHEN C.CONFIGURACAO = '' THEN NULL ELSE REPLACE(C.CONFIGURACAO,',','.') END AS FLOAT) ), 
			SUM(	CAST( CASE WHEN C.PROCESSAMENTO = '' THEN NULL ELSE REPLACE(C.PROCESSAMENTO,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.DESAGREGACAO = '' THEN NULL ELSE REPLACE(C.DESAGREGACAO,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.ESPERA = '' THEN NULL ELSE REPLACE(C.ESPERA,',','.') END AS FLOAT)), 
			SUM(	CAST( CASE WHEN C.MOVIMENTACAO = '' THEN NULL ELSE REPLACE(C.MOVIMENTACAO,',','.') END AS FLOAT)),
				1,0,'P',0,NULL,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
				LEFT JOIN KATVESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE  P.ID IS NULL AND  K.CODATIVIDADE IS NULL
			AND		 @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE,I.CODFILIAL;
		
		PRINT 'FIM ATIVIDADES'	
			-- INCLUSÃO DA ETAPAS AS ATIVIDADES PARA LINHA DE PRODUÇÃO O DISTINCT É PARA NÃO INCLUIR A MESMA ATIVIDADE NA TABELA E DAR ERRO

		INSERT INTO  KETPATIVIDADES 
			SELECT DISTINCT I.CODCOLIGADA,'ETP-GLOBAL',C.CODATIVIDADE,I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
				LEFT JOIN KETPATIVIDADES (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
			WHERE  P.ID IS NULL AND  K.CODATIVIDADE IS NULL
			AND		 @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') 
			GROUP BY  I.CODCOLIGADA, I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL

			
			INSERT INTO KATVESTRUTURACOMPL (CODCOLIGADA, CODESTRUTURA, CODATIVIDADE,CODFILIAL, DETALHE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, C.CODATIVIDADE, I.CODFILIAL, C.DESCPROCESSO , 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND I.EXECUCAO = C.EXECUCAO
				LEFT JOIN KATVESTRUTURACOMPL (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL  AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI = K.CODATIVIDADE
			WHERE  P.ID IS NULL AND K.CODESTRUTURA IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI ;
	
			
			INSERT INTO KATVESTPOSTO (CODCOLIGADA, CODPOSTO, CODATIVIDADE, CODESTRUTURA, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT DISTINCT K.CODCOLIGADA, K.CODPOSTO, C.CODATIVIDADE, I.CODIGOPRD, K.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
				LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) PN ON I.OS = PN.OS AND I.IDCRIACAO = PN.IDCRIACAO
				INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
				INNER JOIN KPOSTO (NOLOCK) K ON K.CODCOLIGADA = 1 AND K.CODFILIAL = I.CODFILIAL AND K.CODPOSTO = C.CODPOSTO COLLATE SQL_Latin1_General_CP1_CI_AI
				LEFT JOIN KATVESTPOSTO (NOLOCK) P ON P.CODCOLIGADA = K.CODCOLIGADA AND P.CODFILIAL = K.CODFILIAL AND P.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI AND P.CODPOSTO = K.CODPOSTO
			WHERE  PN.ID IS NULL AND P.CODCOLIGADA IS NULL AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI ;
		
			PRINT 'COMPONENTES'	
			INSERT INTO KCOMPONENTE (CODCOLIGADA, CODESTRUTURA, IDPRODUTO, IDAUTOINC, QTDUSADA, CODATIVIDADE, OBRIGASERMATERIAPRIMA, FAZPARTEMODELOBASE, PERMITEEXCLUSAO, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON )

			SELECT  COMPONENTES.CODCOLIGADA, CODIGOPRD, IDPRD, (SELECT MAX(IDAUTOINC) FROM KCOMPONENTE)+ ROW_NUMBER () OVER (ORDER BY IDPRD), COMPONENTES.QTD* 10000,
						ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
								) ATIVIDADE,
					1, 0, 0, COMPONENTES.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM (
				SELECT  I.CODIGOPRD, E.IDPRD,  CAST(E.DESQTDE AS float) QTD, I.IDCRIACAOPAI, I.IDCRIACAO, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) E ON I.OS = E.OS AND I.IDCRIACAO = E.IDCRIACAOPAI  AND E.EXECUCAO = I.EXECUCAO
					LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P2 ON I.OS = P2.OS AND I.IDCRIACAO = P2.IDCRIACAO
				WHERE P2.CODCOLIGADA IS NULL AND   @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0 AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO )
		
				UNION ALL
		
				SELECT I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.IDCRIACAOPAI, I.IDCRIACAO, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI 
				FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
					LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P2 ON I.OS = P2.OS AND I.IDCRIACAO = P2.IDCRIACAO
				WHERE P2.CODCOLIGADA IS NULL AND   ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND   @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI 
			
				UNION ALL

					-- CODIGOS NÃO MANUFATURADO
				SELECT P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT)  QTD, I.IDCRIACAOPAI, I.IDCRIACAO, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI
				FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAOPAI  AND P.EXECUCAO = I.EXECUCAO
					LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P2 ON I.OS = P2.OS AND I.IDCRIACAO = P2.IDCRIACAO
				WHERE P2.CODCOLIGADA IS NULL AND ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND   @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO = 'NAOMANUFATURADO' 


			
			) AS COMPONENTES
			LEFT JOIN KCOMPONENTE (NOLOCK) C ON COMPONENTES.CODCOLIGADA = C.CODCOLIGADA 
											AND COMPONENTES.CODFILIAL = C.CODFILIAL 
											AND COMPONENTES.CODIGOPRD = C.CODESTRUTURA COLLATE Latin1_General_CI_AS 
											AND COMPONENTES.IDPRD = C.IDPRODUTO
											AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE ) END
								) = C.CODATIVIDADE
			WHERE C.IDPRODUTO IS NULL AND  IDPRD <> '' 
			AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			
			ORDER BY IDCRIACAO;

			PRINT ' FIM COMPONENTES'

			-- INSERE OS PRODUTOS SUBSTITUTOS

			INSERT INTO  KCOMPSUBSTITUTO
			SELECT SUB.CODCOLIGADA, SUB.CODESTRUTURA, SUB.CODATIVIDADE, SUB.IDAUTOINC, SUB.IDPRD, SUB.IDPRDCOMPONENTES, SUB.QTDUSADA*10000, NULL, NULL, 0,  SUB.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE()
			FROM (
					SELECT 'A' TIPO, I.IDCRIACAOPAI, I.IDCRIACAO, K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
						FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) I
						INNER JOIN FLUIG.DBO.Z_CRM_EX001021 (NOLOCK) A ON I.OS = A.OSPROCESSO AND I.IDCRIACAO = A.IDCRIACAOPROCESSO AND I.EXECUCAO = A.EXECUCAO
						INNER JOIN FLUIG.DBO.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO AND A.PRIORIDADE = C.PRIORIDADEATVCOMPONENTES
						INNER JOIN TPRD P ON P.CODCOLIGADA = I.CODCOLIGADA AND P.CODIGOPRD  COLLATE Latin1_General_CI_AS = C.SUBSTITUTOCOMPONENTES
						INNER JOIN KCOMPONENTE (NOLOCK) K ON  P.IDPRD = K.IDPRODUTO 	AND P.CODCOLIGADA = K.CODCOLIGADA AND K.CODESTRUTURA COLLATE Latin1_General_CI_AS = I.CODIGOPRD AND K.CODFILIAL = I.CODFILIAL AND K.CODATIVIDADE COLLATE Latin1_General_CI_AS = A.CODATIVIDADE
						INNER JOIN KESTRUTURA (NOLOCK) E ON K.CODCOLIGADA = E.CODCOLIGADA AND K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA AND E.CODCCUSTO COLLATE Latin1_General_CI_AS = I.OS  AND E.RECCREATEDBY = 'fluig'
						LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P2 ON I.OS = P2.OS AND I.IDCRIACAO = P2.IDCRIACAO
					WHERE P2.CODCOLIGADA IS NULL AND  C.PRIORIDADEATVCOMPONENTES <> 0 AND E.STATUSESTR = 1 AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> ''
		
			UNION ALL

					SELECT 'B' TIPO, I.IDCRIACAOPAI, I.IDCRIACAO,  K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
					FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) I
						INNER JOIN FLUIG.DBO.Z_CRM_EX001021 (NOLOCK) A ON I.OS = A.OSPROCESSO AND I.IDCRIACAO = A.IDCRIACAOPROCESSO AND I.EXECUCAO = A.EXECUCAO
						INNER JOIN FLUIG.DBO.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO AND A.PRIORIDADE = C.PRIORIDADEATVCOMPONENTES
						INNER JOIN KESTRUTURA (NOLOCK) E ON I.CODCOLIGADA = E.CODCOLIGADA AND I.CODFILIAL = E.CODFILIAL AND I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI = E.CODESTRUTURA
						INNER JOIN KCOMPONENTE (NOLOCK) K ON  E.CODCOLIGADA = K.CODCOLIGADA AND  K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
						INNER JOIN TPRD (NOLOCK) P ON K.CODCOLIGADA = P.CODCOLIGADA AND K.IDPRODUTO = P.IDPRD
						LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P2 ON I.OS = P2.OS AND I.IDCRIACAO = P2.IDCRIACAO
				WHERE P2.CODCOLIGADA IS NULL AND  C.PRIORIDADEATVCOMPONENTES = 0 AND E.STATUSESTR = 1 AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> '' 
				
			UNION ALL 

					SELECT 'A' TIPO, I.IDCRIACAOPAI, I.IDCRIACAO, K.CODCOLIGADA, K.CODESTRUTURA, K.CODATIVIDADE, K.IDAUTOINC, P2.IDPRD, C.IDPRDCOMPONENTES, K.QTDUSADA, K.CODFILIAL
					FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) I
						INNER JOIN FLUIG.DBO.Z_CRM_EX001021 (NOLOCK) A ON I.OS = A.OSPROCESSO AND I.IDCRIACAO = A.IDCRIACAOPROCESSO AND I.EXECUCAO = A.EXECUCAO
						INNER JOIN FLUIG.DBO.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO AND A.PRIORIDADE = C.PRIORIDADEATVCOMPONENTES
						INNER JOIN FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAOPAI AND I.EXECUCAO=P.EXECUCAO
						INNER JOIN KESTRUTURA (NOLOCK) E ON P.CODCOLIGADA = E.CODCOLIGADA AND P.CODFILIAL = E.CODFILIAL AND P.CODIGOPRD COLLATE SQL_LATIN1_GENERAL_CP1_CI_AI = E.CODESTRUTURA
						INNER JOIN KCOMPONENTE (NOLOCK) K ON  E.CODCOLIGADA = K.CODCOLIGADA AND  K.CODFILIAL = E.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
						INNER JOIN TPRD (NOLOCK) P2 ON K.CODCOLIGADA = P2.CODCOLIGADA AND K.IDPRODUTO = P2.IDPRD
						LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) P3 ON I.OS = P3.OS AND I.IDCRIACAO = P3.IDCRIACAO
					WHERE P3.CODCOLIGADA IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO = 'NAOMANUFATURADO' AND ISNULL(C.SUBSTITUTOCOMPONENTES,'') <> '' AND E.STATUSESTR = 1

				) SUB
			LEFT JOIN KCOMPSUBSTITUTO (NOLOCK) S ON S.CODCOLIGADA = SUB.CODCOLIGADA AND S.CODFILIAL = SUB.CODFILIAL AND S.CODESTRUTURA = SUB.CODESTRUTURA AND S.CODATIVIDADE = SUB.CODATIVIDADE AND S.IDAUTOINC = SUB.IDAUTOINC AND S.IDPRDORIGEM = SUB.IDPRD AND S.IDPRD = SUB.IDPRDCOMPONENTES
			WHERE S.CODCOLIGADA IS NULL
			ORDER BY SUB.CODESTRUTURA, SUB.CODATIVIDADE, SUB.IDPRD, SUB.IDPRDCOMPONENTES;
		
	UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM (NOLOCK) WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	
	-- GERANDO ORDENS E CRONOGRAMA
	
			INSERT INTO KORDEM (CODCOLIGADA, CODCCUSTO,  CODORDEM, DSCORDEM, RESPONSAVEL, DTHRINICIALPREV, STATUS, DTHRFINALPREV, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA, I.OS, RIGHT(REPLICATE('0',5) +CAST( ROW_NUMBER() OVER (ORDER BY I.IDCRIACAO) + (SELECT VALAUTOINC FROM GAUTOINC WHERE CODAUTOINC = 'KORDEM-'+CAST(I.CODFILIAL AS VARCHAR(2))) AS varchar(MAX)),5)+'/'+RIGHT(CAST(YEAR(GETDATE()) AS varchar(MAX)),2),
						LEFT(P.DESCRICAO,80), P.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI , GETDATE(), 0, GETDATE(), I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN TPRD (NOLOCK) P ON P.CODCOLIGADA = I.CODCOLIGADA  AND I.IDPRD = P.IDPRD
					INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.IDPRODUTO = P.IDPRD AND K.CODESTRUTURA = P.CODIGOPRD				
					LEFT JOIN ( SELECT OI.CODCOLIGADA , OI.CODFILIAL, OI.CODESTRUTURA, O.RESPONSAVEL, O.CODORDEM
								FROM KITEMORDEM (NOLOCK) OI
									INNER JOIN KORDEM (NOLOCK) O ON  O.CODCOLIGADA = OI.CODCOLIGADA AND O.CODFILIAL = OI.CODFILIAL AND O.CODORDEM = OI.CODORDEM
								WHERE CHARINDEX(';',RESPONSAVEL) <> 0 ) ORDEM ON K.CODCOLIGADA = ORDEM.CODCOLIGADA AND K.CODFILIAL = ORDEM.CODFILIAL AND K.CODESTRUTURA = ORDEM.CODESTRUTURA AND ORDEM.RESPONSAVEL = P.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI
			WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND ORDEM.CODORDEM IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND  I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			ORDER BY I.IDCRIACAO
		
					

			UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM  (NOLOCK) WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	

			INSERT INTO KMODELO
			SELECT I.CODCOLIGADA,  I.CODIGOPRD, 'Base','Modelo Base',I.CODFILIAL, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM   FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN KESTRUTURA E ON E.CODCOLIGADA = I.CODCOLIGADA AND E.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
					LEFT JOIN KMODELO (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = E.CODESTRUTURA
			WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND K.CODESTRUTURA IS NULL
			AND	@NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			ORDER BY I.IDCRIACAO;
		

			INSERT INTO KITEMORDEM(CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, CODLINHA, STATUS, QTDEPLANEJADA, DTHRINICIALPREV, DTHRFINALPREV, IDITEMORDEM, TIPOAPONTAMENTO, CODFILIAL, CODCCUSTO,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
			SELECT I.CODCOLIGADA, O.CODORDEM,
					K.CODESTRUTURA, 'base', '001', 0,CASE WHEN LEFT(K.CODESTRUTURA,2) = '04' THEN 1 ELSE CAST(I.TOTALQTDE AS float) END, GETDATE(), GETDATE(), ROW_NUMBER() OVER (ORDER BY K.CODESTRUTURA)+(SELECT MAX(IDITEMORDEM) FROM KITEMORDEM), 1, I.CODFILIAL, I.OS, 'fluig', GETDATE(),'fluig', GETDATE() 
			FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
					INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI
					LEFT JOIN KITEMORDEM (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND K.CODESTRUTURA = OI.CODESTRUTURA AND OI.CODORDEM = O.CODORDEM
			WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND OI.CODORDEM IS NULL AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
			ORDER BY I.IDCRIACAO;

		
		-- ATUALIZA AS ITEM ORDENS JÁ CADASTRADAS

		UPDATE  OI SET QTDEPLANEJADA = CAST(I.TOTALQTDE AS float), RECCREATEDBY='fluig',RECCREATEDON= GETDATE(),RECMODIFIEDBY='fluig', RECMODIFIEDON=GETDATE() 
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
			INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
			INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
			INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS
			INNER JOIN KITEMORDEM (NOLOCK) OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND K.CODESTRUTURA = OI.CODESTRUTURA AND OI.CODORDEM = O.CODORDEM
		WHERE ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  );

		UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	
		INSERT INTO KORDEMCOMPL (CODCOLIGADA, CODORDEM, CODFILIAL, NUMEXEC, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
				SELECT I.CODCOLIGADA, O.CODORDEM, O.CODFILIAL, I.EXECUCAO, 'fluig', GETDATE(),'fluig', GETDATE() 
				FROM FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
					INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS
					LEFT JOIN KORDEMCOMPL (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND OI.CODORDEM = O.CODORDEM
				WHERE  OI.CODORDEM IS NULL AND ISNULL(I.OPSUNITARIAS,'') <> 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
				ORDER BY I.IDCRIACAO;

		
-- CRIAR ORDENS INDIVIDUAIS

			DECLARE @CODESTRUTURA VARCHAR(MAX), @QTDDESENHO INT, @NUMPROCESSO_ORIGINAL INT

			DECLARE INDIVIDUAL CURSOR FOR 	SELECT DISTINCT K.CODESTRUTURA,  CAST(I.TOTALQTDE AS float) , M.NUMPROCESSO
											FROM FLUIG.DBO.ML001004 (NOLOCK) M
												INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
												INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
											WHERE ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
											ORDER BY K.CODESTRUTURA;
			
			
			OPEN INDIVIDUAL;

			FETCH NEXT FROM INDIVIDUAL INTO @CODESTRUTURA, @QTDDESENHO, @NUMPROCESSO_ORIGINAL;

			WHILE @@FETCH_STATUS = 0 
			BEGIN
				DECLARE @INDIVIDUAL INT = 1;
				WHILE @INDIVIDUAL <= @QTDDESENHO
				BEGIN
							
					INSERT INTO KORDEM (CODCOLIGADA, CODCCUSTO,  CODORDEM, DSCORDEM, RESPONSAVEL, DTHRINICIALPREV, STATUS, DTHRFINALPREV, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
					SELECT I.CODCOLIGADA, M.NUM_OS, RIGHT(REPLICATE('0',5) +CAST( ROW_NUMBER() OVER (ORDER BY I.IDCRIACAO) + (SELECT VALAUTOINC FROM GAUTOINC WHERE CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))) AS varchar(MAX)),5)+'/'+RIGHT(CAST(YEAR(GETDATE()) AS varchar(MAX)),2),
								LEFT(P.DESCRICAO,80), P.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX)), GETDATE(), 0, GETDATE(), I.CODFILIAL,'fluig', GETDATE(),'fluig',GETDATE()
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
							INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on M.NUM_OS = I.OS
							INNER JOIN TPRD (NOLOCK) P ON P.CODCOLIGADA = i.CODCOLIGADA  AND I.IDPRD = P.IDPRD
							INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.IDPRODUTO = P.IDPRD					
							LEFT JOIN ( SELECT OI.CODCOLIGADA , OI.CODFILIAL, OI.CODESTRUTURA, O.RESPONSAVEL, O.CODORDEM
										FROM KITEMORDEM (NOLOCK) OI
											INNER JOIN KORDEM (NOLOCK) O ON  O.CODCOLIGADA = OI.CODCOLIGADA AND O.CODFILIAL = OI.CODFILIAL AND O.CODORDEM = OI.CODORDEM
										WHERE O.RESPONSAVEL =  OI.CODESTRUTURA+';'+CAST(@NUMPROCESSO_ORIGINAL AS VARCHAR(10))+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX))) ORDEM ON K.CODCOLIGADA = ORDEM.CODCOLIGADA AND K.CODFILIAL = ORDEM.CODFILIAL AND K.CODESTRUTURA = ORDEM.CODESTRUTURA
							LEFT JOIN KORDEM (NOLOCK) Z ON Z.CODCOLIGADA = ORDEM.CODCOLIGADA AND Z.CODFILIAL = ORDEM.CODFILIAL AND Z.CODORDEM = ORDEM.CODORDEM
					WHERE ORDEM.CODORDEM IS NULL AND K.CODESTRUTURA = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
					ORDER BY I.IDCRIACAO
		
				
					UPDATE GAUTOINC SET VALAUTOINC = (SELECT MAX(CAST(LEFT(CODORDEM, CHARINDEX('/',CODORDEM)-1) AS int)) FROM KORDEM WHERE CODCOLIGADA = @CODCOLIGADA AND CODFILIAL = @CODFILIAL) WHERE CODCOLIGADA = @CODCOLIGADA AND CODAUTOINC = 'KORDEM-'+CAST(@CODFILIAL AS VARCHAR(2))
	

					INSERT INTO KMODELO
					SELECT I.CODCOLIGADA,  I.CODIGOPRD, 'Base','Modelo Base',I.CODFILIAL, 'fluig', GETDATE(),'fluig',GETDATE() 
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on M.NUM_OS = I.OS
						LEFT JOIN KMODELO (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD  COLLATE SQL_Latin1_General_CP1_CI_AI
					WHERE I.CODIGOPRD = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND K.CODESTRUTURA IS NULL
					AND	I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO )
					ORDER BY I.IDCRIACAO;
			
						
					INSERT INTO KITEMORDEM(CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, CODLINHA, STATUS, QTDEPLANEJADA, DTHRINICIALPREV, DTHRFINALPREV, IDITEMORDEM, TIPOAPONTAMENTO, CODFILIAL, CODCCUSTO,  RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
					SELECT I.CODCOLIGADA, O.CODORDEM,
							K.CODESTRUTURA, 'base', '001', 0, 1 QTDE_INDIVIDUAL, GETDATE(), GETDATE(), ROW_NUMBER() OVER (ORDER BY K.CODESTRUTURA)+(SELECT MAX(IDITEMORDEM) FROM KITEMORDEM), 1, I.CODFILIAL, M.NUM_OS, 'fluig', GETDATE(),'fluig', GETDATE()
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
						INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
						INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX))
						LEFT JOIN KITEMORDEM (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND K.CODESTRUTURA = OI.CODESTRUTURA AND OI.CODORDEM = O.CODORDEM
					WHERE K.CODESTRUTURA = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND OI.CODORDEM IS NULL AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
					ORDER BY I.IDCRIACAO;


					INSERT INTO KORDEMCOMPL (CODCOLIGADA, CODORDEM, CODFILIAL, NUMEXEC, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
					SELECT I.CODCOLIGADA, O.CODORDEM, O.CODFILIAL, @EXECUCAO, 'fluig', GETDATE(),'fluig',GETDATE()
					FROM FLUIG.DBO.ML001004 (NOLOCK) M
						INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I on  M.NUM_OS = I.OS
						INNER JOIN KESTRUTURA (NOLOCK) K ON K.CODCOLIGADA = I.CODCOLIGADA AND K.CODFILIAL = I.CODFILIAL AND K.CODESTRUTURA = I.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
						INNER JOIN KORDEM (NOLOCK) O ON O.RESPONSAVEL = I.CODIGOPRD+';'+M.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(@EXECUCAO AS varchar(10))+'/'+@CODTRFPAI+'|'+CAST(@INDIVIDUAL AS VARCHAR(MAX))
						LEFT JOIN KORDEMCOMPL (NOLOCK)  OI ON K.CODCOLIGADA = OI.CODCOLIGADA AND K.CODFILIAL = OI.CODFILIAL AND OI.CODORDEM = O.CODORDEM
					WHERE K.CODESTRUTURA = @CODESTRUTURA AND ISNULL(I.OPSUNITARIAS,'') = 'SIM' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND OI.CODORDEM IS NULL  AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
					ORDER BY I.IDCRIACAO;

			 
			
				 SET @INDIVIDUAL += 1;
				END;
				
				FETCH NEXT FROM INDIVIDUAL INTO @CODESTRUTURA, @QTDDESENHO, @NUMPROCESSO_ORIGINAL;
			END
			CLOSE INDIVIDUAL;
			DEALLOCATE INDIVIDUAL;
	
	
	DELETE MP
	FROM   FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KATVORDEMMP (NOLOCK) MP ON MP.CODCOLIGADA = O.CODCOLIGADA AND MP.CODFILIAL = O.CODFILIAL AND MP.CODORDEM = O.CODORDEM 
		INNER JOIN KATVORDEM (NOLOCK) A ON A.CODCOLIGADA = O.CODCOLIGADA AND A.CODFILIAL = O.CODFILIAL AND A.CODORDEM = O.CODORDEM AND A.IDATVORDEM=MP.IDATIVIDADE
		LEFT JOIN KATVORDEMMP (NOLOCK) MP2 ON MP2.CODCOLIGADA = O.CODCOLIGADA AND MP2.CODFILIAL = O.CODFILIAL AND MP2.CODORDEM = O.CODORDEM AND MP2.EFETIVADO=1
		LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE PA ON PA.CODCOLIGADA=O.CODCOLIGADA AND PA.CODFILIAL=O.CODFILIAL AND PA.CODORDEM=O.CODORDEM AND PA.CODATIVIDADE=A.CODATIVIDADE
	WHERE ISNULL(O.REPROCESSAMENTO,0) <> 1 AND MP.EFETIVADO = 0 AND MP2.EFETIVADO IS NULL AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND PA.CODORDEM IS NULL

	PRINT 'DELETA MP ADICIONAIS '+CAST(@@ROWCOUNT AS VARCHAR(MAX));

	DELETE C 
	FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KATVORDEM (NOLOCK) K ON O.CODCOLIGADA = K.CODCOLIGADA AND O.CODORDEM = K.CODORDEM AND O.CODFILIAL = K.CODFILIAL
		INNER JOIN KATVORDEMCOMPL (NOLOCK) C ON C.CODCOLIGADA = K.CODCOLIGADA AND C.CODORDEM = K.CODORDEM AND C.CODFILIAL = K.CODFILIAL AND C.IDATVORDEM = K.IDATVORDEM
		LEFT JOIN FLUIG.DBO.Z_DELP_NECESSIDADEPAPC PA ON PA.CODCOLIGADA=K.CODCOLIGADA AND PA.CODFILIAL=K.CODFILIAL AND PA.CODORDEM=K.CODORDEM AND PA.CODATIVIDADE=K.CODATIVIDADE
	WHERE ISNULL(O.REPROCESSAMENTO,0) <> 1 AND K.STATUS = 0 AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND PA.CODORDEM IS NULL 
	
	PRINT 'DELETA CAMPO COMPLEMENTARES ADICIONAIS '+CAST(@@ROWCOUNT AS VARCHAR(MAX));

	DELETE K 
	FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I.EXECUCAO AS varchar(10))+'/'+I.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KATVORDEM (NOLOCK) K ON O.CODCOLIGADA = K.CODCOLIGADA AND O.CODORDEM = K.CODORDEM AND O.CODFILIAL = K.CODFILIAL
		LEFT JOIN FLUIG.DBO.Z_DELP_NECESSIDADEPAPC PA ON PA.CODCOLIGADA=K.CODCOLIGADA AND PA.CODFILIAL=K.CODFILIAL AND PA.CODORDEM=K.CODORDEM AND PA.CODATIVIDADE=K.CODATIVIDADE
	WHERE ISNULL(O.REPROCESSAMENTO,0) <> 1 AND K.STATUS = 0 AND  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND PA.CODORDEM IS NULL 

	PRINT 'DELETA KATVORDEM  ADICIONAIS '+CAST(@@ROWCOUNT AS VARCHAR(MAX));

	INSERT INTO  KATVORDEM (CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, CODATIVIDADE, CODETAPA, CODESTRUTURAFEITA, CODPOSTO, DTHRINICIOPREV, DTHRFINALPREV, QTESTOQUE, QTPREVISTA, QUANTIDADE,PERCENTUAL, STATUS, IDATVORDEM, IDATVDEPEND, TEMPO, DTHORAIDEAL, TIPODELAY, CODMODELOFEITO, CODFILIAL, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON)
	SELECT O.CODCOLIGADA, O.CODORDEM, I.CODESTRUTURA, I.CODMODELO, C.CODATIVIDADE, 'ETP-GLOBAL' , I.CODESTRUTURA, C.CODPOSTO, I.DTHRINICIALPREV, I.DTHRFINALPREV, 0, I.QTDEPLANEJADA, 0, 0, 0,ROW_NUMBER() OVER ( PARTITION BY O.CODCOLIGADA, O.CODORDEM ORDER BY O.CODCOLIGADA, O.CODORDEM, C.PRIORIDADE)+ISNULL((SELECT MAX(IDATVORDEM) FROM KATVORDEM ATV WHERE ATV.CODCOLIGADA = O.CODCOLIGADA AND ATV.CODFILIAL = O.CODFILIAL AND ATV.CODORDEM = O.CODORDEM),0), -1, (ISNULL(C.FILA,0)+ISNULL(C.CONFIGURACAO,0)+ISNULL(CAST(C.PROCESSAMENTO AS INT),0)+ISNULL(C.DESAGREGACAO,0)+ISNULL(C.ESPERA,0)+ISNULL(C.MOVIMENTACAO,0)) * I.QTDEPLANEJADA,I.DTHRFINALPREV, -1, I.CODMODELO, I.CODFILIAL, 'fluig',getdate(),'fluig',getdate() 
	FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I5 
		INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I5.OS
		INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I5.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I5.IDCRIACAO  AND C.EXECUCAO = I5.EXECUCAO
		INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I5.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I5.EXECUCAO AS varchar(10))+'/'+I5.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
		LEFT JOIN KATVORDEM (NOLOCK) AO ON AO.CODCOLIGADA = O.CODCOLIGADA AND AO.CODFILIAL = O.CODFILIAL AND AO.CODORDEM = O.CODORDEM AND AO.CODESTRUTURA = I.CODESTRUTURA AND AO.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
	WHERE AO.CODATIVIDADE IS NULL AND @NUM_OS = I5.OS AND @EXECUCAO = I5.EXECUCAO AND @CODTRFPAI = I5.CODTRFPAI
	ORDER BY O.CODCOLIGADA, O.CODORDEM, C.PRIORIDADE;

	PRINT 'INSERE KATVORDEM  ADICIONAIS'+CAST(@@ROWCOUNT AS VARCHAR(MAX));


	-- ATUALIZA OS TEMPOS (CAMPO TEMPO) DAS ATIVIDADES DAS ORDENS DE PRODUÇÃO (COM STATUS 0,2 E 3) COM BASE NOS TEMPOS (CAMPO PROCESSAMENTO) DA EX0010213
	-- INSERIDO PELO WAGNER NOBRE DIA 22/11/2022

	UPDATE AO SET TEMPO = (AO.QTPREVISTA * C.PROCESSAMENTO) 
		FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I5 
			INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I5.OS
			INNER JOIN FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C ON I5.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I5.IDCRIACAO  AND C.EXECUCAO = I5.EXECUCAO
			INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE I5.CODIGOPRD+';'+Z.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(I5.EXECUCAO AS varchar(10))+'/'+I5.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
			INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
			INNER JOIN KATVORDEM (NOLOCK) AO ON AO.CODCOLIGADA = O.CODCOLIGADA AND AO.CODFILIAL = O.CODFILIAL AND AO.CODORDEM = O.CODORDEM AND AO.CODESTRUTURA = I.CODESTRUTURA AND AO.CODATIVIDADE = C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE  I5.OS = @NUM_OS AND I5.CODTRFPAI = @CODTRFPAI AND I5.EXECUCAO = @EXECUCAO AND AO.STATUS IN (0,2,3)


	-- MATERIA PRIMA DAS ATIVIDADES DA ORDENS

	INSERT INTO KATVORDEMMP
		SELECT 
		(SELECT VALAUTOINC 
		FROM GAUTOINC  (NOLOCK)
		WHERE CODAUTOINC = 'IDATVORDEMMATERIAPRIMA' 
		AND CODSISTEMA = 'K' 
		AND CODCOLIGADA = 0) + ROW_NUMBER() OVER (ORDER BY C.CODCOLIGADA) ID, 
	A.CODCOLIGADA, A.CODORDEM, A.CODESTRUTURA, A.CODMODELO, A.IDATVORDEM, A.DTHRINICIOPREV DTAPONTAMENTO, C.IDPRD, NULL NSEQITMGRD, ISNULL(C.QTD,0) * ISNULL(I.QTDEPLANEJADA,0) QTD,
	0 EFETIVADO, NULL IDLOTE, A.CODFILIAL, ISNULL(C.QTD,0), 0 QTFIXA, 
		ISNULL((SELECT SALDOGERALFISICO FROM TPRD (NOLOCK) WHERE CODCOLIGADA = A.CODCOLIGADA AND  IDPRD = C.IDPRD),0) ESTOQUE, 'fluig',GETDATE(), 'fluig', GETDATE(),
	NULL ESTOQUETERCEIRO, NULL CODCOLCFO, NULL CODCFO, NULL CODFILIALMP, NULL CODLOCAL
	FROM (
			SELECT  CODCOLIGADA, CODIGOPRD, IDPRD, QTD,
										ISNULL((SELECT TOP 1 CODATIVIDADE FROM FLUIG.DBO.Z_CRM_EX001021 E21 WHERE E21.OSPROCESSO = COMPONENTES.OS AND E21.IDCRIACAOPROCESSO = COMPONENTES.IDCRIACAO AND E21.EXECUCAO = COMPONENTES.EXECUCAO AND E21.PRIORIDADE = COMPONENTES.PRIORIDADE),
							CASE WHEN LEFT(CODIGOPRD,2) <> '03'
								THEN (SELECT TOP 1 CODATIVIDADE FROM FLUIG.DBO.Z_CRM_EX001021 E21 WHERE E21.OSPROCESSO = COMPONENTES.OS AND E21.IDCRIACAOPROCESSO = COMPONENTES.IDCRIACAO AND E21.EXECUCAO = COMPONENTES.EXECUCAO ORDER BY E21.PRIORIDADE DESC)
								ELSE (SELECT TOP 1 CODATIVIDADE FROM FLUIG.DBO.Z_CRM_EX001021 E21 WHERE E21.OSPROCESSO = COMPONENTES.OS AND E21.IDCRIACAOPROCESSO = COMPONENTES.IDCRIACAO AND E21.EXECUCAO = COMPONENTES.EXECUCAO ORDER BY E21.PRIORIDADE ) END
								) CODATIVIDADE,
					COMPONENTES.CODFILIAL, EXECUCAO, CODTRFPAI, NUMPROCESSO 
			FROM (
				SELECT  I.CODIGOPRD, E.IDPRD,  CAST(E.DESQTDE AS float) QTD, I.IDCRIACAOPAI, I.IDCRIACAO, NULL PRIORIDADE, E.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO, I.OS
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) E ON I.OS = E.OS AND I.IDCRIACAO = E.IDCRIACAOPAI  AND E.EXECUCAO = I.EXECUCAO
				WHERE  @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO NOT IN ('NAOMANUFATURADO','INDUSTRIALIZACAO') AND COALESCE(E.ITEMDERETORNO,0)=0 
				AND EXISTS (SELECT C.CODATIVIDADE FROM FLUIG.dbo.Z_CRM_EX001021 (NOLOCK) C WHERE I.OS = C.OSPROCESSO AND C.IDCRIACAOPROCESSO = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO  )
		
				UNION ALL
		
				SELECT I.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT) QTD, I.IDCRIACAOPAI, I.IDCRIACAO, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO , I.OS
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I 
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO AND C.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI
			
				UNION ALL

					-- CODIGOS NÃO MANUFATURADO
				SELECT P.CODIGOPRD, C.IDPRDCOMPONENTES IDPRD,  CAST(REPLACE(C.QTDEUNCOMPONENTES,',','.') AS FLOAT)  QTD, I.IDCRIACAOPAI, I.IDCRIACAO, C.PRIORIDADEATVCOMPONENTES PRIORIDADE, I.CODFILIAL, I.CODCOLIGADA,I.EXECUCAO, I.CODTRFPAI, Z.NUMPROCESSO, I.OS
				FROM  FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) I
					INNER JOIN FLUIG.DBO.ML001004 (NOLOCK) Z ON Z.NUM_OS = I.OS
					INNER JOIN FLUIG.dbo.Z_CRM_EX001019 (NOLOCK) C ON I.OS = C.OSCOMPONENTES AND C.IDCRIACAOCOMPONENTES = I.IDCRIACAO  AND C.EXECUCAO = I.EXECUCAO
					INNER JOIN FLUIG.dbo.Z_CRM_EX001005 (NOLOCK) P ON I.OS = P.OS AND I.IDCRIACAO = P.IDCRIACAOPAI  AND P.EXECUCAO = I.EXECUCAO
				WHERE  ISNULL(SUBSTITUTOCOMPONENTES,'') = '' AND @NUM_OS = I.OS AND @EXECUCAO = I.EXECUCAO AND @CODTRFPAI = I.CODTRFPAI AND I.TIPODESENHO = 'NAOMANUFATURADO' 

			
			) AS COMPONENTES
			WHERE IDPRD <> ''
			AND ISNULL((SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL AND PRIORIDADE = ISNULL(COMPONENTES.PRIORIDADE,PRIORIDADE) ORDER BY PRIORIDADE),
							(SELECT TOP 1 CODATIVIDADE FROM KATVESTRUTURA (NOLOCK) WHERE CODCOLIGADA = COMPONENTES.CODCOLIGADA AND CODESTRUTURA = COMPONENTES.CODIGOPRD COLLATE Latin1_General_CI_AS AND CODFILIAL = COMPONENTES.CODFILIAL ORDER BY PRIORIDADE)) IS NOT NULL
			) AS C

			INNER JOIN KORDEM (NOLOCK) O  ON O.RESPONSAVEL LIKE C.CODIGOPRD+';'+C.NUMPROCESSO COLLATE Latin1_General_CI_AS+'-'+CAST(C.EXECUCAO AS varchar(10))+'/'+C.CODTRFPAI COLLATE Latin1_General_CI_AS+'%'
			INNER JOIN KITEMORDEM (NOLOCK) I ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
			INNER JOIN KATVORDEM (NOLOCK) A ON O.CODCOLIGADA = A.CODCOLIGADA AND O.CODFILIAL = A.CODFILIAL AND O.CODORDEM = A.CODORDEM AND C.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI = A.CODATIVIDADE
			LEFT JOIN KATVORDEMMP (NOLOCK) MP ON MP.CODCOLIGADA = O.CODCOLIGADA AND MP.CODFILIAL = O.CODFILIAL AND MP.CODORDEM = O.CODORDEM AND A.IDATVORDEM = MP.IDATIVIDADE AND MP.IDPRODUTO = C.IDPRD AND MP.EFETIVADO = 0
		WHERE MP.CODCOLIGADA IS NULL AND O.STATUS NOT IN (5,6) AND I.STATUS NOT IN (5,6)
	
	UPDATE GAUTOINC SET VALAUTOINC  = (SELECT MAX(IDATVORDEMMATERIAPRIMA) FROM KATVORDEMMP)
	WHERE CODAUTOINC = 'IDATVORDEMMATERIAPRIMA' 
	AND CODSISTEMA = 'K' 
	AND CODCOLIGADA = 0;

	INSERT INTO KATVORDEMCOMPL (CODCOLIGADA, CODORDEM, CODESTRUTURA, CODMODELO, IDATVORDEM, CODFILIAL, CAUSADOR, NUMERORNC2, RNCRR, RETRABALHO, PRIORIDADE, RECCREATEDBY, RECCREATEDON, RECMODIFIEDBY, RECMODIFIEDON )
	SELECT O.CODCOLIGADA, O.CODORDEM, I.CODESTRUTURA, I.CODMODELO, Z.IDATVORDEM, O.CODFILIAL, NULL CODCLIENTECAUSADOR, NULL NUMRNC,  NULL CODCLIENTERNCRR,  NULL CODCLIENTECAUSA, A.PRIORIDADE, 'fluig',getdate(),'fluig',getdate() 
	FROM KORDEM O (NOLOCK)
		INNER JOIN KITEMORDEM I (NOLOCK) ON O.CODCOLIGADA = I.CODCOLIGADA AND O.CODFILIAL = I.CODFILIAL AND O.CODORDEM = I.CODORDEM
		INNER JOIN FLUIG.DBO.ML001004 F (NOLOCK) ON F.NUM_OS = O.CODCCUSTO COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN FLUIG.DBO.Z_CRM_EX001005 M (NOLOCK) ON F.NUM_OS = M.OS AND O.RESPONSAVEL LIKE M.CODIGOPRD+';'+F.NUMPROCESSO COLLATE Latin1_General_CI_AS+'%'
		INNER JOIN FLUIG.DBO.Z_CRM_EX001021 A (NOLOCK) ON M.OS = A.OSPROCESSO AND M.IDCRIACAO = A.IDCRIACAOPROCESSO AND M.EXECUCAO = A.EXECUCAO
		INNER JOIN KATVORDEM Z (NOLOCK) ON Z.CODCOLIGADA = O.CODCOLIGADA AND Z.CODFILIAL = O.CODFILIAL AND Z.CODORDEM = O.CODORDEM AND Z.CODATIVIDADE = A.CODATIVIDADE COLLATE SQL_Latin1_General_CP1_CI_AI
		LEFT JOIN KATVORDEMCOMPL L (NOLOCK) ON L.CODCOLIGADA = Z.CODCOLIGADA AND L.CODFILIAL = Z.CODFILIAL AND L.CODORDEM = Z.CODORDEM AND L.IDATVORDEM = Z.IDATVORDEM
	WHERE L.IDATVORDEM IS NULL AND @NUM_OS = M.OS AND @EXECUCAO = M.EXECUCAO AND @CODTRFPAI = M.CODTRFPAI

-- FIM DA RECRIAÇÃO DAS ORDENS

-- CORRIG COMPONENTES DAS ESTRUTURA QUE NÃO SÃO DA EXECUÇÃO, MAS SÃO DA ESTURUTRA GERAL

DELETE CC
FROM KCOMPONENTE C
	INNER JOIN KCOMPONENTECOMPL (NOLOCK) CC ON C.CODCOLIGADA = CC.CODCOLIGADA AND C.CODESTRUTURA = CC.CODESTRUTURA AND C.IDPRODUTO = CC.IDPRODUTO
	INNER JOIN KESTRUTURA  (NOLOCK) E ON C.CODCOLIGADA = E.CODCOLIGADA AND C.CODFILIAL = E.CODFILIAL AND C.CODESTRUTURA = E.CODESTRUTURA
	INNER JOIN TPRD  (NOLOCK)  P ON P.CODCOLIGADA = C.CODCOLIGADA AND P.IDPRD = C.IDPRODUTO
	LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I ON I.CODCOLIGADA = C.CODCOLIGADA AND I.IDPRD = C.IDPRODUTO AND E.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE LEFT(P.CODIGOPRD,2) IN ('04', '03') AND   E.CODCCUSTO = @NUM_OS AND I.CODCOLIGADA IS NULL AND CC.RECCREATEDBY = 'fluig'

DELETE  C
FROM KCOMPONENTE (NOLOCK) C 
	INNER JOIN KESTRUTURA  (NOLOCK) E ON C.CODCOLIGADA = E.CODCOLIGADA AND C.CODFILIAL = E.CODFILIAL AND C.CODESTRUTURA = E.CODESTRUTURA
	INNER JOIN TPRD  (NOLOCK)  P ON P.CODCOLIGADA = C.CODCOLIGADA AND P.IDPRD = C.IDPRODUTO
	LEFT JOIN FLUIG.dbo.Z_CRM_ML001005 (NOLOCK) I ON I.CODCOLIGADA = C.CODCOLIGADA AND I.IDPRD = C.IDPRODUTO AND E.CODCCUSTO = I.OS COLLATE SQL_Latin1_General_CP1_CI_AI
WHERE LEFT(P.CODIGOPRD,2) IN ('04', '03') AND   E.CODCCUSTO =  @NUM_OS AND C.RECCREATEDBY = 'fluig' AND I.CODCOLIGADA IS NULL 

-- FIM DO AJUSTE

END;

