DECLARE @OLDORDEM VARCHAR(30),@NEWORDEM VARCHAR(30)
SET @OLDORDEM='64033/23'
SET @NEWORDEM='70785/23'
ALTER TABLE KMAOOBRAALOC NOCHECK CONSTRAINT FKKMAOOBRAALOC_KATVORDPROC


	;WITH CTE AS (
	
		SELECT K.*,KA.INDICEPROCESSO IDPROC,KA2.IDATVORDEM IDATV2,(SELECT MAX(INDICEPROCESSO) FROM KATVORDEMPROCESSO WHERE CODORDEM=KA2.CODORDEM 
		AND CODCOLIGADA=KA2.CODCOLIGADA AND CODFILIAL=KA2.CODFILIAL AND IDATVORDEM=KA2.IDATVORDEM
		)+ROW_NUMBER() OVER(PARTITION BY K.CODORDEM,K.IDATVORDEM ORDER BY K.INDICEPROCESSO) IDID FROM KMAOOBRAALOC K 
		INNER JOIN KATVORDEMPROCESSO  KA ON
		K.CODCOLIGADA=KA.CODCOLIGADA
		AND K.CODFILIAL=KA.CODFILIAL
		AND K.CODORDEM=KA.CODORDEM
		AND K.IDATVORDEM=KA.IDATVORDEM
		AND K.INDICEPROCESSO=KA.INDICEPROCESSO
		INNER JOIN KATVORDEM KAA ON
		KAA.CODCOLIGADA=K.CODCOLIGADA
		AND KAA.CODFILIAL=K.CODFILIAL
		AND KAA.CODORDEM=K.CODORDEM
		AND KAA.IDATVORDEM=K.IDATVORDEM
		INNER JOIN KATVORDEM KA2 ON
		KA2.CODCOLIGADA=K.CODCOLIGADA
		AND KA2.CODFILIAL=K.CODFILIAL
		AND KA2.CODORDEM=@NEWORDEM
		AND KA2.CODATIVIDADE=KAA.CODATIVIDADE
		WHERE
		K.CODORDEM=@OLDORDEM 

	)
	SELECT * INTO #TEMP FROM CTE 

	UPDATE K SET CODORDEM=@NEWORDEM,IDATVORDEM=KA.IDATV2,INDICEPROCESSO=KA.IDID FROM KMAOOBRAALOC K 
	INNER JOIN #TEMP KA ON
	K.CODCOLIGADA=KA.CODCOLIGADA
	AND K.CODFILIAL=KA.CODFILIAL
	AND K.CODORDEM=KA.CODORDEM
	AND K.IDATVORDEM=KA.IDATVORDEM
	AND K.INDICEPROCESSO=KA.INDICEPROCESSO
	WHERE K.CODORDEM=@OLDORDEM 

	UPDATE K SET CODORDEM=@NEWORDEM,IDATVORDEM=KA.IDATV2,INDICEPROCESSO=KA.IDID FROM KATVORDEMPROCESSO K 
	INNER JOIN #TEMP KA ON
	K.CODCOLIGADA=KA.CODCOLIGADA
	AND K.CODFILIAL=KA.CODFILIAL
	AND K.CODORDEM=KA.CODORDEM
	AND K.IDATVORDEM=KA.IDATVORDEM
	AND K.INDICEPROCESSO=KA.INDICEPROCESSO
	WHERE K.CODORDEM=@OLDORDEM 

	UPDATE K SET CODORDEM=@NEWORDEM,IDATVORDEM=KA.IDATV2 FROM KPARADAATV K 
	INNER JOIN #TEMP KA ON
	K.CODCOLIGADA=KA.CODCOLIGADA
	AND K.CODFILIAL=KA.CODFILIAL
	AND K.CODORDEM=KA.CODORDEM
	AND K.IDATVORDEM=KA.IDATVORDEM
	WHERE K.CODORDEM=@OLDORDEM 

	DROP TABLE #TEMP

ALTER TABLE KMAOOBRAALOC WITH CHECK CHECK CONSTRAINT FKKMAOOBRAALOC_KATVORDPROC


UPDATE K SET CODORDEM=@NEWORDEM,IDATV=KA2.IDATVORDEM FROM KLOGAPONTAMENTO K 
INNER JOIN KATVORDEM KAA ON
KAA.CODCOLIGADA=K.CODCOLIGADA
AND KAA.CODFILIAL=K.CODFILIAL
AND KAA.CODORDEM=K.CODORDEM
AND KAA.IDATVORDEM=K.IDATV
INNER JOIN KATVORDEM KA2 ON
KA2.CODCOLIGADA=K.CODCOLIGADA
AND KA2.CODFILIAL=K.CODFILIAL
AND KA2.CODORDEM=@NEWORDEM
AND KA2.CODATIVIDADE=KAA.CODATIVIDADE
WHERE K.CODORDEM=@OLDORDEM 

UPDATE KLOGPRODUCAO SET CODORDEM=@NEWORDEM WHERE CODORDEM=@OLDORDEM 

UPDATE KLOGAPONTAMENTO SET CODORDEM=@NEWORDEM WHERE CODORDEM=@OLDORDEM 


---- CASO NECESSÁRIO DELETAR A ORDEM DE ORIGEM
-- DELETE FROM KATVORDEMCUSTOMAOOBRA WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KATVORDEMCUSTOPOSTO WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KATVORDEMCUSTOEQP WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KATVORDEMHISTORICOCUSTO WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KLOGATIVIDADE WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KLOGAPONTAMENTO WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KLOGPRODUCAO WHERE CODORDEM=@OLDORDEM
-- DELETE FROM KATVORDEMMP WHERE CODORDEM =@OLDORDEM 
-- DELETE FROM KATVORDEMCOMPL WHERE CODORDEM=@OLDORDEM 
-- DELETE FROM KATVORDEM WHERE CODORDEM =@OLDORDEM 
-- DELETE FROM KITEMORDEM WHERE CODORDEM =@OLDORDEM 
-- DELETE FROM KORDEMCOMPL WHERE CODORDEM =@OLDORDEM 
-- DELETE FROM KORDEM WHERE CODORDEM=@OLDORDEM



