DECLARE @CODORDEM VARCHAR(30),@IDATVORDEM INT,@CODMOANT VARCHAR(30), @CODMO VARCHAR(30)

UPDATE KMAOOBRAALOC SET CODMO= @CODMO WHERE CODORDEM=@CODORDEM AND IDATVORDEM=@IDATVORDEM AND CODMO=@CODMOANT

UPDATE KPARADAATV SET CODAGENTE= @CODMO WHERE CODORDEM=@CODORDEM AND IDATVORDEM=@IDATVORDEM AND CODAGENTE=@CODMOANT

UPDATE KLOGATIVIDADE SET CODMO= @CODMO,NOMEMO=(SELECT TOP 1 NOME FROM KMAOOBRANOME WHERE CODMO= @CODMO) WHERE CODORDEM=@CODORDEM AND CODMO=@CODMOANT 
AND CODATIVIDADE = (SELECT CODATIVIDADE FROM KATVORDEM WHERE CODORDEM=@CODORDEM AND IDATVORDEM=@IDATVORDEM)
