SELECT 
T.DATAEMISSAO,
T.CODCOLIGADA, 
T.IDMOV, 
T.CODFILIAL, 
T.CODCFO,
T.CODCOLCFO,
T.CODTDO,
T.CHAVEACESSONFE,
T.NUMEROMOV, 
T.CODCCUSTO,
T.CODTB1FLX,
T.FRETECIFOUFOB,
T.CODCPG,
T.CODTB3FLX,
T.NATUREZAVOLUMES,
T.CODLOC,
T.IDNAT,
TI.IDPRD,
TI.CODLOC,
TI.CODNAT,
TI.NSEQITMMOV,
TI.QUANTIDADE,
TI.PRECOUNITARIO,
TI.QUANTIDADE SALDOFISICO2,
TI.NUMEROSEQUENCIAL,
TI.NSEQITMMOV,
Z.NSEQPLANOCORTE,Z.CODCOLIGADA,Z.CODFILIAL,Z.CODORDEM,Z.CODESTRUTURA,KA.IDATVORDEM,Z.NUMPLANOCORTE
,Z.CODSUCATA,Z.QTDESUCATA,Z.CODIGOMP,Z.QTDEMP,Z.NUMLOTE,Z.IDLOTE,
CASE WHEN ROW_NUMBER()OVER(ORDER BY NSEQPLANOCORTE)=(SELECT COUNT(NSEQPLANOCORTE) FROM ZMDPLANOAPROVEITAMENTOCORTE WHERE NUMPLANOCORTE=Z.NUMPLANOCORTE) THEN 
Z.QTDEMP - ( ( SELECT SUM(QTDMPFINAL) FROM ZMDPLANOAPROVEITAMENTOCORTE WHERE NUMPLANOCORTE=Z.NUMPLANOCORTE ) - Z.QTDMPFINAL)
ELSE Z.QTDMPFINAL END AS QTDMPFINAL
,Z.CODATIVIDADE

FROM TMOV T
INNER JOIN TITMMOV TI
ON TI.CODCOLIGADA = T.CODCOLIGADA
AND TI.IDMOV = T.IDMOV
INNER JOIN TPRODUTO TP
ON TP.IDPRD =  TI.IDPRD
INNER JOIN ZMDPLANOAPROVEITAMENTOCORTE Z
ON Z.IDMOVREQ=T.IDMOV
AND Z.NUMPLANOCORTE=T.CAMPOLIVRE3
/*AND TI.QUANTIDADE=Z.QTDEMP
AND TP.CODIGOPRD=Z.CODIGOMP*/
INNER JOIN TMOVRELAC TR 
ON TR.IDMOVORIGEM=T.IDMOV
AND TR.CODCOLORIGEM=T.CODCOLIGADA
INNER JOIN TMOV T2 
ON T2.IDMOV=TR.IDMOVDESTINO
AND T2.CODCOLIGADA=TR.CODCOLDESTINO
INNER JOIN TITMMOV TI2 
ON TI2.IDMOV=T2.IDMOV
AND TI2.CODCOLIGADA=T2.CODCOLIGADA
AND TI2.IDPRD=TP.IDPRD
AND TI2.QUANTIDADE=Z.QTDEMP
INNER JOIN TITMLOTEPRD TL 
ON TL.IDMOV=T2.IDMOV
AND TL.CODCOLIGADA=T2.CODCOLIGADA
AND TL.NSEQITMMOV=TI2.NSEQITMMOV
AND TL.IDLOTE=Z.IDLOTE
AND TL.QUANTIDADE2=Z.QTDEMP
INNER JOIN KATVORDEM KA 
ON KA.CODCOLIGADA=Z.CODCOLIGADA
AND KA.CODFILIAL=Z.CODFILIAL
AND KA.CODORDEM=Z.CODORDEM
AND KA.CODATIVIDADE=Z.CODATIVIDADE
WHERE 
T.IDMOV = 1399342 AND ( SELECT COUNT(NSEQITMMOV) FROM TITMMOV WHERE IDMOV=1399342	 AND CODCOLIGADA=1)=1 
AND ( SELECT COUNT(NSEQITMMOV) FROM TITMMOV WHERE IDMOV=T2.IDMOV AND CODCOLIGADA=T2.CODCOLIGADA)=1
AND ( SELECT COUNT(NSEQITMMOV) FROM TITMLOTEPRD WHERE IDMOV=TL.IDMOV AND CODCOLIGADA=TL.CODCOLIGADA)=1
ORDER BY Z.NSEQPLANOCORTE