USE [CORPORE]
GO
/****** Object:  StoredProcedure [dbo].[SP_DELP_VINCULAMOVIMENTOSPENDENTES]    Script Date: 13/05/2024 15:36:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		RAFAEL.GRANJA
-- Create date: 15/04/2024
-- Description:	VINCULA MOVIMENTOS PENDENTES
-- =============================================
ALTER PROCEDURE [dbo].[SP_DELP_VINCULAMOVIMENTOSPENDENTES]
AS
BEGIN
			

	DECLARE @CODCOLIGADA INT,@CODFILIAL INT,@CODORDEM VARCHAR(30),@IDATV INT,@IDMOV INT,@DATAEMISSAO DATETIME, @KMOVESTOQUE INT,@KATVORDEMMP INT,@NUMPLANOCORTE VARCHAR(100);

	DECLARE MOVIMENTOS CURSOR FOR

		SELECT DISTINCT TOP 10 T.CODCOLIGADA,T.CODFILIAL,T.CAMPOLIVRE1,T.CAMPOLIVRE2,T.IDMOV,T.DATAEMISSAO,
		CASE WHEN ISNULL(K.CODORDEM,'0')='0' THEN 0 ELSE 1 END KMOVESTOQUE,CASE WHEN ISNULL(KM.CODORDEM,'0')='0' THEN 0 ELSE 1 END KATVORDEMMP,T.CAMPOLIVRE3
		FROM TMOV T
		INNER JOIN TITMMOV TI ON
		TI.CODCOLIGADA=T.CODCOLIGADA
		AND TI.IDMOV=T.IDMOV
		INNER JOIN KATVORDEM KA ON
		KA.CODCOLIGADA=T.CODCOLIGADA
		AND KA.CODFILIAL=T.CODFILIAL
		AND KA.CODORDEM=T.CAMPOLIVRE1
		AND KA.IDATVORDEM=T.CAMPOLIVRE2
		LEFT JOIN KMOVESTOQUE K ON
		K.CODCOLIGADA=T.CODCOLIGADA
		AND K.CODFILIAL=T.CODFILIAL
		AND K.IDMOV=T.IDMOV
		AND K.IDPRODUTO = TI.IDPRD
		LEFT JOIN KATVORDEMMP KM ON
		KM.CODCOLIGADA=T.CODCOLIGADA
		AND KM.CODFILIAL=T.CODFILIAL
		AND KM.CODORDEM=T.CAMPOLIVRE1
		AND KM.IDPRODUTO=TI.IDPRD
		AND KM.QUANTIDADE=TI.QUANTIDADE
		AND KM.RECCREATEDON BETWEEN DATEADD(MINUTE,-5,K.RECCREATEDON) AND DATEADD(MINUTE,5,K.RECCREATEDON)
		AND KM.EFETIVADO=1
		WHERE CODTMV IN ('2.2.18','2.2.38','1.2.90','1.2.37','1.2.29') AND T.DATAEMISSAO>'2023-01-01 00:00:00.000'
		AND ( ( K.CODORDEM IS NULL AND KM.CODORDEM IS NULL ) OR ( KM.IDATVORDEMMATERIAPRIMA IS NULL AND CODTMV NOT IN ('1.2.90','1.2.37','1.2.29')) ) 
		AND CAMPOLIVRE1 IS NOT NULL AND CAMPOLIVRE2 IS NOT NULL AND T.STATUS!='C' 
		ORDER BY T.DATAEMISSAO DESC

	OPEN MOVIMENTOS 
	FETCH NEXT FROM MOVIMENTOS INTO @CODCOLIGADA,@CODFILIAL,@CODORDEM,@IDATV,@IDMOV,@DATAEMISSAO,@KMOVESTOQUE,@KATVORDEMMP,@NUMPLANOCORTE
	WHILE @@FETCH_STATUS=0
		BEGIN
			IF @KMOVESTOQUE=1
				BEGIN
					DELETE KK FROM KMOVESTOQUE K 
					INNER JOIN KMOVESTOQUELOTE KK ON
					K.NSEQ=KK.NSEQ
					WHERE K.IDMOV=@IDMOV
					DELETE K FROM KMOVESTOQUE K 
					WHERE K.IDMOV=@IDMOV
				END

			DELETE KL
			FROM KATVORDEMMP K 
			INNER JOIN KATVORDEMMPLOTE KL ON
			KL.IDATVORDEMMATERIAPRIMA=K.IDATVORDEMMATERIAPRIMA
			LEFT JOIN KMOVESTOQUE KK ON
			K.CODCOLIGADA=KK.CODCOLIGADA
			AND K.CODFILIAL=KK.CODFILIAL
			AND K.CODORDEM=KK.CODORDEM
			AND K.IDPRODUTO=KK.IDPRODUTO
			AND K.RECCREATEDON BETWEEN DATEADD(MINUTE,-5,KK.RECCREATEDON) AND DATEADD(MINUTE,5,KK.RECCREATEDON)
			WHERE K.CODCOLIGADA=@CODCOLIGADA AND K.CODFILIAL=@CODFILIAL AND K.CODORDEM=@CODORDEM AND KK.NSEQ IS NULL AND K.EFETIVADO = 1

			DELETE K
			FROM KATVORDEMMP K 
			LEFT JOIN KMOVESTOQUE KK ON
			K.CODCOLIGADA=KK.CODCOLIGADA
			AND K.CODFILIAL=KK.CODFILIAL
			AND K.CODORDEM=KK.CODORDEM
			AND K.IDPRODUTO=KK.IDPRODUTO
			AND K.RECCREATEDON BETWEEN DATEADD(MINUTE,-5,KK.RECCREATEDON) AND DATEADD(MINUTE,5,KK.RECCREATEDON)
			WHERE K.CODCOLIGADA=@CODCOLIGADA AND K.CODFILIAL=@CODFILIAL AND K.CODORDEM=@CODORDEM AND KK.NSEQ IS NULL AND K.EFETIVADO = 1

			EXEC SP_CRM_VINCULAMATERIAL @CODCOLIGADA,@CODFILIAL,@CODORDEM,@IDATV,@IDMOV,@DATAEMISSAO

			IF @NUMPLANOCORTE IS NOT NULL AND @NUMPLANOCORTE!=''
				BEGIN
					UPDATE Z SET QTDEAPONTADA=Z.QUANTIDADE
					FROM ZMDPLANOAPROVEITAMENTOCORTE Z
					INNER JOIN TMOV T ON
					Z.CODCOLIGADA=T.CODCOLIGADA
					AND Z.CODFILIAL=T.CODFILIAL
					AND Z.NUMPLANOCORTE=T.CAMPOLIVRE3
					AND Z.CODORDEM=T.CAMPOLIVRE1
					WHERE Z.CODCOLIGADA=@CODCOLIGADA AND Z.CODFILIAL=@CODFILIAL AND Z.CODORDEM=@CODORDEM AND Z.NUMPLANOCORTE=@NUMPLANOCORTE
				END

			FETCH NEXT FROM MOVIMENTOS INTO @CODCOLIGADA,@CODFILIAL,@CODORDEM,@IDATV,@IDMOV,@DATAEMISSAO,@KMOVESTOQUE,@KATVORDEMMP,@NUMPLANOCORTE
		END
	CLOSE MOVIMENTOS
	DEALLOCATE MOVIMENTOS

END
