SELECT 
	OS,(SUM(TEMPO)/60) HORAS, DESCRICAO, EXECUCAO
	FROM
		(SELECT E.OS,(CONVERT(FLOAT,A.MINUTOSGASTOS)*CONVERT(FLOAT,E.TOTALQTDE)) TEMPO,
			(SELECT DESCRICAO FROM Z_CRM_EX001005 WHERE CODTRFITEM=E.CODTRFITEM AND NIVEL='' AND EXECUCAO=E.EXECUCAO AND OS=E.OS) DESCRICAO, 
			E.EXECUCAO 
				FROM
					Z_CRM_EX001005 E
					INNER JOIN Z_CRM_EX001021 A ON A.IDCRIACAOPROCESSO=E.IDCRIACAO
					AND E.OS=A.OSPROCESSO
					AND A.EXECUCAO=E.EXECUCAO 
				WHERE 
					E.OS='3.07840.32.001') R
	GROUP BY OS,DESCRICAO,EXECUCAO
	ORDER BY EXECUCAO,DESCRICAO

--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT 
	OS,(SUM(TEMPO)/60) HORAS, EXECUCAO
	FROM
	(SELECT E.OS,(CONVERT(FLOAT,A.MINUTOSGASTOS)*CONVERT(FLOAT,E.TOTALQTDE)) TEMPO,
		(SELECT DESCRICAO FROM Z_CRM_EX001005 WHERE CODTRFITEM=E.CODTRFITEM AND NIVEL='' AND EXECUCAO=E.EXECUCAO AND OS=E.OS) DESCRICAO,
		E.EXECUCAO 
			FROM
				Z_CRM_EX001005 E
				INNER JOIN Z_CRM_EX001021 A ON A.IDCRIACAOPROCESSO=E.IDCRIACAO
				AND E.OS=A.OSPROCESSO
				AND A.EXECUCAO=E.EXECUCAO 
			WHERE 
				E.OS='3.07840.32.001') R
	GROUP BY OS,EXECUCAO
	ORDER BY EXECUCAO

--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT A.ID,CODCOLIGADA,CODFILIAL,OS,CODIGOPRD,A.EXECUCAO,PRIORIDADE,CODATIVIDADE,TOTALQTDE,PROCESSAMENTO,MINUTOSGASTOS
		FROM
			FLUIG.DBO.Z_CRM_EX001005 E
			INNER JOIN FLUIG.DBO.Z_CRM_EX001021 A ON A.IDCRIACAOPROCESSO=E.IDCRIACAO
			AND E.OS=A.OSPROCESSO
			AND A.EXECUCAO=E.EXECUCAO 
		WHERE 
			E.OS='3.07840.32.001'
		ORDER BY CODIGOPRD,EXECUCAO,PRIORIDADE
		
SELECT * FROM FLUIG.DBO.Z_CRM_EX001005 WHERE OS='3.07840.32.001'
--TOTALQTDE - QUANTIDADE
--IDCRIACAO - KEY
--CODTRFITEM
--IDTRFITEM
--CODTRFPAI
--EXECUCAO
--OS

SELECT * FROM Z_CRM_EX001021
--IDCRICACAOPROCESSO
--OSPROCESSO
--MINUTOSGASTOS
--EXECUCAO