declare @param varchar(100);
set @param = '128798';
set @param = concat(@param,',');

with cte as 
		(	
			select left(@param,CHARINDEX(',',@param)-1) param,SUBSTRING(@param,CHARINDEX(',',@param)+1,LEN(@param)) param1 
			union all 
			select left(param1,CHARINDEX(',',param1)-1) param,SUBSTRING(param1,CHARINDEX(',',param1)+1,LEN(param1)) param1
			from cte  
			where len(param1)>1
		),
cte_b as
(

SELECT *, RANK() OVER ( PARTITION BY OS,PRODUTO ORDER BY OP,ATIVIDADE DESC) ID FROM (
SELECT K.CODCCUSTO OS,K.CODORDEM OP,KS.DSCSTATUS STATUS_OP,KA.IDATVORDEM ATIVIDADE,KA.CODATIVIDADE,KAA.DSCATIVIDADE,KAS.DSCSTATUS STATUS_ATIVIDADE,KMP.IDPRODUTO PRODUTO FROM
KORDEM K (NOLOCK)
INNER JOIN KATVORDEM KA (NOLOCK)
ON KA.CODCOLIGADA=K.CODCOLIGADA
AND KA.CODFILIAL=K.CODFILIAL
AND KA.CODORDEM=K.CODORDEM
INNER JOIN KATVORDEMMP KMP (NOLOCK)
ON KMP.CODCOLIGADA=K.CODCOLIGADA
AND KMP.CODFILIAL=K.CODFILIAL
AND KMP.CODORDEM=K.CODORDEM
AND KMP.IDATIVIDADE=KA.IDATVORDEM 
INNER JOIN KSTATUS KS (NOLOCK) ON 
KS.CODCOLIGADA=K.CODCOLIGADA
AND KS.CODSTATUS=K.STATUS
INNER JOIN KSTATUS KAS (NOLOCK) ON 
KAS.CODCOLIGADA=K.CODCOLIGADA
AND KAS.CODSTATUS=KA.STATUS
INNER JOIN KATIVIDADE KAA (NOLOCK) ON
KAA.CODCOLIGADA=KA.CODCOLIGADA
AND KAA.CODFILIAL=KA.CODFILIAL
AND KAA.CODATIVIDADE=KA.CODATIVIDADE
INNER JOIN TPRD T (NOLOCK) ON
T.CODCOLIGADA=KA.CODCOLIGADA
AND T.IDPRD=KMP.IDPRODUTO
AND T.CODIGOPRD LIKE '01.053%'
WHERE K.STATUS=3 AND KA.STATUS IN (3,5) AND KMP.IDPRODUTO IN (SELECT DISTINCT PARAM FROM CTE) AND K.CODCCUSTO LIKE CONCAT('%','3.07840.32.001') AND ( K.REPROCESSAMENTO=0 OR K.REPROCESSAMENTO IS NULL)
UNION
SELECT  K.CODCCUSTO,K.CODORDEM,KST.DSCSTATUS,KA.IDATVORDEM,KA.CODATIVIDADE,KAA.DSCATIVIDADE,KAS.DSCSTATUS,KS.IDPRD  FROM
KORDEM K (NOLOCK)
INNER JOIN KATVORDEM KA (NOLOCK)
ON KA.CODCOLIGADA=K.CODCOLIGADA
AND KA.CODFILIAL=K.CODFILIAL
AND KA.CODORDEM=K.CODORDEM
INNER JOIN KATVORDEMMP KMP (NOLOCK)
ON KMP.CODCOLIGADA=K.CODCOLIGADA
AND KMP.CODFILIAL=K.CODFILIAL
AND KMP.CODORDEM=K.CODORDEM
AND KMP.IDATIVIDADE=KA.IDATVORDEM 
INNER JOIN KCOMPONENTE KC (NOLOCK)
ON KC.CODCOLIGADA=K.CODCOLIGADA 
AND KC.CODFILIAL=K.CODFILIAL
AND KC.CODESTRUTURA=KA.CODESTRUTURA
AND KC.IDPRODUTO=KMP.IDPRODUTO
INNER JOIN KCOMPSUBSTITUTO KS (NOLOCK)
ON KS.CODCOLIGADA=K.CODCOLIGADA
AND KS.CODFILIAL=K.CODFILIAL
AND KS.CODESTRUTURA=KA.CODESTRUTURA
AND KS.IDPRDORIGEM=KC.IDPRODUTO
INNER JOIN KSTATUS KST (NOLOCK) ON 
KST.CODCOLIGADA=K.CODCOLIGADA
AND KST.CODSTATUS=K.STATUS
INNER JOIN KSTATUS KAS (NOLOCK) ON 
KAS.CODCOLIGADA=K.CODCOLIGADA
AND KAS.CODSTATUS=KA.STATUS
INNER JOIN KATIVIDADE KAA (NOLOCK) ON
KAA.CODCOLIGADA=KA.CODCOLIGADA
AND KAA.CODFILIAL=KA.CODFILIAL
AND KAA.CODATIVIDADE=KA.CODATIVIDADE
INNER JOIN TPRD T (NOLOCK) ON
T.CODCOLIGADA=KA.CODCOLIGADA
AND T.IDPRD=KS.IDPRD
AND T.CODIGOPRD LIKE '01.053%'
WHERE K.STATUS=3 AND KA.STATUS IN (3,5) AND KS.IDPRD IN (SELECT DISTINCT PARAM FROM CTE) AND K.CODCCUSTO LIKE CONCAT('%','3.07840.32.001') AND ( K.REPROCESSAMENTO=0 OR K.REPROCESSAMENTO IS NULL) ) R ) 

select * from cte_b A where ID = ( SELECT MAX(ID) FROM cte_b WHERE OS=A.OS AND PRODUTO=A.PRODUTO )
