DECLARE @OS VARCHAR(30)='3.07840.32.001'
DECLARE @EXEC INT =1

SELECT DISTINCT K.CODCCUSTO,K.CODORDEM,KAL.IDATVORDEM,T.CODIGOPRD,T.NOMEFANTASIA,PAPC.NUMPLANOCORTE,K.STATUS,KM2.IDPRODUTO,KM3.QUANTIDADE QUANTIDADE_PREVISTA,KM2.QUANTIDADE QUANTIDADE_EFETIVADA
	FROM 
		KORDEM K
		LEFT JOIN KATVORDEM KA ON
		KA.CODCOLIGADA=K.CODCOLIGADA
		AND KA.CODFILIAL=K.CODFILIAL
		AND KA.CODORDEM=K.CODORDEM

		LEFT JOIN KORDEMCOMPL KOL ON 
		KOL.CODCOLIGADA=K.CODCOLIGADA
		AND KOL.CODFILIAL=K.CODFILIAL
		AND KOL.CODORDEM=K.CODORDEM

		LEFT JOIN KATVORDEMMP KM1 ON
		KM1.CODCOLIGADA=K.CODCOLIGADA
		AND KM1.CODFILIAL=K.CODFILIAL
		AND KM1.CODORDEM=K.CODORDEM
		AND KM1.IDATIVIDADE=KA.IDATVORDEM
		AND KM1.EFETIVADO=0

		INNER JOIN KATVORDEMMP KM2 ON
		KM2.CODCOLIGADA=K.CODCOLIGADA
		AND KM2.CODFILIAL=K.CODFILIAL
		AND KM2.CODORDEM=K.CODORDEM
		AND KM2.IDATIVIDADE=KA.IDATVORDEM
		AND KM2.IDPRODUTO!=KM1.IDPRODUTO
		AND KM2.EFETIVADO=1

		LEFT JOIN KATVORDEMMP KM3 ON
		KM3.CODCOLIGADA=K.CODCOLIGADA
		AND KM3.CODFILIAL=K.CODFILIAL
		AND KM3.CODORDEM=K.CODORDEM
		AND KM3.IDATIVIDADE=KM2.IDATIVIDADE
		AND KM3.IDPRODUTO=KM2.IDPRODUTO
		AND KM3.EFETIVADO=0

		INNER JOIN KATVORDEMMPLOTE KML ON
		KML.CODCOLIGADA=KM1.CODCOLIGADA
		AND KML.CODFILIAL=KM1.CODFILIAL

		LEFT JOIN KATVORDEMCOMPL KAL ON 
		KAL.CODCOLIGADA=K.CODCOLIGADA
		AND KAL.CODFILIAL=K.CODFILIAL
		AND KAL.CODORDEM=K.CODORDEM
		AND KAL.IDATVORDEM=KA.IDATVORDEM

		LEFT JOIN TPRODUTO T ON
		T.IDPRD=KM2.IDPRODUTO
		
		LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE PAPC ON
		PAPC.CODCOLIGADA=K.CODCOLIGADA
		AND PAPC.CODFILIAL=K.CODFILIAL
		AND PAPC.CODORDEM=K.CODORDEM
		AND PAPC.IDATVORDEM=KM1.IDATIVIDADE
		AND PAPC.CODIGOMP =T.CODIGOPRD

	WHERE K.CODCCUSTO=@OS AND KOL.NUMEXEC=@EXEC AND KM2.IDPRODUTO = (SELECT IDPRD FROM TLOTEPRD WHERE IDLOTE=KML.IDLOTE) AND KM1.IDPRODUTO != (SELECT IDPRD FROM TLOTEPRD WHERE IDLOTE=KML.IDLOTE)
	ORDER BY K.CODORDEM,KAL.IDATVORDEM
