with CTE as (
SELECT T.IDMOV,T.NUMEROMOV,T.CODTMV,CONVERT(VARCHAR(20),T.RECCREATEDON,103) DATAEMISSAO,CONVERT(VARCHAR(20),T.RECMODIFIEDON,103) DATAMODIFICACAO,T.CAMPOLIVRE1 OP,T.CAMPOLIVRE2 IDATV,T.CAMPOLIVRE3 NUMPLANOCORTE,Z.CODIGOMP PRODUTO_REQUISITADO,TP2.CODIGOPRD PRODUTO_ATENDIDO,
--TL.IDLOTE ID_LOTE_TRANSFERIDO,
TPL1.NUMLOTE NUM_LOTETRANSFERIDO,
--Z.IDLOTE ID_LOTECORRETO,
Z.NUMLOTE NUM_LOTECORRETO,T.STATUS,TI.QUANTIDADETOTAL QUANTIDADE_REQUISITADA,TL.QUANTIDADE2 QUANTIDADE_ATENDIDA
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TITMMOVRELAC TR ON
TR.IDMOVORIGEM = TI.IDMOV
AND TR.NSEQITMMOVORIGEM = TI.NSEQITMMOV
INNER JOIN TITMLOTEPRD TL ON
TL.CODCOLIGADA=T.CODCOLIGADA
AND TL.IDMOV=TR.IDMOVDESTINO
INNER JOIN ZMDPLANOAPROVEITAMENTOCORTE Z ON
Z.CODCOLIGADA=T.CODCOLIGADA 
AND Z.CODFILIAL=T.CODFILIAL
AND Z.NUMPLANOCORTE=T.CAMPOLIVRE3
AND Z.CODORDEM=T.CAMPOLIVRE1
AND Z.IDATVORDEM=T.CAMPOLIVRE2
INNER JOIN TITMMOV TL2 ON
TL2.CODCOLIGADA=T.CODCOLIGADA
AND TL2.IDMOV=TR.IDMOVDESTINO
INNER JOIN TPRD TP2 ON
TP2.CODCOLIGADA=TL2.CODCOLIGADA
AND TP2.IDPRD=TL2.IDPRD
INNER JOIN TLOTEPRD TPL1 ON
TPL1.CODCOLIGADA=TL.CODCOLIGADA
AND TPL1.IDPRD=TP2.IDPRD
AND TPL1.IDLOTE=TL.IDLOTE
WHERE --Z.NUMPLANOCORTE IN ('05429','05430','05426','04562 ') AND 
T.CODTMV ='1.1.05' ) 

 
 SELECT *,CASE WHEN PRODUTO_REQUISITADO!=PRODUTO_ATENDIDO THEN 'PRODUTO ATENDIDO'
				WHEN NUM_LOTETRANSFERIDO!=NUM_LOTECORRETO THEN 'LOTE_ERRADO' 
				WHEN QUANTIDADE_REQUISITADA!=QUANTIDADE_ATENDIDA THEN 'QUANTIDADE DIFERENTE'
			END AS ANALISE FROM 
CTE WHERE PRODUTO_REQUISITADO!=PRODUTO_ATENDIDO OR NUM_LOTETRANSFERIDO!=NUM_LOTECORRETO --OR QUANTIDADE_REQUISITADA!=QUANTIDADE_ATENDIDA
ORDER BY IDMOV DESC

