SELECT
E.CODCCUSTO, A.CODORDEM, D.CODATIVIDADE, D.DSCATIVIDADE, A.IDATIVIDADE,C.QTPREVISTA,C.QUANTIDADE, C.STATUS,Y.NUMLOTE,B.IDLOTE,P.CODIGOPRD,P.IDPRD,
Z.NUMPLANOCORTE,SUM(A.QTDUNITARIA) AS QUANTIDADE_PREVISTA,

 SUM(A.QUANTIDADE) AS QUANTIDADE_EFETIVADA,
R.CODUNDCONTROLE

FROM KATVORDEMMP A
INNER JOIN KATVORDEMMPLOTE B ON
A.IDATVORDEMMATERIAPRIMA = B.IDATVORDEMMATERIAPRIMA

INNER JOIN KATVORDEM C ON
A.CODCOLIGADA 	   = C.CODCOLIGADA
AND A.CODFILIAL	   = C.CODFILIAL
AND A.CODORDEM	   = C.CODORDEM
AND A.CODESTRUTURA = C.CODESTRUTURA
AND A.CODMODELO	   = C.CODMODELO
AND A.IDATIVIDADE  = C.IDATVORDEM

INNER JOIN KATIVIDADE D ON
C.CODCOLIGADA = D.CODCOLIGADA
AND C.CODFILIAL = D.CODFILIAL
AND C.CODATIVIDADE = D.CODATIVIDADE

INNER JOIN  KORDEM E ON 
E.CODCOLIGADA =   C.CODCOLIGADA 
AND E.CODFILIAL = C.CODFILIAL 
AND E.CODORDEM =  C.CODORDEM

INNER JOIN  KATVORDEMCOMPL F ON 
F.CODCOLIGADA =   C.CODCOLIGADA 
AND F.CODFILIAL = C.CODFILIAL 
AND F.CODORDEM =  C.CODORDEM

INNER JOIN TPRD P ON
P.CODCOLIGADA = A.CODCOLIGADA	
AND P.IDPRD = A.IDPRODUTO
AND P.INATIVO = 0

INNER JOIN TLOTEPRD Y ON
P.CODCOLIGADA = Y.CODCOLIGADA AND
B.IDLOTE = Y.IDLOTE

INNER JOIN TPRODUTODEF R ON
R.CODCOLIGADA = P.CODCOLIGADA
AND R.IDPRD = P.IDPRD

LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE Z ON
A.CODFILIAL = Z.CODFILIAL
AND A.CODCOLIGADA = Z.CODCOLIGADA
AND A.CODORDEM = Z.CODORDEM
AND A.IDATIVIDADE = Z.IDATVORDEM

WHERE 
E.CODCCUSTO LIKE '3.07829.32.001'
GROUP BY E.CODCCUSTO, A.CODORDEM, D.CODATIVIDADE, D.DSCATIVIDADE, A.IDATIVIDADE,C.QTPREVISTA,C.QUANTIDADE, C.STATUS,Y.NUMLOTE,B.IDLOTE,P.CODIGOPRD,P.IDPRD,
Z.NUMPLANOCORTE,R.CODUNDCONTROLE,A.IDPRODUTO

ORDER BY A.CODORDEM




