--SELECT ATV.CODCOLIGADA, ATV.CODFILIAL,
-- 	ISNULL((	SELECT TOP 1 AATVD.DSCATIVIDADE 
--			FROM  KATVESTRUTURA AATVE 			
--		INNER JOIN KATIVIDADE AATVD ON AATVE.CODCOLIGADA = AATVD.CODCOLIGADA AND AATVE.CODFILIAL = AATVD.CODFILIAL AND AATVE.CODATIVIDADE = AATVD.CODATIVIDADE 		
--		WHERE	AATVE.CODCOLIGADA = ATV.CODCOLIGADA 		
--		AND		AATVE.CODFILIAL = ATV.CODFILIAL 		
--		AND		AATVE.CODESTRUTURA = ATV.CODESTRUTURA 		
--		AND		AATVE.PRIORIDADE < ATVE.PRIORIDADE 		
--		ORDER BY AATVE.PRIORIDADE DESC),'-') ATV_ANTERIOR, 	
--		P.CODIGOPRD, P.IDPRD, P.DESCRICAO DSCITEM, ATV.QTPREVISTA QTDEPLANEJADA, ATV.QUANTIDADE APONTADO,
--		 ATV.QTPREVISTA-ATV.QUANTIDADE SALDO, ATV.CODPOSTO, P.CODUNDCONTROLE, ATV.CODORDEM OP,ATV.IDATVORDEM, ATVE.PRIORIDADE, 	
--		 (SELECT 		CUSTO 	 
--			FROM 		KCUSTOPOSTO (NOLOCK) X 	 
--			WHERE 		X.CODCOLIGADA = ATV.CODCOLIGADA AND X.CODFILIAL = ATV.CODFILIAL 		
--			AND X.CODPOSTO = ATV.CODPOSTO AND CAST(DTINICIAL AS DATE) <= CAST(GETDATE() AS DATE) AND CAST(DTFINAL AS DATE) >= CAST(GETDATE() AS DATE) 	) 
--			CUSTO_POSTO, 	ATVD.DSCATIVIDADE, ATVD.CODATIVIDADE, TRFC.CELULA, TRFC.CELULA+'-'+C.DESCRICAO CELULAR,  	
--			ATVE.CODESTRUTURA, ATVE.CODATIVIDADE,TRF.IDPRJ, PRJ.CODPRJ OS, 	TRF.FOLGACALC, 	ATV.PERCENTUAL AVANCO_REALIZADO, 	
--			Z.CODSUCATA, Z.QTDESUCATA, Z.QUANTIDADE QTDEPLANO, Z.QTDEAPONTADA, 	
--			ISNULL(( 		SELECT 			SUM(ISNULL(QTDEAPONTADA,0)) 		
--			FROM 			ZMDPLANOAPROVEITAMENTOCORTE 		
--			WHERE  			NUMPLANOCORTE = Z.NUMPLANOCORTE 			
--			AND CODCOLIGADA = ATV.CODCOLIGADA AND CODFILIAL = ATV.CODFILIAL  	),0) TEM_APONTAMENTO, 		
--			ISNULL((	SELECT TOP 1 AATVD.DSCATIVIDADE 		FROM  KATVORDEMCOMPL AATVE 			
--			INNER JOIN KATVORDEM ATVOD ON AATVE.CODCOLIGADA = ATVOD.CODCOLIGADA 
--			AND AATVE.CODFILIAL = ATVOD.CODFILIAL AND AATVE.IDATVORDEM = ATVOD.IDATVORDEM 			
--			INNER JOIN KATIVIDADE AATVD ON AATVE.CODCOLIGADA = AATVD.CODCOLIGADA AND AATVE.CODFILIAL = AATVD.CODFILIAL AND AATVD.CODATIVIDADE = ATVOD.CODATIVIDADE 		
--			WHERE	AATVE.CODCOLIGADA = ATV.CODCOLIGADA 		AND		AATVE.CODFILIAL = ATV.CODFILIAL 		
--			AND		AATVE.CODESTRUTURA = ATV.CODESTRUTURA  		
--			AND		AATVE.PRIORIDADE > ATVOC.PRIORIDADE 		
--			ORDER BY AATVE.PRIORIDADE),'ULTIMA') ATV_POSTERIOR 
--			FROM  	KATVORDEM ATV 	
--			INNER JOIN KATVORDEMCOMPL ATVOC ON ATV.CODCOLIGADA = ATVOC.CODCOLIGADA AND ATV.CODFILIAL = ATVOC.CODFILIAL AND ATV.CODORDEM = ATVOC.CODORDEM AND ATV.IDATVORDEM = ATVOC.IDATVORDEM 	
--			INNER JOIN KATVESTRUTURA ATVE ON ATV.CODCOLIGADA = ATVE.CODCOLIGADA AND ATV.CODFILIAL = ATVE.CODFILIAL AND ATV.CODESTRUTURA = ATVE.CODESTRUTURA AND ATV.CODATIVIDADE = ATVE.CODATIVIDADE
--			INNER JOIN KATIVIDADE ATVD ON ATV.CODCOLIGADA = ATVD.CODCOLIGADA AND ATV.CODFILIAL = ATVD.CODFILIAL AND ATV.CODATIVIDADE = ATVD.CODATIVIDADE 	
--			INNER JOIN TPRD P ON ATV.CODCOLIGADA = P.CODCOLIGADA AND ATV.CODESTRUTURA = P.CODIGOPRD 	
--			left JOIN MTRF TRF ON TRF.CODCOLIGADA = ATV.CODCOLIGADA AND TRF.CODTRFAUX = ATV.CODORDEM 	
--			left JOIN MPRJ PRJ ON PRJ.CODCOLIGADA = TRF.CODCOLIGADA AND PRJ.IDPRJ = TRF.IDPRJ AND PRJ.POSICAO IN (1,4) 	
--			INNER JOIN MTRFCOMPL TRFC ON TRF.CODCOLIGADA = TRFC.CODCOLIGADA AND TRF.IDPRJ = TRFC.IDPRJ  AND TRF.IDTRF = TRFC.IDTRF 	
--			INNER JOIN GCONSIST C ON C.CODTABELA='CELULA' AND C.APLICACAO = 'M' AND C.CODINTERNO = TRFC.CELULA 	
--			INNER JOIN ZMDPLANOAPROVEITAMENTOCORTE Z ON ATV.CODCOLIGADA = Z.CODCOLIGADA AND ATV.CODFILIAL = Z.CODFILIAL AND ATV.CODORDEM = Z.CODORDEM AND ATV.IDATVORDEM = Z.IDATVORDEM 
--			WHERE ATV.CODCOLIGADA = 1 AND ATV.CODFILIAL = 7 AND	Z.NUMPLANOCORTE = 'CNC003952' 
--			ORDER BY 	ATV.CODORDEM, ATVE.PRIORIDADE 

SELECT DISTINCT C.*,P.CODMO,CAST(P.DTHRINICIAL AS DATE) DATAPROGRAMADA FROM (
	SELECT SUM(PC.QUANTIDADE) QUANTIDADE,SUM(PC.QTDEAPONTADA) QTDEAPONTADA,PC.NUMPLANOCORTE--,( SELECT DISTINCT CAST(DTHRINICIAL AS DATE) FROM ZMDKATVORDEMPROGRAMACAO WHERE NUMPLANOCORTE = PC.NUMPLANOCORTE AND STATUS IN (0))
	FROM ZMDPLANOAPROVEITAMENTOCORTE PC
	GROUP BY PC.NUMPLANOCORTE
	HAVING SUM(QUANTIDADE)>SUM(QTDEAPONTADA) AND SUM(QTDEAPONTADA) IS NOT NULL AND SUM(QTDEAPONTADA)<>0 ) C
	INNER JOIN ZMDKATVORDEMPROGRAMACAO P ON
	P.NUMPLANOCORTE=C.NUMPLANOCORTE
	AND P.STATUS IN (0,1)

	select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC004092'

	select * from KMAOOBRAALOC where CODORDEM in (select distinct CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC004002-2') and IDATVORDEM=1