WITH CTE AS (
	SELECT * FROM (
		SELECT EX1.INDICE,K.CODORDEM,KA.IDATVORDEM,A.DSCATIVIDADE,K.STATUS STATUS_OP,KA.STATUS STATUS_ATV,KA.PERCENTUAL,
		(SELECT COUNT(*) FROM  KMAOOBRAALOC WHERE
		CODCOLIGADA=KA.CODCOLIGADA
		AND CODFILIAL=KA.CODFILIAL
		AND CODORDEM=KA.CODORDEM
		AND IDATVORDEM=KA.IDATVORDEM AND EFETIVADO=1) APONT,
		CASE WHEN PAPC.NUMPLANOCORTE IS NULL 
			THEN 0 
			ELSE 
				CASE WHEN PAPC.QTDEAPONTADA IS NULL 
					THEN  CASE WHEN PAPC.QUANTIDADE-KA.QUANTIDADE < 0  
								THEN 0
								ELSE PAPC.QUANTIDADE-KA.QUANTIDADE
								END
					ELSE PAPC.QUANTIDADE-PAPC.QTDEAPONTADA
					END			
			END AS SALDOPAPC,
		(SELECT COUNT(*) FROM (SELECT ID FROM  ZMDKATVORDEMPROGRAMACAO (NOLOCK) WHERE
		CODCOLIGADA=KA.CODCOLIGADA
		AND CODFILIAL=KA.CODFILIAL
		AND CODORDEM=KA.CODORDEM
		AND IDATVORDEM=KA.IDATVORDEM AND STATUS IN (0,1) 
		UNION
		SELECT ID FROM  KMAOOBRAALOC (NOLOCK) WHERE
		CODCOLIGADA=KA.CODCOLIGADA
		AND CODFILIAL=KA.CODFILIAL
		AND CODORDEM=KA.CODORDEM
		AND IDATVORDEM=KA.IDATVORDEM AND EFETIVADO=0
		) R ) PROG,
		CASE WHEN KA.CODATIVIDADE LIKE 'WATVOO5%' THEN 1 ELSE 0 END AS CQ,
		CASE WHEN PAPC.NUMPLANOCORTE IS NULL THEN '0' ELSE PAPC.NUMPLANOCORTE END AS PAPC
		FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) EX1
			INNER JOIN KORDEM (NOLOCK) K ON 
			K.CODCOLIGADA=EX1.CODCOLIGADA
			AND K.CODFILIAL=EX1.CODFILIAL
			AND K.CODCCUSTO=EX1.OS COLLATE SQL_Latin1_General_CP1_CI_AI
			INNER JOIN KATVORDEM (NOLOCK) KA ON
			KA.CODCOLIGADA=K.CODCOLIGADA
			AND KA.CODFILIAL=K.CODFILIAL
			AND KA.CODORDEM=K.CODORDEM
			AND KA.CODESTRUTURA=EX1.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
			LEFT JOIN ZMDPLANOAPROVEITAMENTOCORTE (NOLOCK) PAPC ON
			PAPC.CODCOLIGADA=KA.CODCOLIGADA
			AND PAPC.CODFILIAL=KA.CODFILIAL
			AND PAPC.CODORDEM=KA.CODORDEM
			AND PAPC.CODATIVIDADE=KA.CODATIVIDADE
			INNER JOIN KATIVIDADE (NOLOCK) A ON
			A.CODCOLIGADA=KA.CODCOLIGADA
			AND A.CODFILIAL=KA.CODFILIAL
			AND A.CODATIVIDADE=KA.CODATIVIDADE
			INNER JOIN KORDEMCOMPL (NOLOCK) KL ON
			KL.CODCOLIGADA=KA.CODCOLIGADA
			AND KL.CODFILIAL=KA.CODFILIAL
			AND KL.CODORDEM=KA.CODORDEM
			AND KL.NUMEXEC=EX1.EXECUCAO
		WHERE EX1.ITEMEXCLUSIVO<>2 
		AND OS='3.07847.32.001' AND EX1.EXECUCAO=4 AND K.STATUS NOT IN (5,6) AND KA.STATUS NOT IN (5,6) AND COALESCE(K.REPROCESSAMENTO,0)=0
		) R
	)


SELECT * FROM 
(SELECT INDICE,CODORDEM,IDATVORDEM,DSCATIVIDADE, 
CASE WHEN PAPC = '0' --NÃO É PLANO DE CORTE
	THEN CASE WHEN APONT >=1 --TEM APONTAMENTO
		THEN --TEM APONTAMENTO
			CASE WHEN PERCENTUAL>=100 
				THEN 
				'Corrigir status da atividade'
				ELSE
				'Preencher Avanção da atividade'
			END
		ELSE --NÃOTEM APONTAMENTO
			CASE WHEN PROG >= 1 -- TEM PROGRAMAÇÃO
				THEN -- TEM PROGRAMAÇÃO
				'Realizar apontamento da atividade' 
				ELSE -- NÃOTEM PROGRAMAÇÃO
					CASE WHEN CQ=1 -- É ATIVIDADE DE CQ
						THEN 
						'Realizar apontamento sem programação ou requisitar cancelamento da atividade'
						ELSE
						'Realizar programação da atividade ou requisitar cancelamento da atividade'
					END
				END
			END
	ELSE 
		CASE WHEN PROG >=1 -- PROGRAMAÇÃO
			THEN -- COM PROGRAMAÇÃO
				CASE WHEN APONT >=1 --APONTAMENTO
					THEN -- TEM APONTAMENTO
						CASE WHEN PERCENTUAL=100 -- AVANÇO
							THEN -- AVANÇO TOTAL
							'Corrigir status da atividade'
							ELSE
							CASE WHEN SALDOPAPC > 0 -- SALDO DE QUANTIDADE DO PLANO
								THEN -- FALTA CONCLUIR
								CONCAT('Conluir apontamento do plano ',PAPC)
								ELSE -- SEM SALDO DE QUANTIDADE
								'Cadastrar novo plano e Apontar'
							END
						END
					ELSE -- SEM APONTAMENTO
					CONCAT('Realizar apontamento do plano ',PAPC)
				END
			ELSE -- SEM PROGRAMAÇÃO
			CONCAT('Realizar programação do plano ',PAPC)
		END
	END AS ACAO
	FROM CTE ) R
ORDER BY LEN(INDICE) DESC,CAST('/'+REPLACE(INDICE,'.','/')+'/' AS hierarchyid),CODORDEM,IDATVORDEM

