select sum(quantidade) from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-11')

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-11'

select distinct DTHRINICIAL,reccreatedon,codmo from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-11') and IDATVORDEM=1
select codccusto from KESTRUTURA where CODESTRUTURA in (select distinct CODESTRUTURA from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-11')

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select sum(quantidade) from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-8')

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-8'

select distinct DTHRINICIAL,reccreatedon,codmo  from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-8') and IDATVORDEM=1
select codccusto from KESTRUTURA where CODESTRUTURA in (select distinct CODESTRUTURA from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003930-8')

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select sum(quantidade) from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883')
select * from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883')

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883'

select distinct DTHRINICIAL,reccreatedon,codmo  from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883') and IDATVORDEM=1
select codccusto from KESTRUTURA where CODESTRUTURA in (select distinct CODESTRUTURA from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883')

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

select sum(quantidade) from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1')
select * from KMOVESTOQUELOTE where IDLOTE=30895--(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1')
select * from KATVORDEMMPLOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1')
select * From KATVORDEMMP where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1') and IDATIVIDADE=1

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1'

select distinct reccreatedon,codmo from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1') and IDATVORDEM=1
select codccusto from KESTRUTURA where CODESTRUTURA in (select distinct CODESTRUTURA from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1')

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


select * from TMOV where codtmv='1.2.29'

select * from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003900') and IDATVORDEM=1 order by DTHRINICIAL
CNC003987-1 CNC003987-2


select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-2'


select * from KATVORDEm where CODORDEM in (
select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-2') and IDATVORDEM=1

select * from KATVORDEMMP where CODORDEM in (
select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1') and IDATIVIDADE=1

select sum(quantidade) from KATVORDEMMPLOTE where IDLOTE=30895


select sum(quantidade) from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883')
select * from KMOVESTOQUELOTE where IDLOTE=(select distinct IDLOTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883')

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883'

select distinct reccreatedon from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003883') and IDATVORDEM=1

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC003987-1'

select * from KATVORDEMMPLOTE where IDLOTE=30895


SELECT * FROM KATVORDEMMP WHERE CODORDEM='33808/22'

--##############################################################################################################################################################################################

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC004152'

select NUMPLANOCORTE from ZMDPLANOAPROVEITAMENTOCORTE where CODORDEM  in ('32376/22','38530/22','30719/22','43042/22','39036/22','39383/22','37420/22','30475/22','38530/22','32376/22','30719/22')

select distinct NUMPLANOCORTE from ZMDPLANOAPROVEITAMENTOCORTE where NUMLOTE=207570

select NUMPLANOCORTE from ZMDPLANOAPROVEITAMENTOCORTE where CODORDEM  in ('38575/22')

select * from ZMDPLANOAPROVEITAMENTOCORTE where NUMLOTE=201994

select * from ZMDKATVORDEMPROGRAMACAO where NUMPLANOCORTE='CNC004152'
select * from KMAOOBRAALOC where CODORDEM in (select CODORDEM from ZMDKATVORDEMPROGRAMACAO where NUMPLANOCORTE='CNC004152') and IDATVORDEM=1 and efetivado=0

select * From KMAOOBRAALOC where CODMO=72243 and CODORDEM='35008/22' and IDATVORDEM=1--CORRIGIR APONTAMENTO
select * From KMAOOBRAALOC where CODMO=72243 and CODORDEM='38575/22' and IDATVORDEM=1--CORRIGIR APONTAMENTO
select * From KMAOOBRAALOC where CODMO=72243 and CODORDEM='30632/22' and IDATVORDEM=1--CORRIGIR APONTAMENTO
select * From KMAOOBRAALOC where CODMO=72243 and CODORDEM in (select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC004141') and IDATVORDEM=1 order by DTHRINICIAL--CORRIGIR APONTAMENTO
select * From KMAOOBRAALOC where CODMO=72243 and CODORDEM='38499/22' and IDATVORDEM=1--CORRIGIR APONTAMENTO

SELECT * FROM KPARADAATV WHERE CODORDEM IN ( SELECT CODORDEM FROM ZMDPLANOAPROVEITAMENTOCORTE WHERE NUMPLANOCORTE='CNC004003-1' ) AND IDATVORDEM=1 AND CODRAZAO='DDS' ORDER BY DTHRINICIO --CORRIGIR APONTAMENTO


select * From KMAOOBRAALOC where CODMO=72243 and CODORDEM in 
(select CODORDEM from ZMDPLANOAPROVEITAMENTOCORTE where NUMPLANOCORTE='CNC004014') and IDATVORDEM=1 order by DTHRINICIAL--CORRIGIR APONTAMENTO
--SELECT * FROM KPARADAATV WHERE CODORDEM IN ( SELECT CODORDEM FROM ZMDPLANOAPROVEITAMENTOCORTE WHERE NUMPLANOCORTE='CNC004014' ) AND IDATVORDEM=1 AND CODRAZAO='OPR' ORDER BY DTHRINICIO --CORRIGIR APONTAMENTO


select * from KMAOOBRAALOC where cast (DTHRFINAL as time) ='23:59:59.0000000' and cast (DTHRINICIAL as time)='23:59:59.0000000' order by DTHRINICIAL