SELECT * FROM (
SELECT DISTINCT INDICE,KI.CODORDEM,ISNULL(KI.QTDEEFETIVADA,0) QTDEEFETIVADA,KI.QTDEPLANEJADA,K.STATUS,KS.DSCSTATUS
	FROM FLUIG.DBO.Z_CRM_EX001005 (NOLOCK) EX1
		INNER JOIN KITEMORDEM KI (NOLOCK) ON
		KI.CODCOLIGADA=EX1.CODCOLIGADA
		AND KI.CODFILIAL=EX1.CODFILIAL
		AND KI.CODESTRUTURA=EX1.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
		INNER JOIN KORDEM K (NOLOCK) ON
		K.CODCOLIGADA=KI.CODCOLIGADA
		AND K.CODFILIAL=KI.CODFILIAL
		AND K.CODORDEM=KI.CODORDEM
		INNER JOIN KORDEMCOMPL (NOLOCK) KL ON
		KL.CODCOLIGADA=KI.CODCOLIGADA
		AND KL.CODFILIAL=KI.CODFILIAL
		AND KL.CODORDEM=KI.CODORDEM
		AND KL.NUMEXEC=EX1.EXECUCAO
		INNER JOIN KSTATUS (NOLOCK) KS ON
		KS.CODCOLIGADA=KI.CODCOLIGADA
		AND KS.CODSTATUS=K.STATUS
	WHERE EX1.ITEMEXCLUSIVO<>2 
	AND OS='3.07840.32.001' AND EX1.CODTRFPAI='1.20' AND EX1.EXECUCAO=1 AND KI.STATUS NOT IN (5,6) AND COALESCE(K.REPROCESSAMENTO,0)=0 
	) R
	ORDER BY LEN(INDICE) DESC,CAST('/'+REPLACE(INDICE,'.','/')+'/' AS hierarchyid),CODORDEM



