SELECT * FROM(
	SELECT DISTINCT KE.INDICE,KE.CODTRFPAI,B.IDCRIACAOPROCESSO,B.OSPROCESSO,KE.EXECUCAO,B.PRIORIDADE,B.NUMPRIORIDADE FROM Z_CRM_EX001021 A 
	INNER JOIN (
		SELECT R.IDCRIACAOPROCESSO,R.OSPROCESSO,R.EXECUCAO,COUNT(R.PRIORIDADE) NUMPRIORIDADE,R.PRIORIDADE FROM Z_CRM_EX001021 R
			GROUP BY R.IDCRIACAOPROCESSO,R.OSPROCESSO,R.EXECUCAO,R.PRIORIDADE) B ON
				B.IDCRIACAOPROCESSO=A.IDCRIACAOPROCESSO
				AND B.OSPROCESSO=A.OSPROCESSO
				AND B.EXECUCAO=A.EXECUCAO
		INNER JOIN Z_CRM_EX001005 KE ON
			KE.IDCRIACAO=B.IDCRIACAOPROCESSO
			AND KE.OS=B.OSPROCESSO
			AND KE.EXECUCAO=B.EXECUCAO
	WHERE B.NUMPRIORIDADE>1 AND KE.ITEMEXCLUSIVO<>2) R2
ORDER BY CAST('/' + REPLACE(INDICE, '.', '/') + '/' AS HIERARCHYID),OSPROCESSO,EXECUCAO








