;WITH CTE_SC AS (
SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.CODFILIAL,T.IDMOV,T.NUMEROMOV,TD.NOME DESCMOV,T.SERIE,T.VALORBRUTO,T.VALORLIQUIDO,TI.RECCREATEDBY,T.DATAEXTRA1 DATAENTREGA,
T.STATUS,TI.DATAEMISSAO,TI.IDPRD,TP.CODIGOPRD,TI.QUANTIDADETOTAL,TP.DESCRICAO,TI.CODUND,TI.VALORBRUTOITEM,TI.CODTB1FLX,F.DESCRICAO CLASSIFICACAO,
RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,M.IDTRF,M.CODTRF,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM,
(SELECT NUMEROMOV FROM TMOV X WHERE X.CODCOLIGADA=T.CODCOLIGADA AND X.IDMOV=TLA.IDMOVDESTINO) ORDEM_DE_COMPRA,TLA.IDMOVDESTINO
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=TI.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN FTB1 F ON
F.CODCOLIGADA=T.CODCOLIGADA
AND F.CODFILIAL=T.CODFILIAL
AND F.CODTB1FLX=T.CODTB1FLX
INNER JOIN TITMMOVRATCCU RAT ON
RAT.CODCOLIGADA=T.CODCOLIGADA
AND RAT.IDMOV=T.IDMOV
AND RAT.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN MTRF M ON
M.CODCOLIGADA=T.CODCOLIGADA
AND M.IDPRJ=RAT.IDPRJ
AND M.IDTRF=RAT.IDTRF
INNER JOIN TMOVHISTORICO TH ON
TH.CODCOLIGADA=T.CODCOLIGADA
AND TH.IDMOV=T.IDMOV
INNER JOIN TITMMOVHISTORICO TH2 ON
TH2.CODCOLIGADA=T.CODCOLIGADA
AND TH2.IDMOV=T.IDMOV
AND TH2.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TTMV TD ON
TD.CODTMV=T.CODTMV
AND TD.CODCOLIGADA=T.CODCOLIGADA
LEFT JOIN TMOVRELAC TLA ON
TLA.IDMOVORIGEM=T.IDMOV
AND TLA.CODCOLORIGEM=T.CODCOLIGADA
WHERE T.IDMOV='983263'
), CTE_OC AS (

SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.IDMOV,T.CODFILIAL,T.NUMEROMOV,T.CODTMV,TD.NOME DESCMOV,T.SERIE,T.DATAEMISSAO,T.DATAEXTRA1 DATENTREGA,T.STATUS, F.DESCRICAO CLASSIFICACAO,
TI.IDPRD,TP.CODIGOPRD,TI.CODUND,TI.QUANTIDADETOTAL,TI.VALORLIQUIDO,RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM,
(SELECT NUMEROMOV FROM TMOV X WHERE X.CODCOLIGADA=T.CODCOLIGADA AND X.IDMOV=TLA.IDMOVDESTINO) ENTRADA_DE_NOTA,TLA.IDMOVDESTINO
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=TI.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN FTB1 F ON
F.CODCOLIGADA=T.CODCOLIGADA
AND F.CODTB1FLX=T.CODTB1FLX
INNER JOIN TITMMOVRATCCU RAT ON
RAT.CODCOLIGADA=T.CODCOLIGADA
AND RAT.IDMOV=T.IDMOV
AND RAT.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN MTRF M ON
M.CODCOLIGADA=T.CODCOLIGADA
AND M.IDPRJ=RAT.IDPRJ
AND M.IDTRF=RAT.IDTRF
INNER JOIN TMOVHISTORICO TH ON
TH.CODCOLIGADA=T.CODCOLIGADA
AND TH.IDMOV=T.IDMOV
INNER JOIN TITMMOVHISTORICO TH2 ON
TH2.CODCOLIGADA=T.CODCOLIGADA
AND TH2.IDMOV=T.IDMOV
AND TH2.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TTMV TD ON
TD.CODTMV=T.CODTMV
AND TD.CODCOLIGADA=T.CODCOLIGADA
AND TD.TIPOIDENTIFIC=T.TIPO
LEFT JOIN TMOVRELAC TLA ON
TLA.IDMOVORIGEM=T.IDMOV
AND TLA.CODCOLORIGEM=T.CODCOLIGADA
WHERE T.IDMOV='984256'
)
,
CTE_LOTE AS (
		
		SELECT * FROM TMOVRELAC where IDMOVORIGEM='984256' -- OC e RECEBIMENTO PARCIAL DE NOTA 1.1.02 e 1.1.08

)

SELECT * FROM CTE_OC
SELECT * FROM TMOVRELAC WHERE IDMOVORIGEM='987200'

SELECT * FROM TMOV WHERE IDMOV='987200'

---------------------------------------------------------------------------  CONSULTAS SEPARADAS  --------------------------------------------------------------------------------------------------

SELECT * FROM TMOV WHERE IDMOV='983263' -- SC 1.1.33

SELECT * FROM TMOVRELAC where IDMOVORIGEM='983263' -- SC e OC 1.1.33 e 1.1.02

SELECT * FROM TMOV WHERE IDMOV='984256' -- OC 1.1.02

SELECT * FROM TMOVRELAC where IDMOVORIGEM='984256' -- OC e RECEBIMENTO PARCIAL DE NOTA 1.1.02 e 1.1.08

SELECT * FROM TMOV WHERE IDMOV='987200' -- RECEBIMENTO PARCIAL DE NOTA 1.1.08

SELECT * FROM TMOVRELAC where IDMOVORIGEM='987200' -- RECEBIMENTO PARCIAL DE NOTA e ENTRADA DE NOTA 1.1.08 e 1.2.51

SELECT * FROM TMOV WHERE IDMOV='987218' -- ENTRADA DE NOTA 1.2.51

SELECT * FROM TITMLOTEPRD where IDMOV='987218' -- LOTES DO MOVIMENTO 1.2.51

                                             
---------------------------------------------------------------------------  SC   --------------------------------------------------------------------------------------------------

SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.CODFILIAL,T.IDMOV,T.NUMEROMOV,TD.NOME DESCMOV,T.SERIE,T.VALORBRUTO,T.VALORLIQUIDO,TI.RECCREATEDBY,T.DATAEXTRA1 DATAENTREGA,
T.STATUS,TI.DATAEMISSAO,TI.IDPRD,TP.CODIGOPRD,TI.QUANTIDADETOTAL,TP.DESCRICAO,TI.CODUND,TI.VALORBRUTOITEM,TI.CODTB1FLX,F.DESCRICAO CLASSIFICACAO,
RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,M.IDTRF,M.CODTRF,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM,
(SELECT NUMEROMOV FROM TMOV X WHERE X.CODCOLIGADA=T.CODCOLIGADA AND X.IDMOV=TLA.IDMOVDESTINO) ORDEM_DE_COMPRA,TLA.IDMOVDESTINO
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=TI.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN FTB1 F ON
F.CODCOLIGADA=T.CODCOLIGADA
AND F.CODFILIAL=T.CODFILIAL
AND F.CODTB1FLX=T.CODTB1FLX
INNER JOIN TITMMOVRATCCU RAT ON
RAT.CODCOLIGADA=T.CODCOLIGADA
AND RAT.IDMOV=T.IDMOV
AND RAT.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN MTRF M ON
M.CODCOLIGADA=T.CODCOLIGADA
AND M.IDPRJ=RAT.IDPRJ
AND M.IDTRF=RAT.IDTRF
INNER JOIN TMOVHISTORICO TH ON
TH.CODCOLIGADA=T.CODCOLIGADA
AND TH.IDMOV=T.IDMOV
INNER JOIN TITMMOVHISTORICO TH2 ON
TH2.CODCOLIGADA=T.CODCOLIGADA
AND TH2.IDMOV=T.IDMOV
AND TH2.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TTMV TD ON
TD.CODTMV=T.CODTMV
AND TD.CODCOLIGADA=T.CODCOLIGADA
AND TD.TIPOIDENTIFIC=T.TIPO
LEFT JOIN TMOVRELAC TLA ON
TLA.IDMOVORIGEM=T.IDMOV
AND TLA.CODCOLORIGEM=T.CODCOLIGADA
WHERE T.IDMOV='983263'

--------------------------------------------------------------------------  OC   ------------------------------------------------------------------------------------------------------

SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.IDMOV,T.CODFILIAL,T.NUMEROMOV,T.CODTMV,TD.NOME DESCMOV,T.SERIE,T.DATAEMISSAO,T.DATAEXTRA1 DATENTREGA,T.STATUS, F.DESCRICAO CLASSIFICACAO,
TI.IDPRD,TP.CODIGOPRD,TI.CODUND,TI.QUANTIDADETOTAL,TI.VALORLIQUIDO,RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM,
(SELECT NUMEROMOV FROM TMOV X WHERE X.CODCOLIGADA=T.CODCOLIGADA AND X.IDMOV=TLA.IDMOVDESTINO) ENTRADA_DE_NOTA,TLA.IDMOVDESTINO
FROM TMOV T
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=TI.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN FTB1 F ON
F.CODCOLIGADA=T.CODCOLIGADA
AND F.CODTB1FLX=T.CODTB1FLX
INNER JOIN TITMMOVRATCCU RAT ON
RAT.CODCOLIGADA=T.CODCOLIGADA
AND RAT.IDMOV=T.IDMOV
AND RAT.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN MTRF M ON
M.CODCOLIGADA=T.CODCOLIGADA
AND M.IDPRJ=RAT.IDPRJ
AND M.IDTRF=RAT.IDTRF
INNER JOIN TMOVHISTORICO TH ON
TH.CODCOLIGADA=T.CODCOLIGADA
AND TH.IDMOV=T.IDMOV
INNER JOIN TITMMOVHISTORICO TH2 ON
TH2.CODCOLIGADA=T.CODCOLIGADA
AND TH2.IDMOV=T.IDMOV
AND TH2.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TTMV TD ON
TD.CODTMV=T.CODTMV
AND TD.TIPOIDENTIFIC=T.TIPO
AND TD.CODCOLIGADA=T.CODCOLIGADA
LEFT JOIN TMOVRELAC TLA ON
TLA.IDMOVORIGEM=T.IDMOV
AND TLA.CODCOLORIGEM=T.CODCOLIGADA
WHERE T.IDMOV='984256'

---------------------------------------------------------------------------  RECEBIMENTO PARCIAL DE NOTA e ENTRADA DE NOTA    --------------------------------------------------------------------------------------------------

SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.IDMOV,T.CODFILIAL,T.NUMEROMOV,T.CODTMV,TD.NOME DESCMOV,T.SERIE,T.DATAEMISSAO,T.DATAEXTRA1 DATENTREGA,T.STATUS, F.DESCRICAO CLASSIFICACAO,
TI.IDPRD,TP.CODIGOPRD,TI.CODUND,TI.QUANTIDADETOTAL,TI.VALORLIQUIDO,RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM,
(SELECT NUMEROMOV FROM TMOV X WHERE X.CODCOLIGADA=T.CODCOLIGADA AND X.IDMOV=TLA.IDMOVDESTINO) ENTRADA_DE_NOTA,TLA.IDMOVDESTINO,TCL.OC FROM
TMOV T
INNER JOIN TMOVCOMPL TCL ON
TCL.CODCOLIGADA=T.CODCOLIGADA 
AND TCL.IDMOV=T.IDMOV
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=TI.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN FTB1 F ON
F.CODCOLIGADA=T.CODCOLIGADA
AND F.CODTB1FLX=T.CODTB1FLX
INNER JOIN TITMMOVRATCCU RAT ON
RAT.CODCOLIGADA=T.CODCOLIGADA
AND RAT.IDMOV=T.IDMOV
AND RAT.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN MTRF M ON
M.CODCOLIGADA=T.CODCOLIGADA
AND M.IDPRJ=RAT.IDPRJ
AND M.IDTRF=RAT.IDTRF
INNER JOIN TMOVHISTORICO TH ON
TH.CODCOLIGADA=T.CODCOLIGADA
AND TH.IDMOV=T.IDMOV
INNER JOIN TITMMOVHISTORICO TH2 ON
TH2.CODCOLIGADA=T.CODCOLIGADA
AND TH2.IDMOV=T.IDMOV
AND TH2.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TTMV TD ON
TD.CODTMV=T.CODTMV
AND TD.TIPOIDENTIFIC=T.TIPO
AND TD.CODCOLIGADA=T.CODCOLIGADA
LEFT JOIN TMOVRELAC TLA ON
TLA.IDMOVORIGEM=T.IDMOV
AND TLA.CODCOLORIGEM=T.CODCOLIGADA
WHERE T.IDMOV='987200'

---------------------------------------------------------------------------  ENTRADA DE NOTA    --------------------------------------------------------------------------------------------------

SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.IDMOV,T.CODFILIAL,T.NUMEROMOV,T.CODTMV,TD.NOME DESCMOV,T.SERIE,T.DATAEMISSAO,T.STATUS, F.DESCRICAO CLASSIFICACAO,
TI.IDPRD,TP.CODIGOPRD,TI.CODUND,TI.QUANTIDADETOTAL,TI.VALORLIQUIDO,RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM,TCL.OC,TLOTE.NUMLOTE,TML.QUANTIDADE2 FROM
TMOV T
INNER JOIN TMOVCOMPL TCL ON
TCL.CODCOLIGADA=T.CODCOLIGADA 
AND TCL.IDMOV=T.IDMOV
INNER JOIN TITMMOV TI ON
TI.CODCOLIGADA=T.CODCOLIGADA 
AND TI.CODFILIAL=T.CODFILIAL
AND TI.IDMOV=T.IDMOV
INNER JOIN TPRD TP ON
TP.CODCOLIGADA=TI.CODCOLIGADA
AND TP.IDPRD=TI.IDPRD
INNER JOIN FTB1 F ON
F.CODCOLIGADA=T.CODCOLIGADA
AND F.CODTB1FLX=T.CODTB1FLX
INNER JOIN TITMMOVRATCCU RAT ON
RAT.CODCOLIGADA=T.CODCOLIGADA
AND RAT.IDMOV=T.IDMOV
AND RAT.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN MTRF M ON
M.CODCOLIGADA=T.CODCOLIGADA
AND M.IDPRJ=RAT.IDPRJ
AND M.IDTRF=RAT.IDTRF
INNER JOIN TMOVHISTORICO TH ON
TH.CODCOLIGADA=T.CODCOLIGADA
AND TH.IDMOV=T.IDMOV
INNER JOIN TITMMOVHISTORICO TH2 ON
TH2.CODCOLIGADA=T.CODCOLIGADA
AND TH2.IDMOV=T.IDMOV
AND TH2.NSEQITMMOV=TI.NSEQITMMOV
INNER JOIN TTMV TD ON
TD.CODTMV=T.CODTMV
AND TD.TIPOIDENTIFIC=T.TIPO
AND TD.CODCOLIGADA=T.CODCOLIGADA
LEFT JOIN TMOVRELAC TLA ON
TLA.IDMOVORIGEM=T.IDMOV
AND TLA.CODCOLORIGEM=T.CODCOLIGADA
LEFT JOIN TITMLOTEPRD TML ON
TML.CODCOLIGADA=TI.CODCOLIGADA
AND TML.IDMOV=T.IDMOV 
AND TML.NSEQITMMOV=TI.NSEQITMMOV
LEFT JOIN TLOTEPRD TLOTE ON
TLOTE.CODCOLIGADA=TML.CODCOLIGADA
AND TLOTE.IDLOTE=TML.IDLOTE
WHERE T.IDMOV='987218'

---------------------------------------------------------------------------  TODOS MOVIMENTOS    --------------------------------------------------------------------------------------------------

;WITH CTE_RAS
     AS (SELECT T.CODCOLIGADA,
                TLA.IDMOVDESTINO,
                TLA.IDMOVORIGEM,
                T2.CODTMV,
                T2.STATUS,
                T2.NUMEROMOV,
                TD.NOME
         FROM   TMOV T
                INNER JOIN TMOVRELAC TLA
                        ON TLA.IDMOVORIGEM = T.IDMOV
                           AND TLA.CODCOLORIGEM = T.CODCOLIGADA
                INNER JOIN TMOV T2
                        ON T2.CODCOLIGADA = T.CODCOLIGADA
                           AND T2.IDMOV = TLA.IDMOVDESTINO
                INNER JOIN TTMV TD
                        ON TD.CODTMV = T2.CODTMV
                           AND TD.CODCOLIGADA = T2.CODCOLIGADA
                           AND TD.TIPOIDENTIFIC = T2.TIPO
         WHERE  T.NUMEROMOV = '084901'
                AND T.CODTMV = '1.1.05'
         UNION ALL
         SELECT CTE_RAS.CODCOLIGADA,
                TLA.IDMOVDESTINO,
                CTE_RAS.IDMOVDESTINO,
                T.CODTMV,
                T.STATUS,
                T.NUMEROMOV,
                TD.NOME
         FROM   CTE_RAS
                INNER JOIN TMOVRELAC TLA
                        ON TLA.IDMOVORIGEM = CTE_RAS.IDMOVDESTINO
                           AND TLA.CODCOLORIGEM = CTE_RAS.CODCOLIGADA
                INNER JOIN TMOV T
                        ON T.CODCOLIGADA = CTE_RAS.CODCOLIGADA
                           AND T.IDMOV = TLA.IDMOVDESTINO
                INNER JOIN TTMV TD
                        ON TD.CODTMV = T.CODTMV
                           AND TD.CODCOLIGADA = T.CODCOLIGADA
                           AND TD.TIPOIDENTIFIC = T.TIPO)

SELECT CODCOLIGADA,
       IDMOV,
       PAI,
       CODTMV,
       CASE STATUS
         WHEN 'A' THEN 'PENDENTE / A FATURAR'
         WHEN 'B' THEN 'BLOQUEADO'
         WHEN 'C' THEN 'CANCELADO'
         WHEN 'F' THEN 'FATURADO '
         WHEN 'G' THEN 'PARCIALMENTE FATURADO'
         WHEN 'N' THEN 'NORMAL'
         WHEN 'P' THEN 'PARCIALMENTE QUITADO'
         WHEN 'Q' THEN 'QUITADO'
         WHEN 'R' THEN 'NÃO PROCESSADO'
         WHEN 'U' THEN 'EM FATURAMENTO'
         WHEN 'O' THEN 'AGUARDANDO ANÁLISE'
         WHEN 'Y' THEN 'NÃO INICIADO'
         WHEN 'E' THEN 'EM ANDAMENTO'
         WHEN 'Z' THEN 'TERMINADO'
         ELSE 'TESTE2'
       END AS STATUS,
       NUMEROMOV,
       NOME
FROM   (SELECT T.CODCOLIGADA,
               IDMOV,
               '0' PAI,
               T.CODTMV,
               STATUS,
               NUMEROMOV,
               TD.NOME
        FROM   TMOV T
               INNER JOIN TTMV TD
                       ON TD.CODTMV = T.CODTMV
                          AND TD.CODCOLIGADA = T.CODCOLIGADA
                          AND TD.TIPOIDENTIFIC = T.TIPO
        WHERE  T.NUMEROMOV = '084901'
               AND T.CODTMV = '1.1.05'
		UNION 
		SELECT T.CODCOLIGADA,
                TLA2.IDMOVORIGEM,
                0 IDMOVORIGEM,
                T2.CODTMV,
                T2.STATUS,
                T2.NUMEROMOV,
                TD.NOME
         FROM   TMOV T
                INNER JOIN TMOVRELAC TLA
                        ON TLA.IDMOVORIGEM = T.IDMOV
                           AND TLA.CODCOLORIGEM = T.CODCOLIGADA
				INNER JOIN TMOVRELAC TLA2
						ON TLA2.IDMOVDESTINO = TLA.IDMOVDESTINO
							AND TLA2.CODCOLORIGEM = T.CODCOLIGADA
                INNER JOIN TMOV T2
                        ON T2.CODCOLIGADA = T.CODCOLIGADA
                           AND T2.IDMOV = TLA2.IDMOVORIGEM
                INNER JOIN TTMV TD
                        ON TD.CODTMV = T2.CODTMV
                           AND TD.CODCOLIGADA = T2.CODCOLIGADA
                           AND TD.TIPOIDENTIFIC = T2.TIPO
         WHERE  T.NUMEROMOV = '084901'
                AND T.CODTMV = '1.1.05'
        UNION
        SELECT *
        FROM   CTE_RAS
		) R 

---------------------------------------------------------------------------  MOVIMENTO  --------------------------------------------------------------------------------------------------

 SELECT T.CODCOLIGADA,T.CODMOEVALORLIQUIDO,T.CODFILIAL,T.IDMOV,T.NUMEROMOV,TD.NOME DESCMOV,T.SERIE,
     T.VALORBRUTO,T.VALORLIQUIDO,TI.RECCREATEDBY,T.DATAEXTRA1 DATAENTREGA, 
     T.STATUS,TI.DATAEMISSAO,TI.IDPRD,TP.CODIGOPRD,TI.QUANTIDADETOTAL,TP.DESCRICAO,TI.CODUND,TI.VALORBRUTOITEM,TI.CODTB1FLX,F.DESCRICAO CLASSIFICACAO, 
     RAT.CODCCUSTO,RAT.PERCENTUAL,M.NOME,M.IDTRF,M.CODTRF,TH.HISTORICOLONGO OBSPEDIDO,TH2.HISTORICOLONGO OBSITEM, 
     (SELECT NUMEROMOV FROM TMOV X WHERE X.CODCOLIGADA=T.CODCOLIGADA AND X.IDMOV=TLA.IDMOVDESTINO) ORDEM_DE_COMPRA,
     TLA.IDMOVDESTINO,TLOTE.NUMLOTE,TML.QUANTIDADE2	QUANTIDADE_LOTE 
     FROM TMOV T 
     INNER JOIN TITMMOV TI ON 
     TI.CODCOLIGADA=T.CODCOLIGADA  
     AND TI.CODFILIAL=T.CODFILIAL 
     AND TI.IDMOV=T.IDMOV 
     INNER JOIN TPRD TP ON 
     TP.CODCOLIGADA=TI.CODCOLIGADA 
     AND TP.IDPRD=TI.IDPRD 
     INNER JOIN FTB1 F ON 
     F.CODCOLIGADA=T.CODCOLIGADA 
     AND F.CODFILIAL=T.CODFILIAL 
     AND F.CODTB1FLX=T.CODTB1FLX 
     INNER JOIN TITMMOVRATCCU RAT ON 
     RAT.CODCOLIGADA=T.CODCOLIGADA 
     AND RAT.IDMOV=T.IDMOV 
     AND RAT.NSEQITMMOV=TI.NSEQITMMOV 
     INNER JOIN MTRF M ON 
     M.CODCOLIGADA=T.CODCOLIGADA 
     AND M.IDPRJ=RAT.IDPRJ 
     AND M.IDTRF=RAT.IDTRF 
     INNER JOIN TMOVHISTORICO TH ON 
     TH.CODCOLIGADA=T.CODCOLIGADA 
     AND TH.IDMOV=T.IDMOV 
     INNER JOIN TITMMOVHISTORICO TH2 ON 
     TH2.CODCOLIGADA=T.CODCOLIGADA 
     AND TH2.IDMOV=T.IDMOV 
     AND TH2.NSEQITMMOV=TI.NSEQITMMOV 
     INNER JOIN TTMV TD ON 
     TD.CODTMV=T.CODTMV 
     AND TD.CODCOLIGADA=T.CODCOLIGADA 
     AND TD.TIPOIDENTIFIC=T.TIPO 
     LEFT JOIN TMOVRELAC TLA ON 
     TLA.IDMOVORIGEM=T.IDMOV 
     AND TLA.CODCOLORIGEM=T.CODCOLIGADA 
     LEFT JOIN TITMLOTEPRD TML ON 
     TML.CODCOLIGADA=TI.CODCOLIGADA 
     AND TML.IDMOV=T.IDMOV  
     AND TML.NSEQITMMOV=TI.NSEQITMMOV 
     LEFT JOIN TLOTEPRD TLOTE ON 
     TLOTE.CODCOLIGADA=TML.CODCOLIGADA 
     AND TLOTE.IDLOTE=TML.IDLOTE 
     WHERE T.IDMOV=  AND T.CODCOLIGADA=1 AND T.CODTMV=''






     ;WITH CTE_RAS AS( 
		    		SELECT T.CODCOLIGADA,TLA.IDMOVDESTINO,TLA.IDMOVORIGEM,T2.CODTMV,T2.STATUS,T2.NUMEROMOV,TD.NOME FROM 
		    		TMOV T 
		    		INNER JOIN TMOVRELAC TLA ON 
		    		TLA.IDMOVORIGEM=T.IDMOV 
		    		AND TLA.CODCOLORIGEM=T.CODCOLIGADA 
		    		INNER JOIN TMOV T2 ON 
		    		T2.CODCOLIGADA=T.CODCOLIGADA 
		    		AND T2.IDMOV=TLA.IDMOVDESTINO 
		    		INNER JOIN TTMV TD ON 
		    		TD.CODTMV=T2.CODTMV 
		    		AND TD.CODCOLIGADA=T2.CODCOLIGADA 
		    		AND TD.TIPOIDENTIFIC=T2.TIPO 
                                AND T.IDMOV="IDMOV"
		    		UNION ALL 
		    		SELECT CTE_RAS.CODCOLIGADA,TLA.IDMOVDESTINO,CTE_RAS.IDMOVDESTINO,T.CODTMV,T.STATUS,T.NUMEROMOV,TD.NOME FROM CTE_RAS 
		    		INNER JOIN TMOVRELAC TLA ON 
		    		TLA.IDMOVORIGEM=CTE_RAS.IDMOVDESTINO 
		    		AND TLA.CODCOLORIGEM=CTE_RAS.CODCOLIGADA 
		    		INNER JOIN TMOV T ON 
		    		T.CODCOLIGADA=CTE_RAS.CODCOLIGADA 
		    		AND T.IDMOV=TLA.IDMOVDESTINO 
		    		INNER JOIN TTMV TD ON 
		    		TD.CODTMV=T.CODTMV 
		    		AND TD.CODCOLIGADA=T.CODCOLIGADA 
		    		AND TD.TIPOIDENTIFIC=T.TIPO 
		    	) 
		    	SELECT CODCOLIGADA,IDMOV,PAI,CODTMV, 
		    	CASE STATUS 
		    	WHEN 'A' THEN 'Pendente / A Faturar'  
		    	WHEN 'B' THEN 'Bloqueado'  
		    	WHEN 'C' THEN 'Cancelado'  
		    	WHEN 'F' THEN 'Faturado '  
		    	WHEN 'G' THEN 'Parcialmente Faturado'  
		    	WHEN 'N' THEN 'Normal'  
		    	WHEN 'P' THEN 'Parcialmente Quitado'  
		    	WHEN 'Q' THEN 'Quitado' 
		    	WHEN 'R' THEN 'Não Processado' 
		    	WHEN 'U' THEN 'Em Faturamento' 
		    	WHEN 'O' THEN 'Aguardando Análise' 
		    	WHEN 'Y' THEN 'Não Iniciado' 
		    	WHEN 'E' THEN 'Em Andamento' 
		    	WHEN 'Z' THEN 'Terminado' 
		    	ELSE 'TESTE2' END AS STATUS,NUMEROMOV,NOME FROM ( 
		    	SELECT T.CODCOLIGADA,IDMOV,'0' PAI,T.CODTMV,STATUS,NUMEROMOV,TD.NOME FROM 
		    	TMOV T 
		    	INNER JOIN TTMV TD ON 
		    	TD.CODTMV=T.CODTMV 
		    	AND TD.CODCOLIGADA=T.CODCOLIGADA 
		    	AND TD.TIPOIDENTIFIC=T.TIPO 
                        AND T.IDMOV= "IDMOV"
		    	UNION 
		    	SELECT * FROM CTE_RAS 
		    	) R 