-- PAPC
select * from ml001070
-- MODAL PAPC
select * from ml001080


-- APONTAMENTO
select * from ML001057

select * from ML001058

select * from ML001059


--APONTAMENTO SEM PROGRAMAÇÃO

select * from ML001090
select * from ML001091

SELECT F.LOGIN, SUM(R.APONTAMENTO_PAPC) APONTAMENTO_PAPC,
SUM(R.APONTAMENTO) APONTAMENTO,
ROUND(CAST(SUM(R.NUMO_OPS) AS FLOAT)/CAST(CASE WHEN SUM(R.APONTAMENTO)=0 THEN 1 ELSE SUM(R.APONTAMENTO) END AS FLOAT),2) MEDIA_NUM_OPS,
SUM(R.APONTAMENTO_SEM_PROG) APONTAMENTO_SEM_PROG,
ROUND(CAST(SUM(R.NUMO_OPS_SEM_PROG)AS FLOAT)/CAST((CASE WHEN SUM(R.APONTAMENTO_SEM_PROG)=0 THEN 1 ELSE SUM(R.APONTAMENTO_SEM_PROG) END) AS FLOAT),2) MEDIA_NUM_OPS_SEM_PROG
FROM (
	SELECT USUARIOATUAL,COUNT(*) APONTAMENTO_PAPC,0 APONTAMENTO,0 NUMO_OPS ,0 APONTAMENTO_SEM_PROG,0 NUMO_OPS_SEM_PROG
	FROM ML001070(NOLOCK) AP 
	INNER JOIN PROCES_WORKFLOW P ON
	P.NUM_PROCES=AP.NUMPROCESSO
	GROUP BY USUARIOATUAL
	UNION ALL
	SELECT USUARIOATUAL,0,COUNT(R2.APONTAMENTO),SUM(NUMO_OPS),0,0 FROM (
	SELECT USUARIOATUAL,0 APONTAMENTO_PAPC ,AP.documentid APONTAMENTO,(SELECT COUNT(*) FROM ML001058 WHERE documentid=ap.documentid) NUMO_OPS,0 APONTAMENTO_SEM_PROG,0 NUMO_OPS_SEM_PROG
	FROM ML001057(NOLOCK) AP 
	INNER JOIN PROCES_WORKFLOW P ON
	P.NUM_PROCES=AP.NUMPROCESSO
	GROUP BY USUARIOATUAL,AP.documentid
	) R2
	GROUP BY USUARIOATUAL
	UNION ALL
	SELECT USUARIOATUAL,0,0,0,COUNT(R2.APONTAMENTO_SEM_PROG),SUM(NUMO_OPS_SEM_PROG) FROM (
	SELECT USUARIOATUAL,0 APONTAMENTO_PAPC,0 APONTAMENTO,0 NUMO_OPS,AP.documentid APONTAMENTO_SEM_PROG,(SELECT COUNT(*) FROM ML001091 WHERE documentid=ap.documentid) NUMO_OPS_SEM_PROG
	FROM ML001090 AP 
	INNER JOIN PROCES_WORKFLOW P ON
	P.NUM_PROCES=AP.NUMPROCESSO
	GROUP BY USUARIOATUAL,AP.documentid
	) R2
	GROUP BY R2.USUARIOATUAL
) R
INNER JOIN FDN_USERTENANT F ON
F.USER_CODE=R.USUARIOATUAL
GROUP BY F.LOGIN



SELECT USER_CODE,LOGIN FROM FDN_USERTENANT

select * from PROCES_WORKFLOW