SELECT K.CODCCUSTO,
K.CODORDEM,
KA.IDATVORDEM,

ROUND((CAST(KA.TEMPO AS FLOAT)/60)/
(SELECT COUNT(*) FROM KMAOOBRAALOC 
WHERE CODCOLIGADA=K.CODCOLIGADA
AND CODFILIAL=K.CODFILIAL
AND CODORDEM=K.CODORDEM
AND IDATVORDEM=KA.IDATVORDEM) ,2) PREVISTO,
ROUND(CAST(DATEDIFF(SECOND,KAL.DTHRINICIAL,KAL.DTHRFINAL) AS FLOAT)/3600,2) APONTADO, 
CASE WHEN KAC.RNCRR=1 THEN 'RNC' ELSE 'RR' END AS RNC_RR,
RETRABALHO, 
NUMERORNC2 NUMERORNC, 
CAUSADOR,C.DESCRICAO DSCPOSTO
FROM KORDEM K
INNER JOIN KATVORDEM KA ON
KA.CODCOLIGADA=K.CODCOLIGADA
AND KA.CODFILIAL=K.CODFILIAL
AND KA.CODORDEM=K.CODORDEM
INNER JOIN KMAOOBRAALOC KAL ON
KAL.CODCOLIGADA=K.CODCOLIGADA
AND KAL.CODFILIAL=K.CODFILIAL
AND KAL.CODORDEM=K.CODORDEM
AND KAL.IDATVORDEM=KA.IDATVORDEM
INNER JOIN KATVORDEMCOMPL KAC ON
KAC.CODCOLIGADA=K.CODCOLIGADA
AND KAC.CODFILIAL=K.CODFILIAL
AND KAC.CODORDEM=K.CODORDEM
AND KAC.IDATVORDEM=KA.IDATVORDEM
INNER JOIN MPRJ M ON
M.CODCOLIGADA=KA.CODCOLIGADA
AND M.CODFILIAL=KA.CODFILIAL
AND M.CODPRJ=K.CODCCUSTO
AND M.POSICAO IN ( 1,4)
INNER JOIN MTRF ML ON
ML.CODCOLIGADA=KA.CODCOLIGADA
AND ML.IDPRJ=M.IDPRJ
AND ML.CODTRFAUX=K.CODORDEM
INNER JOIN MTRFCOMPL MCL ON
MCL.CODCOLIGADA=M.CODCOLIGADA
AND MCL.IDPRJ=M.IDPRJ
AND MCL.IDTRF=ML.IDTRF
INNER JOIN GCONSIST C ON 
C.CODTABELA = 'CELULA'
AND C.APLICACAO = 'M'
AND C.CODINTERNO = MCL.CELULA
WHERE K.CODCCUSTO=:OS AND K.REPROCESSAMENTO=1
AND KAL.DTHRINICIAL >= :DATA_INICIAL AND KAL.DTHRFINAL<=:DATA_FINAL
ORDER BY CODORDEM