
SELECT * FROM (
SELECT DISTINCT ATV.ID,A.OS,A.INDICE INDICEK ,B.INDICE,A.IDCRIACAO,A.DESCRICAO NOMEFANTASIA,A.NUMDESENHO,B.POSICAODESENHO,B.DESQTDE,B.PESOUNITARIO,B.BITOLA,B.LARGURA,B.COMPRIMENTO,ATV.IDCRIACAOPROCESSO,ATV.DESCATIVIDADE ATIVIDADE,
(SELECT COUNT(*) FROM Z_CRM_EX001021 WHERE OSPROCESSO=B.OS AND IDCRIACAOPROCESSO=B.IDCRIACAO AND EXECUCAO=B.EXECUCAO) FIM,C.DESCRICAO
FROM Z_CRM_EX001005 A
INNER JOIN Z_CRM_EX001005 B
ON A.OS=B.OS
AND A.INDICE=B.NIVEL
AND B.TIPODESENHO!='NAOMANUFATURADO'
AND A.ITEMEXCLUSIVO=B.ITEMEXCLUSIVO
AND A.EXECUCAO=B.EXECUCAO
INNER JOIN Z_CRM_EX001021 ATV 
ON ATV.OSPROCESSO=B.OS
AND ATV.IDCRIACAOPROCESSO=B.IDCRIACAO
AND ATV.EXECUCAO=B.EXECUCAO
INNER JOIN CORPORE.DBO.KORDEM K
ON K.CODCOLIGADA=A.CODCOLIGADA
AND K.CODFILIAL=A.CODFILIAL
AND SUBSTRING(K.RESPONSAVEL,0,15)=A.CODIGOPRD COLLATE SQL_Latin1_General_CP1_CI_AI
INNER JOIN CORPORE.DBO.KORDEMCOMPL KL
ON KL.CODCOLIGADA=K.CODCOLIGADA
AND KL.CODFILIAL=K.CODFILIAL
AND KL.CODORDEM=K.CODORDEM
AND KL.NUMEXEC=A.EXECUCAO
INNER JOIN CORPORE.DBO.MTRF TRF 
ON TRF.CODCOLIGADA = K.CODCOLIGADA 
AND TRF.CODTRFAUX = KL.CODORDEM 
INNER JOIN CORPORE.DBO.MPRJ PRJ 
ON PRJ.CODCOLIGADA = TRF.CODCOLIGADA 
AND PRJ.IDPRJ = TRF.IDPRJ 
AND PRJ.POSICAO IN (1,4) 
INNER JOIN CORPORE.DBO.MTRFCOMPL TRFC 
ON TRF.CODCOLIGADA = TRFC.CODCOLIGADA 
AND TRF.IDPRJ = TRFC.IDPRJ  
AND TRF.IDTRF = TRFC.IDTRF
INNER JOIN CORPORE.DBO.GCONSIST C 
ON C.CODTABELA='CELULA' 
AND C.APLICACAO = 'M' 
AND C.CODINTERNO = TRFC.CELULA  
WHERE 
A.ITEMEXCLUSIVO<>2
AND A.OS='3.07842.32.001'
AND A.EXECUCAO LIKE 2 ) Z
ORDER BY CAST('/' + REPLACE(Z.INDICEK, '.', '/') + '/' AS HIERARCHYID)

--SELECT * FROM CORPORE.DBO.MTRFCOMPL
--SELECT * FROM CORPORE.DBO.MTRF
--SELECT * FROM CORPORE.DBO.MPRJ
--SELECT * FROM CORPORE.DBO.mtrf
--SELECT * FROM CORPORE.DBO.KORDEM
--SELECT * FROM CORPORE.DBO.GCONSIST
