SELECT RM.*,CONVERT(FLOAT,F.TOTALQTDE)TOTALQTDE,F.MINUTOSGASTOS,F.INDICE,
		CASE 
			WHEN CONVERT(FLOAT,RM.TEMPO)!=CONVERT(FLOAT,F.MINUTOSGASTOS)*CONVERT(FLOAT,F.TOTALQTDE) 
			THEN '1' 
			ELSE '0' 
		END AS TEMPOQTDDIVERGENTE
	FROM
		(SELECT A.ID,CODCOLIGADA,CODFILIAL,OS,CODIGOPRD,A.EXECUCAO,PRIORIDADE,CODATIVIDADE,TOTALQTDE,PROCESSAMENTO,MINUTOSGASTOS,E.INDICE
				FROM
					FLUIG.DBO.Z_CRM_EX001005 E
					INNER JOIN FLUIG.DBO.Z_CRM_EX001021 A ON 
					A.IDCRIACAOPROCESSO=E.IDCRIACAO
					AND E.OS=A.OSPROCESSO
					AND A.EXECUCAO=E.EXECUCAO 
				WHERE 
					E.OS='3.07840.32.001' AND E.INTEGRADO='SIM' ) F 
		RIGHT JOIN (SELECT MT.ID,K.CODCOLIGADA,K.CODFILIAL,MP.CODCCUSTO,K.CODORDEM,CONVERT(VARCHAR,KA.CODESTRUTURA)CODESTRUTURA,NUMEXEC,KL.PRIORIDADE,KA.CODATIVIDADE,ATV.DSCATIVIDADE,CONVERT(FLOAT,KA.QTPREVISTA) QTDPREVISTA,KA.TEMPO, CASE WHEN K.REPROCESSAMENTO IS NULL THEN 0 ELSE 1 END AS REPROCESSAMENTO
						FROM
							MPRJ MP
							INNER JOIN MTAREFA MT ON 
							MT.CODCOLIGADA = MP.CODCOLIGADA
							AND MT.IDPRJ=MP.IDPRJ
							INNER JOIN KATVORDEM KA ON 
							KA.CODCOLIGADA = MP.CODCOLIGADA 
							AND KA.CODFILIAL=MP.CODFILIAL 
							AND KA.CODORDEM=MT.CODTRFAUX
							INNER JOIN KATVORDEMCOMPL KL ON 
							KL.CODCOLIGADA = MP.CODCOLIGADA 
							AND KL.CODFILIAL=MP.CODFILIAL 
							AND KL.CODORDEM=MT.CODTRFAUX 
							AND KL.IDATVORDEM=KA.IDATVORDEM
							INNER JOIN KORDEM K ON 
							K.CODCOLIGADA = MP.CODCOLIGADA 
							AND K.CODFILIAL=MP.CODFILIAL 
							AND K.CODORDEM=MT.CODTRFAUX
							INNER JOIN KORDEMCOMPL KO ON 
							KO.CODCOLIGADA = MP.CODCOLIGADA 
							AND KO.CODFILIAL=MP.CODFILIAL 
							AND KO.CODORDEM=MT.CODTRFAUX
							INNER JOIN KATIVIDADE ATV ON
							ATV.CODCOLIGADA=MP.CODCOLIGADA
							AND ATV.CODFILIAL=MP.CODFILIAL
							AND ATV.CODATIVIDADE=KA.CODATIVIDADE
						WHERE
							MP.CODPRJ='3.07840.32.001'
							AND MP.REVISAO=(SELECT MAX(REVISAO) FROM MPRJ
											WHERE CODPRJ='3.07840.32.001') 
							AND K.STATUS!=6
							AND KA.STATUS!=6) RM ON 
			RM.CODCOLIGADA=F.CODCOLIGADA 
			AND F.CODFILIAL=CONVERT(VARCHAR,RM.CODFILIAL) COLLATE SQL_Latin1_General_CP1_CI_AI
			AND F.CODIGOPRD=CONVERT(VARCHAR,RM.CODESTRUTURA) COLLATE SQL_Latin1_General_CP1_CI_AI
			AND F.EXECUCAO=CONVERT(VARCHAR,RM.NUMEXEC) COLLATE SQL_Latin1_General_CP1_CI_AI
			AND F.PRIORIDADE=CONVERT(VARCHAR,RM.PRIORIDADE) COLLATE SQL_Latin1_General_CP1_CI_AI
			AND F.CODATIVIDADE=CONVERT(VARCHAR,RM.CODATIVIDADE) COLLATE SQL_Latin1_General_CP1_CI_AI
		WHERE F.ID IS NULL OR CONVERT(FLOAT,RM.TEMPO)!=CONVERT(FLOAT,F.MINUTOSGASTOS)*CONVERT(FLOAT,F.TOTALQTDE)



